import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")!;
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const OPENAI_MODEL=Deno.env.get("INSURANCE_OPENAI_MODEL")||Deno.env.get("OPENAI_MODEL")||"";
const CONTACT_KEY=Deno.env.get("INSURANCE_CONTACT_KEY")||"";
const PROMPT_VERSION="insurance-ai-v1-20260815";
const allowedOrigins=new Set([
  "https://ins.ekodi.kr",
  "https://ekodi-insurance-staging.topmaster-joseph.workers.dev",
  "https://admin.ekodi.kr",
  "http://localhost:8788",
  "http://127.0.0.1:8788",
]);
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const encoder=new TextEncoder();
const decoder=new TextDecoder();

const clip=(v:unknown,n:number)=>String(v??"").trim().slice(0,n);
const cors=(req:Request)=>{const origin=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":allowedOrigins.has(origin)?origin:"null","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"}};
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors(req),"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
async function session(req:Request){const authorization=req.headers.get("Authorization");if(!authorization)return null;const db=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}});const {data,error}=await db.auth.getUser();if(error||!data.user)return null;return{db,user:data.user};}
async function staffRole(userId:string){const {data}=await admin.from("insurance_staff").select("role,active").eq("user_id",userId).maybeSingle();return data?.active?String(data.role||""):"";}
function requireOrigin(req:Request){const origin=req.headers.get("Origin")||"";return allowedOrigins.has(origin);}

function redact(text:string){return clip(text,4000)
  .replace(/\b\d{6}-?\d{7}\b/g,"[고유식별정보 가림]")
  .replace(/\b01[016789][- .]?\d{3,4}[- .]?\d{4}\b/g,"[연락처 가림]")
  .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,"[이메일 가림]")
  .replace(/\b\d{2,4}-\d{2,4}-\d{4}\b/g,"[연락처 가림]");}
function safeHistory(value:unknown){return(Array.isArray(value)?value:[]).slice(-12).map((m:any)=>({role:m?.role==="assistant"?"assistant":"user",content:redact(clip(m?.content||m?.text,1800))})).filter((m:any)=>m.content);}
function needsHuman(text:string){return/(설계사|전화|연락|상담원|사람 상담|가입 상담|직접 상담|콜백)/i.test(text)}
function fallbackReply(message:string){if(needsHuman(message))return"실제 설계사의 설명이나 전화상담이 필요하시면 설계사 연결 요청을 남길 수 있습니다. 연락처는 요청 시에만 별도로 수집합니다.";if(/(청구|병원|진료|입원|수술|실손|사고)/i.test(message))return"보험청구는 가입계약, 사고·진료 상황, 보험사에서 요구하는 증빙을 순서대로 확인하면 좋습니다. 지급 여부는 약관과 보험사 심사에 따라 달라지므로 여기서는 준비 순서만 안내합니다.";if(/(추천|어떤 보험|상품|보험사|가입)/i.test(message))return"특정 보험사나 상품부터 고르기보다 현재 가입내역, 월 보험료, 가족상황, 걱정되는 위험을 먼저 정리해 보세요. 실제 상품 설명이나 가입 절차가 필요하면 설계사 연결을 요청할 수 있습니다.";return"현재 보험을 이해하고 관리하는 데 필요한 확인 순서를 함께 정리해 드릴 수 있습니다. 주민번호나 상세 병명 같은 불필요한 민감정보는 입력하지 않으셔도 됩니다.";}
function outputText(data:any){if(typeof data?.output_text==="string")return data.output_text;const out:string[]=[];for(const item of Array.isArray(data?.output)?data.output:[])for(const c of Array.isArray(item?.content)?item.content:[])if(typeof c?.text==="string")out.push(c.text);return out.join("\n").trim();}
async function providerReply(message:string,history:any[]){if(!OPENAI_API_KEY||!OPENAI_MODEL)return{reply:fallbackReply(message),provider:"fallback",model:"local-rules"};const instructions=`You are EKODI Insurance AI, a Korean insurance-management assistant. Help users understand existing insurance, organize coverage-review questions, premiums, renewal issues, and claim-preparation steps. Do not promise claim payment. Do not state that a specific insurance product is definitively best. Do not complete insurance solicitation or contracting. When the user clearly asks for a human, phone call, product-specific enrollment explanation, or a licensed planner, explain that a human planner callback can be requested. Never ask for resident registration numbers or detailed medical records. Be concise, calm, and transparent about uncertainty.`;const input=[...history.map(m=>({role:m.role,content:m.content})),{role:"user",content:redact(message)}];try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:OPENAI_MODEL,instructions,input,store:false,max_output_tokens:700})});if(!r.ok){console.error("insurance ai provider",r.status);return{reply:fallbackReply(message),provider:"fallback",model:"local-rules"}}const d=await r.json();const text=clip(outputText(d),4000);return{reply:text||fallbackReply(message),provider:"openai",model:String(d.model||OPENAI_MODEL)}}catch(e){console.error("insurance ai provider",e);return{reply:fallbackReply(message),provider:"fallback",model:"local-rules"}}}

function b64(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function unb64(value:string){const s=atob(value);return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function contactKey(){if(!CONTACT_KEY)throw new Error("contact_encryption_key_missing");const raw=unb64(CONTACT_KEY);if(raw.byteLength!==32)throw new Error("contact_encryption_key_invalid");return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["encrypt","decrypt"])}
async function encryptContact(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await contactKey();const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,encoder.encode(value)));return`${b64(iv)}.${b64(encrypted)}`}
async function decryptContact(value:string){const [ivPart,dataPart]=String(value||"").split(".");if(!ivPart||!dataPart)return"";const key=await contactKey();const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(ivPart)},key,unb64(dataPart));return decoder.decode(decrypted)}
function contactHint(value:string){const digits=value.replace(/\D/g,"");return digits.length>=4?`••••${digits.slice(-4)}`:"연락처 등록됨"}
async function audit(actorUserId:string,action:string,subjectUserId:string|null=null,consultationId:string|null=null,metadata:Record<string,unknown>={}){await admin.from("insurance_audit_events").insert({actor_user_id:actorUserId,subject_user_id:subjectUserId,consultation_id:consultationId,action,metadata});}

async function aiChat(req:Request,userId:string){const body=await req.json().catch(()=>({}));const message=redact(clip(body?.message,4000));if(message.length<2)return json(req,{error:"message_required"},400);const history=safeHistory(body?.history);const result=await providerReply(message,history);return json(req,{reply:result.reply,handoffSuggested:needsHuman(message),provider:result.provider,model:result.model,promptVersion:PROMPT_VERSION,stored:false});}
async function createConsultation(req:Request,userId:string){const body=await req.json().catch(()=>({}));const name=clip(body?.name||body?.contactName,80),contact=clip(body?.contact,120),preferredTime=clip(body?.preferredTime,60),summary=redact(clip(body?.summary||body?.aiSummary,600));const transcript=safeHistory(body?.transcript).slice(-30);if(!name||!contact||!summary)return json(req,{error:"name_contact_summary_required"},400);if(body?.consent!==true)return json(req,{error:"consultation_share_consent_required"},400);const {data:consent,error:consentError}=await admin.from("insurance_consents").insert({user_id:userId,purpose:"human_advisor_callback",policy_version:clip(body?.policyVersion||"insurance-consult-v1",80),granted:true,metadata:{shareTranscript:body?.shareTranscript!==false}}).select("id").single();if(consentError)throw consentError;let conversationId:null|string=null;if(transcript.length){const {data:conversation,error:conversationError}=await admin.from("insurance_ai_conversations").insert({user_id:userId,title:"Human handoff",summary,status:"closed",model_provider:"handoff-copy",model_name:"shared-transcript",prompt_version:PROMPT_VERSION}).select("id").single();if(conversationError)throw conversationError;conversationId=conversation.id;const rows=transcript.map((m:any)=>({conversation_id:conversationId,user_id:userId,role:m.role,content:m.content,safety_class:"shared_by_user"}));const {error:messageError}=await admin.from("insurance_ai_messages").insert(rows);if(messageError)throw messageError;}const encrypted=await encryptContact(contact);const {data,error}=await admin.from("insurance_consultation_requests").insert({user_id:userId,conversation_id:conversationId,consent_id:consent.id,contact_name:name,contact_ciphertext:encrypted,contact_hint:contactHint(contact),preferred_time:preferredTime,ai_summary:summary,share_transcript:body?.shareTranscript!==false,status:"new"}).select("id,status,created_at").single();if(error)throw error;await audit(userId,"consultation.created",userId,data.id,{shareTranscript:body?.shareTranscript!==false});return json(req,{consultation:{id:data.id,status:data.status,createdAt:data.created_at}},201)}
async function listAdmin(req:Request,userId:string){const role=await staffRole(userId);if(!["admin","advisor","auditor"].includes(role))return json(req,{error:"forbidden"},403);const {data,error}=await admin.from("insurance_consultation_requests").select("id,user_id,contact_name,contact_ciphertext,contact_hint,preferred_time,ai_summary,status,created_at,updated_at,assigned_staff_id").order("created_at",{ascending:false}).limit(300);if(error)throw error;const consultations=[];for(const row of data||[]){let contactValue="";if(role!=="auditor"){try{contactValue=await decryptContact(row.contact_ciphertext)}catch{contactValue=row.contact_hint||""}}consultations.push({id:row.id,userId:row.user_id,contactName:row.contact_name,contact:contactValue,contactHint:row.contact_hint,preferredTime:row.preferred_time,aiSummary:row.ai_summary,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,assignedStaffId:row.assigned_staff_id});}await audit(userId,"admin.consultations.listed",null,null,{count:consultations.length,role});return json(req,{consultations,role})}
async function consultationDetail(req:Request,userId:string,id:string){const role=await staffRole(userId);if(!["admin","advisor","auditor"].includes(role))return json(req,{error:"forbidden"},403);const {data:row,error}=await admin.from("insurance_consultation_requests").select("*").eq("id",id).maybeSingle();if(error)throw error;if(!row)return json(req,{error:"not_found"},404);let contactValue="";if(role!=="auditor"){try{contactValue=await decryptContact(row.contact_ciphertext)}catch{contactValue=row.contact_hint||""}}let transcript:any[]=[];if(row.share_transcript&&row.conversation_id){const {data:messages}=await admin.from("insurance_ai_messages").select("role,content,created_at").eq("conversation_id",row.conversation_id).order("created_at");transcript=(messages||[]).map(m=>({role:m.role,text:m.content,createdAt:m.created_at}));}await audit(userId,"admin.consultation.viewed",row.user_id,id,{role,transcriptShared:row.share_transcript});return json(req,{consultation:{id:row.id,userId:row.user_id,contactName:row.contact_name,contact:contactValue,contactHint:row.contact_hint,preferredTime:row.preferred_time,aiSummary:row.ai_summary,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,shareTranscript:row.share_transcript,transcript}})}
async function updateStatus(req:Request,userId:string,id:string){const role=await staffRole(userId);if(!["admin","advisor"].includes(role))return json(req,{error:"forbidden"},403);const body=await req.json().catch(()=>({}));const status=String(body?.status||"");if(!["new","working","contacted","closed"].includes(status))return json(req,{error:"invalid_status"},400);const {data,error}=await admin.from("insurance_consultation_requests").update({status,updated_at:new Date().toISOString()}).eq("id",id).select("id,user_id,status").maybeSingle();if(error)throw error;if(!data)return json(req,{error:"not_found"},404);await audit(userId,"admin.consultation.status_changed",data.user_id,id,{status,role});return json(req,{consultation:{id:data.id,status:data.status}})}
async function revokeConsultation(req:Request,userId:string,id:string){const {data,error}=await admin.from("insurance_consultation_requests").select("id,user_id,status").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)return json(req,{error:"not_found"},404);if(data.status==="contacted")return json(req,{error:"already_contacted"},409);const {error:updateError}=await admin.from("insurance_consultation_requests").update({status:"closed",share_transcript:false,contact_ciphertext:"revoked",contact_hint:"철회됨",updated_at:new Date().toISOString()}).eq("id",id);if(updateError)throw updateError;await admin.from("insurance_consents").update({revoked_at:new Date().toISOString()}).eq("user_id",userId).eq("purpose","human_advisor_callback").is("revoked_at",null);await audit(userId,"consultation.revoked",userId,id,{});return json(req,{ok:true})}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(!requireOrigin(req))return json(req,{error:"origin_not_allowed"},403);const auth=await session(req);if(!auth)return json(req,{error:"unauthorized"},401);const path=new URL(req.url).pathname.replace(/^\/insurance-api/,"")||"/";try{if(req.method==="POST"&&path==="/ai/chat")return await aiChat(req,auth.user.id);if(req.method==="POST"&&path==="/consultations")return await createConsultation(req,auth.user.id);if(req.method==="GET"&&path==="/admin/consultations")return await listAdmin(req,auth.user.id);const detail=path.match(/^\/admin\/consultations\/([0-9a-f-]+)$/i);if(req.method==="GET"&&detail)return await consultationDetail(req,auth.user.id,detail[1]);const status=path.match(/^\/admin\/consultations\/([0-9a-f-]+)\/status$/i);if(req.method==="PATCH"&&status)return await updateStatus(req,auth.user.id,status[1]);const revoke=path.match(/^\/me\/consultations\/([0-9a-f-]+)\/revoke$/i);if(req.method==="POST"&&revoke)return await revokeConsultation(req,auth.user.id,revoke[1]);return json(req,{error:"not_found"},404)}catch(e){console.error("insurance-api",e);return json(req,{error:"insurance_api_failed"},500)}});
