-- EKODI Bible Conversation database contract
-- Namespace: public.bible_*
-- Privacy default: owner-only; community sharing is explicit.

create table if not exists public.bible_journeys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  tenant_slug text not null default 'ekodi-church',
  topic text not null,
  title text not null,
  scripture_ref text not null default '',
  reflection text not null default '',
  prayer text not null default '',
  status text not null default 'open' check (status in ('open','practicing','completed','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bible_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  journey_id uuid references public.bible_journeys(id) on delete set null,
  tenant_slug text not null default 'ekodi-church',
  topic text not null default '삶',
  mode text not null default 'guided' check (mode in ('guided','ai','free_assist')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bible_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.bible_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null check (char_length(content) between 1 and 8000),
  scripture_ref text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.bible_practices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  journey_id uuid not null references public.bible_journeys(id) on delete cascade,
  action_text text not null,
  due_date date,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.bible_followups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  journey_id uuid not null references public.bible_journeys(id) on delete cascade,
  prompt text not null,
  due_at timestamptz not null,
  answered_at timestamptz,
  answer text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.bible_groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  tenant_slug text not null default 'ekodi-church',
  name text not null,
  kind text not null default 'small_group' check (kind in ('family','small_group','church','other')),
  invite_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),
  created_at timestamptz not null default now()
);

create table if not exists public.bible_group_members (
  group_id uuid not null references public.bible_groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','leader','member')),
  joined_at timestamptz not null default now(),
  primary key(group_id,user_id)
);

create table if not exists public.bible_shared_journeys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  group_id uuid not null references public.bible_groups(id) on delete cascade,
  journey_id uuid not null references public.bible_journeys(id) on delete cascade,
  note text not null default '',
  created_at timestamptz not null default now(),
  unique(group_id,journey_id)
);

create table if not exists public.bible_content_plans (
  id uuid primary key default gen_random_uuid(),
  tenant_slug text not null default 'ekodi-church',
  title text not null,
  question text not null,
  scripture_ref text not null,
  scripture_note text not null default '',
  practice_prompt text not null default '',
  active_date date not null default current_date,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_bible_journeys_user_created on public.bible_journeys(user_id, created_at desc);
create index if not exists idx_bible_conversations_user_created on public.bible_conversations(user_id, created_at desc);
create index if not exists idx_bible_messages_conversation_created on public.bible_messages(conversation_id, created_at);
create index if not exists idx_bible_followups_user_due on public.bible_followups(user_id, due_at);
create index if not exists idx_bible_practices_user_created on public.bible_practices(user_id, created_at desc);
create index if not exists idx_bible_group_members_user on public.bible_group_members(user_id, group_id);
create index if not exists idx_bible_shared_group_created on public.bible_shared_journeys(group_id, created_at desc);
create index if not exists idx_bible_content_tenant_date on public.bible_content_plans(tenant_slug, active_date desc) where is_active=true;

alter table public.bible_journeys enable row level security;
alter table public.bible_conversations enable row level security;
alter table public.bible_messages enable row level security;
alter table public.bible_practices enable row level security;
alter table public.bible_followups enable row level security;
alter table public.bible_groups enable row level security;
alter table public.bible_group_members enable row level security;
alter table public.bible_shared_journeys enable row level security;
alter table public.bible_content_plans enable row level security;

create or replace function public.bible_is_group_member(p_group_id uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.bible_group_members gm where gm.group_id=p_group_id and gm.user_id=auth.uid()) $$;

create or replace function public.bible_create_group(p_name text, p_kind text default 'small_group', p_tenant_slug text default 'ekodi-church')
returns public.bible_groups language plpgsql security definer set search_path=public
as $$
declare g public.bible_groups;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  insert into public.bible_groups(owner_id,name,kind,tenant_slug)
  values(auth.uid(),left(trim(p_name),120),coalesce(nullif(p_kind,''),'small_group'),coalesce(nullif(p_tenant_slug,''),'ekodi-church'))
  returning * into g;
  insert into public.bible_group_members(group_id,user_id,role) values(g.id,auth.uid(),'owner') on conflict do nothing;
  return g;
end $$;

create or replace function public.bible_join_group(p_invite_code text)
returns uuid language plpgsql security definer set search_path=public
as $$
declare gid uuid;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select id into gid from public.bible_groups where invite_code=upper(trim(p_invite_code));
  if gid is null then raise exception 'INVITE_NOT_FOUND'; end if;
  insert into public.bible_group_members(group_id,user_id,role) values(gid,auth.uid(),'member') on conflict do nothing;
  return gid;
end $$;

create or replace function public.bible_shared_feed(p_limit integer default 50)
returns table(share_id uuid,group_id uuid,journey_id uuid,owner_id uuid,title text,topic text,scripture_ref text,reflection text,note text,shared_at timestamptz)
language sql stable security definer set search_path=public
as $$
  select s.id,s.group_id,s.journey_id,s.user_id,j.title,j.topic,j.scripture_ref,j.reflection,s.note,s.created_at
  from public.bible_shared_journeys s
  join public.bible_journeys j on j.id=s.journey_id and j.user_id=s.user_id
  where auth.uid() is not null
    and exists(select 1 from public.bible_group_members gm where gm.group_id=s.group_id and gm.user_id=auth.uid())
  order by s.created_at desc
  limit least(greatest(coalesce(p_limit,50),1),100)
$$;

revoke all on function public.bible_is_group_member(uuid) from public, anon;
revoke all on function public.bible_create_group(text,text,text) from public, anon;
revoke all on function public.bible_join_group(text) from public, anon;
revoke all on function public.bible_shared_feed(integer) from public, anon;
grant execute on function public.bible_is_group_member(uuid) to authenticated;
grant execute on function public.bible_create_group(text,text,text) to authenticated;
grant execute on function public.bible_join_group(text) to authenticated;
grant execute on function public.bible_shared_feed(integer) to authenticated;

-- Policies are recreated to keep this file idempotent for reviewed environments.
drop policy if exists bible_journeys_own_all on public.bible_journeys;
create policy bible_journeys_own_all on public.bible_journeys for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists bible_conversations_own_all on public.bible_conversations;
create policy bible_conversations_own_all on public.bible_conversations for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists bible_messages_own_all on public.bible_messages;
create policy bible_messages_own_all on public.bible_messages for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists bible_practices_own_all on public.bible_practices;
create policy bible_practices_own_all on public.bible_practices for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists bible_followups_own_all on public.bible_followups;
create policy bible_followups_own_all on public.bible_followups for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists bible_groups_owner_all on public.bible_groups;
create policy bible_groups_owner_all on public.bible_groups for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
drop policy if exists bible_groups_member_read on public.bible_groups;
create policy bible_groups_member_read on public.bible_groups for select to authenticated using (public.bible_is_group_member(id));
drop policy if exists bible_group_members_self_read on public.bible_group_members;
create policy bible_group_members_self_read on public.bible_group_members for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists bible_group_members_owner_read on public.bible_group_members;
create policy bible_group_members_owner_read on public.bible_group_members for select to authenticated using (exists(select 1 from public.bible_groups g where g.id=group_id and g.owner_id=(select auth.uid())));
drop policy if exists bible_group_members_owner_write on public.bible_group_members;
create policy bible_group_members_owner_write on public.bible_group_members for all to authenticated using (exists(select 1 from public.bible_groups g where g.id=group_id and g.owner_id=(select auth.uid()))) with check (exists(select 1 from public.bible_groups g where g.id=group_id and g.owner_id=(select auth.uid())));
drop policy if exists bible_shared_member_read on public.bible_shared_journeys;
create policy bible_shared_member_read on public.bible_shared_journeys for select to authenticated using (public.bible_is_group_member(group_id));
drop policy if exists bible_shared_own_write on public.bible_shared_journeys;
create policy bible_shared_own_write on public.bible_shared_journeys for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id and exists(select 1 from public.bible_journeys j where j.id=journey_id and j.user_id=(select auth.uid())) and public.bible_is_group_member(group_id));
drop policy if exists bible_content_active_read on public.bible_content_plans;
create policy bible_content_active_read on public.bible_content_plans for select to anon,authenticated using (is_active=true);
