(()=>{
'use strict';
if(window.__EKODIAN_BOOTED)return;window.__EKODIAN_BOOTED=true;
const current=document.currentScript;
const service=String(current?.dataset?.ekodiService||document.documentElement.dataset.ekodiService||'ekodi').trim().toLowerCase()||'ekodi';
const surface=String(current?.dataset?.ekodiSurface||document.documentElement.dataset.ekodiUserSurface||'public').trim().toLowerCase();
const assetOrigin=new URL(current?.src||location.href).origin;
const TRAITS=Object.freeze(['proactive','personalized','future-oriented','relationship-oriented','context-aware','companion','restrained','life-giving']);
const PROFILES={ekodi:{role:'platform-guide',prompt:'무엇부터 함께 시작할까요?',next:'필요한 곳으로 이어드릴게요.'},my:{role:'personal-companion',prompt:'오늘 이어갈 일을 살펴볼까요?',next:'지금과 다음을 한 흐름으로 이어드릴게요.'},try:{role:'explorer',prompt:'어디부터 둘러볼까요?',next:'안전한 체험 안에서 다음 화면을 안내할게요.'},church:{role:'faith-companion',prompt:'오늘 말씀 앞에 잠시 머물러 보실래요?',next:'말씀에서 삶과 공동체로 이어지도록 곁에 있을게요.'},mall:{role:'relationship-curator',prompt:'누구를 생각하며 오셨나요?',next:'상품보다 사람과 상황에 맞는 선택부터 살펴볼게요.'},marketing:{role:'marketing-coach',prompt:'오늘 알리고 싶은 이야기는 무엇인가요?',next:'콘텐츠가 다음 관계로 이어지도록 준비할게요.'},biz:{role:'business-partner',prompt:'어떤 문제부터 함께 풀어볼까요?',next:'오늘의 선택이 다음 운영으로 이어지도록 정리할게요.'},business:{role:'business-partner',prompt:'어떤 문제부터 함께 풀어볼까요?',next:'오늘의 선택이 다음 운영으로 이어지도록 정리할게요.'},community:{role:'community-neighbor',prompt:'오늘 누구와 연결되고 싶으세요?',next:'사람과 사람이 자연스럽게 이어지도록 도울게요.'}};
const IMAGES=['welcome','guide','community','business','current'];
function hash(v){let h=2166136261;for(const ch of String(v)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0;}
function profile(){return PROFILES[service]||{role:'guide',prompt:'지금 필요한 것을 함께 살펴볼까요?',next:'다음에 필요한 곳까지 자연스럽게 이어드릴게요.'};}
function state(){const forced=document.documentElement.dataset.ekodianState||document.body?.dataset?.ekodianState;if(forced)return forced;if(document.querySelector('[data-empty-state],.empty-state'))return'help';if(/onboard|start|welcome/.test(location.pathname))return'onboarding';return surface==='public'?'welcome':'guide';}
function imageUrl(){return `${assetOrigin}/character/${IMAGES[hash(`${service}:${state()}:${location.pathname}`)%IMAGES.length]}.webp`;}
function placement(){if(service==='ekodi')return{mode:'hero',side:'right',size:'large'};if(new Set(['business','biz','marketing','management','trade','invest','mall']).has(service))return{mode:'edge',side:'right',size:'medium'};if(new Set(['church','community','bible','education','life']).has(service))return{mode:'edge',side:'left',size:'medium'};return{mode:'edge',side:(hash(service)%2?'right':'left'),size:'small'};}
function context(){try{return window.EKODIShell?.getContext?.()||{};}catch{return{};}}
function message(){const p=profile(),name=String(context().personName||'').trim();return{headline:name?`${name}님, ${p.prompt}`:p.prompt,detail:p.next,role:p.role};}
function installStyles(){if(document.getElementById('ekodian-v2-style'))return;const s=document.createElement('style');s.id='ekodian-v2-style';s.textContent=`[data-ekodian]{z-index:30;pointer-events:none;box-sizing:border-box;font-family:inherit}[data-ekodian] img{display:block;width:100%;height:auto;max-height:100%;object-fit:contain;filter:drop-shadow(0 18px 28px rgba(27,48,37,.12))}[data-ekodian][data-mode="edge"]{position:fixed;bottom:12px;width:clamp(108px,13vw,176px);max-height:46vh}[data-ekodian][data-side="right"]{right:max(8px,env(safe-area-inset-right))}[data-ekodian][data-side="left"]{left:max(8px,env(safe-area-inset-left))}[data-ekodian][data-size="small"]{width:clamp(92px,10vw,132px)}[data-ekodian][data-size="large"]{width:clamp(230px,30vw,390px)}[data-ekodi-character-host="true"]{position:relative;overflow:visible}[data-ekodi-character-host="true"]>[data-ekodian][data-mode="hero"]{position:absolute;right:0;bottom:-10px;max-height:100%}.ekodian-dialog{pointer-events:auto;position:absolute;right:72%;bottom:18%;width:min(260px,70vw);padding:11px 13px;border:1px solid rgba(49,93,72,.16);border-radius:16px;background:color-mix(in srgb,#fff 94%,var(--ekodi-service-accent,#315d48) 6%);box-shadow:0 14px 36px rgba(20,40,30,.12);color:var(--ekodi-service-ink,#18251d);line-height:1.42}.ekodian-name{display:block;font-size:11px;letter-spacing:.04em}.ekodian-name span{opacity:.56;margin-left:4px}.ekodian-prompt{display:block;margin-top:4px;font-size:13px;font-weight:700}.ekodian-next{display:block;margin-top:4px;font-size:11px;opacity:.7}.ekodian-action{margin-top:7px;border:0;border-radius:999px;padding:6px 9px;background:var(--ekodi-service-accent,#315d48);color:#fff;font:inherit;font-size:11px;cursor:pointer}@media(max-width:720px){[data-ekodian][data-mode="edge"]{width:clamp(86px,24vw,118px);bottom:8px}.ekodian-dialog{right:50%;bottom:70%;width:min(220px,70vw)}[data-ekodian][data-mode="hero"]{width:clamp(128px,38vw,190px)!important}}@media(prefers-reduced-motion:no-preference){[data-ekodian]{animation:ekodian-arrive .5s ease-out both}@keyframes ekodian-arrive{from{opacity:0;transform:translateY(10px)}to{opacity:.96;transform:translateY(0)}}}@media(prefers-reduced-motion:reduce){[data-ekodian]{animation:none!important}}`;document.head.append(s);}
function nextAction(){return document.querySelector('[data-ekodian-action],.hero a[href],.hero button,[data-hero] a[href],[data-hero] button,main a[href],main button');}
function mount(){if(document.querySelector('[data-ekodian]'))return;installStyles();const spec=placement(),copy=message(),host=document.createElement('aside');host.dataset.ekodian='v2';host.dataset.service=service;host.dataset.mode=spec.mode;host.dataset.side=spec.side;host.dataset.size=spec.size;host.dataset.state=state();host.dataset.role=copy.role;host.setAttribute('aria-label',`에코디언 안내: ${copy.headline}`);
const img=document.createElement('img');img.src=imageUrl();img.alt='에코디언';img.loading=service==='ekodi'?'eager':'lazy';img.decoding='async';
const box=document.createElement('div');box.className='ekodian-dialog';const name=document.createElement('strong');name.className='ekodian-name';name.innerHTML='에코디언 <span>EKODIAN</span>';const prompt=document.createElement('span');prompt.className='ekodian-prompt';prompt.textContent=copy.headline;const detail=document.createElement('small');detail.className='ekodian-next';detail.textContent=copy.detail;const action=document.createElement('button');action.type='button';action.className='ekodian-action';action.textContent='다음 보기';
action.addEventListener('click',()=>{const target=nextAction();window.dispatchEvent(new CustomEvent('ekodi:ekodian-action',{detail:{service,state:state(),role:copy.role,traits:TRAITS,targetFound:Boolean(target)}}));if(target){target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});target.focus?.({preventScroll:true});}});box.append(name,prompt,detail,action);host.append(img,box);
if(spec.mode==='hero'){const hero=document.querySelector('.hero,.hero-section,[data-hero],main>section');if(hero){hero.dataset.ekodiCharacterHost='true';hero.append(host);}else document.body.append(host);}else document.body.append(host);
window.dispatchEvent(new CustomEvent('ekodi:character-ready',{detail:{name:'EKODIAN',service,state:state(),role:copy.role,traits:TRAITS,...spec}}));}
function boot(){if(!['public','workspace'].includes(surface)||document.documentElement.dataset.ekodiCharacter==='off')return;mount();}
window.EKODIAN=Object.freeze({name:'EKODIAN',koreanName:'에코디언',version:2,traits:TRAITS,getProfile:()=>({...profile()}),getState:state,getContext:context});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
