import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../my-worker.js';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'pub',ASSETS:{fetch:async()=>new Response('not found',{status:404})}};
const execute=(body,token='token')=>worker.fetch(new Request('https://my.ekodi.kr/api/intent/execute',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)}),env);
test('execution bridge requires server-verifiable authentication',async()=>{const res=await worker.fetch(new Request('https://my.ekodi.kr/api/intent/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'행사를 준비해줘',audience:'organization',workspace_key:'tenant:one'})}),env);assert.equal(res.status,401)});
test('execution bridge rejects a workspace not returned by canonical membership authority',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({workspaces:[{workspace_key:'tenant:other',status:'active'}],user:{id:'u1'}},{status:200});try{const res=await execute({text:'행사를 준비해줘',audience:'organization',workspace_key:'tenant:one'});assert.equal(res.status,403)}finally{globalThis.fetch=original}});
test('execution bridge recomputes intent and only executes safe observe or prepare tiers',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({workspaces:[{workspace_key:'tenant:one',workspace_name:'One',workspace_kind:'organization',role:'owner',status:'active'}],user:{id:'u1'}},{status:200});try{const res=await execute({text:'상인회 행사와 홍보를 준비해줘',audience:'organization',workspace_key:'tenant:one'});const body=await res.json();assert.equal(res.status,200);assert.equal(body.contract,'ekodi.intent-execution.v1');assert.equal(body.authority.verified,true);assert.ok(body.decisions.some(item=>item.state==='execute_now'));assert.ok(body.decisions.some(item=>item.state==='adapter_required'));assert.equal(body.executionPolicy,'safe_observe_and_prepare_only')}finally{globalThis.fetch=original}});
test('high-impact trade capabilities remain behind the sovereign human gate',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({workspaces:[{workspace_key:'tenant:one',workspace_name:'One',workspace_kind:'organization',role:'owner',status:'active'}],user:{id:'u1'}},{status:200});try{const body=await (await execute({text:'무역 거래와 계약을 준비해줘',audience:'business',workspace_key:'tenant:one'})).json();assert.ok(body.decisions.some(item=>item.capabilityId==='trade.operations'&&item.state==='human_gate'));assert.ok(body.summary.humanGate>0)}finally{globalThis.fetch=original}});
