import assert from 'node:assert/strict';
import test from 'node:test';
import worker from '../personal-finance-worker.js';

function fakeDb({first=null,all=[]}={}){const calls=[];return{calls,prepare(sql){const stmt={sql,args:[],bind(...args){this.args=args;return this},async run(){calls.push({kind:'run',sql,args:this.args});return{success:true}},async first(){calls.push({kind:'first',sql,args:this.args});return typeof first==='function'?first(sql,this.args):first},async all(){calls.push({kind:'all',sql,args:this.args});return{results:typeof all==='function'?all(sql,this.args):all}}};return stmt},async batch(stmts){calls.push({kind:'batch',count:stmts.length});for(const stmt of stmts)await stmt.run();return stmts.map(()=>({success:true}))}}}
async function withUser(id,fn){const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({id,email:`${id}@example.com`}),{status:200,headers:{'content-type':'application/json'}});try{return await fn()}finally{globalThis.fetch=original}}
const env=(DB)=>({PERSONAL_DB:DB,SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'publishable'});
const auth={authorization:'Bearer valid-user-token'};

test('personal finance health is public and declares the dedicated data boundary',async()=>{const r=await worker.fetch(new Request('https://personal-finance-api.ekodi.kr/health'),{});assert.equal(r.status,200);const d=await r.json();assert.equal(d.service,'ekodi-personal-finance-api');assert.equal(d.dataBoundary,'dedicated-d1');assert.equal(d.aiWriteEnabled,false)});

test('personal finance admin route hands off without exposing personal data',async()=>{const r=await worker.fetch(new Request('https://personal-finance-api.ekodi.kr/admin'),{});assert.equal(r.status,307);assert.equal(r.headers.get('location'),'https://admin.ekodi.kr/?route=finance&source=personal-finance-api.ekodi.kr')});

test('personal finance rejects untrusted browser origins',async()=>{const r=await worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/summary',{headers:{origin:'https://example.com'}}),{});assert.equal(r.status,403);assert.equal((await r.json()).code,'PF_ORIGIN_DENIED')});

test('personal finance fails closed without its dedicated D1 binding',async()=>{const r=await worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/summary'),{});assert.equal(r.status,503);assert.equal((await r.json()).code,'PF_DB_REQUIRED')});

test('personal finance requires a My EKODI member token',async()=>{const r=await worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/summary'),env(fakeDb()));assert.equal(r.status,401);assert.equal((await r.json()).code,'PF_AUTH_REQUIRED')});

test('account ownership comes only from the verified user token',async()=>{const DB=fakeDb();const r=await withUser('user-a',()=>worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/accounts',{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify({profileId:'user-b',accountType:'BANK',balanceRole:'asset',accountAlias:'생활비',institutionName:'NH',last4:'1234',currentBalance:150000})}),env(DB)));assert.equal(r.status,201);const insert=DB.calls.find(x=>x.kind==='run'&&/INSERT INTO personal_finance_accounts/.test(x.sql));assert.ok(insert);assert.equal(insert.args[1],'user-a');assert.notEqual(insert.args[1],'user-b')});

test('summary queries are always scoped to the verified profile',async()=>{const DB=fakeDb({first:(sql)=>/personal_finance_accounts/.test(sql)?{assets:1000,liabilities:250,accounts:2}:{inflow:500,outflow:200,transactions:3}});const r=await withUser('user-summary',()=>worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/summary',{headers:auth}),env(DB)));assert.equal(r.status,200);const d=await r.json();assert.equal(d.netWorth,750);const scoped=DB.calls.filter(x=>x.kind==='first');assert.equal(scoped.length,2);assert.ok(scoped.every(x=>x.args[0]==='user-summary'))});

test('import preview validates account ownership and marks server-detected duplicates',async()=>{let known='';const DB=fakeDb({first:(sql,args)=>/SELECT id,account_type/.test(sql)?{id:args[0],accountType:'BANK',balanceRole:'asset',currency:'KRW'}:null,all:(sql,args)=>{if(/duplicate_fingerprint/.test(sql)&&known)return[{fingerprint:known}];return[]}});const first=await withUser('user-import',()=>worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/import/preview',{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify({accountId:'acc-1',rows:[{date:'2026-09-05',direction:'OUTFLOW',amount:12000,merchant:'식당'}]})}),env(DB)));assert.equal(first.status,200);const p1=await first.json();assert.equal(p1.valid,1);assert.equal(p1.duplicates,0);known=p1.rows[0].fingerprint;const second=await withUser('user-import',()=>worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/import/preview',{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify({accountId:'acc-1',rows:[{date:'2026-09-05',direction:'OUTFLOW',amount:12000,merchant:'식당'}]})}),env(DB)));assert.equal((await second.json()).duplicates,1)});

test('import preview caps each batch at 500 rows',async()=>{const DB=fakeDb();const rows=Array.from({length:501},()=>({date:'2026-09-05',direction:'OUTFLOW',amount:1}));const r=await withUser('user-limit',()=>worker.fetch(new Request('https://personal-finance-api.ekodi.kr/api/finance/personal/import/preview',{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify({accountId:'acc',rows})}),env(DB)));assert.equal(r.status,400);assert.equal((await r.json()).code,'PF_IMPORT_SIZE')});
