import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import platformRouter from '../platform-router-entry-worker.js';
const root=new URL('../sites/seonam-medi/public/',import.meta.url);
test('seonam-medi civic channel keeps source attribution, media evidence and privacy boundaries',async()=>{const [html,data,app]=await Promise.all([readFile(new URL('index.html',root),'utf8'),readFile(new URL('data.json',root),'utf8'),readFile(new URL('app.js',root),'utf8')]);assert.match(html,/사실은 출처와 함께/);assert.match(html,/후원·회계 공개/);assert.match(html,/개인정보/);assert.match(html,/원출처 링크/);const parsed=JSON.parse(data);assert.ok(parsed.timeline.length>=10);assert.ok(parsed.sources.every(s=>s.publisher&&s.url));assert.equal(parsed.finance.raised,null);assert.equal(parsed.mediaPolicy.mode,'source-link-first');for(const row of parsed.timeline){assert.ok(Array.isArray(row.links));assert.ok(Array.isArray(row.media));for(const media of row.media){assert.ok(['photo','video'].includes(media.type));assert.match(media.url,/^https:\/\//);assert.ok(media.source)}}assert.ok(parsed.timeline.some(row=>row.media.some(media=>media.type==='photo')));assert.match(app,/mediaLabel/);assert.match(app,/safeUrl/);assert.match(html,/href="#notices">공지/);assert.match(html,/href="#organization">조직/);assert.match(html,/href="#channels">채널/);assert.match(app,/\/api\/seonam-medi\/notices/);assert.match(app,/\/api\/seonam-medi\/channels/);});

test('canonical path, assets and feedback API use seonam-medi',async()=>{const [html,app,build,router,wrangler]=await Promise.all([readFile(new URL('index.html',root),'utf8'),readFile(new URL('app.js',root),'utf8'),readFile(new URL('../scripts/build.mjs',import.meta.url),'utf8'),readFile(new URL('../platform-router-entry-worker.js',import.meta.url),'utf8'),readFile(new URL('../wrangler.site.toml',import.meta.url),'utf8')]);assert.match(html,/https:\/\/ekodi\.kr\/seonam-medi\//);assert.match(html,/\/seonam-medi\/app\.css/);assert.match(app,/\/api\/seonam-medi\/voices/);assert.match(build,/sites\/seonam-medi\/public/);assert.match(router,/SEONAM_MEDI_PREFIX='\/seonam-medi'/);assert.match(router,/SEONAM_MED_LEGACY_PREFIX='\/seonam-med'/);const workerFirst=(wrangler.match(/run_worker_first = \[(.*?)\]/s)?.[1].match(/\"[^\"]+\"/g)||[]);assert.ok(workerFirst.length<=100);assert.ok(wrangler.includes('\"/seonam-medi*\"'));assert.ok(!wrangler.includes('\"/seonam-med*\"'));assert.doesNotMatch(wrangler,/crons\s*=/);assert.match(html,/사이트 일일점검/);assert.match(app,/\/api\/seonam-medi\/monitor/);});

test('Shared Site router serves seonam-medi assets before generic workspace routing',async()=>{
  const env={ENVIRONMENT:'production',ASSETS:{fetch:async request=>{const path=new URL(request.url).pathname;const type=path.endsWith('.css')?'text/css; charset=utf-8':path.endsWith('.js')?'application/javascript; charset=utf-8':path.endsWith('.json')?'application/json; charset=utf-8':'text/html; charset=utf-8';return new Response(path,{status:200,headers:{'content-type':type}})}}};
  const home=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/'),env,{});
  assert.equal(home.status,200);assert.equal(home.headers.get('x-ekodi-route'),'seonam-medi-static');assert.match(home.headers.get('x-robots-tag')||'',/index, follow/);
  const css=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/app.css'),env,{});
  assert.equal(css.status,200);assert.equal(css.headers.get('x-ekodi-route'),'seonam-medi-static');assert.match(await css.text(),/\/seonam-medi\/app\.css/);
  const js=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/app.js'),env,{});
  assert.equal(js.status,200);assert.equal(js.headers.get('x-ekodi-route'),'seonam-medi-static');
  const old=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-med/app.css?v=1'),env,{});
  assert.equal(old.status,308);assert.equal(old.headers.get('location'),'https://ekodi.kr/seonam-medi/app.css?v=1');assert.equal(old.headers.get('x-ekodi-route'),'seonam-medi-canonical');
});

test('seonam-medi private mode blocks public content and search indexing while keeping admin route available',async()=>{
  const db={
    prepare(sql){return{bind(){return this},first:async()=>String(sql).startsWith('SELECT')?{public_status:'private'}:null}},
    batch:async()=>[]
  };
  const env={ENVIRONMENT:'production',DB:db,ASSETS:{fetch:async request=>new Response(new URL(request.url).pathname,{status:200,headers:{'content-type':'text/html; charset=utf-8'}})}};
  const hidden=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/'),env,{});
  assert.equal(hidden.status,404);assert.equal(hidden.headers.get('x-ekodi-public-site-mode'),'private');assert.match(hidden.headers.get('x-robots-tag')||'',/noindex/);
  const admin=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/admin/'),env,{});
  assert.equal(admin.status,200);assert.equal(admin.headers.get('x-ekodi-route'),'seonam-medi-static');assert.match(admin.headers.get('x-robots-tag')||'',/noindex/);
});

test('seonam-medi visibility is registered in the common public-site control catalog',async()=>{
  const [api,admin]=await Promise.all([readFile(new URL('../api-worker.js',import.meta.url),'utf8'),readFile(new URL('../admin-public-site-controls.js',import.meta.url),'utf8')]);
  assert.match(api,/id: 'seonam-medi'/);assert.match(api,/\['public', 'private', 'maintenance'\]/);
  assert.match(admin,/비공개 · 검색 차단/);assert.match(admin,/공개 · 검색 허용/);
});

test('dedicated admin console is site-scoped and grants the requested board administrator only notice and channel capabilities',async()=>{const [html,adminJs,adminCss,control,migration,directory,authSite]=await Promise.all([readFile(new URL('admin/index.html',root),'utf8'),readFile(new URL('admin/admin.js',root),'utf8'),readFile(new URL('admin/admin.css',root),'utf8'),readFile(new URL('../seonam-medi-admin-control.js',import.meta.url),'utf8'),readFile(new URL('../migrations/0113_seonam_medi_site_admin.sql',import.meta.url),'utf8'),readFile(new URL('../customer-member-directory.js',import.meta.url),'utf8'),readFile(new URL('../auth-site/auth.js',import.meta.url),'utf8')]);assert.doesNotMatch(html,/http-equiv="refresh"/);assert.match(html,/공지 관리/);assert.match(html,/채널 관리/);assert.match(html,/조직/);assert.match(adminJs,/\/api\/seonam-medi\/admin\/me/);assert.match(adminJs,/\/api\/seonam-medi\/admin\/notices/);assert.match(adminJs,/\/api\/seonam-medi\/admin\/channels/);assert.match(adminCss,/\.two-col/);assert.match(control,/seonam\.notice\.manage/);assert.match(control,/seonam\.channel\.manage/);assert.match(migration,/ohwon69@gmail\.com/);assert.match(migration,/'board_admin'/);assert.match(migration,/seonam\.notice\.manage/);assert.match(migration,/seonam\.channel\.manage/);assert.match(directory,/board_admin: '게시판 관리자'/);assert.match(adminJs,/site','seonam-medi'/);assert.match(authSite,/'seonam-medi':\{name:'서남권 국립의대 시민소통센터'/);assert.match(authSite,/site==='seonam-medi'/);});

test('site daily monitor is runtime-owned, source-only and media-evidence aware',async()=>{const [monitor,migration,mediaMigration,app,data]=await Promise.all([readFile(new URL('../seonam-medi-monitor.js',import.meta.url),'utf8'),readFile(new URL('../migrations/0104_seonam_medi_monitor.sql',import.meta.url),'utf8'),readFile(new URL('../migrations/0105_seonam_medi_media_evidence.sql',import.meta.url),'utf8'),readFile(new URL('app.js',root),'utf8'),readFile(new URL('data.json',root),'utf8')]);assert.match(monitor,/runSeonamMediDailyCheck/);assert.match(monitor,/aiProvider:false/);assert.match(monitor,/source_only/);assert.match(monitor,/news\.google\.com\/rss\/search/);assert.match(monitor,/enrichMedia/);assert.match(monitor,/og:video/);assert.match(monitor,/og:image/);assert.match(monitor,/mediaCandidateCount/);assert.match(migration,/seonam_medi_monitor_runs/);assert.match(migration,/seonam_medi_monitor_items/);assert.match(mediaMigration,/media_type/);assert.match(mediaMigration,/media_state/);assert.match(app,/attachMonitorMedia/);assert.match(app,/monitorMatches/);assert.match(app,/원문 확인 필요/);const parsed=JSON.parse(data);assert.ok(parsed.timeline.some(row=>Array.isArray(row.monitorKeywords)&&row.monitorKeywords.length));assert.match(parsed.mediaPolicy.autoLinkRule,/근거자료 후보/);});

test('seonam-medi static headers allow first-party assets while admin auth stays noindex and may reach Supabase',async()=>{const headers=await readFile(new URL('../_headers',import.meta.url),'utf8');assert.match(headers,/\/seonam-medi\/\*/);assert.match(headers,/style-src 'self'/);assert.match(headers,/script-src 'self'/);assert.match(headers,/connect-src 'self'/);assert.match(headers,/\/seonam-medi\/admin\/\*[\s\S]{0,500}renzehysxirjilvdxacv\.supabase\.co/);assert.match(headers,/\/seonam-medi\/admin\/\*[\s\S]{0,700}X-Robots-Tag: noindex, nofollow, noarchive/);assert.doesNotMatch(headers,/\/seonam-medi\*[\s\S]{0,300}script-src 'none'/);});

test('seonam-medi daily monitoring reuses the existing Control API cron instead of adding a sixth Cloudflare trigger',async()=>{const [siteWrangler,apiWrangler,mission,monitor,router]=await Promise.all([readFile(new URL('../wrangler.site.toml',import.meta.url),'utf8'),readFile(new URL('../wrangler.api.toml',import.meta.url),'utf8'),readFile(new URL('../mission-control-entry-worker.js',import.meta.url),'utf8'),readFile(new URL('../seonam-medi-monitor.js',import.meta.url),'utf8'),readFile(new URL('../platform-router-entry-worker.js',import.meta.url),'utf8')]);assert.doesNotMatch(siteWrangler,/\[triggers\]/);assert.match(apiWrangler,/crons = \["\*\/10 \* \* \* \*"\]/);assert.match(mission,/runSeonamMediDailyCheck/);assert.match(mission,/getUTCHours\(\) === 23/);assert.match(monitor,/status:'already_checked'/);assert.match(monitor,/existing-control-cron/);assert.doesNotMatch(router,/async scheduled\(_controller,env,ctx\)/);});


test('seonam-medi source changes are wired to both Shared Site and Control API releases',async()=>{const [shared,control,manifestText]=await Promise.all([readFile(new URL('../.github/workflows/deploy-site-core.yml',import.meta.url),'utf8'),readFile(new URL('../.github/workflows/deploy-control-api.yml',import.meta.url),'utf8'),readFile(new URL('../deploy/manifests/shared-site.worker.json',import.meta.url),'utf8')]);for(const marker of ["sites/seonam-medi/public/**","seonam-medi-monitor.js","seonam-medi-civic-control.js","seonam-medi-admin-control.js","test/seonam-medi-site.test.mjs"])assert.ok(shared.includes(marker),marker);for(const marker of ["seonam-medi-monitor.js","seonam-medi-civic-control.js","test/seonam-medi-site.test.mjs"])assert.ok(control.split(marker).length>=3,marker);const manifest=JSON.parse(manifestText);const urls=new Set(manifest.worker.requests.map(item=>item.url));for(const url of ['https://ekodi.kr/seonam-medi/','https://ekodi.kr/seonam-medi/app.js','https://ekodi.kr/seonam-medi/data.json','https://ekodi.kr/seonam-med'])assert.ok(urls.has(url),url);});
