import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import platformRouter from '../platform-router-entry-worker.js';
const root=new URL('../sites/seonam-medi/public/',import.meta.url);
test('seonam-medi civic channel keeps source attribution, media evidence and privacy boundaries',async()=>{const [html,data,app]=await Promise.all([readFile(new URL('index.html',root),'utf8'),readFile(new URL('data.json',root),'utf8'),readFile(new URL('app.js',root),'utf8')]);assert.match(html,/사실은 출처와 함께/);assert.match(html,/후원·회계 공개/);assert.match(html,/개인정보/);assert.match(html,/원출처 링크/);const parsed=JSON.parse(data);assert.ok(parsed.timeline.length>=10);assert.ok(parsed.sources.every(s=>s.publisher&&s.url));assert.equal(parsed.finance.raised,null);assert.equal(parsed.mediaPolicy.mode,'source-link-first');for(const row of parsed.timeline){assert.ok(Array.isArray(row.links));assert.ok(Array.isArray(row.media));for(const media of row.media){assert.ok(['photo','video'].includes(media.type));assert.match(media.url,/^https:\/\//);assert.ok(media.source)}}assert.ok(parsed.timeline.some(row=>row.media.some(media=>media.type==='photo')));assert.match(app,/mediaLabel/);assert.match(app,/safeUrl/);});

test('canonical path, assets and feedback API use seonam-medi',async()=>{const [html,app,build,router,wrangler]=await Promise.all([readFile(new URL('index.html',root),'utf8'),readFile(new URL('app.js',root),'utf8'),readFile(new URL('../scripts/build.mjs',import.meta.url),'utf8'),readFile(new URL('../platform-router-entry-worker.js',import.meta.url),'utf8'),readFile(new URL('../wrangler.site.toml',import.meta.url),'utf8')]);assert.match(html,/https:\/\/ekodi\.kr\/seonam-medi\//);assert.match(html,/\/seonam-medi\/app\.css/);assert.match(app,/\/api\/seonam-medi\/voices/);assert.match(build,/sites\/seonam-medi\/public/);assert.match(router,/SEONAM_MEDI_PREFIX='\/seonam-medi'/);assert.match(router,/SEONAM_MED_LEGACY_PREFIX='\/seonam-med'/);const workerFirst=(wrangler.match(/run_worker_first = \[(.*?)\]/s)?.[1].match(/\"[^\"]+\"/g)||[]);assert.ok(workerFirst.length<=100);assert.doesNotMatch(wrangler,/\"\/seonam-medi\\\*\"/);assert.doesNotMatch(wrangler,/\"\/seonam-med\\\*\"/);assert.match(wrangler,/crons = \["0 23 \* \* \*"\]/);assert.match(html,/사이트 일일점검/);assert.match(app,/\/api\/seonam-medi\/monitor/);});

test('Shared Site router serves seonam-medi assets before generic workspace routing',async()=>{
  const env={ENVIRONMENT:'production',ASSETS:{fetch:async request=>{const path=new URL(request.url).pathname;const type=path.endsWith('.css')?'text/css; charset=utf-8':path.endsWith('.js')?'application/javascript; charset=utf-8':path.endsWith('.json')?'application/json; charset=utf-8':'text/html; charset=utf-8';return new Response(path,{status:200,headers:{'content-type':type}})}}};
  const css=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/app.css'),env,{});
  assert.equal(css.status,200);assert.equal(css.headers.get('x-ekodi-route'),'seonam-medi-static');assert.match(await css.text(),/\/seonam-medi\/app\.css/);
  const js=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-medi/app.js'),env,{});
  assert.equal(js.status,200);assert.equal(js.headers.get('x-ekodi-route'),'seonam-medi-static');
  const old=await platformRouter.fetch(new Request('https://ekodi.kr/seonam-med/app.css?v=1'),env,{});
  assert.equal(old.status,308);assert.equal(old.headers.get('location'),'https://ekodi.kr/seonam-medi/app.css?v=1');assert.equal(old.headers.get('x-ekodi-route'),'seonam-medi-canonical');
});

test('site daily monitor is runtime-owned and source-only',async()=>{const [monitor,migration]=await Promise.all([readFile(new URL('../seonam-medi-monitor.js',import.meta.url),'utf8'),readFile(new URL('../migrations/0104_seonam_medi_monitor.sql',import.meta.url),'utf8')]);assert.match(monitor,/runSeonamMediDailyCheck/);assert.match(monitor,/aiProvider:false/);assert.match(monitor,/source_only/);assert.match(monitor,/news\.google\.com\/rss\/search/);assert.match(migration,/seonam_medi_monitor_runs/);assert.match(migration,/seonam_medi_monitor_items/);});

test('seonam-medi static headers allow its first-party CSS, JS and API calls',async()=>{const headers=await readFile(new URL('../_headers',import.meta.url),'utf8');assert.match(headers,/\/seonam-medi\/\*/);assert.match(headers,/style-src 'self'/);assert.match(headers,/script-src 'self'/);assert.match(headers,/connect-src 'self'/);assert.doesNotMatch(headers,/\/seonam-medi\*[\s\S]{0,300}script-src 'none'/);});

test('seonam-medi daily monitoring reuses the existing Control API cron instead of adding a sixth Cloudflare trigger',async()=>{const [siteWrangler,apiWrangler,mission,monitor,router]=await Promise.all([readFile(new URL('../wrangler.site.toml',import.meta.url),'utf8'),readFile(new URL('../wrangler.api.toml',import.meta.url),'utf8'),readFile(new URL('../mission-control-entry-worker.js',import.meta.url),'utf8'),readFile(new URL('../seonam-medi-monitor.js',import.meta.url),'utf8'),readFile(new URL('../platform-router-entry-worker.js',import.meta.url),'utf8')]);assert.doesNotMatch(siteWrangler,/\[triggers\]/);assert.match(apiWrangler,/crons = \["\*\/10 \* \* \* \*"\]/);assert.match(mission,/runSeonamMediDailyCheck/);assert.match(mission,/getUTCHours\(\) === 23/);assert.match(monitor,/status:'already_checked'/);assert.match(monitor,/existing-control-cron/);assert.doesNotMatch(router,/async scheduled\(_controller,env,ctx\)/);});
