export const SUPPORT_STAGES=Object.freeze(['discovery','fit-review','application-prep','submitted','document-review','presentation','selected','agreement','execution','mid-review','change-control','final-report','settlement','completed','follow-up']);

export const OPPORTUNITY_SERVICES=Object.freeze([
  {id:'grant',path:'/grants',label:'지원금AI',title:'사업·성장 지원금',description:'소상공인·기업·기관의 사업화, 기술, 마케팅, 시설, 경영 지원사업을 찾고 신청부터 수행·정산까지 관리합니다.',audiences:['사업자','소상공인','기관·단체'],keywords:['지원사업','지원금','사업화','기술','마케팅','디지털','경영','시설','소상공인'],sourceStatus:'live'},
  {id:'subsidy',path:'/subsidies',label:'보조금AI',title:'비용·생활 보조',description:'정부·지자체의 비용지원, 환급, 감면, 바우처와 보조사업을 조건별로 연결합니다.',audiences:['개인','가정','사업자','기관·단체'],keywords:['보조금','보조사업','지원비','환급','감면','바우처','비용지원'],sourceStatus:'expanding'},
  {id:'scholarship',path:'/scholarships',label:'장학금AI',title:'학업·연구 장학',description:'학생·청년·연구자의 학교, 전공, 지역, 소득, 성적 조건에 맞는 장학기회를 연결합니다.',audiences:['학생','청년','연구자'],keywords:['장학금','장학생','학자금','등록금','연구장려금','학업지원'],sourceStatus:'expanding'},
  {id:'contest',path:'/contests',label:'공모AI',title:'공모·프로젝트',description:'기관·단체·교회·기업의 목적과 수행역량에 맞는 공모사업과 프로젝트 재원을 연결합니다.',audiences:['기관·단체','교회','비영리','기업'],keywords:['공모','공모사업','모집','프로젝트','수행기관','사업계획'],sourceStatus:'expanding'},
  {id:'welfare',path:'/welfare',label:'복지AI',title:'복지·생활 지원',description:'개인과 가정의 생애주기, 소득, 지역, 상황에 맞는 복지급여와 생활지원 제도를 연결합니다.',audiences:['개인','가정','청년','시니어'],keywords:['복지','급여','생활지원','돌봄','주거지원','의료지원','바우처'],sourceStatus:'expanding'},
  {id:'private',path:'/private-support',label:'민간지원AI',title:'재단·기업·민간 지원',description:'재단, 기업 사회공헌, 민간단체의 지원사업을 공공지원과 함께 비교해 연결합니다.',audiences:['개인','단체','지역사회'],keywords:['재단','민간지원','사회공헌','CSR','기부','지원재단'],sourceStatus:'planned'},
  {id:'sponsorship',path:'/sponsorship',label:'후원AI',title:'후원·자원 연결',description:'후원하고 싶은 사람·기업과 필요한 사람·프로젝트를 조건과 목적에 따라 안전하게 연결합니다.',audiences:['후원자','기업','단체','프로젝트'],keywords:['후원','후원자','기부','매칭','사회공헌','프로젝트 후원'],sourceStatus:'planned'}
]);

const SERVICE_PATHS=new Map(OPPORTUNITY_SERVICES.map(service=>[service.path,service.id]));
const SERVICE_BY_ID=new Map(OPPORTUNITY_SERVICES.map(service=>[service.id,service]));
export function getOpportunityService(id='grant'){return SERVICE_BY_ID.get(id)||SERVICE_BY_ID.get('grant')}
export function resolveOpportunityService(pathname='/',fallback='all'){const clean=String(pathname||'/').replace(/\/$/,'')||'/';return SERVICE_PATHS.get(clean)||fallback}

export function nextStage(stage){const i=SUPPORT_STAGES.indexOf(stage);return i<0?SUPPORT_STAGES[0]:SUPPORT_STAGES[Math.min(i+1,SUPPORT_STAGES.length-1)]}
export function normalizeText(value){return String(value||'').replace(/\s+/g,' ').trim()}
function extractDeadline(text){const m=String(text||'').match(/(20\d{2}[.\-/]\s?\d{1,2}[.\-/]\s?\d{1,2}|\d{1,2}월\s?\d{1,2}일)/);return m?m[1]:null}
function extractDocument(text){return ['사업계획서','신청서','협약서','결과보고서','정산보고서','증빙자료','발표자료','수행계획서'].find(k=>String(text||'').includes(k))||null}
export function analyzeGuidanceChange(previous,current){const before=normalizeText(previous),after=normalizeText(current);if(!before&&!after)return{kind:'UNCHANGED',changed:false,impact:'none',action:'none',deadline:null,document:null};if(!before&&after)return{kind:'NEW',changed:true,impact:'review-required',action:'review-new-guidance',deadline:extractDeadline(after),document:extractDocument(after)};if(before===after)return{kind:'UNCHANGED',changed:false,impact:'none',action:'none',deadline:extractDeadline(after),document:extractDocument(after)};const prior=new Set(before.split(' '));const added=after.split(' ').filter(t=>!prior.has(t));return{kind:'CHANGED',changed:true,impact:added.length?'possible-project-impact':'review-required',action:'compare-and-confirm',deadline:extractDeadline(after),document:extractDocument(after),added:added.slice(0,30)}}
function includesLoose(haystack,needle){const h=normalizeText(haystack).toLowerCase(),n=normalizeText(needle).toLowerCase();return !n||h.includes(n)||n.includes(h)}

export function classifyOpportunity(notice={}){
  const text=normalizeText([notice.title,notice.summary,notice.target,notice.category,notice.agency,notice.operator,...(notice.tags||[])].filter(Boolean).join(' ')).toLowerCase();
  let best={id:'grant',score:0};
  for(const service of OPPORTUNITY_SERVICES){
    const score=service.keywords.reduce((total,keyword)=>total+(text.includes(String(keyword).toLowerCase())?1:0),0);
    if(score>best.score)best={id:service.id,score};
  }
  return{...getOpportunityService(best.id),matchScore:best.score};
}

export function scoreOpportunity(profile={},notice={}){const checks=[['region',notice.region],['industry',notice.industry],['businessType',notice.businessType],['employeeBand',notice.employeeBand]];let applicable=0,matched=0;for(const[key,rule]of checks){if(!rule)continue;applicable++;const values=Array.isArray(rule)?rule:[rule];if(values.some(v=>includesLoose(profile[key],v)))matched++}let base=applicable?Math.round(matched/applicable*80):50;const text=[notice.title,notice.summary,notice.target,notice.category,...(notice.tags||[])].join(' ');const interests=[profile.industry,profile.need,...(profile.interests||[]),...(profile.keywords||[])].filter(Boolean);const keywordHits=new Set(interests.filter(v=>includesLoose(text,v))).size;base+=Math.min(keywordHits*4,12);const readiness=['businessName','registrationNumber','summary','recentRevenue'].reduce((n,k)=>n+(profile[k]?1:0),0)*5;const generalReadiness=['profileType','region','need'].reduce((n,k)=>n+(profile[k]?1:0),0)*2;return Math.min(100,base+readiness+generalReadiness)}
export function fillOfficialForm(schema=[],profile={},project={}){return schema.map(field=>{const key=field.key;const source=Object.prototype.hasOwnProperty.call(project,key)?'project':Object.prototype.hasOwnProperty.call(profile,key)?'profile':'missing';const value=source==='project'?project[key]:source==='profile'?profile[key]:'';return{...field,value,source,needsHumanReview:field.highImpact===true||source==='missing'}})}
export function buildNextActions(project={}){const stage=project.stage||'discovery';const map={discovery:['공식 공고문 확보','지원자격 확인'],'fit-review':['적합도 검토','중복수혜·제외조건 확인'],'application-prep':['공식 양식 확보','부족정보 보완','사업계획서 검수'],submitted:['접수증 보관','추가 공지 모니터링'],'document-review':['보완요청 확인','평가기준 재점검'],presentation:['발표자료 준비','예상질문 점검'],selected:['최종 선정 공문 확인','협약조건 검토'],agreement:['협약서 검수','자부담·의무사항 확인'],execution:['수행일정 관리','지출·성과 증빙 축적'],'mid-review':['중간보고 작성','변경사항 사전승인 확인'],'change-control':['변경승인 근거 보관','예산·일정 재검증'],'final-report':['결과보고서 작성','성과근거 연결'],settlement:['정산서류 검수','불인정 가능 지출 확인'],completed:['완료자료 보존','성과 프로필 반영'],'follow-up':['후속 지원사업 탐색']};return map[stage]||map.discovery}
export function requiresHumanGate(action){return['submit','sign','agreement','payment','budget-change','settlement','withdraw'].includes(String(action||'').toLowerCase())}
function parseEndDate(period){const matches=String(period||'').match(/20\d{6}/g);if(!matches?.length)return null;const v=matches[matches.length-1];return new Date(`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}T23:59:59+09:00`)}
export function opportunityUrgency(notice={},now=new Date()){const end=parseEndDate(notice.applicationPeriod);if(!end)return{daysLeft:null,level:'unknown'};const daysLeft=Math.ceil((end-now)/(24*60*60*1000));return{daysLeft,level:daysLeft<0?'closed':daysLeft<=3?'critical':daysLeft<=7?'soon':'normal'}}
export function rankOpportunities(profile={},notices=[],options={}){const now=options.now?new Date(options.now):new Date();return notices.map(notice=>{const score=scoreOpportunity(profile,notice),urgency=opportunityUrgency(notice,now),specialist=classifyOpportunity(notice);const serviceMatch=!options.serviceId||options.serviceId==='all'||specialist.id===options.serviceId;const actionable=serviceMatch&&urgency.level!=='closed'&&score>=(options.minScore??55);return{...notice,score,urgency,specialist:{id:specialist.id,label:specialist.label,path:specialist.path},serviceMatch,actionable,recommendation:score>=80?'적극 검토':score>=65?'검토 권장':score>=55?'조건 확인':'우선순위 낮음'}}).sort((a,b)=>Number(b.actionable)-Number(a.actionable)||Number(b.serviceMatch)-Number(a.serviceMatch)||b.score-a.score||((a.urgency.daysLeft??9999)-(b.urgency.daysLeft??9999)))}
export function buildProactiveBrief(profile={},notices=[],projects=[],options={}){const ranked=rankOpportunities(profile,notices,options);const opportunities=ranked.filter(x=>x.actionable).slice(0,5);const projectActions=projects.flatMap(project=>buildNextActions(project).slice(0,2).map(action=>({projectId:project.id||null,projectName:project.name||project.title||'지원사업',stage:project.stage||'discovery',action}))).slice(0,8);const urgent=opportunities.filter(x=>['critical','soon'].includes(x.urgency.level));return{generatedAt:new Date().toISOString(),serviceId:options.serviceId||'all',summary:urgent.length?`마감 임박 ${urgent.length}건을 포함해 우선 검토할 기회 ${opportunities.length}건이 있습니다.`:`우선 검토할 기회 ${opportunities.length}건과 진행 중 과제의 다음 행동을 정리했습니다.`,opportunities,projectActions,humanReviewRequired:true,autoSubmission:false}}
