export const SUPPORT_STAGES=Object.freeze(['discovery','fit-review','application-prep','submitted','document-review','presentation','selected','agreement','execution','mid-review','change-control','final-report','settlement','completed','follow-up']);
export function nextStage(stage){const i=SUPPORT_STAGES.indexOf(stage);return i<0?SUPPORT_STAGES[0]:SUPPORT_STAGES[Math.min(i+1,SUPPORT_STAGES.length-1)]}
export function normalizeText(value){return String(value||'').replace(/\s+/g,' ').trim()}
function extractDeadline(text){const m=String(text||'').match(/(20\d{2}[.\-/]\s?\d{1,2}[.\-/]\s?\d{1,2}|\d{1,2}월\s?\d{1,2}일)/);return m?m[1]:null}
function extractDocument(text){return ['사업계획서','신청서','협약서','결과보고서','정산보고서','증빙자료','발표자료','수행계획서'].find(k=>String(text||'').includes(k))||null}
export function analyzeGuidanceChange(previous,current){const before=normalizeText(previous),after=normalizeText(current);if(!before&&!after)return{kind:'UNCHANGED',changed:false,impact:'none',action:'none',deadline:null,document:null};if(!before&&after)return{kind:'NEW',changed:true,impact:'review-required',action:'review-new-guidance',deadline:extractDeadline(after),document:extractDocument(after)};if(before===after)return{kind:'UNCHANGED',changed:false,impact:'none',action:'none',deadline:extractDeadline(after),document:extractDocument(after)};const prior=new Set(before.split(' '));const added=after.split(' ').filter(t=>!prior.has(t));return{kind:'CHANGED',changed:true,impact:added.length?'possible-project-impact':'review-required',action:'compare-and-confirm',deadline:extractDeadline(after),document:extractDocument(after),added:added.slice(0,30)}}
function includesLoose(haystack,needle){const h=normalizeText(haystack).toLowerCase(),n=normalizeText(needle).toLowerCase();return !n||h.includes(n)||n.includes(h)}
export function scoreOpportunity(profile={},notice={}){const checks=[['region',notice.region],['industry',notice.industry],['businessType',notice.businessType],['employeeBand',notice.employeeBand]];let applicable=0,matched=0;for(const[key,rule]of checks){if(!rule)continue;applicable++;const values=Array.isArray(rule)?rule:[rule];if(values.some(v=>includesLoose(profile[key],v)))matched++}let base=applicable?Math.round(matched/applicable*65):45;const text=[notice.title,notice.summary,notice.target,notice.category,...(notice.tags||[])].join(' ');const interests=[profile.industry,profile.businessType,profile.region,...(profile.interests||[]),...(profile.keywords||[])].filter(Boolean);const keywordHits=new Set(interests.filter(v=>includesLoose(text,v))).size;base+=Math.min(keywordHits*5,20);const readiness=['businessName','registrationNumber','summary','recentRevenue'].reduce((n,k)=>n+(profile[k]?1:0),0)*4;return Math.min(100,base+readiness)}
export function fillOfficialForm(schema=[],profile={},project={}){return schema.map(field=>{const key=field.key;const source=Object.prototype.hasOwnProperty.call(project,key)?'project':Object.prototype.hasOwnProperty.call(profile,key)?'profile':'missing';const value=source==='project'?project[key]:source==='profile'?profile[key]:'';return{...field,value,source,needsHumanReview:field.highImpact===true||source==='missing'}})}
export function buildNextActions(project={}){const stage=project.stage||'discovery';const map={discovery:['공식 공고문 확보','지원자격 확인'],'fit-review':['적합도 검토','중복수혜·제외조건 확인'],'application-prep':['공식 양식 확보','부족정보 보완','사업계획서 검수'],submitted:['접수증 보관','추가 공지 모니터링'],'document-review':['보완요청 확인','평가기준 재점검'],presentation:['발표자료 준비','예상질문 점검'],selected:['최종 선정 공문 확인','협약조건 검토'],agreement:['협약서 검수','자부담·의무사항 확인'],execution:['수행일정 관리','지출·성과 증빙 축적'],'mid-review':['중간보고 작성','변경사항 사전승인 확인'],'change-control':['변경승인 근거 보관','예산·일정 재검증'],'final-report':['결과보고서 작성','성과근거 연결'],settlement:['정산서류 검수','불인정 가능 지출 확인'],completed:['완료자료 보존','성과 프로필 반영'],'follow-up':['후속 지원사업 탐색']};return map[stage]||map.discovery}
export function requiresHumanGate(action){return['submit','sign','agreement','payment','budget-change','settlement','withdraw'].includes(String(action||'').toLowerCase())}
function parseEndDate(period){const matches=String(period||'').match(/20\d{6}/g);if(!matches?.length)return null;const v=matches[matches.length-1];return new Date(`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}T23:59:59+09:00`)}
export function opportunityUrgency(notice={},now=new Date()){const end=parseEndDate(notice.applicationPeriod);if(!end)return{daysLeft:null,level:'unknown'};const daysLeft=Math.ceil((end-now)/(24*60*60*1000));return{daysLeft,level:daysLeft<0?'closed':daysLeft<=3?'critical':daysLeft<=7?'soon':'normal'}}
export function rankOpportunities(profile={},notices=[],options={}){const now=options.now?new Date(options.now):new Date();return notices.map(notice=>{const score=scoreOpportunity(profile,notice),urgency=opportunityUrgency(notice,now);const actionable=urgency.level!=='closed'&&score>=(options.minScore??55);return{...notice,score,urgency,actionable,recommendation:score>=80?'적극 검토':score>=65?'검토 권장':score>=55?'조건 확인':'우선순위 낮음'}}).sort((a,b)=>Number(b.actionable)-Number(a.actionable)||b.score-a.score||((a.urgency.daysLeft??9999)-(b.urgency.daysLeft??9999)))}
export function buildProactiveBrief(profile={},notices=[],projects=[],options={}){const ranked=rankOpportunities(profile,notices,options);const opportunities=ranked.filter(x=>x.actionable).slice(0,5);const projectActions=projects.flatMap(project=>buildNextActions(project).slice(0,2).map(action=>({projectId:project.id||null,projectName:project.name||project.title||'지원사업',stage:project.stage||'discovery',action}))).slice(0,8);const urgent=opportunities.filter(x=>['critical','soon'].includes(x.urgency.level));return{generatedAt:new Date().toISOString(),summary:urgent.length?`마감 임박 ${urgent.length}건을 포함해 우선 검토할 지원사업 ${opportunities.length}건이 있습니다.`:`우선 검토할 지원사업 ${opportunities.length}건과 진행 중 과제의 다음 행동을 정리했습니다.`,opportunities,projectActions,humanReviewRequired:true,autoSubmission:false}}
