const BIZINFO_DEFAULT_URL='https://www.bizinfo.go.kr/uss/rss/bizinfoApi.do';
const BIZINFO_PUBLIC_URL='https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/list.do';
const entity=v=>String(v??'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');
const clean=v=>entity(String(v??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();
const splitTags=v=>clean(v).split(',').map(s=>s.trim()).filter(Boolean);
const regionFrom=(...values)=>['서울','부산','대구','인천','전남광주','대전','울산','세종','경기','강원','충북','충남','전북','경북','경남','제주'].find(r=>values.some(v=>String(v||'').includes(r)))||'';
export function normalizeBizinfoItem(item={}){const tags=splitTags(item.hashTags||item.hashTagsNm||'');const period=clean(item.reqstBeginEndDe||item.reqstDt||'');return{id:clean(item.pblancId||item.seq),source:'bizinfo',sourceName:'기업마당',sourceMode:'api',official:true,title:clean(item.pblancNm||item.title),url:clean(item.pblancUrl||item.link),agency:clean(item.jrsdInsttNm||item.author),operator:clean(item.excInsttNm),summary:clean(item.bsnsSumryCn||item.description),category:clean(item.pldirSportRealmLclasCodeNm||item.lcategory),target:clean(item.trgetNm),applicationMethod:clean(item.reqstMthPapersCn),applicationUrl:clean(item.rceptEngnHmpgUrl),contact:clean(item.refrncNm),applicationPeriod:period,publishedAt:clean(item.creatPnttm||item.pubDate),attachmentUrl:clean(item.flpthNm||item.printFlpthNm),attachmentName:clean(item.fileNm||item.printFileNm),tags,region:regionFrom(...tags),industry:'',businessType:clean(item.trgetNm),raw:item}}
export function normalizeBizinfoResponse(payload={}){const root=payload?.jsonArray||payload?.response||payload||{};const items=Array.isArray(root.item)?root.item:root.item?[root.item]:[];return items.map(normalizeBizinfoItem).filter(x=>x.id&&x.title)}
export function parseBizinfoPublicHtml(html='',base=BIZINFO_PUBLIC_URL){const body=(String(html).match(/<tbody[^>]*>([\s\S]*?)<\/tbody>/i)||[])[1]||String(html);const rows=[...body.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)];return rows.map((m,index)=>{const cells=[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>x[1]);if(cells.length<6)return null;const anchor=(cells[2]||'').match(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);const title=clean(anchor?.[2]||cells[2]);if(!title)return null;let url='';try{url=new URL(entity(anchor?.[1]||''),base).toString()}catch{}const id=(url.match(/[?&]pblancId=([^&#]+)/)||[])[1]||`public-${clean(cells[0])||index}`;const category=clean(cells[1]),period=clean(cells[3]),agency=clean(cells[4]),operator=clean(cells[5]),publishedAt=clean(cells[6]);return{id,source:'bizinfo',sourceName:'기업마당',sourceMode:'public-list',official:true,title,url,agency,operator,summary:'',category,target:'',applicationMethod:'',applicationUrl:'',contact:'',applicationPeriod:period,publishedAt,attachmentUrl:'',attachmentName:'',tags:[category,regionFrom(title,agency)].filter(Boolean),region:regionFrom(title,agency),industry:'',businessType:'',raw:null}}).filter(Boolean)}
export function officialSourceStatus(env={}){return[{id:'bizinfo',name:'기업마당',official:true,mode:env.BIZINFO_API_KEY?'ready_api':'ready_public',endpoint:env.BIZINFO_API_KEY?(env.BIZINFO_API_URL||BIZINFO_DEFAULT_URL):(env.BIZINFO_PUBLIC_URL||BIZINFO_PUBLIC_URL),credential:env.BIZINFO_API_KEY?'configured':'optional_for_richer_data',capabilities:env.BIZINFO_API_KEY?['latest-notices','category-filter','hashtag-filter','attachments']:['latest-notices','category','period','agency','operator']},{id:'kstartup',name:'K-Startup',official:true,mode:env.KSTARTUP_API_URL?'ready':'configured-next',endpoint:env.KSTARTUP_API_URL||'https://www.k-startup.go.kr/',credential:env.KSTARTUP_API_URL?'runtime-configured':'adapter-pending',capabilities:['startup-notices','target-filter','region-filter']} ]}
async function fetchPublic(env={},options={}){const response=await fetch(env.BIZINFO_PUBLIC_URL||BIZINFO_PUBLIC_URL,{headers:{accept:'text/html,application/xhtml+xml'},redirect:'follow',cf:{cacheTtl:300,cacheEverything:true}});if(!response.ok)return{ok:false,source:'bizinfo',reason:`public_upstream_${response.status}`,items:[]};const items=parseBizinfoPublicHtml(await response.text(),response.url).slice(0,Math.min(Math.max(Number(options.limit)||30,1),100));return{ok:true,source:'bizinfo',sourceMode:'public-list',fetchedAt:new Date().toISOString(),items}}
export async function fetchBizinfoNotices(env={},options={}){if(!env.BIZINFO_API_KEY)return fetchPublic(env,options);const endpoint=new URL(env.BIZINFO_API_URL||BIZINFO_DEFAULT_URL);endpoint.searchParams.set('crtfcKey',env.BIZINFO_API_KEY);endpoint.searchParams.set('dataType','json');endpoint.searchParams.set('searchCnt',String(Math.min(Math.max(Number(options.limit)||100,1),300)));if(options.category)endpoint.searchParams.set('searchLclasId',String(options.category));if(options.hashtags)endpoint.searchParams.set('hashtags',Array.isArray(options.hashtags)?options.hashtags.join(','):String(options.hashtags));const response=await fetch(endpoint.toString(),{headers:{accept:'application/json'},cf:{cacheTtl:300,cacheEverything:true}});if(!response.ok)return fetchPublic(env,options);let payload;try{payload=await response.json()}catch{return fetchPublic(env,options)}return{ok:true,source:'bizinfo',sourceMode:'api',fetchedAt:new Date().toISOString(),items:normalizeBizinfoResponse(payload)}}
