import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg=window.EKODI_LIFE_CONFIG||{};
const enabled=Boolean(cfg.dataEnabled&&cfg.supabaseUrl&&cfg.supabasePublishableKey);
const sb=enabled?createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{detectSessionInUrl:true,persistSession:true}}):null;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const TOPIC_COPY={relationship:'사람 사이의 거리와 사랑',money:'돈·생활·사업의 불안',work:'일·진로·소명의 방향',family:'가족 안의 기대와 돌봄',heart:'불안·지침·마음의 무게',future:'선택과 앞으로의 길',faith:'믿음·의심·하나님',meaning:'삶·의미·상실과 희망'};
let session=null;let selectedTopic='';let currentReflection=null;

function authUrl(){const u=new URL(cfg.authUrl||'https://auth.ekodi.kr/?site=life');u.searchParams.set('site','life');u.searchParams.set('return_to',location.href.split('#')[0]);return u.href}
async function handoff(){if(!sb||!location.hash.startsWith('#'))return;const p=new URLSearchParams(location.hash.slice(1));const token=p.get('ekodi_token');if(!token)return;const {error}=await sb.auth.verifyOtp({token_hash:token,type:p.get('ekodi_type')||'email'});history.replaceState({},document.title,location.pathname+location.search);if(error)throw error}
async function refreshSession(){if(!sb)return;session=(await sb.auth.getSession()).data.session;renderAuth()}
function renderAuth(){const b=$('#authButton');if(!b)return;if(!enabled){b.textContent='무료 이용';b.disabled=true;return}b.disabled=false;b.textContent=session?'로그아웃':'Google로 시작'}
async function authAction(){if(!enabled)return;if(!session){location.assign(authUrl());return}await sb.auth.signOut();session=null;renderAuth();note('로그아웃했습니다.')}
function note(message,urgent=false){const el=$('#statusNote');if(!el)return;el.textContent=message||'';el.classList.toggle('urgent',urgent)}
function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch])}

function renderTopics(topics=[]){const host=$('#topics');host.innerHTML='';for(const topic of topics){const b=document.createElement('button');b.type='button';b.className='topic-chip';b.dataset.topic=topic.id;b.textContent=topic.label;b.setAttribute('aria-pressed',String(selectedTopic===topic.id));b.addEventListener('click',()=>selectTopic(topic.id));host.append(b)}renderServices(topics)}
function renderServices(topics=[]){const host=$('#serviceGrid');if(!host)return;host.innerHTML=topics.map(topic=>`<button class="service-card" type="button" data-service-topic="${esc(topic.id)}"><strong>${esc(topic.label)}</strong><span>${esc(TOPIC_COPY[topic.id]||topic.rootQuestion||'삶의 질문을 함께 살펴봅니다')}</span></button>`).join('');$$('[data-service-topic]',host).forEach(b=>b.addEventListener('click',()=>{selectTopic(b.dataset.serviceTopic);$('#story')?.focus();$('.question-card')?.scrollIntoView({behavior:'smooth',block:'center'})}))}
function selectTopic(id){selectedTopic=id;$$('.topic-chip').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.topic===id)));const copy=TOPIC_COPY[id];if(copy)$('#story').placeholder=`${copy}에 대해 지금 떠오르는 이야기를 적어 보세요.`}
function renderReflection(r){currentReflection=r;$('#responsePanel').hidden=false;$('#responseTopic').textContent=r.topic?.label||'삶의 질문';$('#mirrorText').textContent=r.mirror||r.notice||'';$('#rootQuestion').textContent=r.rootQuestion||'';$('#nextQuestion').textContent=r.nextQuestion||'';$('#todayAction').textContent=r.action||'';$('#scriptures').innerHTML=(r.scriptures||[]).map(v=>`<span class="scripture-pill">${esc(v)}</span>`).join('')||'<span class="scripture-pill">지금은 사람의 도움이 먼저입니다</span>';note(r.notice||'',Boolean(r.urgent));$('#aiButton').disabled=Boolean(r.urgent);$('#responsePanel').scrollIntoView({behavior:'smooth',block:'start'})}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;const r=await fetch(path,{...options,headers,cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`http_${r.status}`);return data}
async function submitReflection(event){event.preventDefault();const story=$('#story').value.trim();if(!story){note('지금 떠오르는 이야기를 한 줄만 적어도 좋습니다.');return}if(enabled&&!session){try{sessionStorage.setItem('ekodi-life-pending-story',story);sessionStorage.setItem('ekodi-life-pending-topic',selectedTopic||'')}catch{}note('Google 로그인한 무료회원부터 질문 대화를 이용할 수 있습니다.');location.assign(authUrl());return}const submit=event.currentTarget.querySelector('button[type=submit]');submit.disabled=true;note('');try{const data=await api('/api/reflect',{method:'POST',body:JSON.stringify({message:story,topic:selectedTopic})});renderReflection(data.reflection)}catch(error){note('질문을 정리하지 못했습니다. 잠시 후 다시 시도해 주세요.')}finally{submit.disabled=false}}

async function continueWithAi(){if(!currentReflection)return;const button=$('#aiButton');button.disabled=true;$('#aiReply').hidden=true;note('대화를 이어가는 중입니다…');try{const story=$('#story').value.trim();const data=await api('/api/ai',{method:'POST',body:JSON.stringify({message:story,topic:currentReflection.topic?.id||selectedTopic})});if(data.reflection)currentReflection=data.reflection;const text=data.text||data.reply||data.notice||currentReflection.nextQuestion||'';const box=$('#aiReply');box.textContent=text;box.hidden=false;if(data.loginRequired)note('로그인하면 AI 심화대화와 저장을 이어갈 수 있습니다.');else if(data.mode==='personal-web'&&Array.isArray(data.handoffs))note('개인 AI 연결 경로를 사용할 수 있습니다.');else note(data.notice||'AI와 대화를 이어갔습니다.')}catch(error){note('AI 연결이 어려워 기본 질문으로 계속합니다.');const box=$('#aiReply');box.textContent=currentReflection.nextQuestion||'';box.hidden=false}finally{button.disabled=false}}
async function saveJourney(){if(!currentReflection)return;if(!session){location.assign(authUrl());return}const story=$('#story').value.trim();const row={user_id:session.user.id,topic:currentReflection.topic?.id||selectedTopic||'meaning',question_text:story.slice(0,4000),root_question:String(currentReflection.rootQuestion||'').slice(0,1000),scriptures:currentReflection.scriptures||[],next_question:String(currentReflection.nextQuestion||'').slice(0,1000),action_text:String(currentReflection.action||'').slice(0,1000),source:'life.ekodi.kr'};const {error}=await sb.from('life_reflections').insert(row);if(error){console.error(error);note('저장하지 못했습니다. 로그인 상태를 다시 확인해 주세요.');return}note('나의 여정에 저장했습니다.')}
async function shareReflection(){if(!currentReflection)return;const text=[`오늘의 질문 · ${currentReflection.topic?.label||'삶'}`,currentReflection.rootQuestion,currentReflection.scriptures?.length?`함께 볼 말씀: ${currentReflection.scriptures.join(', ')}`:'',`오늘의 한 걸음: ${currentReflection.action||''}`,'https://life.ekodi.kr/'].filter(Boolean).join('\n');try{if(navigator.share)await navigator.share({title:'오늘의 질문',text});else{await navigator.clipboard.writeText(text);note('나눌 내용을 복사했습니다.')}}catch(error){if(error?.name!=='AbortError')note('공유 기능을 열지 못했습니다.')}}
async function loadTenant(){try{const profile=await api('/api/tenant',{headers:{}});$('#brandName').textContent=profile.brandName||'오늘의 질문';$('#platformName').textContent=profile.platformName||'인생AI';$('#tagline').textContent=profile.tagline||'당신의 삶을 함께 생각합니다';if(profile.communityLabel)$('#communityLink').textContent=profile.communityLabel}catch{}}
async function loadToday(){const data=await api('/api/today',{headers:{}});$('#todayDate').textContent=data.date||'오늘';$('#dailyQuestion').textContent=data.question||'요즘 가장 마음에 걸리는 것은 무엇인가요?';const pathTopic=location.pathname.split('/').filter(Boolean)[0]||new URLSearchParams(location.search).get('topic')||'';if(data.topics?.some(t=>t.id===pathTopic))selectedTopic=pathTopic;renderTopics(data.topics||[])}

$('#reflectionForm')?.addEventListener('submit',submitReflection);
$('#authButton')?.addEventListener('click',authAction);
$('#aiButton')?.addEventListener('click',continueWithAi);
$('#saveButton')?.addEventListener('click',saveJourney);
$('#shareButton')?.addEventListener('click',shareReflection);
await Promise.allSettled([loadToday(),loadTenant()]);
if(enabled){
  try{await handoff()}catch(error){console.error('life auth handoff',error)}
  await refreshSession();
  sb.auth.onAuthStateChange((_event,next)=>{session=next;renderAuth()});
}else renderAuth();

function restorePending(){try{const story=sessionStorage.getItem('ekodi-life-pending-story')||'';const topic=sessionStorage.getItem('ekodi-life-pending-topic')||'';if(story&&session){$('#story').value=story;if(topic)selectTopic(topic);sessionStorage.removeItem('ekodi-life-pending-story');sessionStorage.removeItem('ekodi-life-pending-topic');note('로그인이 완료되었습니다. 작성하던 질문을 이어갈 수 있습니다.')}}catch{}}
