import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const INTERNAL_TOKEN=Deno.env.get("INSURANCE_INTERNAL_TOKEN")||"";
const CONTACT_KEY=Deno.env.get("INSURANCE_CONTACT_KEY")||"";
const CONTROL_ORIGIN="https://api.ekodi.kr";
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const encoder=new TextEncoder(),decoder=new TextDecoder();

const cors=(req:Request)=>{const origin=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":origin===CONTROL_ORIGIN?CONTROL_ORIGIN:"null","Access-Control-Allow-Headers":"content-type, apikey, x-ekodi-internal-token, x-ekodi-actor, x-ekodi-role","Access-Control-Allow-Methods":"GET,PATCH,OPTIONS","Vary":"Origin"}};
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors(req),"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
function unb64(value:string){const s=atob(value);return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function contactKey(){if(!CONTACT_KEY)throw new Error("contact_encryption_key_missing");const raw=unb64(CONTACT_KEY);if(raw.byteLength!==32)throw new Error("contact_encryption_key_invalid");return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["decrypt"])}
async function decryptContact(value:string){const [ivPart,dataPart]=String(value||"").split(".");if(!ivPart||!dataPart)return"";const key=await contactKey();const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(ivPart)},key,unb64(dataPart));return decoder.decode(decrypted)}
async function digest(value:string){return new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)))}
async function secretEqual(a:string,b:string){if(!a||!b)return false;const [x,y]=await Promise.all([digest(a),digest(b)]);if(x.length!==y.length)return false;let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}
async function context(req:Request){if(req.headers.get("Origin")!==CONTROL_ORIGIN)return null;const token=req.headers.get("x-ekodi-internal-token")||"";if(!(await secretEqual(token,INTERNAL_TOKEN)))return null;const principal=String(req.headers.get("x-ekodi-actor")||"").trim().toLowerCase().slice(0,180);const role=String(req.headers.get("x-ekodi-role")||"").trim();if(!principal||!["admin","advisor","auditor"].includes(role))return null;return{principal,role};}
async function audit(ctx:{principal:string,role:string},action:string,subjectUserId:string|null=null,consultationId:string|null=null,metadata:Record<string,unknown>={}){const {error}=await admin.from("insurance_audit_events").insert({actor_user_id:null,actor_principal:ctx.principal,subject_user_id:subjectUserId,consultation_id:consultationId,action,metadata:{...metadata,centralRole:ctx.role}});if(error)console.error("insurance admin audit",error.message);}
async function list(req:Request,ctx:{principal:string,role:string}){const {data,error}=await admin.from("insurance_consultation_requests").select("id,user_id,contact_name,contact_ciphertext,contact_hint,preferred_time,ai_summary,status,created_at,updated_at,assigned_staff_id").order("created_at",{ascending:false}).limit(300);if(error)throw error;const consultations=[];for(const row of data||[]){let contact="";if(ctx.role!=="auditor"){try{contact=await decryptContact(row.contact_ciphertext)}catch{contact=row.contact_hint||""}}consultations.push({id:row.id,userId:row.user_id,contactName:row.contact_name,contact,contactHint:row.contact_hint,preferredTime:row.preferred_time,aiSummary:row.ai_summary,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,assignedStaffId:row.assigned_staff_id})}await audit(ctx,"central_admin.consultations.listed",null,null,{count:consultations.length});return json(req,{consultations,role:ctx.role})}
async function detail(req:Request,ctx:{principal:string,role:string},id:string){const {data:row,error}=await admin.from("insurance_consultation_requests").select("*").eq("id",id).maybeSingle();if(error)throw error;if(!row)return json(req,{error:"not_found"},404);let contact="";if(ctx.role!=="auditor"){try{contact=await decryptContact(row.contact_ciphertext)}catch{contact=row.contact_hint||""}}let transcript:any[]=[];if(row.share_transcript&&row.conversation_id){const {data:messages}=await admin.from("insurance_ai_messages").select("role,content,created_at").eq("conversation_id",row.conversation_id).order("created_at");transcript=(messages||[]).map(m=>({role:m.role,text:m.content,createdAt:m.created_at}))}await audit(ctx,"central_admin.consultation.viewed",row.user_id,id,{transcriptShared:Boolean(row.share_transcript)});return json(req,{consultation:{id:row.id,userId:row.user_id,contactName:row.contact_name,contact,contactHint:row.contact_hint,preferredTime:row.preferred_time,aiSummary:row.ai_summary,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,shareTranscript:row.share_transcript,transcript}})}
async function status(req:Request,ctx:{principal:string,role:string},id:string){if(!["admin","advisor"].includes(ctx.role))return json(req,{error:"forbidden"},403);const body=await req.json().catch(()=>({}));const value=String(body?.status||"");if(!["new","working","contacted","closed"].includes(value))return json(req,{error:"invalid_status"},400);const {data,error}=await admin.from("insurance_consultation_requests").update({status:value,updated_at:new Date().toISOString()}).eq("id",id).select("id,user_id,status").maybeSingle();if(error)throw error;if(!data)return json(req,{error:"not_found"},404);await audit(ctx,"central_admin.consultation.status_changed",data.user_id,id,{status:value});return json(req,{consultation:{id:data.id,status:data.status}})}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});const ctx=await context(req);if(!ctx)return json(req,{error:"unauthorized_internal_proxy"},401);const path=new URL(req.url).pathname.replace(/^\/insurance-admin-internal/,"")||"/";try{if(req.method==="GET"&&path==="/admin/consultations")return await list(req,ctx);const d=path.match(/^\/admin\/consultations\/([0-9a-f-]+)$/i);if(req.method==="GET"&&d)return await detail(req,ctx,d[1]);const s=path.match(/^\/admin\/consultations\/([0-9a-f-]+)\/status$/i);if(req.method==="PATCH"&&s)return await status(req,ctx,s[1]);return json(req,{error:"not_found"},404)}catch(e){console.error("insurance-admin-internal",e);return json(req,{error:"insurance_admin_internal_failed"},500)}});
