(()=>{
'use strict';
const API='https://api.ekodi.kr/api/control/devotional';
const TOKEN_KEY='ekodi-auth-token';
const content=document.querySelector('.content');
const nav=document.querySelector('.sidebar nav');
if(!content||!nav)return;
const passages=['신명기 14:22-29','신명기 15:1-11','신명기 15:12-23','신명기 16:1-12','신명기 16:13-22','신명기 17:1-13','신명기 17:14-20','신명기 18:1-14','신명기 18:15-22','신명기 19:1-13','신명기 19:14-21','신명기 20:1-9','신명기 20:10-20','신명기 21:1-9','신명기 21:10-21','신명기 21:22-22:12','신명기 22:13-21','신명기 22:22-30','신명기 23:1-8','신명기 23:9-14','신명기 23:15-25','신명기 24:1-13','신명기 24:14-22','신명기 25:1-12','신명기 25:13-19','신명기 26:1-11','신명기 26:12-19','신명기 27:1-10','신명기 27:11-26','신명기 28:1-14'];
let panel=document.querySelector('[data-panel~="devotional"]');
if(!panel){panel=document.createElement('section');panel.className='section devotional-panel hidden-panel';panel.hidden=true;panel.dataset.panel='devotional';content.append(panel);}
let button=nav.querySelector('[data-section="devotional"],[data-lazy-section="devotional"]');
if(!button){button=document.createElement('button');button.type='button';button.className='nav';button.dataset.section='devotional';button.innerHTML='<span>매일묵상</span>';nav.append(button);}
const auth=()=>{try{return sessionStorage.getItem(TOKEN_KEY)||''}catch{return''}};
async function request(path='',options={}){const headers=new Headers(options.headers||{});headers.set('authorization',`Bearer ${auth()}`);if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');const res=await fetch(`${API}${path}`,{...options,headers});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`HTTP ${res.status}`);return body;}
function fallback(){return{month:'2026-09',connected:false,renderReady:false,channels:[{id:'church',name:'에코디교회',time:'06:00',connected:false},{id:'mission',name:'에코디선교회',time:'07:00',connected:false}],items:passages.map((passage,i)=>({day:i+1,passage,status:'draft',church:'not_connected',mission:'not_connected'}))};}
function pill(value){const ready=['ready','scheduled','published'].includes(value);const blocked=['error','not_connected','blocked'].includes(value);const label={draft:'대본 준비',queued:'생성 대기',rendering:'영상 생성중',ready:'영상 완료',scheduled:'예약',published:'게시',not_connected:'채널 미연결',blocked:'중지',error:'오류'}[value]||value;return `<span class="devotional-pill ${ready?'ready':blocked?'blocked':'wait'}">${label}</span>`;}
function render(state){const items=state.items?.length?state.items:fallback().items;const rendered=items.filter(x=>['ready','scheduled','published'].includes(x.status)).length;const scheduled=items.reduce((n,x)=>n+(x.church==='scheduled'?1:0)+(x.mission==='scheduled'?1:0),0);panel.innerHTML=`<div class="devotional-head"><div><h2>매일묵상 자동화</h2><p>성경본문 → 30초 대본 → Full HD 세로영상 → 채널별 패키징 → YouTube 예약 게시</p></div><div class="devotional-actions"><button class="devotional-btn" data-dev-refresh>새로고침</button><button class="devotional-btn primary" data-dev-seed>9월 본문 등록</button><button class="devotional-btn primary" data-dev-generate ${state.renderReady?'':'disabled'}>30편 일괄 생성</button></div></div><div class="devotional-summary"><div class="devotional-card"><b>${items.length}</b><span>등록 본문</span></div><div class="devotional-card"><b>${rendered}</b><span>영상 완료</span></div><div class="devotional-card"><b>${scheduled}/60</b><span>YouTube 예약</span></div><div class="devotional-card"><b>${state.renderReady?'준비':'연결 필요'}</b><span>렌더 노드</span></div></div><div class="devotional-channel-grid">${(state.channels||fallback().channels).map(c=>`<div class="devotional-channel"><strong>${c.name}</strong><small>${c.connected?'YouTube 연결됨':'YouTube OAuth 연결 필요'} · 기본 공개 ${c.time||'-'}</small></div>`).join('')}</div>${!state.connected?'<div class="devotional-note">현재 관리 화면과 작업 원장은 준비되었지만 YouTube OAuth 및 FFmpeg 렌더 노드 연결 전에는 실제 업로드를 실행하지 않습니다. 연결되지 않은 기능을 완료된 것처럼 표시하지 않습니다.</div>':''}<div class="devotional-table-wrap"><table class="devotional-table"><thead><tr><th>날짜</th><th>본문</th><th>영상</th><th>에코디교회</th><th>에코디선교회</th></tr></thead><tbody>${items.map(x=>`<tr><td>09/${String(x.day).padStart(2,'0')}</td><td>${x.passage}</td><td>${pill(x.status)}</td><td>${pill(x.church||'not_connected')}</td><td>${pill(x.mission||'not_connected')}</td></tr>`).join('')}</tbody></table></div>`;
panel.querySelector('[data-dev-refresh]')?.addEventListener('click',load);panel.querySelector('[data-dev-seed]')?.addEventListener('click',seed);panel.querySelector('[data-dev-generate]')?.addEventListener('click',generate);}
async function load(){try{render(await request())}catch(error){const state=fallback();render(state);const note=document.createElement('div');note.className='devotional-note devotional-error';note.textContent=`API 연결 확인 필요: ${error.message}`;panel.prepend(note);}}
async function seed(){try{await request('/seed',{method:'POST',body:JSON.stringify({month:'2026-09',passages})});await load()}catch(error){alert(`본문 등록 실패: ${error.message}`)}}
async function generate(){try{await request('/generate',{method:'POST',body:JSON.stringify({month:'2026-09'})});await load()}catch(error){alert(`일괄 생성 요청 실패: ${error.message}`)}}
button.addEventListener('click',()=>queueMicrotask(load));
window.addEventListener('ekodi-admin-section-changed',event=>{if(event.detail?.section==='devotional')load()});
window.dispatchEvent(new CustomEvent('ekodi-feature-installed',{detail:{section:'devotional'}}));
})();