function securityHeaders(){return{'x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...securityHeaders()}})}
function withHeaders(response){const headers=new Headers(response.headers);for(const [key,value]of Object.entries(securityHeaders()))headers.set(key,value);if(!headers.has('cache-control'))headers.set('cache-control',response.headers.get('content-type')?.includes('text/html')?'no-cache':'public, max-age=300');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function boundedNumber(value,min,max,fallback=0){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function runtimeConfig(env={}){return{telemetryEnabled:env.TELEMETRY_ENABLED==='true',telemetryMode:env.TELEMETRY_MODE||'isolated-staging',controlEnabled:env.CONTROL_ENABLED==='true',controlPolicy:'observe-suggest-approve-bounded',authUrl:env.AUTH_URL||'https://auth.ekodi.kr/?site=energy'}}
function buildInsight(body={}){const t=body.telemetry||{};const solar=boundedNumber(t.solarNow,0,100,0);const home=boundedNumber(t.homeNow,0,100,0);const soc=boundedNumber(t.essSoc,0,100,0);const surplus=Math.max(0,solar-home);let title='현재는 에너지 흐름을 관찰하는 것이 좋습니다.';let text='발전량과 소비량이 안정 범위에 있는지 계속 비교하고, 충분한 데이터가 쌓인 뒤 자동화 범위를 넓히세요.';if(surplus>=1){title='정오 잉여 태양광 시간대로 부하를 옮겨 보세요.';text=`현재 샘플 기준 잉여전력이 약 ${surplus.toFixed(1)} kW입니다. 세탁·건조·온수·EV 충전처럼 시간 이동이 가능한 부하를 태양광 생산시간에 맞추는 방안을 권합니다.`}else if(solar>0&&home>solar){title='계통 구매전력이 늘고 있습니다.';text='필수 부하는 유지하고, 시간 이동이 가능한 대형 가전이나 EV 충전을 다음 태양광 생산 구간으로 예약하는 방안을 검토하세요.'}if(soc<25){title='ESS 비상 여유를 먼저 확보하세요.';text='배터리 잔량이 낮습니다. 비용 최적화보다 비상용 예비전력 기준을 우선하고 방전 자동화를 제한하는 편이 안전합니다.'}return{title,body:text,actuationRequested:false}}
const permanentlyBlocked=new Set(['breaker_off','breaker_trip','protection_override','protection_setting_change','inverter_safety_change','emergency_control','safety_interlock_bypass']);
const lowRisk=new Set(['schedule_load','ev_charge_schedule','ess_charge_target','water_heater_schedule']);
function checkAction(env,body={}){const cfg=runtimeConfig(env);const action=String(body.action||'').trim();const mode=boundedNumber(body.controlMode,0,3,0);if(!action)return{allowed:false,reason:'action_required',executable:false};if(permanentlyBlocked.has(action))return{allowed:false,reason:'safety_boundary_permanent',executable:false};if(!lowRisk.has(action))return{allowed:false,reason:'unsupported_action',executable:false};if(mode<2)return{allowed:false,reason:'human_approval_required',executable:false};if(!cfg.controlEnabled)return{allowed:true,reason:'policy_allows_but_control_adapter_disabled',executable:false};return{allowed:true,reason:mode===2?'approved_low_risk_action':'bounded_automation_rule',executable:true}}
export default{async fetch(request,env){const url=new URL(request.url);const cfg=runtimeConfig(env);if(url.pathname==='/config.js')return new Response(`window.EKODI_ENERGY_CONFIG=${JSON.stringify(cfg)};`,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store',...securityHeaders()}});if(url.pathname==='/health')return json({ok:true,service:'ekodi-energy-ai',stage:cfg.telemetryMode,telemetryEnabled:cfg.telemetryEnabled,controlEnabled:cfg.controlEnabled,safetyPolicy:cfg.controlPolicy});if(url.pathname==='/admin'||url.pathname==='/admin/')return Response.redirect('https://admin.ekodi.kr/energy',307);if(request.method==='POST'&&url.pathname==='/api/insight'){let body={};try{body=await request.json()}catch{return json({error:'invalid_json'},400)}return json({mode:'explainable-rule-mvp',insight:buildInsight(body)});}if(request.method==='POST'&&url.pathname==='/api/action-check'){let body={};try{body=await request.json()}catch{return json({error:'invalid_json'},400)}return json({policy:cfg.controlPolicy,...checkAction(env,body)});}if(url.pathname.startsWith('/api/'))return json({error:'not_found'},404);return withHeaders(await env.ASSETS.fetch(request))}};
