(()=>{
'use strict';
const SECTION='entitlements',API='https://api.ekodi.kr/api/control/entitlements',TOKEN_KEY='ekodi-auth-token';
if(!document.querySelector('link[data-entitlement-admin]')){const l=document.createElement('link');l.rel='stylesheet';l.href='entitlement-admin.css';l.dataset.entitlementAdmin='1';document.head.append(l)}
let state=null,busy=false;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>{try{return sessionStorage.getItem(TOKEN_KEY)||''}catch{return''}};
const t=(ko,en)=>String(window.EKODIAdminMenu?.locale?.()||document.documentElement.lang||'ko').toLowerCase().startsWith('en')?en:ko;
function query(){const w=$('#entWorkspace')?.value.trim()||'',s=$('#entSubject')?.value.trim()||'';const p=new URLSearchParams();if(w)p.set('workspace',w);if(s)p.set('subject',s);return p.toString()?`?${p}`:''}
async function request(method='GET',body=null){const response=await fetch(API+(method==='GET'?query():''),{method,cache:'no-store',headers:{authorization:`Bearer ${token()}`,accept:'application/json',...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error||`Entitlement ${response.status}`);e.code=data.code||data.error;e.status=response.status;throw e}return data}
function key(row){return`${row.workspace_key}|${row.subject_type}|${row.subject_key}|${row.capability_id}`}
function overrideMaps(){const map=new Map();for(const row of state?.overrides||[])map.set(key(row),row);return map}
function defaultCell(item,tier,index){const value=item.defaults[index];return `<span class="ent-default ${value===true?'on':value===false?'off':''}">${typeof value==='boolean'?(value?'ON':'OFF'):esc(value)}</span>`}
function scopeOverride(item,scope,maps){const w=$('#entWorkspace')?.value.trim()||'',s=$('#entSubject')?.value.trim()||'',tier=scope.startsWith('tier:')?scope.slice(5):'',subjectType=tier?'tier':scope==='user'?'person':'default',subjectKey=tier||((scope==='user')?s:''),workspaceKey=tier?'':w,row=maps.get(`${workspaceKey}|${subjectType}|${subjectKey}|${item.id}`);return row?.value}
function valueControl(item,scope,maps){const current=scopeOverride(item,scope,maps),subject=$('#entSubject')?.value.trim()||'',workspace=$('#entWorkspace')?.value.trim()||'',disabled=(scope==='user'&&!subject)||(scope==='workspace'&&!workspace)?'disabled':'';const attr=`data-ent-cap="${esc(item.id)}" data-ent-scope="${scope}" ${disabled}`;if(item.kind==='boolean')return `<select ${attr}><option value="">상속</option><option value="true" ${current===true?'selected':''}>ON</option><option value="false" ${current===false?'selected':''}>OFF</option></select>`;return `<input ${attr} type="number" min="0" max="100000" placeholder="상속" value="${current==null?'':esc(current)}">`}
function tierCell(item,tier,index,maps,platform){if(!platform)return defaultCell(item,tier,index);const control=valueControl(item,`tier:${tier}`,maps);return `<div class="ent-tier-edit">${control}<small>기본 ${typeof item.defaults[index]==='boolean'?(item.defaults[index]?'ON':'OFF'):esc(item.defaults[index])}</small></div>`}
function render(){const host=$('#entitlementAdminPanel');if(!host||!state)return;const maps=overrideMaps(),actor=state.actor||{};host.innerHTML=`<div class="ent-head"><div><p class="kicker">ENTITLEMENT ENGINE</p><h2>${t('회원·기능 권한','Membership & Entitlements')}</h2><p>${t('회원등급 기본값 위에 운영공간 정책과 사용자별 예외를 적용합니다. 모든 변경은 감사기록에 남습니다.','Tier defaults are refined by workspace policy and per-user exceptions. Every change is audited.')}</p></div><a class="secondary" href="/my/presentation/" target="_blank" rel="noopener">${t('발표 기능 열기','Open presentation')}</a></div>
<div class="ent-filter"><label>${t('운영공간','Workspace')}<input id="entWorkspace" value="${esc(state.workspaceKey||'')}" placeholder="예: cgma" ${actor.platform?'':'disabled'}></label><label>${t('사용자 키','Person key')}<input id="entSubject" value="" placeholder="person:..."></label><button id="entLoad" class="secondary" type="button">${t('조회','Load')}</button><span>${actor.platform?'PLATFORM ADMIN':esc(actor.role||'WORKSPACE ADMIN')}</span></div>
<div class="ent-policy"><strong>FREE CORE COMPLETE</strong><span>tier-default → workspace-default → user-exception</span><span>${t('빈 값은 상속','Blank = inherit')}</span></div>
<div class="ent-table-wrap"><table class="ent-table"><thead><tr><th>${t('기능','Capability')}</th>${state.tiers.map(x=>`<th>${esc(x.toUpperCase())}</th>`).join('')}<th>${t('공간정책','Workspace')}</th><th>${t('사용자예외','User')}</th></tr></thead><tbody>${state.catalog.map(item=>`<tr><td><strong>${esc(item.label)}</strong><small>${esc(item.id)}</small></td>${state.tiers.map((tier,i)=>`<td>${tierCell(item,tier,i,maps,actor.platform)}</td>`).join('')}<td>${valueControl(item,'workspace',maps)}</td><td>${valueControl(item,'user',maps)}</td></tr>`).join('')}</tbody></table></div>
<div class="ent-actions"><span id="entState">${t('값을 바꾸면 즉시 저장할 수 있습니다.','Change a value and save it immediately.')}</span><button id="entSave" class="primary" type="button">${t('변경 저장','Save changes')}</button></div>
<section class="ent-audit"><div><small>AUDIT</small><h3>${t('최근 권한 변경','Recent entitlement changes')}</h3></div><div>${(state.audit||[]).length?(state.audit||[]).map(row=>`<article><strong>${esc(row.capability_id)}</strong><span>${esc(row.action)} · ${esc(row.actor_key)}</span><small>${esc(row.workspace_key||'GLOBAL')} · ${esc(row.created_at)}</small></article>`).join(''):`<p>${t('아직 변경 기록이 없습니다.','No entitlement changes yet.')}</p>`}</div></section>`;$('#entLoad')?.addEventListener('click',()=>load(true));$('#entSave')?.addEventListener('click',save)}
async function save(){if(busy)return;const workspaceKey=$('#entWorkspace')?.value.trim()||'',subjectKey=$('#entSubject')?.value.trim()||'',maps=overrideMaps(),controls=[...document.querySelectorAll('[data-ent-cap]')];busy=true;const status=$('#entState');if(status)status.textContent=t('저장 중…','Saving…');try{for(const control of controls){const scope=control.dataset.entScope,capabilityId=control.dataset.entCap,isTier=scope.startsWith('tier:'),subjectType=isTier?'tier':scope==='user'?'person':'default',keyValue=isTier?scope.slice(5):scope==='user'?subjectKey:'',effectiveWorkspace=isTier?'':workspaceKey,row=maps.get(`${effectiveWorkspace}|${subjectType}|${keyValue}|${capabilityId}`),raw=control.value;if(scope==='user'&&!subjectKey)continue;if(scope==='workspace'&&!workspaceKey)continue;if(raw===''){if(row)await request('DELETE',{workspaceKey:effectiveWorkspace,subjectType,subjectKey:keyValue,capabilityId});continue}const value=raw==='true'?true:raw==='false'?false:Number(raw);if(row&&row.value===value)continue;await request('PUT',{workspaceKey:effectiveWorkspace,subjectType,subjectKey:keyValue,capabilityId,value})}await load(false);const next=$('#entState');if(next)next.textContent=t('권한 변경이 저장되었습니다.','Entitlements saved.')}catch(error){if(status)status.textContent=error.message;console.error('[Entitlement Admin]',error)}finally{busy=false}}
async function load(preserve=true){if(busy)return;const workspace=preserve?$('#entWorkspace')?.value.trim()||'':state?.workspaceKey||'',subject=preserve?$('#entSubject')?.value.trim()||'':'';busy=true;try{const p=new URLSearchParams();if(workspace)p.set('workspace',workspace);if(subject)p.set('subject',subject);const response=await fetch(API+(p.toString()?`?${p}`:''),{headers:{authorization:`Bearer ${token()}`,accept:'application/json'},cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Entitlement ${response.status}`);state=data;render();if(subject)$('#entSubject').value=subject}catch(error){const host=$('#entitlementAdminPanel');if(host)host.innerHTML=`<div class="ent-error"><strong>${t('권한 설정을 불러오지 못했습니다.','Could not load entitlements.')}</strong><p>${esc(error.message)}</p><button id="entRetry" class="secondary" type="button">${t('다시 시도','Retry')}</button></div>`;$('#entRetry')?.addEventListener('click',()=>load(false))}finally{busy=false}}
function activate(button){document.querySelectorAll('[data-panel]').forEach(panel=>{const visible=String(panel.dataset.panel||'').split(/\s+/).includes(SECTION);panel.hidden=!visible;panel.classList.toggle('hidden-panel',!visible)});document.querySelectorAll('.sidebar .nav').forEach(item=>item.classList.toggle('active',item===button));const title=$('#pageTitle');if(title)title.textContent=t('회원·기능 권한','Membership & Entitlements');document.querySelector('.sidebar')?.classList.remove('open');if(location.hash!=='#entitlements'&&location.hostname!=='ekodi.kr')history.replaceState(null,'','#entitlements');void load(false)}
function install(){const nav=document.querySelector('.sidebar nav'),content=document.querySelector('.content');if(!nav||!content)return;let button=nav.querySelector('[data-section="entitlements"],[data-lazy-section="entitlements"],[data-demand-feature="entitlements"]');if(!button){button=document.createElement('button');button.type='button';button.className='nav';button.textContent=t('회원·기능 권한','Entitlements');nav.append(button)}button.dataset.section=SECTION;delete button.dataset.lazySection;delete button.dataset.demandFeature;let section=$('#entitlementAdminPanel');if(!section){section=document.createElement('section');section.id='entitlementAdminPanel';section.className='section entitlement-admin hidden-panel';section.dataset.panel=SECTION;section.hidden=true;content.append(section)}if(button.dataset.entBound!=='true'){button.dataset.entBound='true';button.addEventListener('click',()=>activate(button))}window.dispatchEvent(new CustomEvent('ekodi-nav-changed',{detail:{feature:SECTION}}));if(location.hash==='#entitlements'||location.pathname.endsWith('/entitlements'))queueMicrotask(()=>activate(button))}
install();window.addEventListener('ekodi-admin-ready',install);window.addEventListener('ekodi-admin-locale-changed',()=>{if(state&&$('#entitlementAdminPanel:not(.hidden-panel)'))render()});window.EKODIEntitlementAdmin=Object.freeze({load});
})();
