(() => {
  const API='https://api.ekodi.kr';
  const token=()=>sessionStorage.getItem('ekodi-auth-token')||'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let installed=false,loading=false,state={consultations:[],metrics:{}};
  const activeAffiliation=()=>{try{return sessionStorage.getItem('ekodi-insurance-affiliation-v1')||''}catch{return''}};
  async function request(path,options={}){const h=new Headers(options.headers||{});if(token())h.set('authorization',`Bearer ${token()}`);if(options.body&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(`${API}${path}`,{...options,headers:h,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Insurance Admin API 오류 (${r.status})`);return d}
  function flash(text,error=false){const el=document.querySelector('#insuranceAdminFlash');if(!el)return;el.textContent=text||'';el.dataset.error=error?'true':'false'}
  function fmt(value){try{return value?new Date(value).toLocaleString('ko-KR'):'-'}catch{return value||'-'}}
  function install(){if(installed)return true;const nav=document.querySelector('.sidebar nav'),content=document.querySelector('.content');if(!nav||!content)return false;installed=true;
    let button=nav.querySelector('[data-section="insurance"], [data-lazy-section="insurance"]');if(!button){button=document.createElement('button');button.type='button';button.className='nav';button.dataset.section='insurance';button.innerHTML='◇ <span>Insurance</span>';nav.append(button)}
    const section=document.createElement('section');section.id='insuranceAdminSection';section.className='section insurance-admin hidden-panel';section.dataset.panel='insurance';section.innerHTML=`<div class="insurance-admin-head"><div><p>EKODI INSURANCE · HUMAN HANDOFF</p><h2>Consultations</h2><span>AI 상담 후 사용자가 실제 설계사 연락을 요청한 건만 관리합니다.</span></div><button class="secondary" id="insuranceAdminRefresh" type="button">↻ Refresh</button></div><p id="insuranceAdminFlash" class="insurance-admin-flash" role="status"></p><div id="insuranceAdminMetrics" class="insurance-admin-metrics"></div><div class="insurance-admin-card"><div class="insurance-admin-toolbar"><strong>상담대기열</strong><select id="insuranceAdminFilter"><option value="all">전체</option><option value="new">신규</option><option value="working">확인중</option><option value="contacted">연락완료</option><option value="closed">종료</option></select></div><div id="insuranceAdminList" class="insurance-admin-list"></div></div><div id="insuranceAdminDetail" class="insurance-admin-card" hidden></div>`;content.append(section);
    button.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('hidden-panel',!String(p.dataset.panel||'').split(' ').includes('insurance')));document.querySelectorAll('.sidebar .nav[data-section]').forEach(n=>n.classList.toggle('active',n.dataset.section==='insurance'));document.querySelector('#pageTitle')&&(document.querySelector('#pageTitle').textContent='Insurance');document.querySelector('.sidebar')?.classList.remove('open');if(location.hash!=='#insurance')history.replaceState(null,'','#insurance');load()});
    section.querySelector('#insuranceAdminRefresh').addEventListener('click',load);section.querySelector('#insuranceAdminFilter').addEventListener('change',renderList);section.querySelector('#insuranceAdminList').addEventListener('click',e=>{const b=e.target.closest('[data-consultation]');if(b)openDetail(b.dataset.consultation)});section.querySelector('#insuranceAdminList').addEventListener('change',e=>{const s=e.target.closest('[data-status]');if(s)updateStatus(s.dataset.status,s.value)});
    if(location.hash==='#insurance'||location.pathname==='/insurance'||location.pathname==='/insurance/')setTimeout(()=>button.click(),80);return true}
  async function load(){if(loading)return;if(!token()){flash('관리자 인증 후 Insurance 상담요청을 불러올 수 있습니다.',true);return}loading=true;const affiliationId=activeAffiliation(),query=affiliationId?`?affiliationId=${encodeURIComponent(affiliationId)}`:'';flash(affiliationId?'선택 보험사 상담요청을 불러오는 중입니다.':'전체 상담요청을 불러오는 중입니다.');try{state=await request(`/api/insurance/admin/consultations${query}`);state.consultations=Array.isArray(state.consultations)?state.consultations:[];render();flash(`마지막 갱신 ${new Date().toLocaleTimeString('ko-KR')}${affiliationId?' · 보험사 Context':''}`)}catch(e){state={consultations:[],metrics:{}};render();flash(`${e.message} · API 스테이징 연결 전에는 실제 고객정보를 표시하지 않습니다.`,true)}finally{loading=false}}
  function render(){renderMetrics();renderList()}
  function renderMetrics(){const list=state.consultations||[];const counts={new:list.filter(x=>x.status==='new').length,working:list.filter(x=>x.status==='working').length,contacted:list.filter(x=>x.status==='contacted').length,closed:list.filter(x=>x.status==='closed').length};document.querySelector('#insuranceAdminMetrics').innerHTML=`<article><small>전체</small><strong>${list.length}</strong></article><article><small>신규</small><strong>${counts.new}</strong></article><article><small>확인중</small><strong>${counts.working}</strong></article><article><small>연락완료</small><strong>${counts.contacted}</strong></article>`}
  function statusLabel(v){return({new:'신규',working:'확인중',contacted:'연락완료',closed:'종료'})[v]||v}
  function renderList(){const filter=document.querySelector('#insuranceAdminFilter')?.value||'all',host=document.querySelector('#insuranceAdminList');const list=(state.consultations||[]).filter(x=>filter==='all'||x.status===filter);if(!list.length){host.innerHTML='<p class="insurance-admin-empty">표시할 상담요청이 없습니다.</p>';return}host.innerHTML=list.map(x=>`<article class="insurance-admin-row"><div><strong>${esc(x.contactName||x.name||'고객')}</strong><small>${esc(x.contactHint||x.contact||'-')} · ${esc(x.preferredTime||'시간 미지정')}</small></div><div class="insurance-admin-summary"><strong>${esc(x.aiSummary||x.summary||'AI 요약 없음')}</strong><small>${esc(fmt(x.createdAt||x.created_at))}</small></div><select data-status="${esc(x.id)}"><option value="new"${x.status==='new'?' selected':''}>신규</option><option value="working"${x.status==='working'?' selected':''}>확인중</option><option value="contacted"${x.status==='contacted'?' selected':''}>연락완료</option><option value="closed"${x.status==='closed'?' selected':''}>종료</option></select><button type="button" data-consultation="${esc(x.id)}">상세</button></article>`).join('')}
  async function openDetail(id){const box=document.querySelector('#insuranceAdminDetail');box.hidden=false;box.innerHTML='<p class="insurance-admin-empty">상세 상담을 불러오는 중입니다.</p>';try{const d=await request(`/api/insurance/admin/consultations/${encodeURIComponent(id)}`);const c=d.consultation||d;const transcript=(c.transcript||[]).map(m=>`<article><span>${esc(m.role==='user'?'고객':'AI')}</span><p>${esc(m.text||m.content||'')}</p></article>`).join('');box.innerHTML=`<div class="insurance-admin-detail-head"><div><p>CONSULTATION DETAIL</p><h3>${esc(c.contactName||c.name||'상담')}</h3></div><button class="secondary" type="button" id="insuranceAdminCloseDetail">Close</button></div><dl><div><dt>연락처</dt><dd>${esc(c.contact||c.contactValue||c.contactHint||'-')}</dd></div><div><dt>희망시간</dt><dd>${esc(c.preferredTime||'-')}</dd></div><div><dt>상태</dt><dd>${esc(statusLabel(c.status))}</dd></div><div><dt>요청시각</dt><dd>${esc(fmt(c.createdAt||c.created_at))}</dd></div></dl><section><strong>AI 상담요약</strong><p>${esc(c.aiSummary||c.summary||'')}</p></section><section><strong>공유된 대화</strong><div class="insurance-admin-transcript">${transcript||'<p>공유된 대화가 없습니다.</p>'}</div></section><p class="insurance-admin-boundary">이 화면은 상담요청에 공유된 범위만 표시해야 하며 고객의 전체 보험계약·청구기록을 자동 열람해서는 안 됩니다.</p>`;box.querySelector('#insuranceAdminCloseDetail').addEventListener('click',()=>{box.hidden=true;box.replaceChildren()})}catch(e){box.innerHTML=`<p class="insurance-admin-empty">${esc(e.message)}</p>`}}
  async function updateStatus(id,status){try{await request(`/api/insurance/admin/consultations/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({status})});const item=(state.consultations||[]).find(x=>x.id===id);if(item)item.status=status;render();flash('상담 상태를 변경했습니다.')}catch(e){flash(e.message,true);await load()}}
  function loadStyle(href){if(document.querySelector(`link[href="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link)}
  function loadExtensions(){for(const href of ['insurance-network-admin.css','insurance-advisor-admin.css','insurance-practice-admin.css'])loadStyle(href);Promise.all([import('./insurance-network-admin.js'),import('./insurance-advisor-admin.js'),import('./insurance-practice-admin.js')]).catch(error=>console.warn('[EKODI Insurance] admin extension load failed',error))}
  window.addEventListener('ekodi:insurance-affiliation-change',()=>load());
  loadStyle('insurance-admin.css');
  install();
  loadExtensions();
})();