export const JOURNAL_META = Object.freeze({
  id: 'journal',
  name: 'EKODI Journal',
  nameKo: '에코디 저널',
  description: 'EKODI의 정신, 실천, 기술, 공동체의 배움을 공개적으로 기록하는 저널',
  canonicalOrigin: 'https://journal.ekodi.kr',
  startedAt: '2026-09-02',
});

const author = Object.freeze({
  name: 'EKODI Editorial',
  type: 'platform-editorial',
  disclosure: '에코디 플랫폼의 공개 원칙과 운영 기록을 바탕으로 정리한 편집 글입니다.',
});

export const JOURNAL_POSTS = Object.freeze([
  {
    slug: 'beginning-ekodi-journal',
    title: '에코디 저널을 시작합니다',
    titleEn: 'Introducing EKODI Journal',
    excerpt: '말씀과 삶, 기술과 공동체 사이에서 무엇을 만들었고 왜 그렇게 선택했는지를 꾸준히 남깁니다.',
    excerptEn: 'A living record of what EKODI builds, why it chooses that path, and what it learns between faith, life, technology, and community.',
    publishedAt: '2026-09-02T22:30:00+09:00',
    updatedAt: '2026-09-02T22:30:00+09:00',
    category: 'ekodi',
    categoryLabel: 'EKODI 생각',
    categoryLabelEn: 'EKODI Thinking',
    values: ['Ecclesia', 'Koinonia', 'Diaspora', 'Jubilee'],
    author,
    readMinutes: 4,
    featured: true,
    imageVariant: 1,
    body: [
      { type: 'lead', text: '플랫폼에는 코드만 쌓이는 것이 아닙니다. 선택의 이유와 사람들의 이야기, 실패와 수정, 다시 시작한 흔적도 함께 쌓입니다.' },
      { type: 'p', text: 'EKODI Journal은 에코디가 무엇을 만들고 있는지를 홍보하기 위한 게시판에 머물지 않습니다. 우리가 무엇을 중요하게 여기는지, 어떤 선택을 했는지, 그 선택이 사람과 공동체에 어떤 영향을 주었는지를 공개적으로 기록하는 공간입니다.' },
      { type: 'heading', text: '기록은 기억을 넘어 책임이 됩니다' },
      { type: 'p', text: '서비스가 많아질수록 결정은 빠르게 지나가고 이유는 희미해지기 쉽습니다. 그래서 우리는 결과만 남기지 않고 판단의 기준도 남기려 합니다. 다음 사람이 같은 길을 걸을 때 처음부터 다시 헤매지 않도록 하기 위해서입니다.' },
      { type: 'quote', text: '말씀을 해석하고, 현장에서 살아내고, 기술로 확장하고, 다시 기록하여 다음 사람에게 건넨다.' },
      { type: 'heading', text: '저널이 다룰 것' },
      { type: 'list', items: ['에클레시아, 코이노니아, 디아스포라, 희년의 관점에서 오늘을 읽는 글', '에코디플랫폼의 설계 원칙과 실제 구축 과정', '교회, 지역, 비즈니스, 연구 현장에서 얻은 배움', 'AI와 기술이 사람의 자유와 책임을 더 잘 섬기도록 만드는 실험', '성공뿐 아니라 실패, 수정, 검증의 기록'] },
      { type: 'p', text: '좋은 기록은 완성된 정답을 전시하지 않습니다. 변화의 방향을 볼 수 있게 합니다. 이 저널은 그런 방향표가 되려 합니다.' },
    ],
    bodyEn: [
      { type: 'lead', text: 'A platform accumulates more than code. It also accumulates reasons, people, failures, corrections, and beginnings.' },
      { type: 'p', text: 'EKODI Journal is not merely a promotional blog. It records what EKODI values, why decisions are made, and how those decisions affect people and communities.' },
      { type: 'heading', text: 'A record becomes accountability' },
      { type: 'p', text: 'As services multiply, decisions move quickly and their reasons can disappear. We want to preserve not only outcomes but also the standards behind them so the next person does not have to start from zero.' },
      { type: 'quote', text: 'Interpret the Word, live it in the field, extend it through technology, and pass the record to the next person.' },
      { type: 'heading', text: 'What this journal will cover' },
      { type: 'list', items: ['Reflections shaped by Ecclesia, Koinonia, Diaspora, and Jubilee', 'Platform principles and the real process of building EKODI', 'Lessons from church, local communities, business, and research', 'Experiments that make AI and technology serve human freedom and responsibility', 'Failures, corrections, and verification, not only successes'] },
    ],
  },
  {
    slug: 'ai-does-not-replace-community',
    title: 'AI가 공동체를 대신하지 않도록',
    titleEn: 'AI Should Not Replace Community',
    excerpt: '좋은 AI는 사람을 더 의존하게 만드는 것이 아니라 더 책임 있게 선택하고 서로 돌볼 수 있게 해야 합니다.',
    excerptEn: 'Good AI should not deepen dependency. It should help people choose responsibly and care for one another.',
    publishedAt: '2026-09-02T18:00:00+09:00',
    updatedAt: '2026-09-02T18:00:00+09:00',
    category: 'ai',
    categoryLabel: 'AI & Technology',
    categoryLabelEn: 'AI & Technology',
    values: ['Koinonia', 'Jubilee', 'Agency'],
    author,
    readMinutes: 5,
    featured: false,
    imageVariant: 2,
    body: [
      { type: 'lead', text: 'AI가 대답을 더 빨리 주는 시대일수록 중요한 질문은 하나 더 생깁니다. 그 대답이 사람의 판단과 관계를 더 건강하게 만드는가?' },
      { type: 'p', text: '에코디에서 AI는 주권자가 아니라 위임받은 도구입니다. 사용자가 선택할 수 있어야 하고, 취소할 수 있어야 하며, 중요한 결정은 사람이 검토할 수 있어야 합니다.' },
      { type: 'heading', text: '편리함보다 먼저 지켜야 할 것' },
      { type: 'list', items: ['사람의 최종 선택권', '공동체 안에서의 진실한 관계', '데이터와 기록의 이동 가능성', '특정 AI 제공자에게 묶이지 않는 구조', '실패했을 때 AI 없이도 계속되는 핵심 기능'] },
      { type: 'p', text: '공동체는 효율성으로만 설명되지 않습니다. 느린 대화, 서로 다른 의견, 책임을 나누는 과정 자체가 공동체의 일부입니다. AI가 그 과정을 지워버리면 편리해질 수는 있어도 공동체는 약해질 수 있습니다.' },
      { type: 'quote', text: 'AI의 역할은 사람을 대신해 살아주는 것이 아니라, 사람이 더 잘 살아낼 수 있도록 돕는 것입니다.' },
    ],
    bodyEn: [
      { type: 'lead', text: 'When AI gives answers faster, one more question matters: does the answer make human judgment and relationships healthier?' },
      { type: 'p', text: 'At EKODI, AI is a delegated tool, not a sovereign. People must be able to choose, revoke, review, and continue safely without a model when needed.' },
      { type: 'heading', text: 'What comes before convenience' },
      { type: 'list', items: ['Human final agency', 'Truthful relationships in community', 'Portable data and records', 'Freedom from lock-in to one AI provider', 'Core functions that continue when AI is unavailable'] },
      { type: 'quote', text: 'AI should not live a person’s life for them. It should help them live it more faithfully and responsibly.' },
    ],
  },
  {
    slug: 'paths-for-spaces-boundaries-for-services',
    title: '주소도 철학을 담습니다',
    titleEn: 'Architecture Is Visible in an Address',
    excerpt: '사람과 기관의 공간은 ekodi.kr 아래 경로로, 독립 공통서비스는 필요한 경우에만 서브도메인으로 구분합니다.',
    excerptEn: 'People and organizations live under canonical ekodi.kr paths, while justified common-service boundaries may use subdomains.',
    publishedAt: '2026-09-01T16:00:00+09:00',
    updatedAt: '2026-09-02T16:00:00+09:00',
    category: 'build',
    categoryLabel: 'Build in Public',
    categoryLabelEn: 'Build in Public',
    values: ['Independence', 'Portability', 'Stewardship'],
    author,
    readMinutes: 4,
    featured: false,
    imageVariant: 3,
    body: [
      { type: 'lead', text: 'URL은 단순한 표지판처럼 보이지만, 그 안에는 누가 주체이고 무엇이 공통 기능인지에 대한 설계 철학이 숨어 있습니다.' },
      { type: 'p', text: '에코디의 개인, 기관, 단체, 프로젝트 공간은 원칙적으로 ekodi.kr 아래의 경로를 사용합니다. 공간의 실제 권한과 데이터는 주소가 아니라 변하지 않는 workspace_id를 기준으로 관리합니다.' },
      { type: 'heading', text: '공간은 경로로, 경계는 서브도메인으로' },
      { type: 'p', text: '서브도메인은 편의를 위해 늘리지 않습니다. 인증, 관리자, API, 그리고 독립적으로 운영되어야 하는 공통서비스처럼 보안이나 운영 경계가 분명할 때 사용합니다.' },
      { type: 'quote', text: 'URL은 사용자의 공간을 가리키고, 권한은 불변의 내부 ID를 따른다.' },
      { type: 'p', text: 'journal.ekodi.kr 역시 특정 개인이나 기관의 블로그가 아니라 여러 공간에서 사용할 수 있는 공통 기록·발행 서비스의 공개 경계로 설계합니다.' },
    ],
    bodyEn: [
      { type: 'lead', text: 'A URL may look like a label, but it can reveal who owns a space and what belongs to shared infrastructure.' },
      { type: 'p', text: 'EKODI user spaces use paths under ekodi.kr. Authorization and data ownership follow immutable workspace_id values rather than hostnames or slugs.' },
      { type: 'heading', text: 'Paths for spaces, subdomains for justified service boundaries' },
      { type: 'p', text: 'Subdomains are not created for convenience. They are reserved for clear security, protocol, or independently operated common-service boundaries.' },
      { type: 'quote', text: 'The URL locates a space. Authority follows an immutable internal identity.' },
    ],
  },
  {
    slug: 'less-dependency-more-independence',
    title: '기술을 더 쌓기보다 의존을 줄입니다',
    titleEn: 'Reduce Dependency Before Adding More Technology',
    excerpt: '외부 서비스는 중요한 도구이지만 플랫폼의 정체성과 생존을 한 업체의 정책에 맡기지 않습니다.',
    excerptEn: 'External services are valuable tools, but the platform should not surrender its identity or survival to one vendor.',
    publishedAt: '2026-08-29T09:00:00+09:00',
    updatedAt: '2026-08-29T09:00:00+09:00',
    category: 'principles',
    categoryLabel: '원칙과 가치',
    categoryLabelEn: 'Principles',
    values: ['Diaspora', 'Jubilee', 'Portability'],
    author,
    readMinutes: 4,
    featured: false,
    imageVariant: 4,
    body: [
      { type: 'lead', text: '좋은 플랫폼은 연결을 많이 가진 플랫폼이 아니라, 연결이 하나 끊겨도 전체가 무너지지 않는 플랫폼입니다.' },
      { type: 'p', text: '에코디는 Google, Cloudflare, AI 제공자 같은 외부 서비스를 적극적으로 사용합니다. 그러나 핵심 정체성, 권한, 업무 상태와 데이터의 기준은 에코디가 통제 가능한 영역에 둡니다.' },
      { type: 'heading', text: '교체 가능한 부품처럼 연결하기' },
      { type: 'list', items: ['표준 프로토콜과 이식 가능한 데이터 구조 우선', '외부 서비스별 어댑터와 명시적 계약', '핵심 기능의 비AI 또는 대체 경로 유지', '사용자가 자신의 데이터를 가져갈 수 있는 출구 보장'] },
      { type: 'p', text: '독립성은 외부와 단절하는 것이 아닙니다. 더 자유롭게 연결하기 위해 결박을 줄이는 일입니다.' },
    ],
    bodyEn: [
      { type: 'lead', text: 'A resilient platform is not one with the most connections. It is one that keeps standing when one connection fails.' },
      { type: 'p', text: 'EKODI actively uses external providers while keeping identity, authorization, operational truth, and portable data under EKODI-controlled boundaries.' },
      { type: 'heading', text: 'Connect providers as replaceable parts' },
      { type: 'list', items: ['Prefer open protocols and portable formats', 'Use explicit provider adapters and contracts', 'Preserve non-AI or alternate core paths', 'Keep a real exit path for user data'] },
    ],
  },
  {
    slug: 'build-in-public-verifiable-change',
    title: '완성보다 검증 가능한 변화',
    titleEn: 'Prefer Verifiable Change Over the Appearance of Completion',
    excerpt: '구축했다고 말하는 것과 실제 운영환경에서 확인되는 것은 다릅니다. 에코디는 변경을 검증 가능한 단위로 남깁니다.',
    excerptEn: 'Saying something is built is different from proving it works in production. EKODI records change in verifiable units.',
    publishedAt: '2026-08-28T15:00:00+09:00',
    updatedAt: '2026-08-28T15:00:00+09:00',
    category: 'build',
    categoryLabel: 'Build in Public',
    categoryLabelEn: 'Build in Public',
    values: ['Stewardship', 'Trust', 'Agency'],
    author,
    readMinutes: 3,
    featured: false,
    imageVariant: 5,
    body: [
      { type: 'lead', text: '코드가 저장되었다고 끝난 것이 아니고, 배포 명령이 성공했다고 운영이 증명된 것도 아닙니다.' },
      { type: 'p', text: '에코디의 완료 기준은 소스 검증, 테스트, 배포, 실제 도메인 확인, 모니터링까지 이어집니다. 여러 AI와 개발자가 동시에 작업할 때는 독립 브랜치와 격리된 작업공간을 사용하고 중앙 검증을 거칩니다.' },
      { type: 'heading', text: '작게 만들고, 분리하고, 확인하기' },
      { type: 'p', text: '큰 변경 한 번보다 되돌릴 수 있는 작은 변경을 선호합니다. 실패를 숨기지 않고 관찰 가능한 상태로 남겨 다음 판단의 재료로 사용합니다.' },
      { type: 'quote', text: '완료는 선언이 아니라 검증된 상태입니다.' },
    ],
    bodyEn: [
      { type: 'lead', text: 'A commit is not completion, and a successful deploy command is not proof that production works.' },
      { type: 'p', text: 'EKODI treats validation, tests, release, real-host verification, and observability as part of the definition of done. Parallel agents work in isolated branches and worktrees before central validation.' },
      { type: 'heading', text: 'Build small, isolate, verify' },
      { type: 'quote', text: 'Completion is not a declaration. It is a verified state.' },
    ],
  },
]);

export function getPublishedPosts() {
  return JOURNAL_POSTS
    .filter((post) => post.publishedAt)
    .slice()
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));
}

export function getPost(slug) {
  return getPublishedPosts().find((post) => post.slug === String(slug || '').trim()) || null;
}

export function toPublicSummary(post) {
  return {
    slug: post.slug,
    title: post.title,
    titleEn: post.titleEn,
    excerpt: post.excerpt,
    excerptEn: post.excerptEn,
    publishedAt: post.publishedAt,
    updatedAt: post.updatedAt,
    category: post.category,
    categoryLabel: post.categoryLabel,
    categoryLabelEn: post.categoryLabelEn,
    values: post.values,
    author: post.author,
    readMinutes: post.readMinutes,
    featured: post.featured,
    imageVariant: post.imageVariant,
    url: `${JOURNAL_META.canonicalOrigin}/p/${encodeURIComponent(post.slug)}`,
  };
}
