import { isAllowedOrigin } from './auth-worker.js';
import { canonicalAiSubject, resolveCanonicalEkodiIdentity } from './personal-ai-bridge.js';

const SB='https://renzehysxirjilvdxacv.supabase.co';
const KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const VALID_STATUS=new Set(['started','completed']);
const TRACKS=Object.freeze([
  {id:'ai-foundations',title:{ko:'AI와 에이전트 기초',en:'AI & Agent Foundations'},summary:{ko:'AI를 책임 있는 실행 파트너로 이해합니다.',en:'Understand AI as a bounded execution partner.'},skills:[
    {id:'ai-literacy',title:{ko:'AI 리터러시',en:'AI literacy'},minutes:20},
    {id:'prompt-to-workflow',title:{ko:'프롬프트에서 워크플로로',en:'Prompt to workflow'},minutes:25,requires:['ai-literacy']},
    {id:'human-gates',title:{ko:'사람의 승인과 안전',en:'Human gates & safety'},minutes:20,requires:['prompt-to-workflow']}]},
  {id:'small-business-ai',title:{ko:'소상공인 AI 실전',en:'Small Business AI'},summary:{ko:'고객·마케팅·운영 문제를 작은 자동화로 바꿉니다.',en:'Turn customer, marketing and operations work into small automations.'},skills:[
    {id:'customer-map',title:{ko:'고객 여정 그리기',en:'Customer journey map'},minutes:20},
    {id:'content-loop',title:{ko:'콘텐츠 반복업무 자동화',en:'Content loop automation'},minutes:25,requires:['customer-map']},
    {id:'measure-learn',title:{ko:'성과 측정과 개선',en:'Measure and learn'},minutes:25,requires:['content-loop']}]},
  {id:'ekodi-builder',title:{ko:'EKODI 운영자',en:'EKODI Builder'},summary:{ko:'격리 개발부터 실서비스 확인까지 익힙니다.',en:'Learn isolated development through verified production release.'},skills:[
    {id:'isolated-change',title:{ko:'격리된 변경',en:'Isolated change'},minutes:20},
    {id:'guardrails',title:{ko:'가드레일과 테스트',en:'Guardrails & tests'},minutes:25,requires:['isolated-change']},
    {id:'production-proof',title:{ko:'운영 배포와 증거',en:'Production proof'},minutes:25,requires:['guardrails']}]}
]);const ALL_SKILLS=new Map(TRACKS.flatMap(track=>track.skills.map(skill=>[skill.id,{...skill,trackId:track.id}])));
function json(data,status,request,env){const origin=request.headers.get('origin')||'';const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',vary:'Origin','access-control-allow-methods':'GET, PUT, OPTIONS','access-control-allow-headers':'content-type, authorization'};if(origin&&isAllowedOrigin(origin,env))headers['access-control-allow-origin']=origin;return new Response(JSON.stringify(data),{status,headers});}
function token(request){const raw=String(request.headers.get('authorization')||'');return raw.toLowerCase().startsWith('bearer ')?raw.slice(7).trim():'';}
async function identity(request){const access=token(request);if(!access||access.length>8192)return null;const response=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,authorization:`Bearer ${access}`}});if(!response.ok)return null;const user=await response.json().catch(()=>null);if(!user?.id||!user?.email_confirmed_at)return null;return resolveCanonicalEkodiIdentity({token:access,authUser:{id:String(user.id),email:String(user.email||'')}});}
function subject(identity){return canonicalAiSubject(identity)||`auth:${identity?.authUserId||identity?.id||''}`;}
async function ensureSchema(db){await db.batch([
  db.prepare("CREATE TABLE IF NOT EXISTS learning_progress (user_id TEXT NOT NULL,skill_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'started',score INTEGER NOT NULL DEFAULT 0,minutes INTEGER NOT NULL DEFAULT 0,evidence TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT,PRIMARY KEY(user_id,skill_id))"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_learning_progress_user_updated ON learning_progress(user_id,updated_at DESC)"),
  db.prepare("CREATE TABLE IF NOT EXISTS learning_events (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,skill_id TEXT NOT NULL,event_type TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_learning_events_user_created ON learning_events(user_id,created_at DESC)")
]);}
function recommendations(progress=[]){const done=new Set(progress.filter(item=>item.status==='completed').map(item=>item.skillId));const out=[];for(const track of TRACKS){for(const skill of track.skills){if(done.has(skill.id))continue;const requires=skill.requires||[];if(requires.every(id=>done.has(id)))out.push({skillId:skill.id,trackId:track.id,title:skill.title,minutes:skill.minutes});if(out.length>=3)return out;}}return out;}
async function readProgress(env,userId){const rows=await env.DB.prepare('SELECT skill_id,status,score,minutes,evidence,created_at,updated_at,completed_at FROM learning_progress WHERE user_id=? ORDER BY updated_at DESC').bind(userId).all();return(rows.results||[]).map(row=>({skillId:row.skill_id,status:row.status,score:Number(row.score||0),minutes:Number(row.minutes||0),evidence:row.evidence||'',createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at||null}));}async function saveProgress(request,env,userId){let body=null;try{body=await request.json();}catch{}const skillId=String(body?.skillId||'').trim();if(!ALL_SKILLS.has(skillId))return json({error:'learning_skill_not_found'},404,request,env);const status=VALID_STATUS.has(body?.status)?body.status:'started';const score=Math.max(0,Math.min(100,Math.trunc(Number(body?.score)||0)));const minutes=Math.max(0,Math.min(10000,Math.trunc(Number(body?.minutes)||0)));const evidence=String(body?.evidence||'').trim().slice(0,500);const now=new Date().toISOString();const completedAt=status==='completed'?now:null;await env.DB.prepare(`INSERT INTO learning_progress(user_id,skill_id,status,score,minutes,evidence,created_at,updated_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,skill_id) DO UPDATE SET status=excluded.status,score=MAX(learning_progress.score,excluded.score),minutes=MAX(learning_progress.minutes,excluded.minutes),evidence=CASE WHEN excluded.evidence='' THEN learning_progress.evidence ELSE excluded.evidence END,updated_at=excluded.updated_at,completed_at=CASE WHEN excluded.status='completed' THEN COALESCE(learning_progress.completed_at,excluded.completed_at) ELSE learning_progress.completed_at END`).bind(userId,skillId,status,score,minutes,evidence,now,now,completedAt).run();await env.DB.prepare('INSERT INTO learning_events(id,user_id,skill_id,event_type,detail,created_at) VALUES(?,?,?,?,?,?)').bind(`lev_${crypto.randomUUID()}`,userId,skillId,status==='completed'?'skill.completed':'skill.updated',JSON.stringify({score,minutes}),now).run();const progress=await readProgress(env,userId);return json({ok:true,progress,recommendations:recommendations(progress)},200,request,env);}
export async function handleLearningControl(request,env={}){const url=new URL(request.url);if(!url.pathname.startsWith('/api/learning/'))return null;const origin=request.headers.get('origin');if(origin&&!isAllowedOrigin(origin,env))return json({error:'learning_origin_forbidden'},403,request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-methods':'GET, PUT, OPTIONS','access-control-allow-headers':'content-type, authorization',...(origin?{'access-control-allow-origin':origin,vary:'Origin'}:{})}});if(request.method==='GET'&&url.pathname==='/api/learning/catalog')return json({schemaVersion:1,service:'ekodi-learning-fabric',tracks:TRACKS,guestAccess:true,memberProgressSync:true,aiCoach:'/api/user-ai/assist'},200,request,env);if(request.method==='GET'&&url.pathname==='/api/learning/health'){let dbReady=false;try{if(env.DB){await ensureSchema(env.DB);dbReady=true;}}catch{}return json({ok:dbReady,service:'ekodi-learning-fabric',catalogTracks:TRACKS.length,dbReady},dbReady?200:503,request,env);}if(!env.DB)return json({error:'learning_database_unavailable'},503,request,env);const who=await identity(request);if(!who)return json({error:'learning_auth_required'},401,request,env);await ensureSchema(env.DB);const userId=subject(who);if(request.method==='GET'&&url.pathname==='/api/learning/progress'){const progress=await readProgress(env,userId);return json({progress,recommendations:recommendations(progress)},200,request,env);}if(request.method==='PUT'&&url.pathname==='/api/learning/progress')return saveProgress(request,env,userId);return json({error:'learning_endpoint_not_found'},404,request,env);}
export const LEARNING_FABRIC_CATALOG=TRACKS;