const HTML=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EKODI Learning Fabric</title><link rel="stylesheet" href="/learn/assets/style.css"></head><body><header class="hero"><div class="wrap"><p class="eyebrow">EKODI LEARNING FABRIC</p><h1>배움이 실제 능력이 되게.</h1><p class="lead">작게 배우고, 직접 해보고, 완료 증거를 남깁니다.</p><div class="actions"><span id="identityStatus">비회원도 바로 학습 가능</span><a id="authLink" class="button" href="https://auth.ekodi.kr/?site=learn&return_to=https%3A%2F%2Fekodi.kr%2Flearn">Google로 진도 연결</a></div></div></header><main class="wrap"><p id="summary">학습 경로 불러오는 중</p><section id="tracks" class="grid"></section><section class="coach"><h2>AI 코치</h2><p>로그인 회원은 EKODI 개인 AI 라우팅으로 질문할 수 있습니다.</p><textarea id="coachInput" maxlength="2000" placeholder="막힌 지점을 질문해 주세요"></textarea><button id="coachAsk" class="button" type="button">AI 코치에게 묻기</button><div id="coachOutput" hidden></div></section></main><script src="/learn/assets/app.js" defer></script></body></html>`;

const STYLE=`*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#f4f7f2;color:#17231d}.wrap{width:min(1100px,calc(100% - 32px));margin:auto}.hero{padding:64px 0 36px;background:linear-gradient(180deg,#eef4ed,#f8faf6)}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.15em;color:#50705d}h1{font-size:clamp(40px,7vw,72px);line-height:1;letter-spacing:-.05em;margin:12px 0}.lead{font-size:20px;color:#58675f}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.button{border:0;border-radius:14px;padding:11px 15px;background:#214c35;color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:28px 0}.track{background:#fff;border:1px solid #dce4dd;border-radius:22px;padding:20px}.skill{padding:12px 0;border-top:1px solid #e7ece8}.skill button{margin-top:8px}.done{color:#2c6c42;font-weight:800}.locked{opacity:.5}.coach{margin:30px 0 60px;background:#172a20;color:#fff;border-radius:24px;padding:24px}.coach textarea{width:100%;min-height:100px;border:0;border-radius:14px;padding:12px;margin:10px 0}.coach div{white-space:pre-wrap;background:#223c2e;padding:14px;border-radius:14px;margin-top:12px}@media(max-width:850px){.grid{grid-template-columns:1fr}}`;

function out(body,type){return new Response(body,{headers:{'content-type':type+'; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; script-src 'self' https://shell.ekodi.kr; style-src 'self' 'unsafe-inline' https://shell.ekodi.kr; connect-src 'self' https://renzehysxirjilvdxacv.supabase.co https://shell.ekodi.kr; img-src 'self' data: https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"}})}
export function isLearningPath(path){return path==='/learn'||path==='/learn/'||path==='/learn/assets/style.css'||path==='/learn/assets/app.js'}
export function learningPage(){return out(HTML,'text/html')}
export function learningStyles(){return out(STYLE,'text/css')}const APP=`const SB='https://renzehysxirjilvdxacv.supabase.co';
const KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const SESSION='ekodi-learning-session-v1',GUEST='ekodi-learning-guest-v1';
let catalog=[],progress=new Map(),session=null;
const $=id=>document.getElementById(id);const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readGuest(){try{return JSON.parse(localStorage.getItem(GUEST)||'{}')}catch{return{}}}function saveGuest(){const data={};for(const [id,row] of progress)data[id]=row;localStorage.setItem(GUEST,JSON.stringify(data))}
function readSession(){try{const v=JSON.parse(sessionStorage.getItem(SESSION)||'null');return v&&v.accessToken?v:null}catch{return null}}function authHeaders(){return session?{authorization:'Bearer '+session.accessToken}:{}}
async function exchange(){const p=new URLSearchParams(location.hash.slice(1)),token=p.get('ekodi_token');if(!token)return false;const r=await fetch(SB+'/auth/v1/verify',{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body:JSON.stringify({token_hash:token,type:p.get('ekodi_type')||'email'})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'login_failed');session={accessToken:d.access_token,user:d.user||{}};sessionStorage.setItem(SESSION,JSON.stringify(session));history.replaceState(null,'',location.pathname);return true}
async function api(path,options={}){const headers={accept:'application/json',...authHeaders(),...(options.headers||{})};if(options.body&&!headers['content-type'])headers['content-type']='application/json';const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('http_'+r.status));return d}
function identity(){if(session){$('identityStatus').textContent=(session.user.email||'EKODI 회원')+' · 진도 동기화';$('authLink').textContent='로그아웃';$('authLink').href='#logout'}else{$('identityStatus').textContent='비회원도 바로 학습 가능';$('authLink').textContent='Google로 진도 연결';$('authLink').href='https://auth.ekodi.kr/?site=learn&return_to=https%3A%2F%2Fekodi.kr%2Flearn'}}
function unlocked(skill){return (skill.requires||[]).every(id=>progress.get(id)?.status==='completed')}
function render(){let total=0,done=0;for(const t of catalog){total+=t.skills.length;done+=t.skills.filter(s=>progress.get(s.id)?.status==='completed').length}$('summary').textContent='완료 '+done+' / '+total+' · '+Math.round((done/Math.max(total,1))*100)+'%';$('tracks').innerHTML=catalog.map(t=>'<article class="track"><p class="eyebrow">'+esc(t.title.ko)+'</p><h2>'+esc(t.title.ko)+'</h2><p>'+esc(t.summary.ko)+'</p>'+t.skills.map(s=>{const row=progress.get(s.id),lock=!unlocked(s);return '<div class="skill '+(lock?'locked':'')+'"><strong>'+esc(s.title.ko)+'</strong><small> · '+s.minutes+'분</small><div class="'+(row?.status==='completed'?'done':'')+'">'+(row?.status==='completed'?'완료':'진행 전')+'</div><button class="button" data-skill="'+s.id+'" '+(lock?'disabled':'')+'>'+(row?.status==='completed'?'완료됨':'완료 표시')+'</button></div>'}).join('')+'</article>').join('');document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>complete(b.dataset.skill))}
async function complete(id){const skill=catalog.flatMap(t=>t.skills).find(s=>s.id===id);progress.set(id,{skillId:id,status:'completed',minutes:skill?.minutes||0,score:100});saveGuest();render();if(session){try{await api('/api/learning/progress',{method:'PUT',body:JSON.stringify(progress.get(id))})}catch(e){console.error(e)}}}
async function loadProgress(){const guest=readGuest();for(const [id,row] of Object.entries(guest))progress.set(id,row);if(session){const d=await api('/api/learning/progress');for(const row of d.progress||[])progress.set(row.skillId,row);for(const row of Object.values(guest)){if(row.status==='completed')await api('/api/learning/progress',{method:'PUT',body:JSON.stringify(row)}).catch(()=>{})}}render()}
async function coach(){if(!session){$('coachOutput').hidden=false;$('coachOutput').textContent='AI 코치는 로그인 회원에게 제공됩니다. 위의 Google 연결을 먼저 이용해 주세요.';return}const q=$('coachInput').value.trim();if(!q)return;const r=await api('/api/user-ai/assist',{method:'POST',body:JSON.stringify({site:'edu',intent:'interactive',aiRequired:true,dataClass:'general',message:'EKODI Learning Fabric 학습 코치로 답해 주세요. 짧은 설명, 바로 해볼 실습 1개, 확인 질문 1개를 주세요. 질문: '+q})});$('coachOutput').hidden=false;$('coachOutput').textContent=r.text||r.notice||'현재 Core 학습 모드로 계속 이용할 수 있습니다.'}
async function boot(){session=readSession();try{await exchange()}catch(e){console.error(e)}identity();const d=await api('/api/learning/catalog');catalog=d.tracks||[];await loadProgress();$('coachAsk').onclick=coach;$('authLink').onclick=e=>{if(session&&$('authLink').getAttribute('href')==='#logout'){e.preventDefault();sessionStorage.removeItem(SESSION);session=null;identity();render()}}}
boot().catch(e=>{$('summary').textContent='학습 시스템 연결 확인 필요: '+e.message});`;
export function learningScript(){return out(APP,'application/javascript')}
