const BRAND=Object.freeze({
  pizzamaru:{brand:'피자마루',branch:'목포대점',category:'피자',mark:'PM',tagline:'목포대 후문에서 오늘 먹고 싶은 피자를 바로 만나보세요.',address:'전남 무안군 청계면 승달산길 37-1 1층',phone:'061-453-8295',officialImageHosts:['www.pizzamaru.co.kr','pizzamaru.co.kr']},
  jadam:{brand:'자담치킨',branch:'목포대점',category:'치킨',mark:'JD',tagline:'국립목포대학교 후문, 메뉴·앱별 가격·주문을 한 화면에서 확인하세요.',address:'전남 무안군 청계면 승달산길 37-1',phone:'061-453-8295'},
  yogurt:{brand:'요거트퍼플',branch:'목포대점',category:'요거트',mark:'YP',tagline:'목포대점의 디저트와 주문을 가장 빠르게 연결합니다.'},
});
const PROVIDERS=Object.freeze({
  ddangyo:{label:'땡겨요',order:1},baemin:{label:'배달의민족',order:2},
  yogiyo:{label:'요기요',order:3},mukkebi:{label:'먹깨비',order:4},
  coupang_eats:{label:'쿠팡이츠',order:5},store:{label:'피자마루 공식 주문',order:6},
});
const YOGURT_REFERENCE_MENU=Object.freeze([
  {name:'플레인 요거트아이스크림',category:'요거트아이스크림',base_price:4500,icon:'🍦'},
  {name:'딸기 요거트아이스크림',category:'요거트아이스크림',base_price:5500,icon:'🍓'},
  {name:'초코 요거트아이스크림',category:'요거트아이스크림',base_price:5500,icon:'🍫'},
  {name:'퍼플 요거트아이스크림',category:'요거트아이스크림',base_price:5500,icon:'💜'},
  {name:'그릭요거트 100g',category:'그릭요거트',base_price:4500,icon:'🥣'},
  {name:'요아츄',category:'요거트아이스크림',base_price:6000,icon:'✨'},
  {name:'딸기 요아츄',category:'요거트아이스크림',base_price:7000,icon:'🍓'},
  {name:'초코 요아츄',category:'요거트아이스크림',base_price:7000,icon:'🍫'},
  {name:'퍼플 요아츄',category:'요거트아이스크림',base_price:7000,icon:'💜'},
  {name:'초코갤럭시',category:'요거트아이스크림',base_price:11900,icon:'🌌'},
  {name:'베리베리그래놀라',category:'요거트아이스크림',base_price:12900,icon:'🫐'},
  {name:'바나나몽땅',category:'요거트아이스크림',base_price:12900,icon:'🍌'},
]);
const YOGURT_ORDER_PROVIDERS=Object.freeze([
  {provider:'baemin',label:'배달의민족',mark:'배민',url:'https://www.baemin.com/'},
  {provider:'coupang_eats',label:'쿠팡이츠',mark:'C',url:'https://www.coupangeats.com/'},
  {provider:'yogiyo',label:'요기요',mark:'요기요',url:'https://www.yogiyo.co.kr/mobile/'},
  {provider:'daangn_order',label:'당근주문',mark:'🥕',url:'https://www.daangn.com/kr/local-profile/?search='+encodeURIComponent('요거트퍼플 목포대점')},
  {provider:'naver_order',label:'네이버주문',mark:'N',url:'https://map.naver.com/p/search/'+encodeURIComponent('요거트퍼플 무안목포대점')},
]);

const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeHttps(value){try{const u=new URL(String(value||''));return u.protocol==='https:'?u.href:''}catch{return''}}
function officialImage(value,hosts=[]){const src=safeHttps(value);if(!src)return'';try{return hosts.map(x=>String(x).toLowerCase()).includes(new URL(src).hostname.toLowerCase())?src:''}catch{return''}}
function phoneText(value){return String(value||'').trim()}
function telUrl(value){const phone=phoneText(value).replace(/[^0-9+]/g,'');return phone?`tel:${phone}`:''}
function won(value){return Number.isFinite(Number(value))?`${Number(value).toLocaleString('ko-KR')}원`:''}
function hoursText(value){
  if(!value||typeof value!=='object'||!Object.keys(value).length)return'';
  if(Array.isArray(value))return value.map(String).join(' · ');
  return Object.entries(value).map(([k,v])=>`${k} ${Array.isArray(v)?v.join(', '):String(v)}`).join(' · ');
}
function mapUrl(address){return address?`https://map.naver.com/p/search/${encodeURIComponent(address)}`:''}
async function snapshot(slug,env){
  if(!slug||!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)return null;
  const endpoint=`${env.SUPABASE_URL}/rest/v1/rpc/store_user_site_public_snapshot`;
  try{
    const r=await fetch(endpoint,{method:'POST',headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({p_slug:slug})});
    if(!r.ok)return null;
    const d=await r.json().catch(()=>null);
    return d&&typeof d==='object'?d:null;
  }catch{return null}
}
function officialLinks(slug){
  if(slug==='pizzamaru')return{menu:'https://www.pizzamaru.co.kr/menu/',order:'https://www.pizzamaru.co.kr/orderchoice/?deliv_type=1'};
  return{menu:'',order:''};
}
function providerMeta(provider){return PROVIDERS[provider]||{label:String(provider||'배달앱'),order:99}}
function action(href,label,{primary=false,external=false}={}){
  return href?`<a class="action${primary?' primary':''}" href="${e(href)}"${external?' target="_blank" rel="noopener noreferrer"':''}>${e(label)}</a>`:'';
}
function mobile(href,label,external=false){
  return href?`<a href="${e(href)}"${external?' target="_blank" rel="noopener noreferrer"':''}>${e(label)}</a>`:'<span></span>';
}
const CSS=`:root{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif;--ink:#251b18;--muted:#72625c;--brand:#a33f2d;--dark:#7b2e21;--soft:#fff0e9;--paper:#fffdfb;--line:#ead8d0;color:var(--ink);background:#fffaf7;word-break:keep-all}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fffaf7;color:var(--ink)}a{color:inherit}.sf{min-height:100vh;overflow:hidden}.top{width:min(1180px,calc(100% - 40px));height:70px;margin:auto;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;gap:9px;align-items:baseline;text-decoration:none}.brand b{font-size:18px}.brand span{font-size:12px;font-weight:900;color:var(--brand)}nav{display:flex;gap:20px}nav a{text-decoration:none;font-size:13px;font-weight:800;color:#5e4d47}
html[data-store-page="pizzamaru"]{--brand:#b3132b;--dark:#121827;--soft:#fff0f2;--line:#eadde1}html[data-store-page="pizzamaru"] .hero{background:radial-gradient(circle at 83% 39%,#f5c5b6 0 13%,transparent 13.4%),radial-gradient(circle at 83% 39%,#d75a48 0 22%,transparent 22.4%),linear-gradient(125deg,#fff8f8,#fbe9ed 58%,#121827)}html[data-store-page="pizzamaru"] .hero h1 span{color:#6d1728}html[data-store-page="pizzamaru"] .action.primary{background:#b3132b;border-color:#b3132b}
html[data-store-page="jadam"]{--ink:#152219;--muted:#607066;--brand:#174f2c;--dark:#10391f;--soft:#edf6ef;--paper:#fff;--line:#dce8df;background:#f7faf7}html[data-store-page="jadam"] body{background:#f7faf7}html[data-store-page="jadam"] .hero{background:radial-gradient(circle at 84% 38%,rgba(23,79,44,.16) 0 14%,transparent 14.5%),linear-gradient(125deg,#fbfefb,#edf6ef 62%,#d6e7da)}html[data-store-page="jadam"] .hero h1 span{color:#315b3e}html[data-store-page="jadam"] .action.primary{background:#174f2c;border-color:#174f2c}
.hero{min-height:550px;border-block:1px solid var(--line);background:linear-gradient(125deg,#fff8f4,#ffede4 58%,#f8d9cb)}.hero-in{width:min(1180px,calc(100% - 40px));margin:auto;padding:76px 0 64px;display:grid;grid-template-columns:minmax(0,720px) 1fr;gap:42px}.kicker{margin:0 0 14px;color:var(--brand);font-size:12px;font-weight:950;letter-spacing:.12em}.hero h1{margin:0;line-height:.93;letter-spacing:-.065em}.hero h1 span{display:block;font-size:clamp(26px,3vw,43px);font-weight:700;color:#64473e}.hero h1 strong{display:block;margin-top:8px;font-size:clamp(62px,9vw,116px);font-weight:950}.lead{max-width:600px;margin:24px 0 0;font-size:18px;line-height:1.7;color:#64534d}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:30px}.action{display:inline-flex;align-items:center;justify-content:center;min-height:52px;padding:0 19px;border:1px solid #d8bbb0;border-radius:14px;background:rgba(255,255,255,.86);text-decoration:none;font-size:14px;font-weight:900}.action.primary{background:var(--brand);border-color:var(--brand);color:#fff}
.facts{align-self:end;display:grid;gap:15px;padding:24px;border-left:1px solid rgba(80,46,35,.16)}.fact small{display:block;margin-bottom:4px;color:#806c65;font-size:11px}.fact strong,.fact a{font-size:15px;font-weight:850;line-height:1.5;text-decoration:none}.section{width:min(1180px,calc(100% - 40px));margin:auto;padding:72px 0}.section+.section{border-top:1px solid var(--line)}.head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:28px}.head h2{margin:0;font-size:clamp(34px,5vw,52px);letter-spacing:-.05em}.head p{max-width:560px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}
`;const MENU_CSS=`.menu{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.menu-card{overflow:hidden;border:1px solid var(--line);border-radius:20px;background:var(--paper);box-shadow:0 10px 34px rgba(82,44,32,.06)}.menu-media{aspect-ratio:4/3;background:linear-gradient(145deg,#f7e8e2,#fff7f4);overflow:hidden;display:grid;place-items:center}.menu-media img{width:100%;height:100%;object-fit:cover;display:block}.menu-media .fallback{font-size:34px;font-weight:950;color:var(--brand);letter-spacing:-.06em}.menu-body{padding:20px}.menu-meta{display:flex;align-items:center;justify-content:space-between;gap:10px}.menu-meta small{color:var(--brand);font-size:10px;font-weight:950;letter-spacing:.06em}.menu-source{font-size:10px;color:#8b7770}.menu h3{margin:10px 0 6px;font-size:21px;letter-spacing:-.03em}.menu-desc{min-height:42px;margin:0;color:var(--muted);font-size:13px;line-height:1.55}.base-price{display:flex;align-items:center;justify-content:space-between;margin-top:16px;padding-top:14px;border-top:1px solid #f0e5e1}.base-price span{font-size:11px;color:#806e68}.base-price strong{font-size:18px}.platform-prices{display:grid;gap:7px;margin-top:14px}.platform-price{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:8px;padding:9px 10px;border:1px solid #eee4e0;border-radius:11px;background:#fff}.platform-price b{font-size:11px}.platform-price strong{font-size:13px}.platform-price a{padding:6px 8px;border-radius:8px;background:var(--brand);color:#fff;text-decoration:none;font-size:10px;font-weight:900}.platform-empty{margin-top:13px;padding:10px 11px;border-radius:10px;background:#faf5f3;color:#89736b;font-size:10px;line-height:1.55}.lowest{display:inline-flex;margin-top:11px;border-radius:999px;background:#fff1db;color:#8e5a11;padding:5px 8px;font-size:10px;font-weight:900}.price-note{margin-top:18px;padding:12px 14px;border-radius:12px;background:#f8f2ef;color:#7c6760;font-size:11px;line-height:1.6}
.order{display:grid;grid-template-columns:1.15fr .85fr;gap:40px}.order-links{display:grid;gap:10px}.order-link{display:flex;align-items:center;justify-content:space-between;min-height:62px;padding:0 18px;border:1px solid var(--line);background:#fff;text-decoration:none;font-weight:900}.order-link span{color:var(--brand);font-size:12px}.note{padding:24px;background:var(--soft);color:#604b44;line-height:1.7}.note strong{display:block;margin-bottom:6px;color:var(--dark)}.empty{padding:32px;border:1px solid var(--line);background:var(--paper)}.empty strong{display:block;font-size:20px}.empty p{margin:8px 0 18px;color:var(--muted);line-height:1.6}footer{padding:34px 20px 108px;text-align:center;color:#88756e;font-size:12px}.mobile{display:none}
@media(max-width:920px){.menu{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:820px){.top{height:62px}nav{display:none}.hero{min-height:auto}.hero-in{grid-template-columns:1fr;padding:52px 0 46px}.facts{border-left:0;border-top:1px solid rgba(80,46,35,.16);padding:20px 0 0;grid-template-columns:1fr 1fr}.order{grid-template-columns:1fr}.section{padding:54px 0}.head{align-items:flex-start;flex-direction:column}.mobile{position:fixed;z-index:50;left:10px;right:10px;bottom:10px;display:grid;grid-template-columns:repeat(4,1fr);padding:6px;border:1px solid var(--line);border-radius:16px;background:rgba(255,253,251,.96);box-shadow:0 12px 40px rgba(65,38,28,.15)}.mobile a,.mobile span{padding:10px 3px;text-align:center;text-decoration:none;font-size:11px;font-weight:900}.mobile a:last-child{background:var(--brand);color:#fff;border-radius:11px}}@media(max-width:560px){.top,.hero-in,.section{width:min(100% - 24px,1180px)}.hero h1 strong{font-size:64px}.lead{font-size:16px}.actions{display:grid;grid-template-columns:1fr 1fr}.action{padding:0 10px}.facts{grid-template-columns:1fr}.menu{grid-template-columns:1fr}.head h2{font-size:36px}.menu-desc{min-height:auto}}`;
const YOGURT_CSS=`html[data-store-page="yogurt"]{--yp:#5b168f;--yp2:#7a30b5;--gold:#ffd51f;--ink:#311343;--muted:#75667d;--line:#eadcf1;background:#fff}html[data-store-page="yogurt"] body{background:#fff;color:var(--ink)}html[data-store-page="yogurt"] .sf{background:#fff}.yp-top{position:sticky;top:0;z-index:50;height:76px;padding:0 max(22px,calc((100vw - 1280px)/2 + 22px));display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:24px;background:rgba(255,255,255,.97);box-shadow:0 1px 0 rgba(91,22,143,.08);backdrop-filter:blur(16px)}.yp-brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:var(--yp)}.yp-brand .crown{font-size:34px;color:var(--gold)}.yp-brand b{display:block;font-size:20px;line-height:1;font-weight:1000;letter-spacing:-.045em}.yp-brand small{display:block;margin-top:5px;font-size:7px;letter-spacing:.08em;font-weight:800}.yp-nav{display:flex;gap:34px}.yp-nav a{text-decoration:none;font-size:14px;font-weight:850}.yp-branch{justify-self:end;padding:10px 16px;border-radius:999px;background:linear-gradient(135deg,var(--yp2),var(--yp));color:#fff;font-size:13px;font-weight:900;text-decoration:none}
.yp-hero{min-height:590px;display:grid;grid-template-columns:1.02fr .98fr;background:radial-gradient(circle at 8% 8%,#fff 0 5%,transparent 23%),linear-gradient(110deg,#fff 0%,#f4e6ff 47%,#b778df 100%)}.yp-copy{padding:68px 0 52px;margin-left:max(22px,calc((100vw - 1280px)/2 + 22px));max-width:650px;z-index:2}.yp-script{display:block;color:#8a2db0;font-size:25px;font-weight:900;letter-spacing:-.04em;transform:rotate(-2deg);transform-origin:left}.yp-copy h1{margin:16px 0 0;color:var(--yp);font-size:clamp(58px,6.4vw,92px);line-height:.92;letter-spacing:-.08em;font-weight:1000}.yp-copy h1 strong{display:inline-block;margin-top:11px;padding:6px 12px 10px;border-radius:14px;background:var(--gold);color:var(--yp)}.yp-copy p{max-width:600px;margin:26px 0 0;color:#442852;font-size:18px;line-height:1.65;font-weight:650}.yp-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:28px}.yp-action{display:inline-flex;min-height:50px;padding:0 18px;border-radius:12px;align-items:center;justify-content:center;text-decoration:none;font-size:13px;font-weight:900}.yp-action.menu{background:var(--yp);color:#fff}.yp-action.phone{background:var(--gold);color:#382347}.yp-action.order{background:#fa2c64;color:#fff}.yp-benefits{display:flex;gap:18px;flex-wrap:wrap;margin-top:21px;color:#563565;font-size:12px;font-weight:850}
.yp-art{position:relative;min-height:590px}.yp-campus{position:absolute;left:5%;top:8%;width:250px;padding:14px;border-radius:15px;background:rgba(255,255,255,.88);box-shadow:0 12px 30px rgba(74,20,107,.12)}.yp-campus small{display:block;color:#718091;font-size:8px;font-weight:900;letter-spacing:.12em}.yp-campus b{display:block;margin-top:4px;color:#31516f;font-size:15px}.yp-bowl{position:absolute;right:8%;bottom:5%;width:375px;height:295px;border-radius:36% 36% 19% 19%/18% 18% 14% 14%;background:linear-gradient(180deg,#7b2fb0,#561783 75%);box-shadow:0 35px 65px rgba(79,20,113,.28)}.yp-bowl:before{content:"";position:absolute;left:-2%;right:-2%;top:-9%;height:26%;border-radius:50%;background:#fff;box-shadow:inset 0 -10px 20px rgba(91,22,143,.12)}.yp-swirl{position:absolute;z-index:3;left:50%;top:-130px;width:175px;height:190px;transform:translateX(-50%);border-radius:55% 45% 48% 52%;background:radial-gradient(ellipse at 45% 18%,#fff 0 18%,transparent 19%),radial-gradient(ellipse at 56% 39%,#fff 0 29%,transparent 30%),radial-gradient(ellipse at 50% 72%,#fff 0 38%,transparent 39%)}.yp-swirl:after{content:"";position:absolute;left:57%;top:52%;width:43px;height:106px;border-radius:50%;background:linear-gradient(#ff2769,#c31853);transform:rotate(16deg)}.yp-bowl .logo{position:absolute;left:0;right:0;bottom:56px;display:flex;flex-direction:column;align-items:center;color:#ffd72f;font-size:44px;line-height:.8}.yp-bowl .logo span{margin-top:9px;color:#fff;font-size:20px}.fruit{position:absolute;z-index:4;font-size:48px;filter:drop-shadow(0 8px 8px rgba(75,28,92,.15))}.f1{left:68px;top:-47px}.f2{right:68px;top:-55px}.f3{left:21px;top:-26px;font-size:39px}.f4{right:22px;top:-28px;font-size:39px}.yp-bubble{position:absolute;right:2%;top:17%;width:126px;height:126px;border-radius:50%;background:var(--gold);display:grid;place-items:center;text-align:center;color:#582589;font-size:13px;line-height:1.4;font-weight:950;transform:rotate(7deg)}
`;const YOGURT_CSS_2=`.yp-section{width:min(1280px,calc(100% - 40px));margin:auto;padding:34px 0}.yp-section+.yp-section{border-top:1px solid var(--line)}.yp-bar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.yp-bar>div{display:flex;align-items:center;gap:10px}.yp-bar .crown{color:var(--gold);font-size:25px}.yp-bar h2{margin:0;color:var(--yp);font-size:24px;letter-spacing:-.04em}.yp-bar>a{font-size:11px;font-weight:900;color:#65338f}.yp-cat{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px}.yp-cat article{min-height:98px;padding:10px 6px;border:1px solid #eadbf3;border-radius:15px;background:linear-gradient(180deg,#faf3ff,#fff);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.yp-cat span{font-size:31px}.yp-cat b{margin-top:7px;font-size:10px;line-height:1.25}.yp-note{margin:-5px 0 18px;color:#7c6e84;font-size:11px;line-height:1.6}.yp-products{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.yp-product{position:relative;min-height:224px;padding:14px;border:1px solid var(--line);border-radius:18px;background:#fff;box-shadow:0 11px 27px rgba(91,22,143,.05)}.yp-product .art{height:115px;margin-bottom:11px;border-radius:14px;background:linear-gradient(145deg,#fff5fb,#f5e9ff);display:grid;place-items:center;overflow:hidden}.yp-product .art span{font-size:60px;filter:drop-shadow(0 9px 9px rgba(93,36,127,.14))}.yp-product small{display:block;color:#8b7d93;font-size:9px;font-weight:800}.yp-product strong{display:block;min-height:40px;margin-top:5px;font-size:14px;line-height:1.35}.yp-product b{display:block;margin-top:7px;color:var(--yp);font-size:18px}.yp-product em{position:absolute;right:12px;bottom:15px;padding:4px 7px;border-radius:999px;background:#fff6c8;color:#7b6312;font-size:8px;font-style:normal;font-weight:900}.yp-combo{margin-top:16px;padding:13px 15px;border-radius:15px;background:linear-gradient(90deg,#fff0fa,#f5eaff);display:flex;gap:8px;flex-wrap:wrap;align-items:center}.yp-combo strong{color:#d82e75}.yp-combo span{padding:6px 10px;border:1px solid #ead8ef;border-radius:999px;background:#fff;font-size:10px;font-weight:850}
.yp-info{display:grid;grid-template-columns:.95fr 1.05fr;gap:14px}.yp-card{padding:23px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:0 12px 34px rgba(73,33,94,.05)}.yp-card h2{margin:0;color:var(--yp);font-size:22px}.yp-store dl{display:grid;grid-template-columns:28px 1fr;gap:14px 8px;margin:22px 0}.yp-store dd,.yp-store dt{margin:0}.yp-store dd strong{display:block;font-size:13px}.yp-store dd small{display:block;margin-top:3px;color:#8b7d92;font-size:9px}.yp-map{display:grid;grid-template-columns:1fr 1fr;gap:8px}.yp-map a{min-height:43px;border-radius:11px;display:flex;align-items:center;justify-content:center;text-decoration:none;font-size:11px;font-weight:900}.yp-map a:first-child{background:#03c75a;color:#fff}.yp-map a:last-child{background:#ffdc00;color:#382b16}.yp-orders{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:20px}.yp-order{min-height:105px;padding:8px 4px;border:1px solid #eee5f1;border-radius:14px;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;text-decoration:none}.yp-order i{display:grid;place-items:center;width:46px;height:46px;border-radius:11px;background:#f5eff8;color:#592282;font-size:15px;font-style:normal;font-weight:1000}.yp-order b{margin-top:6px;font-size:9px}.yp-order small{margin-top:2px;color:#8c7f92;font-size:7px}.yp-order.baemin i{background:#38c9c5;color:#fff}.yp-order.coupang_eats i{background:#fff0ea;color:#9f3c11}.yp-order.yogiyo i{background:#ff2453;color:#fff}.yp-order.daangn_order i{background:#ff8a2f;color:#fff}.yp-order.naver_order i{background:#03c75a;color:#fff}.yp-story{width:min(1280px,calc(100% - 40px));margin:0 auto 30px;padding:20px 22px;border-radius:20px;background:linear-gradient(110deg,#f7eaff,#fff6cc);display:flex;align-items:center;justify-content:space-between;gap:20px}.yp-story strong{color:#5b168f;font-size:18px}.yp-story a{padding:9px 12px;border-radius:999px;background:#fff;text-decoration:none;color:#60298e;font-size:10px;font-weight:900}.yp-footer{padding:25px max(22px,calc((100vw - 1280px)/2 + 22px)) 100px;background:linear-gradient(100deg,#471368,#6b2195);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:20px}.yp-footer strong{font-size:15px}.yp-footer small{opacity:.7;font-size:8px}.yp-mobile{display:none}
`;const YOGURT_CSS_3=`@media(max-width:960px){.yp-top{grid-template-columns:1fr auto}.yp-nav{display:none}.yp-hero{grid-template-columns:1fr}.yp-copy{margin:0;padding:52px 24px 26px}.yp-art{min-height:450px}.yp-bowl{right:12%;width:340px;height:270px}.yp-cat{grid-template-columns:repeat(4,minmax(0,1fr))}.yp-products{grid-template-columns:repeat(3,minmax(0,1fr))}.yp-info{grid-template-columns:1fr}}@media(max-width:680px){.yp-top{height:66px;padding:0 16px}.yp-brand b{font-size:16px}.yp-brand small{font-size:6px}.yp-brand .crown{font-size:28px}.yp-branch{padding:8px 11px;font-size:11px}.yp-copy{padding:40px 18px 18px}.yp-script{font-size:20px}.yp-copy h1{font-size:52px}.yp-copy p{font-size:15px}.yp-actions{display:grid;grid-template-columns:1.2fr 1fr}.yp-action{min-height:45px;padding:0 10px}.yp-action.order{grid-column:1/-1}.yp-benefits{gap:10px;font-size:10px}.yp-art{min-height:365px}.yp-campus{left:16px;top:18px;width:220px}.yp-bowl{right:7%;width:265px;height:210px}.yp-swirl{top:-102px;width:135px;height:150px}.yp-bowl .logo{bottom:40px;font-size:32px}.yp-bowl .logo span{font-size:14px}.yp-bubble{right:7px;top:68px;width:102px;height:102px;font-size:10px}.fruit{font-size:39px}.yp-section,.yp-story{width:min(100% - 24px,1280px)}.yp-cat{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.yp-cat article{min-height:84px}.yp-cat span{font-size:26px}.yp-products{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.yp-product{min-height:204px;padding:10px}.yp-product .art{height:100px}.yp-product .art span{font-size:50px}.yp-product strong{font-size:12px}.yp-product b{font-size:15px}.yp-orders{gap:4px}.yp-order{min-height:92px;padding:6px 2px}.yp-order i{width:39px;height:39px;font-size:12px}.yp-order b{font-size:7px}.yp-order small{font-size:6px}.yp-story{align-items:flex-start;flex-direction:column}.yp-footer{padding:22px 18px 88px}.yp-mobile{position:fixed;z-index:80;left:8px;right:8px;bottom:calc(8px + env(safe-area-inset-bottom,0px));display:grid;grid-template-columns:repeat(5,1fr);padding:5px;border:1px solid #eadcef;border-radius:17px;background:rgba(255,255,255,.97);box-shadow:0 18px 45px rgba(61,18,81,.22);backdrop-filter:blur(16px)}.yp-mobile a{min-height:49px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;text-decoration:none;color:#54236c;font-size:9px;font-weight:900}.yp-mobile a:last-child{border-radius:12px;background:#5b168f;color:#fff}}
`;
function normalizeChannels(data){
  const map=new Map();
  for(const row of Array.isArray(data)?data:[]){
    if(!row?.provider)continue;
    map.set(row.provider,{...row,order_url:safeHttps(row.order_url)});
  }
  return map;
}
function normalizedListings(item,channels){
  const rows=(Array.isArray(item?.listings)?item.listings:[]).map(row=>{
    const meta=providerMeta(row.provider);
    const channel=channels.get(row.provider);
    return {...row,label:row.display_name||meta.label,sort:meta.order,
      image_url:safeHttps(row.image_url),order_url:safeHttps(row.order_url)||channel?.order_url||''};
  }).filter(row=>row.price!=null||row.order_url||row.image_url);
  return rows.sort((a,b)=>a.sort-b.sort||String(a.label).localeCompare(String(b.label),'ko'));
}
function menuCard(item,meta,channels){
  const listings=normalizedListings(item,channels);
  const image=Array.isArray(meta.officialImageHosts)?officialImage(item.image_url,meta.officialImageHosts):(safeHttps(listings.find(x=>x.image_url)?.image_url)||safeHttps(item.image_url));
  const priced=listings.filter(x=>Number.isFinite(Number(x.price)));
  const min=priced.length?Math.min(...priced.map(x=>Number(x.price))):null;
  const fallbackMark=meta.mark||String(meta.brand||'ST').slice(0,2);
  const source=item.source_basis==='brand_official'?'본사 기준':'목포대점 확인';
  const base=item.base_price!=null?`<div class="base-price"><span>${e(source)}</span><strong>${e(won(item.base_price))}</strong></div>`:'';
  const platform=priced.length||listings.length?`<div class="platform-prices">${listings.map(row=>`<div class="platform-price"><b>${e(row.label)}</b><strong>${row.price!=null?e(won(row.price)):'가격 확인'}</strong>${row.order_url?`<a href="${e(row.order_url)}" target="_blank" rel="noopener noreferrer">주문</a>`:'<span></span>'}</div>`).join('')}</div>`:'<div class="platform-empty">땡겨요 · 배달의민족 · 요기요 · 먹깨비의 목포대점 가격은 검증된 스냅샷이 연결되는 순서대로 표시됩니다.</div>';
  const lowest=min!=null&&priced.length>1?`<span class="lowest">앱 최저 ${e(won(min))}</span>`:'';
  return `<article class="menu-card"><div class="menu-media">${image?`<img src="${e(image)}" alt="${e(item.name)}" loading="lazy" referrerpolicy="no-referrer">`:`<span class="fallback">${e(fallbackMark)}</span>`}</div><div class="menu-body"><div class="menu-meta"><small>${e(item.category||meta.category||'MENU')}</small><span class="menu-source">${e(source)}</span></div><h3>${e(item.name)}</h3>${item.description?`<p class="menu-desc">${e(item.description)}</p>`:'<p class="menu-desc"></p>'}${base}${platform}${lowest}</div></article>`;
}
function yogurtProductCard(item,isReference){
  const icon=item.icon||(/딸기/.test(item.name)?'🍓':/초코/.test(item.name)?'🍫':/그릭/.test(item.name)?'🥣':/베리/.test(item.name)?'🫐':/바나나/.test(item.name)?'🍌':'🍦');
  const price=item.base_price!=null?won(item.base_price):'';
  return `<article class="yp-product"><div class="art"><span>${e(icon)}</span></div><small>${e(item.category||'요거트 · 디저트')}</small><strong>${e(item.name)}</strong><b>${price?e(price):'가격 확인'}</b>${isReference?'<em>참고가</em>':''}</article>`;
}
function yogurtOrderCard(provider,channels){
  const row=channels.get(provider.provider)||{};
  const href=safeHttps(row.order_url)||safeHttps(row.direct_url)||provider.url;
  const direct=Boolean(safeHttps(row.order_url)||safeHttps(row.direct_url));
  return `<a class="yp-order ${e(provider.provider)}" href="${e(href)}" target="_blank" rel="noopener noreferrer"><i>${e(provider.mark)}</i><b>${e(provider.label)}</b><small>${direct?'바로 주문':'매장 찾기'}</small></a>`;
}
async function renderYogurtStorefront(env,page){
  const data=await snapshot('yogurt',env);
  const store=data?.store||{};
  const address=String(store.address||'전남 무안군 청계면 승달산길 37-1').trim();
  const phone=phoneText(store.phone||'061-453-8295');
  const hours=hoursText(store.business_hours)||'11:00–22:00';
  const description=String(store.description||'국립목포대학교 후문에서 만나는 요거트퍼플 목포대점').trim();
  const liveMenu=Array.isArray(data?.menu)?data.menu.filter(item=>item&&item.name).slice(0,24):[];
  const menu=liveMenu.length?liveMenu:YOGURT_REFERENCE_MENU;
  const reference=!liveMenu.length;
  const channels=normalizeChannels(data?.channels);
  const map=mapUrl(address);
  const kakao=`https://map.kakao.com/?q=${encodeURIComponent(`요거트퍼플 목포대점 ${address}`)}`;
  const orders=YOGURT_ORDER_PROVIDERS.map(provider=>yogurtOrderCard(provider,channels)).join('');
  const products=menu.map(item=>yogurtProductCard(item,reference)).join('');
  const body=`<!doctype html><html lang="ko" data-store-page="yogurt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="${e(description)}"><meta name="robots" content="index,follow"><title>요거트퍼플 목포대점 | 메뉴 · 가격 · 주문</title><link rel="stylesheet" href="/_ekodi/space/storefront.css?v=20260909-yogurt-v3"></head><body><main class="sf">
<header class="yp-top"><a class="yp-brand" href="/yogurt"><span class="crown">♛</span><span><b>YOGURT PURPLE</b><small>PREMIUM YOGURT &amp; DESSERT</small></span></a><nav class="yp-nav"><a href="#menu">메뉴</a><a href="#store">매장안내</a><a href="#order">배달주문</a><a href="https://www.yogurtpurple.com/" target="_blank" rel="noopener noreferrer">본사</a></nav><a class="yp-branch" href="#store">● 목포대점</a></header>
<section class="yp-hero"><div class="yp-copy"><span class="yp-script">오늘도, 상큼한 하루! ♡</span><h1>요거트퍼플<br><strong>목포대점</strong></h1><p>${e(description)}. 메뉴와 앱별 가격 확인부터 전화, 지도, 배달주문까지 한 화면에서 연결합니다.</p><div class="yp-actions"><a class="yp-action menu" href="#menu">🍴 메뉴·가격 보기</a><a class="yp-action phone" href="${e(telUrl(phone))}">☎ 전화하기</a><a class="yp-action order" href="#order">🛵 배달앱 주문</a></div><div class="yp-benefits"><span>🌿 신선한 재료</span><span>♥ 건강한 디저트</span><span>☺ 행복한 하루</span></div></div><div class="yp-art"><div class="yp-campus"><small>MOKPO NATIONAL UNIVERSITY</small><b>국립목포대학교 후문</b></div><div class="yp-bowl"><div class="yp-swirl"></div><span class="fruit f1">🍓</span><span class="fruit f2">🍓</span><span class="fruit f3">🫐</span><span class="fruit f4">🫐</span><strong class="logo">♛<span>YOGURT PURPLE</span></strong></div><span class="yp-bubble">좋은 요거트가<br>좋은 하루를<br>만듭니다. ♡</span></div></section>
<section class="yp-section"><div class="yp-bar"><div><span class="crown">♛</span><h2>본사 공식 메뉴 카테고리</h2></div><a href="https://www.yogurtpurple.com/" target="_blank" rel="noopener noreferrer">본사 전체 메뉴 ↗</a></div><div class="yp-cat"><article><span>🍦</span><b>요거트아이스크림</b></article><article><span>🥤</span><b>1인·2인 아이스크림</b></article><article><span>🥣</span><b>그릭요거트</b></article><article><span>🫐</span><b>스무디볼</b></article><article><span>🥐</span><b>요거와상</b></article><article><span>🥨</span><b>츄러스</b></article><article><span>☕</span><b>커피</b></article><article><span>🍓</span><b>논커피</b></article><article><span>🥪</span><b>그릭샌드위치·크로플</b></article><article><span>🍪</span><b>베이커리</b></article><article><span>🍉</span><b>컵과일·후르츠컵</b></article><article><span>🐙</span><b>타코야끼</b></article></div></section>
<section id="menu" class="yp-section"><div class="yp-bar"><div><span class="crown">♛</span><h2>목포대점 메뉴와 앱별 가격</h2></div><span>${reference?'본사 공식 메뉴 + 공개 등록가 참고':'목포대점 검증 메뉴'}</span></div><p class="yp-note">${reference?'본사 공식 메뉴명과 공개된 동일 브랜드 매장 등록가격을 참고용으로 표시합니다. 목포대점 최종 판매가·옵션은 주문앱 또는 매장에서 확인해 주세요.':'목포대점에 연결된 검증 메뉴·가격입니다. 플랫폼별 쿠폰·옵션·배달비는 최종 주문화면을 기준으로 합니다.'}</p><div class="yp-products">${products}</div><div class="yp-combo"><strong>♥ 인기 맛 조합 추천!</strong><span>반반딸기초코</span><span>반반플레인딸기</span><span>반반플레인초코</span><span>초코쉘요거트아이스크림</span></div></section>
<section class="yp-section yp-info"><article id="store" class="yp-card yp-store"><h2>♛ 목포대점 안내</h2><dl><dt>📍</dt><dd><strong>${e(address)}</strong><small>국립목포대학교 후문 앞 · 본사 등록명 ‘무안목포대점’</small></dd><dt>☎</dt><dd><a href="${e(telUrl(phone))}"><strong>${e(phone)}</strong></a></dd><dt>◷</dt><dd><strong>${e(hours)}</strong><small>휴무·마감시간은 전화로 최종 확인해 주세요.</small></dd></dl><div class="yp-map"><a href="${e(map)}" target="_blank" rel="noopener noreferrer">N 네이버지도</a><a href="${e(kakao)}" target="_blank" rel="noopener noreferrer">● 카카오맵</a></div></article><article id="order" class="yp-card"><h2>🛵 배달앱에서 바로 주문</h2><p class="yp-note">배달의민족 · 쿠팡이츠 · 요기요 · 당근주문 · 네이버주문을 한곳에 모았습니다. 공식 목포대점 직행 링크가 확인되면 자동으로 우선 연결합니다.</p><div class="yp-orders">${orders}</div></article></section>
<section class="yp-story"><strong>좋은 요거트가 좋은 하루를 만듭니다. ♡</strong><a href="https://www.yogurtpurple.com/" target="_blank" rel="noopener noreferrer">요거트퍼플 공식 홈페이지 ↗</a></section><footer class="yp-footer"><strong>♛ YOGURT PURPLE · 목포대점</strong><small>PREMIUM YOGURT &amp; DESSERT · Powered by EKODI</small></footer></main><nav class="yp-mobile"><a href="/yogurt">⌂<small>홈</small></a><a href="#menu">☰<small>메뉴</small></a><a href="${e(telUrl(phone))}">☎<small>전화</small></a><a href="${e(map)}" target="_blank" rel="noopener noreferrer">●<small>지도</small></a><a href="#order">🛵<small>주문</small></a></nav></body></html>`;
  return new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
}

export function storefrontCss(){
  return new Response(CSS+MENU_CSS+YOGURT_CSS+YOGURT_CSS_2+YOGURT_CSS_3,{headers:{'content-type':'text/css; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}});
}
export async function renderStorefrontPage(request,env,resolved,slug){
  const page=resolved?.profile||{};
  if(slug==='yogurt')return renderYogurtStorefront(env,page);
  const meta=BRAND[slug]||{brand:page.name||slug,branch:'매장',category:'매장',tagline:'오늘의 메뉴와 주문을 빠르게 확인하세요.'};
  const links=officialLinks(slug);
  const data=await snapshot(slug,env);
  const store=data?.store||{};
  const address=String(store.address||meta.address||'').trim();
  const phone=phoneText(store.phone||meta.phone||'');
  const hours=hoursText(store.business_hours);
  const description=String(store.description||meta.tagline||page.description||'').trim();
  const menu=Array.isArray(data?.menu)?data.menu.filter(item=>item&&item.name).slice(0,36):[];
  const channels=normalizeChannels(data?.channels);
  const officialMenu=safeHttps(links.menu),officialOrder=safeHttps(links.order);
  const channelRows=[...channels.values()].sort((a,b)=>providerMeta(a.provider).order-providerMeta(b.provider).order);
  const firstAppOrder=channelRows.find(row=>['ddangyo','baemin','yogiyo','mukkebi'].includes(row.provider)&&row.order_url)?.order_url||'';
  const order=firstAppOrder||channelRows.find(row=>row.order_url)?.order_url||officialOrder||telUrl(phone);
  const map=mapUrl(address);
  const menuTarget=menu.length?'#menu':officialMenu||'#menu';
  const menuHtml=menu.length
    ?`<div class="menu">${menu.map(item=>menuCard(item,meta,channels)).join('')}</div><div class="price-note">앱별 가격은 마지막으로 검증된 공개 스냅샷 기준입니다. 쿠폰·배달비·옵션·실시간 판매 여부는 각 앱의 최종 주문화면을 기준으로 합니다.</div>`
    :`<div class="empty"><strong>목포대점 메뉴를 확인하세요.</strong><p>검증된 매장 메뉴가 연결되기 전에는 임의 가격을 표시하지 않습니다.</p>${officialMenu?action(officialMenu,`${meta.brand} 본사 메뉴 보기`,{external:true}):''}</div>`;
  const channelLinks=channelRows.filter(row=>row.order_url).map(row=>{
    const label=row.display_name||providerMeta(row.provider).label;
    return `<a class="order-link" href="${e(row.order_url)}" target="_blank" rel="noopener noreferrer"><b>${e(label)}</b><span>목포대점 주문하기 →</span></a>`;
  }).join('');
  const orderHtml=channelLinks||`${officialOrder?`<a class="order-link" href="${e(officialOrder)}" target="_blank" rel="noopener noreferrer"><b>${e(meta.brand)} 공식 주문</b><span>주문하기 →</span></a>`:''}${phone?`<a class="order-link" href="${e(telUrl(phone))}"><b>${e(meta.branch)} 전화 주문</b><span>${e(phone)} →</span></a>`:''}`;
  const title=page.name||`${meta.brand} ${meta.branch}`;
  const body=`<!doctype html><html lang="ko" data-store-page="${e(page.theme||slug||'default')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="${e(description||title)}"><meta name="robots" content="index,follow"><title>${e(title)} | 메뉴 · 가격 · 주문</title><link rel="stylesheet" href="/_ekodi/space/storefront.css?v=20260909-platform-menu-v1"></head><body><main class="sf"><header class="top"><a class="brand" href="/${e(slug)}"><b>${e(meta.brand)}</b><span>${e(meta.branch)}</span></a><nav><a href="#menu">메뉴·가격</a><a href="#store">매장정보</a><a href="#order">배달앱 주문</a></nav></header>
<section class="hero"><div class="hero-in"><div><p class="kicker">${e(meta.brand)} · ${e(address?'목포대 후문':'우리 동네 매장')}</p><h1><span>${e(meta.brand)}</span><strong>${e(meta.branch)}</strong></h1><p class="lead">${e(description||meta.tagline)}</p><div class="actions">${action(menuTarget,'메뉴·가격 보기',{primary:true,external:menuTarget.startsWith('http')})}${action(telUrl(phone),'전화하기')}${action(map,'지도 보기',{external:true})}${action(order,'배달앱 주문',{external:order.startsWith('http')})}</div></div><aside id="store" class="facts">${address?`<div class="fact"><small>매장 위치</small><strong>${e(address)}</strong></div>`:''}${phone?`<div class="fact"><small>전화</small><a href="${e(telUrl(phone))}">${e(phone)}</a></div>`:''}${hours?`<div class="fact"><small>영업시간</small><strong>${e(hours)}</strong></div>`:''}<div class="fact"><small>한 화면에서</small><strong>메뉴 · 앱별 가격 · 주문 연결</strong></div></aside></div></section>
<section id="menu" class="section"><div class="head"><h2>메뉴와 앱별 가격</h2><p>${e(meta.brand)} 기준 메뉴와 땡겨요·배달의민족·요기요·먹깨비에서 실제 확인된 목포대점 가격을 함께 보여줍니다. 확인되지 않은 앱 가격은 만들지 않습니다.</p></div>${menuHtml}</section>
<section id="order" class="section"><div class="head"><h2>배달앱에서 바로 주문</h2><p>목포대점으로 확인된 주문 링크만 연결합니다. 앱에서 최종 가격·쿠폰·배달비와 주문 가능 여부를 확인해 주세요.</p></div><div class="order"><div class="order-links">${orderHtml||'<div class="empty"><strong>주문 경로를 준비하고 있습니다.</strong><p>목포대점의 검증된 앱 주문 링크가 연결되는 즉시 여기에 표시됩니다.</p></div>'}</div><aside class="note"><strong>${e(meta.branch)} 안내</strong>${e(address||'매장 위치 정보를 확인하고 있습니다.')}<br>${phone?`문의 · 주문 ${e(phone)}`:'전화번호를 확인하고 있습니다.'}</aside></div></section><footer>${e(meta.brand)} ${e(meta.branch)} · EKODI</footer></main>
<div class="mobile">${mobile('#menu','메뉴·가격')}${mobile(telUrl(phone),'전화')}${mobile(map,'지도',true)}${mobile(order,'주문',order.startsWith('http'))}</div></body></html>`;
  return new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
}
