const BRAND=Object.freeze({
  pizzamaru:{brand:'피자마루',branch:'목포대점',category:'피자',tagline:'목포대 후문에서 오늘 먹고 싶은 피자를 바로 만나보세요.',address:'전남 무안군 청계면 승달산길 37-1 1층',phone:'061-453-8295'},
  jadam:{brand:'자담치킨',branch:'목포대점',category:'치킨',tagline:'목포대점의 메뉴와 주문을 가장 빠르게 연결합니다.'},
  yogurt:{brand:'요거트퍼플',branch:'목포대점',category:'요거트',tagline:'목포대점의 디저트와 주문을 가장 빠르게 연결합니다.'},
});
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeHttps(value){try{const u=new URL(String(value||''));return u.protocol==='https:'?u.href:''}catch{return''}}
function phoneText(value){return String(value||'').trim()}
function telUrl(value){const phone=phoneText(value).replace(/[^0-9+]/g,'');return phone?`tel:${phone}`:''}
function won(value){return Number.isFinite(Number(value))?`${Number(value).toLocaleString('ko-KR')}원`:''}
function hoursText(value){
  if(!value||typeof value!=='object'||!Object.keys(value).length)return'';
  if(Array.isArray(value))return value.map(String).join(' · ');
  return Object.entries(value).map(([k,v])=>`${k} ${Array.isArray(v)?v.join(', '):String(v)}`).join(' · ');
}
function mapUrl(address){return address?`https://map.naver.com/p/search/${encodeURIComponent(address)}`:''}
async function snapshot(slug,env){
  if(!slug||!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)return null;
  const endpoint=`${env.SUPABASE_URL}/rest/v1/rpc/store_user_site_public_snapshot`;
  try{
    const r=await fetch(endpoint,{method:'POST',headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({p_slug:slug})});
    if(!r.ok)return null;const d=await r.json().catch(()=>null);return d&&typeof d==='object'?d:null;
  }catch{return null}
}
const CSS=`:root{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif;--ink:#251b18;--muted:#72625c;--brand:#a33f2d;--dark:#7b2e21;--soft:#fff0e9;--paper:#fffdfb;--line:#ead8d0;color:var(--ink);background:#fffaf7;word-break:keep-all}*{box-sizing:border-box}html{scroll-behavior:smooth}html[data-store-page="pizzamaru"]{--brand:#b3132b;--dark:#121827;--soft:#fff0f2;--line:#eadde1}html[data-store-page="pizzamaru"] .hero{background:radial-gradient(circle at 83% 39%,#f5c5b6 0 13%,transparent 13.4%),radial-gradient(circle at 83% 39%,#d75a48 0 22%,transparent 22.4%),linear-gradient(125deg,#fff8f8,#fbe9ed 58%,#121827)}html[data-store-page="pizzamaru"] .hero h1 span{color:#6d1728}html[data-store-page="pizzamaru"] .facts{border-color:rgba(179,19,43,.18)}html[data-store-page="pizzamaru"] .action.primary{background:#b3132b;border-color:#b3132b}body{margin:0;background:#fffaf7;color:var(--ink)}a{color:inherit}.sf{min-height:100vh;overflow:hidden}.top{width:min(1180px,calc(100% - 40px));height:70px;margin:auto;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;gap:9px;align-items:baseline;text-decoration:none}.brand b{font-size:18px}.brand span{font-size:12px;font-weight:900;color:var(--brand)}nav{display:flex;gap:20px}nav a{text-decoration:none;font-size:13px;font-weight:800;color:#5e4d47}
.hero{min-height:550px;border-block:1px solid var(--line);background:radial-gradient(circle at 83% 39%,#f0baa5 0 13%,transparent 13.4%),radial-gradient(circle at 83% 39%,#d97451 0 22%,transparent 22.4%),linear-gradient(125deg,#fff8f4,#ffede4 58%,#f8d9cb)}.hero-in{width:min(1180px,calc(100% - 40px));margin:auto;padding:76px 0 64px;display:grid;grid-template-columns:minmax(0,720px) 1fr;gap:42px}.kicker{margin:0 0 14px;color:var(--brand);font-size:12px;font-weight:950;letter-spacing:.12em}.hero h1{margin:0;line-height:.93;letter-spacing:-.065em}.hero h1 span{display:block;font-size:clamp(26px,3vw,43px);font-weight:700;color:#64473e}.hero h1 strong{display:block;margin-top:8px;font-size:clamp(62px,9vw,116px);font-weight:950}.lead{max-width:600px;margin:24px 0 0;font-size:18px;line-height:1.7;color:#64534d}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:30px}.action{display:inline-flex;align-items:center;justify-content:center;min-height:52px;padding:0 19px;border:1px solid #d8bbb0;border-radius:14px;background:rgba(255,255,255,.82);text-decoration:none;font-size:14px;font-weight:900}.action.primary{background:var(--brand);border-color:var(--brand);color:#fff}
.facts{align-self:end;display:grid;gap:15px;padding:24px;border-left:1px solid rgba(80,46,35,.16)}.fact small{display:block;margin-bottom:4px;color:#806c65;font-size:11px}.fact strong,.fact a{font-size:15px;font-weight:850;line-height:1.5;text-decoration:none}.section{width:min(1180px,calc(100% - 40px));margin:auto;padding:72px 0}.section+.section{border-top:1px solid var(--line)}.head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:28px}.head h2{margin:0;font-size:clamp(34px,5vw,52px);letter-spacing:-.05em}.head p{max-width:540px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}.menu{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:2px;background:var(--line);border:1px solid var(--line)}.menu article{min-height:180px;padding:24px;background:var(--paper)}.menu small{color:var(--brand);font-size:11px;font-weight:900}.menu h3{margin:13px 0 6px;font-size:21px;letter-spacing:-.03em}.menu p{margin:0;color:var(--muted);font-size:13px;line-height:1.55}.price{display:block;margin-top:20px;font-size:18px;font-weight:950}.empty{padding:32px;border:1px solid var(--line);background:var(--paper)}.empty strong{display:block;font-size:20px}.empty p{margin:8px 0 18px;color:var(--muted);line-height:1.6}
.order{display:grid;grid-template-columns:1.15fr .85fr;gap:40px}.order-links{display:grid;gap:10px}.order-link{display:flex;align-items:center;justify-content:space-between;min-height:62px;padding:0 18px;border:1px solid var(--line);background:#fff;text-decoration:none;font-weight:900}.order-link span{color:var(--brand);font-size:12px}.note{padding:24px;background:var(--soft);color:#604b44;line-height:1.7}.note strong{display:block;margin-bottom:6px;color:var(--dark)}footer{padding:34px 20px 108px;text-align:center;color:#88756e;font-size:12px}.mobile{display:none}
@media(max-width:820px){.top{height:62px}nav{display:none}.hero{min-height:auto}.hero-in{grid-template-columns:1fr;padding:52px 0 46px}.facts{border-left:0;border-top:1px solid rgba(80,46,35,.16);padding:20px 0 0;grid-template-columns:1fr 1fr}.menu{grid-template-columns:1fr 1fr}.order{grid-template-columns:1fr}.section{padding:54px 0}.head{align-items:flex-start;flex-direction:column}.mobile{position:fixed;z-index:50;left:10px;right:10px;bottom:10px;display:grid;grid-template-columns:repeat(4,1fr);padding:6px;border:1px solid var(--line);border-radius:16px;background:rgba(255,253,251,.96);box-shadow:0 12px 40px rgba(65,38,28,.15)}.mobile a,.mobile span{padding:10px 3px;text-align:center;text-decoration:none;font-size:11px;font-weight:900}.mobile a:last-child{background:var(--brand);color:#fff;border-radius:11px}}
@media(max-width:520px){.top,.hero-in,.section{width:min(100% - 24px,1180px)}.hero h1 strong{font-size:64px}.lead{font-size:16px}.actions{display:grid;grid-template-columns:1fr 1fr}.action{padding:0 10px}.facts{grid-template-columns:1fr}.menu{grid-template-columns:1fr}.head h2{font-size:36px}}`;
function officialLinks(slug){
  if(slug==='pizzamaru')return{menu:'https://www.pizzamaru.co.kr/menu/',order:'https://www.pizzamaru.co.kr/orderchoice/?deliv_type=1'};
  return{menu:'',order:''};
}
function action(href,label,{primary=false,external=false}={}){return href?`<a class="action${primary?' primary':''}" href="${e(href)}"${external?' target="_blank" rel="noopener"':''}>${e(label)}</a>`:''}
function mobile(href,label,external=false){return href?`<a href="${e(href)}"${external?' target="_blank" rel="noopener"':''}>${e(label)}</a>`:'<span></span>'}
export function storefrontCss(){return new Response(CSS,{headers:{'content-type':'text/css; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}})}
export async function renderStorefrontPage(request,env,resolved,slug){
  const page=resolved?.profile||{};const meta=BRAND[slug]||{brand:page.name||slug,branch:'매장',category:'매장',tagline:'오늘의 메뉴와 주문을 빠르게 확인하세요.'};const links=officialLinks(slug);
  const data=await snapshot(slug,env);const store=data?.store||{};const address=String(store.address||meta.address||'').trim();const phone=phoneText(store.phone||meta.phone||'');const hours=hoursText(store.business_hours);const description=String(store.description||meta.tagline||page.description||'').trim();
  const menu=Array.isArray(data?.menu)?data.menu.filter(item=>item&&item.name).slice(0,18):[];const channels=Array.isArray(data?.channels)?data.channels.filter(item=>safeHttps(item.order_url)):[];const officialMenu=safeHttps(links.menu);const officialOrder=safeHttps(links.order);
  const order=channels[0]?.order_url||officialOrder||telUrl(phone);const map=mapUrl(address);const menuTarget=menu.length?'#menu':officialMenu||'#menu';
  const menuHtml=menu.length?`<div class="menu">${menu.map(item=>`<article><small>${e(item.category||meta.category||'MENU')}</small><h3>${e(item.name)}</h3>${item.description?`<p>${e(item.description)}</p>`:''}${item.base_price!=null?`<span class="price">${e(won(item.base_price))}</span>`:''}</article>`).join('')}</div>`:`<div class="empty"><strong>목포대점 메뉴를 확인하세요.</strong><p>매장에 검증된 메뉴 가격이 연결되기 전에는 임의 가격을 표시하지 않습니다.</p>${officialMenu?action(officialMenu,`${meta.brand} 본사 메뉴 보기`,{external:true}):''}</div>`;
  const channelLinks=channels.map(item=>`<a class="order-link" href="${e(item.order_url)}" target="_blank" rel="noopener"><b>${e(item.display_name||'배달 주문')}</b><span>주문하기 →</span></a>`).join('');
  const orderHtml=channelLinks||`${officialOrder?`<a class="order-link" href="${e(officialOrder)}" target="_blank" rel="noopener"><b>${e(meta.brand)} 공식 주문</b><span>주문하기 →</span></a>`:''}${phone?`<a class="order-link" href="${e(telUrl(phone))}"><b>${e(meta.branch)} 전화 주문</b><span>${e(phone)} →</span></a>`:''}`;
  const title=page.name||`${meta.brand} ${meta.branch}`;
  const body=`<!doctype html><html lang="ko" data-store-page="${e(page.theme||slug||'default')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="${e(description||title)}"><meta name="robots" content="index,follow"><title>${e(title)} | 메뉴 · 전화 · 지도 · 주문</title><link rel="stylesheet" href="/_ekodi/space/storefront.css?v=20260909-customer-first-v1"></head><body><main class="sf"><header class="top"><a class="brand" href="/${e(slug)}"><b>${e(meta.brand)}</b><span>${e(meta.branch)}</span></a><nav><a href="#menu">메뉴</a><a href="#store">매장정보</a><a href="#order">주문</a></nav></header>
<section class="hero"><div class="hero-in"><div><p class="kicker">${e(meta.brand)} · ${e(address?'목포대 후문':'우리 동네 매장')}</p><h1><span>${e(meta.brand)}</span><strong>${e(meta.branch)}</strong></h1><p class="lead">${e(description||meta.tagline)}</p><div class="actions">${action(menuTarget,'메뉴 보기',{primary:true,external:menuTarget.startsWith('http')})}${action(telUrl(phone),'전화하기')}${action(map,'지도 보기',{external:true})}${action(order,'주문하기',{external:order.startsWith('http')})}</div></div><aside id="store" class="facts">${address?`<div class="fact"><small>매장 위치</small><strong>${e(address)}</strong></div>`:''}${phone?`<div class="fact"><small>전화</small><a href="${e(telUrl(phone))}">${e(phone)}</a></div>`:''}${hours?`<div class="fact"><small>영업시간</small><strong>${e(hours)}</strong></div>`:''}<div class="fact"><small>이 페이지의 중심</small><strong>${e(meta.branch)}에서 먹고 주문하기</strong></div></aside></div></section>
<section id="menu" class="section"><div class="head"><h2>오늘 뭐 먹을까?</h2><p>목포대점에서 확인된 메뉴를 우선 보여드립니다. 매장 가격이 확인되지 않은 항목은 가격을 만들어 표시하지 않습니다.</p></div>${menuHtml}</section>
<section id="order" class="section"><div class="head"><h2>바로 주문하기</h2><p>공식 주문경로와 매장 전화만 연결합니다. 운영 상태값이나 내부 연결정보는 고객 화면에 노출하지 않습니다.</p></div><div class="order"><div class="order-links">${orderHtml||'<div class="empty"><strong>주문 경로를 준비하고 있습니다.</strong><p>매장 전화 또는 공식 주문경로가 확인되는 즉시 연결됩니다.</p></div>'}</div><aside class="note"><strong>${e(meta.branch)} 안내</strong>${e(address||'매장 위치 정보를 확인하고 있습니다.')}<br>${phone?`문의 · 주문 ${e(phone)}`:'전화번호를 확인하고 있습니다.'}</aside></div></section><footer>${e(meta.brand)} ${e(meta.branch)} · EKODI</footer></main>
<div class="mobile">${mobile('#menu','메뉴')}${mobile(telUrl(phone),'전화')}${mobile(map,'지도',true)}${mobile(order,'주문',order.startsWith('http'))}</div></body></html>`;
  return new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
}
