(() => {
  'use strict';
  const GOOGLE_API='https://drive.ekodi.kr/api/control/storage/google';
  const BROWSER_API='https://drive.ekodi.kr/api/control/storage/browser';
  const TOKEN_KEY='ekodi-auth-token';
  const LOCALE_KEY='ekodi-admin-locale';
  const GOOGLE_ACCOUNT_BY_ROLE=Object.freeze({primary:'joseph@ekodi.kr',secondary:'topmaster.joseph@gmail.com'});
  const AUTO_RECONNECT_KEY='ekodi-storage-auto-reconnect-at';
  const AUTO_RECONNECT_COOLDOWN_MS=5*60*1000;
  const CANONICAL_ADMIN_HOST='ekodi.kr';
  const CANONICAL_ADMIN_PATH='/admin';
  let state=null;
  let browserState={connectionId:'',rootId:'',folder:null,items:[],nextPageToken:null,query:'',stack:[]};
  let autoReconnectInFlight=false;

  function el(tag,text='',className=''){const node=document.createElement(tag);if(className)node.className=className;if(text)node.textContent=text;return node;}
  function token(){try{return sessionStorage.getItem(TOKEN_KEY)||'';}catch{return '';}}
  function locale(){try{return String(window.EKODIAdminSidebar?.locale?.()||localStorage.getItem(LOCALE_KEY)||document.documentElement.lang||navigator.language||'ko').toLowerCase().startsWith('en')?'en':'ko';}catch{return 'ko';}}
  function t(ko,en){return locale()==='en'?en:ko;}
  function statusText(connection){if(connection.status==='ready')return t('준비 완료','Ready');if(connection.status==='connected'&&!connection.drive_id)return t('Drive 선택 필요','Select a Drive');if(connection.status==='connected')return t('연결됨','Connected');return t('설정 확인','Check setup');}
  function autoReconnectAllowed(){try{const last=Number(sessionStorage.getItem(AUTO_RECONNECT_KEY)||0);return !last||Date.now()-last>AUTO_RECONNECT_COOLDOWN_MS;}catch{return true;}}
  function markAutoReconnect(){try{sessionStorage.setItem(AUTO_RECONNECT_KEY,String(Date.now()));}catch{}}
  function clearAutoReconnect(){try{sessionStorage.removeItem(AUTO_RECONNECT_KEY);}catch{}}
  function isStorageRoute(){const params=new URLSearchParams(location.search);return location.hash==='#storage'||params.get('route')==='storage'||location.pathname==='/admin/storage'||location.pathname==='/admin/storage/';}
  function canonicalStorageUrl(){const url=new URL(location.href);url.protocol='https:';url.hostname=CANONICAL_ADMIN_HOST;url.port='';url.pathname=CANONICAL_ADMIN_PATH;url.hash='';url.searchParams.set('route','storage');return url;}
  function migrateLegacyStorageLocation(){if(location.hostname==='admin.ekodi.kr'&&isStorageRoute()){location.replace(canonicalStorageUrl().toString());return true;}return false;}
  function currentAdminReturnPath(){return `${CANONICAL_ADMIN_PATH}?route=storage`;}
  function syncCanonicalRoute(){if(location.hostname!==CANONICAL_ADMIN_HOST)return;const url=canonicalStorageUrl();if(location.pathname!==url.pathname||location.hash||new URLSearchParams(location.search).get('route')!=='storage')history.replaceState(null,'',`${url.pathname}${url.search}`);}
  async function request(base,path,options={}){const {skipAutoReconnect=false,...fetchOptions}=options;const headers=new Headers(fetchOptions.headers||{});headers.set('authorization',`Bearer ${token()}`);if(fetchOptions.body&&!headers.has('content-type'))headers.set('content-type','application/json');const response=await fetch(`${base}${path}`,{cache:'no-store',credentials:'include',...fetchOptions,headers});const data=await response.json().catch(()=>({}));if(!response.ok){if(data.code==='GOOGLE_REAUTH_REQUIRED'&&!skipAutoReconnect&&autoReconnectAllowed()&&!autoReconnectInFlight){markAutoReconnect();autoReconnectInFlight=true;await startOAuth(data.reconnectRole||'primary',{automatic:true});return new Promise(()=>{});}const error=new Error(data.error||t(`저장소 API 오류 (${response.status})`,`Storage API error (${response.status})`));error.code=data.code||'';throw error;}if(path!=='/oauth/start')clearAutoReconnect();return data;}
  function googleRequest(path,options={}){return request(GOOGLE_API,path,options);}
  function browserRequest(path,options={}){return request(BROWSER_API,path,options);}
  function button(text,handler,className='secondary'){const node=el('button',text,className);node.type='button';node.addEventListener('click',handler);return node;}
  function showError(error){const section=document.querySelector('#storageAdminPanel');if(!section)return;let box=document.querySelector('#storageMessage');if(!box){box=el('div','','storage-banner');box.id='storageMessage';section.prepend(box);}box.className='storage-banner';const raw=String(error?.message||error||'');const network=error instanceof TypeError||/failed to fetch|networkerror|load failed/i.test(raw);box.textContent=network?t('저장소 연결을 확인할 수 없습니다. 잠시 후 새로고침해 주세요.','Unable to reach the storage service. Please refresh shortly.'):raw||t('처리 중 오류가 발생했습니다.','An error occurred.');}

  function accountHintedAuthorizeUrl(authorizeUrl,role){const target=new URL(authorizeUrl,location.href);const account=GOOGLE_ACCOUNT_BY_ROLE[role];if(account)target.searchParams.set('login_hint',account);const prompts=(target.searchParams.get('prompt')||'').split(/\s+/).filter(Boolean).filter(value=>value!=='select_account');if(prompts.length)target.searchParams.set('prompt',prompts.join(' '));else target.searchParams.delete('prompt');return target.toString();}
  async function startOAuth(role,{automatic=false}={}){try{const result=await googleRequest('/oauth/start',{method:'POST',body:JSON.stringify({role,returnTo:currentAdminReturnPath()}),skipAutoReconnect:true});location.assign(accountHintedAuthorizeUrl(result.authorizeUrl,role));}catch(error){autoReconnectInFlight=false;if(automatic)markAutoReconnect();showError(error);}}
  async function loadDrives(connection,wrap){wrap.textContent=t('Drive 목록을 불러오는 중…','Loading Drive list…');try{const result=await googleRequest(`/connections/${encodeURIComponent(connection.id)}/drives`);wrap.textContent='';const select=document.createElement('select');select.setAttribute('aria-label',t('Google Drive 선택','Select Google Drive'));for(const drive of result.drives||[]){const option=document.createElement('option');option.value=drive.id;option.textContent=`${drive.name}${drive.type==='shared-drive'?t(' · 공유 드라이브',' · Shared Drive'):''}`;if(drive.id===connection.drive_id)option.selected=true;select.append(option);}const save=button(t('이 Drive 사용','Use this Drive'),async()=>{try{save.disabled=true;await googleRequest(`/connections/${encodeURIComponent(connection.id)}/select`,{method:'POST',body:JSON.stringify({driveId:select.value})});browserState={connectionId:'',rootId:'',folder:null,items:[],nextPageToken:null,query:'',stack:[]};await refresh();}catch(error){showError(error);}finally{save.disabled=false;}},'primary');wrap.append(select,save);}catch(error){wrap.textContent='';showError(error);}}
  async function bootstrap(connection,trigger){if(!confirm(t('선택한 기본 Google Drive에 표준 폴더 구조를 생성합니다. 계속할까요?','Create the standard folder structure in the selected primary Google Drive?')))return;try{trigger.disabled=true;await googleRequest(`/connections/${encodeURIComponent(connection.id)}/bootstrap`,{method:'POST'});await refresh();}catch(error){showError(error);}finally{trigger.disabled=false;}}
  async function disconnect(connection){if(!confirm(t(`${connection.account_email} 연결을 해제할까요? 파일은 삭제되지 않습니다.`,`Disconnect ${connection.account_email}? Files will not be deleted.`)))return;try{await googleRequest(`/connections/${encodeURIComponent(connection.id)}`,{method:'DELETE'});browserState={connectionId:'',rootId:'',folder:null,items:[],nextPageToken:null,query:'',stack:[]};await refresh();}catch(error){showError(error);}}

  function summary(container){const cards=locale()==='en'?[['Original files','Google Workspace Drive'],['Extra account','Optional secondary Google Drive'],['Web files','Copy to Cloudflare R2 only when needed'],['Security','Credentials encrypted with AES-GCM']]:[['원본 파일','Google Workspace Drive'],['추가 계정','필요할 때 보조 Google Drive 연결'],['웹 배포 파일','필요한 파일만 Cloudflare R2로 복제'],['보안','연결 정보 AES-GCM 암호화 저장']];const grid=el('div','','storage-summary');for(const [title,copy] of cards){const card=el('div','','storage-card');card.append(el('strong',title),el('span',copy));grid.append(card);}container.append(grid);}
  function renderConnections(container){const area=el('div','','storage-connections');if(!(state.connections||[]).length)area.append(el('div',t('연결된 Google Drive가 없습니다. 위 버튼에서 기본 계정을 먼저 연결하세요.','No Google Drive is connected. Connect the primary account first.'),'storage-banner'));for(const connection of state.connections||[]){const card=el('article','','storage-connection'),head=el('div','','storage-connection-head');head.append(el('span',connection.role==='primary'?t('기본 계정','PRIMARY'):t('추가 계정','SECONDARY'),'storage-role'),el('span',statusText(connection),'storage-state'));card.append(head);card.append(el('h3',connection.display_name||connection.account_email),el('div',connection.account_email,'storage-muted'));const meta=el('div','','storage-meta');meta.append(el('span',`${t('사용 Drive','Drive')}: ${connection.drive_name||t('아직 선택하지 않음','Not selected')}`),el('span',`${t('연결 상태','Connection')}: ${connection.status==='ready'||connection.status==='connected'?t('정상','OK'):t('확인 필요','Needs attention')}`));card.append(meta);const controls=el('div','','storage-control-row');controls.append(button(connection.drive_id?t('Drive 변경','Change Drive'):t('Drive 선택','Select Drive'),()=>loadDrives(connection,controls)));if(connection.role==='primary'&&connection.drive_root_id){const boot=button(connection.status==='ready'?t('폴더 확인·보완','Check folders'):t('표준 폴더 만들기','Build folders'),()=>bootstrap(connection,boot),'primary');controls.append(boot);}controls.append(button(t('연결 해제','Disconnect'),()=>disconnect(connection)));card.append(controls);area.append(card);}container.append(area);}
  function renderRoutes(container){const box=el('div','','storage-route-box');box.append(el('h3',t('기본 폴더 구조','Default folder structure')));const grid=el('div','','storage-routes');for(const route of state.routes||[]){const row=el('div','','storage-route');row.append(el('span',route.service_key),el('code',`${route.folder_name}${route.folder_id?' ✓':''}`));grid.append(row);}box.append(grid);container.append(box);}

  function formatBytes(value){const bytes=Number(value);if(!Number.isFinite(bytes)||bytes<0)return '—';if(bytes<1024)return `${bytes} B`;const units=['KB','MB','GB','TB'];let size=bytes/1024,index=0;while(size>=1024&&index<units.length-1){size/=1024;index+=1;}return `${size>=10?size.toFixed(0):size.toFixed(1)} ${units[index]}`;}
  function formatDate(value){if(!value)return '—';try{return new Intl.DateTimeFormat(locale()==='en'?'en-US':'ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}catch{return String(value);}}
  function browserConnection(){return (state?.connections||[]).find(connection=>connection.role==='primary'&&connection.drive_id&&connection.drive_root_id)||null;}
  function renderBrowserShell(container){const box=el('section','','storage-browser');box.id='storageBrowser';const head=el('div','','storage-browser-head'),copy=el('div');copy.append(el('div',t('실제 연결 파일','CONNECTED FILES'),'storage-kicker'),el('h3',t('Google Drive 파일 탐색','Google Drive browser')),el('p',t('선택한 Drive의 실제 폴더와 파일을 읽기 전용으로 확인합니다. 삭제·이동·게시 기능은 다음 안전 단계에서 활성화합니다.','Browse real folders and files in the selected Drive in read-only mode. Mutating actions will be enabled in the next guarded phase.'),'storage-muted'));head.append(copy,el('span',t('V1 · 읽기 전용','V1 · READ ONLY'),'storage-readonly-badge'));box.append(head);const body=el('div','','storage-browser-body');body.id='storageBrowserBody';box.append(body);container.append(box);}
  function renderBrowserBody(connection){const body=document.querySelector('#storageBrowserBody');if(!body)return;body.textContent='';if(!connection){body.append(el('div',t('기본 Google Drive를 선택하면 실제 파일이 여기에 표시됩니다.','Select the primary Google Drive to show real files here.'),'storage-browser-empty'));return;}if(browserState.connectionId!==connection.id||!browserState.folder){body.append(el('div',t('실제 파일 목록을 불러오는 중…','Loading real files…'),'storage-loading'));return;}
    const toolbar=el('div','','storage-browser-toolbar');const nav=el('div','','storage-browser-nav');const up=button('←',()=>navigateUp(connection),'ghost');up.title=t('상위 폴더','Parent folder');up.disabled=browserState.stack.length===0;const crumb=el('div','','storage-browser-crumb');crumb.append(el('strong',connection.drive_name||'Drive'),el('span',' / '),el('span',browserState.folder?.name||''));nav.append(up,crumb);const form=el('form','','storage-browser-search');const input=document.createElement('input');input.type='search';input.value=browserState.query||'';input.placeholder=t('현재 폴더에서 검색','Search this folder');input.setAttribute('aria-label',input.placeholder);form.append(input,button(t('검색','Search'),()=>{},'secondary'));form.addEventListener('submit',event=>{event.preventDefault();loadBrowser(connection,browserState.folder?.id||'',input.value,{preserveStack:true});});toolbar.append(nav,form,button(t('새로고침','Refresh'),()=>loadBrowser(connection,browserState.folder?.id||'',browserState.query,{preserveStack:true}),'ghost'));body.append(toolbar);
    const table=el('div','','storage-file-table');const header=el('div','','storage-file-row storage-file-header');header.append(el('span',t('이름','Name')),el('span',t('수정','Modified')),el('span',t('크기','Size')),el('span',t('상태','State')));table.append(header);if(!browserState.items.length){table.append(el('div',browserState.query?t('검색 결과가 없습니다.','No matching files.'):t('이 폴더는 비어 있습니다.','This folder is empty.'),'storage-browser-empty'));}
    for(const item of browserState.items){const row=el('button','','storage-file-row storage-file-item');row.type='button';const name=el('span','','storage-file-name');name.append(el('span',item.kind==='folder'?'▣':'▤','storage-file-icon'),el('span',item.name||t('이름 없음','Untitled')));row.append(name,el('span',formatDate(item.modifiedTime)),el('span',item.kind==='folder'?'—':formatBytes(item.size)),el('span',item.kind==='folder'?t('폴더','Folder'):t('Drive 원본','Drive original'),'storage-file-state'));row.addEventListener('click',()=>{if(item.kind==='folder'){browserState.stack.push({id:browserState.folder.id,name:browserState.folder.name});loadBrowser(connection,item.id,'',{preserveStack:true});}else if(item.webViewLink){window.open(item.webViewLink,'_blank','noopener,noreferrer');}});table.append(row);}body.append(table);
    if(browserState.nextPageToken){body.append(button(t('다음 파일 더 보기','Load more'),()=>loadBrowser(connection,browserState.folder.id,browserState.query,{append:true,pageToken:browserState.nextPageToken,preserveStack:true}),'secondary'));}
  }
  async function navigateUp(connection){const parent=browserState.stack.pop();if(!parent)return;await loadBrowser(connection,parent.id,'',{preserveStack:true});}
  async function loadBrowser(connection,parentId='',query='',options={}){const body=document.querySelector('#storageBrowserBody');if(body&&!options.append)body.innerHTML=`<div class="storage-loading">${t('실제 파일 목록을 불러오는 중…','Loading real files…')}</div>`;try{const params=new URLSearchParams();if(parentId)params.set('parentId',parentId);if(query)params.set('q',query);if(options.pageToken)params.set('pageToken',options.pageToken);const result=await browserRequest(`/connections/${encodeURIComponent(connection.id)}/items${params.toString()?`?${params}`:''}`);const previousItems=options.append&&browserState.connectionId===connection.id?browserState.items:[];const oldStack=options.preserveStack?browserState.stack:[];browserState={connectionId:connection.id,rootId:result.rootId||'',folder:result.folder||null,items:[...previousItems,...(result.items||[])],nextPageToken:result.nextPageToken||null,query:result.query||'',stack:oldStack};renderBrowserBody(connection);}catch(error){if(body){body.textContent='';const box=el('div','','storage-banner');box.textContent=String(error?.message||error);body.append(box);}showError(error);}}

  function paint(){const section=document.querySelector('#storageAdminPanel');if(!section)return;section.textContent='';const head=el('div','','storage-head'),copy=el('div');copy.append(el('div',t('저장 아카이브','CLOUD ARCHIVE'),'storage-kicker'),el('h2',t('저장소','Storage')),el('p',t('원본은 Google Drive에 보관하고, 웹 서비스에 필요한 파일만 R2로 복제합니다.','Keep originals in Google Drive and replicate only web-ready files to R2.'),'storage-muted'));const actions=el('div','','storage-actions');actions.append(button(t('기본 Drive 연결','Connect primary Drive'),()=>startOAuth('primary'),'primary'),button(t('추가 계정 연결','Add account'),()=>startOAuth('secondary')),button(t('새로고침','Refresh'),refresh));head.append(copy,actions);section.append(head);const message=el('div',state.configured?t(`허용 조직: ${state.primaryDomains.join(', ')}`,`Allowed domains: ${state.primaryDomains.join(', ')}`):t('Google Drive 연결 설정이 더 필요합니다.','Google Drive connection setup is incomplete.'),`storage-banner ${state.configured?'ok':''}`);message.id='storageMessage';section.append(message);summary(section);renderConnections(section);renderBrowserShell(section);renderRoutes(section);const connection=browserConnection();renderBrowserBody(connection);if(connection&&(browserState.connectionId!==connection.id||!browserState.folder))queueMicrotask(()=>loadBrowser(connection));}
  async function refresh(){const section=document.querySelector('#storageAdminPanel');if(section)section.innerHTML=`<div class="storage-loading">${t('저장소 상태를 확인하는 중…','Checking storage status…')}</div>`;try{state=await googleRequest('/status');paint();}catch(error){if(section)section.textContent='';showError(error);}}
  function activate(button,section){document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('hidden-panel',panel!==section));document.querySelectorAll('.sidebar .nav').forEach(item=>item.classList.toggle('active',item===button));const title=document.querySelector('#pageTitle');if(title)title.textContent=t('저장소','Storage');document.querySelector('.sidebar')?.classList.remove('open');syncCanonicalRoute();refresh();}
  function install(){if(migrateLegacyStorageLocation())return;const nav=document.querySelector('.sidebar nav'),content=document.querySelector('.content');if(!nav||!content)return;let button=nav.querySelector('[data-section="storage"]');if(!button){button=el('button','','nav');button.type='button';button.dataset.section='storage';button.append(document.createTextNode('▣ '),el('span',t('저장소','Storage')));const security=nav.querySelector('[data-section="security"],[data-demand-feature="security"]');if(security)nav.insertBefore(button,security);else nav.append(button);}let section=document.querySelector('#storageAdminPanel');if(!section){section=el('section','','section storage-admin hidden-panel');section.dataset.panel='storage';section.id='storageAdminPanel';content.append(section);}if(!button.dataset.storageBound){button.dataset.storageBound='true';button.addEventListener('click',()=>activate(button,section));}if(isStorageRoute())queueMicrotask(()=>activate(button,section));}
  install();window.addEventListener('popstate',install);window.addEventListener('hashchange',install);window.addEventListener('ekodi-admin-ready',install);window.addEventListener('ekodi-admin-locale-changed',()=>{if(document.querySelector('#storageAdminPanel:not(.hidden-panel)'))paint();window.EKODIAdminSidebar?.sync?.();});window.EKODIStorageAdmin=Object.freeze({refresh});
})();