(()=>{'use strict';
const API='/api/realtime',SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co',PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_',cfg=document.body.dataset,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),LANDSCAPE={width:1280,height:720},PORTRAIT={width:720,height:1280};
const state={room:null,pc:null,session:null,local:null,screen:null,program:null,canvas:null,ctx:null,canvasStream:null,animationFrame:null,remote:new MediaStream(),hosting:false,isLive:false,closing:false,viewerMutedFallback:false,viewerTracks:[],viewerLanguage:'original',recording:null,studioPrepared:false,destinationCatalogLoaded:false,overlayDrag:null,overlays:new Map(),extraCameras:new Map(),participantPulls:new Map(),participantPublish:null,presenterHidden:false,chatMessages:[],chatTimer:null,participantTimer:null,participantWatchMode:'',managementCameraTimer:null,managementCameraPair:null,managementDeviceKey:'',managementDeviceStream:null,managementDevicePc:null,managementDeviceSession:null,managementFacing:'environment',orientation:'landscape',cameraFit:'contain'};
const LANGUAGE_LABELS=Object.freeze({original:'원음',ko:'한국어',en:'English',zh:'中文',ja:'日本語',vi:'Tiếng Việt',mn:'Монгол'});
function token(){try{return sessionStorage.getItem('ekodi-auth-token')||''}catch{return''}}
async function bootstrapAuthHandoff(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const tokenHash=hash.get('ekodi_token');if(!tokenHash)return false;history.replaceState(null,'',location.pathname+location.search);const response=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({token_hash:tokenHash,type:hash.get('ekodi_type')||'email'})});const data=await response.json().catch(()=>({}));const access=data?.access_token||data?.session?.access_token||'';if(!response.ok||!access)throw new Error(data?.msg||data?.error_description||'login_handoff_failed');sessionStorage.setItem('ekodi-auth-token',access);return true}
function headers(json=false,session=false){const h=new Headers();if(token())h.set('authorization',`Bearer ${token()}`);if(json)h.set('content-type','application/json');if(session&&state.session?.accessKey)h.set('x-ekodi-session-key',state.session.accessKey);return h}
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:headers(Boolean(options.body),Boolean(options.session)),cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error||`HTTP ${response.status}`);e.status=response.status;e.data=data;throw e}return data}
async function sessionApi(path,accessKey,options={}){const h=headers(Boolean(options.body),false);if(accessKey)h.set('x-ekodi-session-key',accessKey);const response=await fetch(`${API}${path}`,{...options,headers:h,cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error||`HTTP ${response.status}`);e.status=response.status;e.data=data;throw e}return data}
function show(id){for(const key of ['entryView','studioView','viewerView'])$(key)?.classList.add('hidden');$(id)?.classList.remove('hidden')}
function note(message,target='statusLog'){if($(target))$(target).textContent=message}
function login(){const returnTo=location.href;location.href=`/auth/?site=${encodeURIComponent(cfg.authSite||cfg.tenant)}&return_to=${encodeURIComponent(returnTo)}`}
async function waitIce(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const timer=setTimeout(resolve,2500);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve()}},{once:false})})}
function providerDescription(data){return data?.provider?.sessionDescription||data?.provider?.data?.sessionDescription||data?.sessionDescription||null}
function broadcastSelection(){const destinationIds=[...document.querySelectorAll('#externalDestinations input[data-destination]:checked')].map(input=>input.value).filter(Boolean);return {broadcastMode:destinationIds.length?'ekodi+external':'ekodi',destinationIds,multistream:destinationIds.length>0}}
function destinationReason(value){return ({channel_connection_required:'채널 연결 필요',live_provider_not_supported:'실시간 송출 미지원',live_permission_required:'실시간 권한 준비 필요',distribution_engine_pending:'외부 송출 엔진 준비 중'})[value]||'사용 준비 필요'}
function renderExternalDestinations(channels=[]){
  const root=$('externalDestinations');if(!root)return;
  root.replaceChildren();
  if(!channels.length){const empty=document.createElement('small');empty.textContent='연결된 외부 방송 채널이 없습니다. 사이트 관리자에서 채널을 연결한 뒤 다시 확인하세요.';root.append(empty);return}
  for(const channel of channels){
    const label=document.createElement('label');label.className='destination-row';
    const input=document.createElement('input');input.type='checkbox';input.value=channel.id;input.dataset.destination='true';input.disabled=!channel.selectable;
    const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=channel.label||channel.provider;const small=document.createElement('small');small.textContent=channel.selectable?'동시방송 선택 가능':destinationReason(channel.reason);copy.append(strong,small);label.append(input,copy);root.append(label);
  }
}
async function loadExternalDestinations(){
  if(!token()){renderExternalDestinations([]);const root=$('externalDestinations');if(root)root.querySelector('small').textContent='외부 방송 채널은 로그인 후 선택할 수 있습니다.';return false}
  try{const data=await api(`/destinations/catalog?tenant=${encodeURIComponent(cfg.tenant)}`);state.destinationCatalogLoaded=true;renderExternalDestinations(data.channels||[]);return true}
  catch(error){state.destinationCatalogLoaded=false;const root=$('externalDestinations');if(root)root.innerHTML='<small>외부 채널을 불러오지 못했습니다. 내부 방송과 자동 저장은 정상적으로 사용할 수 있습니다.</small>';note(`외부 채널 확인 실패: ${error.message}`);return false}
}
async function createRoom(){const body={tenant:cfg.tenant,mode:cfg.roomMode,title:params.get('title')||cfg.defaultTitle,interactiveParticipants:6,languages:0,durationMinutes:180,recording:true,publicViewers:true,ai:true,...broadcastSelection()};try{return await api('/rooms',{method:'POST',body:JSON.stringify(body)})}catch(error){if(error.status===401){login();return null}if(error.status===402&&error.data?.subscriptionUrl){location.href=error.data.subscriptionUrl;return null}throw error}}
async function createSession(roomId,role){const data=await api(`/rooms/${encodeURIComponent(roomId)}/sessions`,{method:'POST',body:JSON.stringify({role})});state.session=data.session;state.pc=new RTCPeerConnection({iceServers:data.iceServers||[]});state.pc.onconnectionstatechange=()=>{$('connectionState')&&($('connectionState').textContent=state.pc.connectionState)};return data}
function liveRemoteTracks(){return state.remote.getTracks().filter(track=>track.readyState==='live')}
async function waitForRemoteTracks(timeoutMs=5000){if(liveRemoteTracks().length)return liveRemoteTracks();const started=Date.now();while(Date.now()-started<timeoutMs){await new Promise(resolve=>setTimeout(resolve,150));if(liveRemoteTracks().length)return liveRemoteTracks()}return []}
async function closeViewerSession(){const roomId=state.room?.id,session=state.session;if(roomId&&session)await api(`/rooms/${roomId}/sessions/${session.id}/leave`,{method:'POST',session:true,body:'{}'}).catch(()=>{});state.pc?.close();state.pc=null;state.session=null;state.remote.getTracks().forEach(track=>track.stop());state.remote=new MediaStream();if($('viewerVideo'))$('viewerVideo').srcObject=null}
function attachViewerTracks(event){const incoming=event.streams?.length?event.streams.flatMap(stream=>stream.getTracks()):[event.track];for(const track of incoming)if(track&&!state.remote.getTracks().some(item=>item.id===track.id))state.remote.addTrack(track);const video=$('viewerVideo');if(!video)return;video.srcObject=state.remote;$('viewerEmpty')?.classList.add('hidden');video.play?.().catch(error=>{if(error?.name!=='NotAllowedError')return;video.muted=true;state.viewerMutedFallback=true;video.play?.().catch(()=>{})})}
function viewerTrackSelection(tracks,language=state.viewerLanguage){
  const rows=(tracks||[]).map(track=>({trackName:track.track_name||track.trackName,kind:track.media_kind||track.kind,sourceType:track.source_type||track.sourceType,languageCode:String(track.language_code||track.languageCode||'').toLowerCase()})).filter(track=>track.trackName);
  const videos=rows.filter(track=>track.kind==='video'),programVideos=videos.filter(track=>track.sourceType==='program'),audio=rows.filter(track=>track.kind==='audio');
  const selected=[...(programVideos.length?programVideos:videos).slice(0,1)];
  let chosen=null;
  if(language&&language!=='original')chosen=audio.find(track=>track.sourceType==='translation'&&track.languageCode===String(language).toLowerCase())||null;
  if(!chosen)chosen=audio.find(track=>track.sourceType!=='translation')||audio[0]||null;
  if(chosen)selected.push(chosen);
  return selected;
}
function renderInterpretationAvailability(tracks=[]){
  const available=new Set((tracks||[]).filter(track=>(track.source_type||track.sourceType)==='translation').map(track=>String(track.language_code||track.languageCode||'').toLowerCase()).filter(Boolean));
  const select=$('viewerListenLanguage');if(!select)return;
  for(const option of select.options){if(option.value==='original'){option.disabled=false;continue}option.dataset.available=available.has(option.value)?'true':'false'}
  const status=$('interpretationState');if(status)status.textContent=state.viewerLanguage==='original'?'원음':available.has(state.viewerLanguage)?LANGUAGE_LABELS[state.viewerLanguage]||state.viewerLanguage:'통역 준비 중';
}
async function connectViewerMedia(id,tracks,language=state.viewerLanguage){await createSession(id,'viewer');state.pc.ontrack=attachViewerTracks;const selected=viewerTrackSelection(tracks,language);const pulled=await api(`/rooms/${id}/sessions/${state.session.id}/pull`,{method:'POST',session:true,body:JSON.stringify({tracks:selected.map(track=>({trackName:track.trackName}))})});if(pulled.empty)return {ok:false,empty:true};const offer=providerDescription(pulled);if(!offer?.sdp)throw new Error('media_server_offer_missing');await state.pc.setRemoteDescription(offer);const answer=await state.pc.createAnswer();await state.pc.setLocalDescription(answer);await waitIce(state.pc);await api(`/rooms/${id}/sessions/${state.session.id}/renegotiate`,{method:'PUT',session:true,body:JSON.stringify({sessionDescription:state.pc.localDescription})});const received=await waitForRemoteTracks();return {ok:received.length>0,empty:false,received:received.length}}
function openViewerWindow(){const url=$('shareLink')?.value;if(!url)return note('먼저 방송을 준비해 주세요.');const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';document.body.appendChild(link);link.click();link.remove();note('시청 화면을 새 탭으로 열었습니다. 송출 스튜디오는 그대로 유지합니다.')}
function hostExitCleanup(){if(!state.hosting||!state.isLive||state.closing||!state.room)return;state.isLive=false;const roomId=encodeURIComponent(state.room.id);if(state.session)fetch(`${API}/rooms/${roomId}/sessions/${state.session.id}/leave`,{method:'POST',headers:headers(true,true),body:'{}',keepalive:true,cache:'no-store'}).catch(()=>{});fetch(`${API}/rooms/${roomId}/status`,{method:'POST',headers:headers(true,false),body:JSON.stringify({status:'ended'}),keepalive:true,cache:'no-store'}).catch(()=>{})}
function setSourceVideo(id,stream){const video=$(id);if(!video)return;video.srcObject=stream;video.play?.().catch(()=>{})}
function drawContained(ctx,video,x,y,w,h){ctx.fillStyle='#090b0a';ctx.fillRect(x,y,w,h);if(!video?.videoWidth||!video?.videoHeight)return;const scale=Math.min(w/video.videoWidth,h/video.videoHeight),dw=video.videoWidth*scale,dh=video.videoHeight*scale;ctx.drawImage(video,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function drawCovered(ctx,video,x,y,w,h){if(!video?.videoWidth||!video?.videoHeight){ctx.fillStyle='#142019';ctx.fillRect(x,y,w,h);return}const scale=Math.max(w/video.videoWidth,h/video.videoHeight),sw=w/scale,sh=h/scale,sx=(video.videoWidth-sw)/2,sy=(video.videoHeight-sh)/2;ctx.drawImage(video,sx,sy,sw,sh,x,y,w,h)}
function programBox(){const stage=$('programStage');if(!stage)return null;const rect=stage.getBoundingClientRect();if(!rect.width||!rect.height)return null;const target=state.canvas?state.canvas.width/state.canvas.height:16/9;let width=rect.width,height=rect.height,left=0,top=0;if(width/height>target){width=height*target;left=(rect.width-width)/2}else if(width/height<target){height=width/target;top=(rect.height-height)/2}return {rect,left,top,width,height}}
function overlayDefaults(type,index=0){const video=type!=='chat';return {x:Math.min(.72,.04+(index%3)*.29),y:Math.min(.72,.08+Math.floor(index/3)*.22),w:video ? .26 : .34,h:video ? .146 : .38}}
function createOverlayVideo(stream,id){const video=document.createElement('video');video.className='source-video';video.autoplay=true;video.playsInline=true;video.muted=true;video.srcObject=stream;video.dataset.overlayVideo=id;$('programStage')?.append(video);video.play?.().catch(()=>{});return video}
function ensureOverlay(id,{type='video',label='소스',stream=null}={}){let overlay=state.overlays.get(id);if(!overlay){overlay={id,type,label,visible:false,...overlayDefaults(type,state.overlays.size),stream:null,video:null};state.overlays.set(id,overlay)}overlay.label=label||overlay.label;overlay.type=type;if(stream&&overlay.stream!==stream){overlay.stream=stream;overlay.video?.remove?.();overlay.video=createOverlayVideo(stream,id)}syncOverlayHandles();return overlay}
function overlayHandle(id){const layer=$('programOverlayLayer');if(!layer)return null;let h=[...layer.querySelectorAll('[data-program-overlay]')].find(node=>node.dataset.programOverlay===id);if(h)return h;const overlay=state.overlays.get(id);if(!overlay)return null;h=document.createElement('div');h.className='program-drag-handle';h.dataset.programOverlay=id;const label=document.createElement('span');label.textContent=overlay.label;const close=document.createElement('button');close.type='button';close.className='overlay-remove';close.textContent='×';close.addEventListener('click',event=>{event.stopPropagation();removeOverlay(id)});h.append(label,close);layer.append(h);h.addEventListener('pointerdown',beginOverlayDrag);h.addEventListener('pointermove',moveOverlayDrag);h.addEventListener('pointerup',endOverlayDrag);h.addEventListener('pointercancel',endOverlayDrag);return h}
function syncOverlayHandles(){const box=programBox();if(!box)return;for(const overlay of state.overlays.values()){const h=overlayHandle(overlay.id);if(!h)continue;h.classList.toggle('hidden',!overlay.visible);if(!overlay.visible)continue;h.style.left=`${box.left+overlay.x*box.width}px`;h.style.top=`${box.top+overlay.y*box.height}px`;h.style.width=`${overlay.w*box.width}px`;h.style.height=`${overlay.h*box.height}px`;h.querySelector('span').textContent=overlay.label}}
function addOverlay(id){const overlay=state.overlays.get(id);if(!overlay)return;if(id==='presenter'){if(!state.screen)return note('발표자는 화면공유 중에 방송화면에 추가할 수 있습니다.');state.presenterHidden=false}overlay.visible=true;syncOverlayHandles();renderSourceCards()}
function removeOverlay(id){const overlay=state.overlays.get(id);if(!overlay)return;if(id==='presenter')state.presenterHidden=true;overlay.visible=false;syncOverlayHandles();renderSourceCards()}
function beginOverlayDrag(event){if(event.target.closest('.overlay-remove'))return;const id=event.currentTarget.dataset.programOverlay,overlay=state.overlays.get(id),box=programBox();if(!overlay||!box)return;const rect=event.currentTarget.getBoundingClientRect();state.overlayDrag={id,pointerId:event.pointerId,offsetX:event.clientX-rect.left,offsetY:event.clientY-rect.top};event.currentTarget.setPointerCapture?.(event.pointerId);event.currentTarget.classList.add('dragging');event.preventDefault()}
function moveOverlayDrag(event){const drag=state.overlayDrag;if(!drag||drag.pointerId!==event.pointerId)return;const overlay=state.overlays.get(drag.id),box=programBox();if(!overlay||!box)return;const left=box.rect.left+box.left,top=box.rect.top+box.top;overlay.x=Math.max(0,Math.min(1-overlay.w,(event.clientX-left-drag.offsetX)/box.width));overlay.y=Math.max(0,Math.min(1-overlay.h,(event.clientY-top-drag.offsetY)/box.height));syncOverlayHandles()}
function endOverlayDrag(event){if(!state.overlayDrag||state.overlayDrag.pointerId!==event.pointerId)return;event.currentTarget.classList.remove('dragging');state.overlayDrag=null}
function drawChatOverlay(ctx,overlay,w,h){const x=Math.round(overlay.x*w),y=Math.round(overlay.y*h),ow=Math.round(overlay.w*w),oh=Math.round(overlay.h*h);ctx.save();ctx.fillStyle='rgba(16,21,18,.82)';ctx.fillRect(x,y,ow,oh);ctx.fillStyle='#fff';ctx.font='700 20px sans-serif';ctx.fillText('실시간 채팅',x+16,y+28);let line=y+58;for(const row of state.chatMessages.slice(-6)){ctx.fillStyle='#b9d1c1';ctx.font='700 14px sans-serif';ctx.fillText(String(row.displayName||'참여자').slice(0,16),x+16,line);ctx.fillStyle='#fff';ctx.font='500 16px sans-serif';let text=String(row.message||'').slice(0,70);while(ctx.measureText(text).width>ow-32&&text.length>4)text=text.slice(0,-2);ctx.fillText(text,x+16,line+20);line+=46;if(line>y+oh-18)break}ctx.restore()}
function drawOverlays(ctx,w,h){for(const overlay of state.overlays.values()){if(!overlay.visible)continue;if(overlay.type==='chat'){drawChatOverlay(ctx,overlay,w,h);continue}if(!overlay.video?.videoWidth)continue;const x=Math.round(overlay.x*w),y=Math.round(overlay.y*h),ow=Math.round(overlay.w*w),oh=Math.round(overlay.h*h);ctx.fillStyle='#f6f1e8';ctx.fillRect(x-3,y-3,ow+6,oh+6);drawCovered(ctx,overlay.video,x,y,ow,oh)}}
function drawProgram(){if(!state.ctx||!state.canvas)return;const ctx=state.ctx,w=state.canvas.width,h=state.canvas.height,camera=$('cameraSource'),screen=$('screenSource');ctx.fillStyle='#090b0a';ctx.fillRect(0,0,w,h);if(state.screen&&screen?.videoWidth){drawContained(ctx,screen,0,0,w,h);const presenter=ensureOverlay('presenter',{type:'video',label:'발표자',stream:state.local});presenter.visible=!state.presenterHidden}else{(state.cameraFit==='cover'?drawCovered:drawContained)(ctx,camera,0,0,w,h);const presenter=state.overlays.get('presenter');if(presenter)presenter.visible=false}drawOverlays(ctx,w,h);syncOverlayHandles();state.animationFrame=requestAnimationFrame(drawProgram)}
function ensureProgram(){if(state.program)return state.program;const canvas=document.createElement('canvas');const size=state.orientation==='portrait'?PORTRAIT:LANDSCAPE;canvas.width=size.width;canvas.height=size.height;state.canvas=canvas;state.ctx=canvas.getContext('2d',{alpha:false});if(typeof canvas.captureStream!=='function'){state.program=state.local;$('mainVideo').srcObject=state.local;return state.program}state.canvasStream=canvas.captureStream(30);state.program=new MediaStream([...state.canvasStream.getVideoTracks(),...state.local.getAudioTracks()]);$('mainVideo').srcObject=state.program;$('mainVideo').play?.().catch(()=>{});drawProgram();return state.program}
function setProgramOrientation(value){state.orientation=value==='portrait'?'portrait':'landscape';if(state.canvas){const size=state.orientation==='portrait'?PORTRAIT:LANDSCAPE;state.canvas.width=size.width;state.canvas.height=size.height}const stage=$('programStage');stage?.classList.toggle('portrait',state.orientation==='portrait');for(const [id,pressed] of [['landscapeButton',state.orientation==='landscape'],['portraitButton',state.orientation==='portrait']]){const button=$(id);if(button){button.classList.toggle('active',pressed);button.setAttribute('aria-pressed',String(pressed))}}syncOverlayHandles();note(state.orientation==='portrait'?'세로 9:16 방송 화면으로 전환했습니다.':'가로 16:9 방송 화면으로 전환했습니다.')}
function setCameraFit(value){state.cameraFit=value==='cover'?'cover':'contain';note(state.cameraFit==='contain'?'카메라를 맞춤 표시합니다. 주변이 잘리지 않습니다.':'카메라를 화면에 꽉 채워 표시합니다.')}
async function acquireCamera(){if(state.local)return state.local;const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true}});state.local=stream;setSourceVideo('cameraSource',stream);$('programPlaceholder')?.classList.add('hidden');ensureProgram();return stream}
function sourceCard(id,label,{subtitle='화면에 추가',onDelete=null}={}){
  const card=document.createElement('div');card.className='source-card-row';card.draggable=true;card.dataset.overlayId=id;
  const copy=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=label;small.textContent=subtitle;copy.append(strong,small);
  const add=document.createElement('button');add.type='button';add.textContent=state.overlays.get(id)?.visible?'화면에서 빼기':'추가';add.addEventListener('click',()=>state.overlays.get(id)?.visible?removeOverlay(id):addOverlay(id));card.append(copy,add);
  if(onDelete){const del=document.createElement('button');del.type='button';del.className='source-delete';del.textContent='연결 해제';del.addEventListener('click',onDelete);card.append(del)}
  card.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay',id));return card;
}
function renderSourceCards(){
  const presenter=$('presenterOverlaySource');if(presenter){const active=state.overlays.get('presenter')?.visible;presenter.querySelector('span').textContent=active?'빼기':'추가';presenter.classList.toggle('active',Boolean(active))}
  const chat=$('chatOverlaySource');if(chat){const active=state.overlays.get('chat')?.visible;chat.querySelector('span').textContent=active?'빼기':'추가';chat.classList.toggle('active',Boolean(active))}
  const cameras=$('extraCameraSources');if(cameras){cameras.replaceChildren();for(const [id,item] of state.extraCameras)cameras.append(sourceCard(id,item.label,{onDelete:()=>disconnectExtraCamera(id)}))}
  const managed=$('managementCameraSources'),participants=$('participantSources');if(managed)managed.replaceChildren();if(participants)participants.replaceChildren();
  for(const [id,item] of state.participantPulls){const card=sourceCard(id,item.label,{subtitle:item.ready?'추가':'연결 중'});if(item.kind==='management_camera')managed?.append(card);else participants?.append(card)}
}
async function refreshCameraDevices(){
  if(!navigator.mediaDevices?.enumerateDevices)return;const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput'),primary=state.local?.getVideoTracks?.()[0]?.getSettings?.().deviceId||'';
  for(const select of [$('extraCameraSelect'),$('participantCameraSelect')].filter(Boolean)){const selected=select.value;select.replaceChildren(new Option(select.id==='extraCameraSelect'?'추가 카메라 선택':'카메라 선택',''));for(const [i,d] of devices.entries()){if(select.id==='extraCameraSelect'&&d.deviceId===primary)continue;select.append(new Option(d.label||`카메라 ${i+1}`,d.deviceId))}if([...select.options].some(o=>o.value===selected))select.value=selected}
}
async function connectExtraCamera(){const deviceId=$('extraCameraSelect')?.value;if(!deviceId)return note('추가할 카메라를 선택해 주세요.');const existing=[...state.extraCameras.values()].find(item=>item.deviceId===deviceId);if(existing){addOverlay(existing.id);return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}},audio:false}),label=$('extraCameraSelect').selectedOptions?.[0]?.textContent||'추가 카메라',id=`camera:${crypto.randomUUID()}`,overlay=ensureOverlay(id,{type:'video',label,stream});state.extraCameras.set(id,{id,deviceId,label,stream,overlay});renderSourceCards();note(`${label} 연결 완료. 끌어서 방송화면에 추가할 수 있습니다.`)}catch(error){note(`추가 카메라 연결 실패: ${error.message}`)}}
function disconnectExtraCamera(id){const item=state.extraCameras.get(id);if(!item)return;item.stream.getTracks().forEach(t=>t.stop());item.overlay?.video?.remove?.();state.extraCameras.delete(id);state.overlays.delete(id);syncOverlayHandles();renderSourceCards()}
function qrMatrixV5(text){
  const bytes=[...new TextEncoder().encode(String(text||''))];if(bytes.length>100)throw new Error('qr_payload_too_long');
  const bits=[],push=(value,count)=>{for(let i=count-1;i>=0;i--)bits.push((value>>>i)&1)};push(4,4);push(bytes.length,8);for(const byte of bytes)push(byte,8);
  const capacity=108*8;for(let i=0;i<Math.min(4,capacity-bits.length);i++)bits.push(0);while(bits.length%8)bits.push(0);
  const data=[];for(let i=0;i<bits.length;i+=8){let value=0;for(let j=0;j<8;j++)value=(value<<1)|(bits[i+j]||0);data.push(value)}for(let pad=0;data.length<108;pad++)data.push(pad%2?0x11:0xec);
  const exp=new Uint8Array(512),log=new Uint8Array(256);let x=1;for(let i=0;i<255;i++){exp[i]=x;log[x]=i;x<<=1;if(x&0x100)x^=0x11d}for(let i=255;i<512;i++)exp[i]=exp[i-255];
  const mul=(a,b)=>!a||!b?0:exp[log[a]+log[b]];let gen=[1];for(let i=0;i<26;i++){const next=new Array(gen.length+1).fill(0);for(let j=0;j<gen.length;j++){next[j]^=gen[j];next[j+1]^=mul(gen[j],exp[i])}gen=next}
  const ecc=new Array(26).fill(0);for(const byte of data){const factor=byte^ecc[0];ecc.shift();ecc.push(0);for(let j=0;j<26;j++)ecc[j]^=mul(gen[j+1],factor)}
  const stream=[];for(const byte of [...data,...ecc])for(let i=7;i>=0;i--)stream.push((byte>>>i)&1);
  const size=37,m=Array.from({length:size},()=>Array(size).fill(null));
  const finder=(row,col)=>{for(let r=-1;r<=7;r++)for(let c=-1;c<=7;c++){const y=row+r,z=col+c;if(y<0||z<0||y>=size||z>=size)continue;m[y][z]=r>=0&&r<=6&&c>=0&&c<=6&&(r===0||r===6||c===0||c===6||(r>=2&&r<=4&&c>=2&&c<=4))}};
  finder(0,0);finder(size-7,0);finder(0,size-7);
  for(const cy of [6,30])for(const cx of [6,30]){if(m[cy][cx]!==null)continue;for(let r=-2;r<=2;r++)for(let c=-2;c<=2;c++)m[cy+r][cx+c]=Math.abs(r)===2||Math.abs(c)===2||(r===0&&c===0)}
  for(let i=8;i<size-8;i++){if(m[i][6]===null)m[i][6]=i%2===0;if(m[6][i]===null)m[6][i]=i%2===0}
  const digit=v=>{let n=0;while(v){n++;v>>>=1}return n},format=mask=>{const dataBits=(1<<3)|mask;let d=dataBits<<10;while(digit(d)-digit(0x537)>=0)d^=0x537<<(digit(d)-digit(0x537));return ((dataBits<<10)|d)^0x5412},fmt=format(0);
  for(let i=0;i<15;i++){const bit=((fmt>>>i)&1)===1;if(i<6)m[i][8]=bit;else if(i<8)m[i+1][8]=bit;else m[size-15+i][8]=bit}
  for(let i=0;i<15;i++){const bit=((fmt>>>i)&1)===1;if(i<8)m[8][size-i-1]=bit;else if(i<9)m[8][15-i]=bit;else m[8][15-i-1]=bit}m[size-8][8]=true;
  let row=size-1,inc=-1,index=0;for(let col=size-1;col>0;col-=2){if(col===6)col--;for(;;){for(let c=0;c<2;c++){const xcol=col-c;if(m[row][xcol]!==null)continue;let dark=index<stream.length?stream[index++]===1:false;if((row+xcol)%2===0)dark=!dark;m[row][xcol]=dark}row+=inc;if(row<0||row>=size){row-=inc;inc=-inc;break}}}
  return m;
}
function drawManagementCameraQr(text){const canvas=$('managementCameraQr');if(!canvas)return;const matrix=qrMatrixV5(text),quiet=4,scale=4,size=matrix.length+quiet*2;canvas.width=canvas.height=size*scale;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let y=0;y<matrix.length;y++)for(let x=0;x<matrix.length;x++)if(matrix[y][x])ctx.fillRect((x+quiet)*scale,(y+quiet)*scale,scale,scale)}
function managementPairLabel(status){return ({issued:'QR 생성',pending:'승인 대기',approved:'승인됨',connected:'연결됨',revoked:'해제됨',expired:'만료'})[status]||status}
function renderManagementCameraPairs(rows=[]){const root=$('managementCameraPairs');if(!root)return;root.replaceChildren();let pending=0,connected=0;for(const row of rows){if(row.status==='pending')pending++;if(row.status==='connected')connected++;const item=document.createElement('div');item.className='pair-row';const copy=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=row.label||'관리 카메라';small.textContent=managementPairLabel(row.status);copy.append(strong,small);const actions=document.createElement('div');actions.className='pair-row-actions';if(row.status==='pending'){const approve=document.createElement('button');approve.type='button';approve.textContent='승인';approve.addEventListener('click',()=>decideManagementCameraPair(row.id,'approved'));actions.append(approve)}if(!['revoked','expired'].includes(row.status)){const revoke=document.createElement('button');revoke.type='button';revoke.textContent='해제';revoke.addEventListener('click',()=>decideManagementCameraPair(row.id,'revoked'));actions.append(revoke)}item.append(copy,actions);root.append(item)}const stateEl=$('managementCameraState');if(stateEl)stateEl.textContent=connected?`${connected}대 연결`:pending?`${pending}대 승인 대기`:'대기'}
async function ensureRoomForManagementCamera(){if(state.room)return state.room;if(!token()){login();return null}const created=await createRoom();if(!created)return null;state.room=created.room;if($('roomTitle'))$('roomTitle').textContent=state.room.title;if($('shareLink'))$('shareLink').value=`${location.origin}${cfg.livePath}?room=${encodeURIComponent(state.room.id)}`;$('roomLinks')?.classList.remove('hidden');return state.room}
async function refreshManagementCameraPairs(){if(!state.room||!token())return;try{const data=await api(`/rooms/${encodeURIComponent(state.room.id)}/management-cameras`);renderManagementCameraPairs(data.pairs||[]);if((data.pairs||[]).some(row=>row.status==='connected'))await refreshParticipantSources()}catch(error){note(`QR카메라 확인 실패: ${error.message}`)}}
function startManagementCameraPolling(){clearTimeout(state.managementCameraTimer);const poll=async()=>{if(!state.room)return;await refreshManagementCameraPairs();if($('managementCameraDialog')?.open)state.managementCameraTimer=setTimeout(poll,3000)};void poll()}
async function openManagementCameraDialog(){const dialog=$('managementCameraDialog');if(state.managementCameraPair&&$('managementCameraUrl')?.value){if(dialog&&!dialog.open)dialog.showModal();await refreshManagementCameraPairs();startManagementCameraPolling();return}await createManagementCameraPair()}
async function createManagementCameraPair(){const room=await ensureRoomForManagementCamera();if(!room)return;try{const data=await api(`/rooms/${encodeURIComponent(room.id)}/management-cameras`,{method:'POST',body:JSON.stringify({label:'관리 카메라'})});state.managementCameraPair=data.pair;$('managementCameraUrl').value=data.cameraUrl;drawManagementCameraQr(data.cameraUrl);const dialog=$('managementCameraDialog');if(dialog&&!dialog.open)dialog.showModal();await refreshManagementCameraPairs();startManagementCameraPolling()}catch(error){note(`QR카메라 생성 실패: ${error.message}`)}}
async function decideManagementCameraPair(id,status){if(!state.room)return;try{await api(`/rooms/${encodeURIComponent(state.room.id)}/management-cameras/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});await refreshManagementCameraPairs()}catch(error){note(`QR카메라 처리 실패: ${error.message}`)}}
function managementDeviceKey(pairCode){const key=`ekodi-live-camera:${pairCode}`;try{let value=localStorage.getItem(key)||'';if(value)return value;const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);value=[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem(key,value);return value}catch{const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}}
async function managementCameraApi(pairCode,action,options={}){const h=new Headers(options.headers||{});if(state.managementDeviceKey)h.set('x-ekodi-camera-key',state.managementDeviceKey);if(options.body&&!h.has('content-type'))h.set('content-type','application/json');const response=await fetch(`${API}/management-cameras/${encodeURIComponent(pairCode)}/${action}`,{...options,headers:h,cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`HTTP ${response.status}`);error.status=response.status;throw error}return data}
async function acquireManagementDeviceCamera(){const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:state.managementFacing},width:{ideal:1280},height:{ideal:720}},audio:false}),old=state.managementDeviceStream;state.managementDeviceStream=next;const preview=$('managementCameraPreview');if(preview){preview.srcObject=next;preview.play?.().catch(()=>{})}if(state.managementDevicePc){const sender=state.managementDevicePc.getSenders().find(item=>item.track?.kind==='video');if(sender)await sender.replaceTrack(next.getVideoTracks()[0])}old?.getTracks?.().forEach(track=>track.stop());return next}
async function publishManagementDeviceCamera(pairCode){if(state.managementDeviceSession||!state.managementDeviceStream)return;const created=await managementCameraApi(pairCode,'session',{method:'POST',body:'{}'}),session=created.session,pc=new RTCPeerConnection({iceServers:created.iceServers||[]});for(const track of state.managementDeviceStream.getTracks())pc.addTrack(track,state.managementDeviceStream);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const tracks=trackPayload(pc,state.managementDeviceStream,'camera');const published=await sessionApi(`/rooms/${encodeURIComponent(created.pair.roomId)}/sessions/${encodeURIComponent(session.id)}/publish`,session.accessKey,{method:'POST',body:JSON.stringify({sessionDescription:pc.localDescription,tracks})}),answer=providerDescription(published);if(!answer?.sdp)throw new Error('media_server_answer_missing');await pc.setRemoteDescription(answer);state.managementDevicePc=pc;state.managementDeviceSession=session;note('연결됨','managementCameraDeviceStatus')}
function pollManagementDeviceApproval(pairCode){clearTimeout(state.managementCameraTimer);const poll=async()=>{try{const data=await managementCameraApi(pairCode,'status');const status=data.pair?.status||'';note(managementPairLabel(status),'managementCameraDeviceStatus');if(['approved','connected'].includes(status)){await publishManagementDeviceCamera(pairCode);return}if(['revoked','expired'].includes(status))return}catch(error){note(error.status===410?'만료됨':'승인 확인 실패','managementCameraDeviceStatus');return}state.managementCameraTimer=setTimeout(poll,1800)};void poll()}
async function connectManagementDeviceCamera(){const pairCode=cfg.cameraPair;if(!pairCode)return;try{state.managementDeviceKey=managementDeviceKey(pairCode);await acquireManagementDeviceCamera();await managementCameraApi(pairCode,'request',{method:'POST',body:JSON.stringify({deviceKey:state.managementDeviceKey,label:'관리 카메라'})});note('승인 대기','managementCameraDeviceStatus');pollManagementDeviceApproval(pairCode)}catch(error){note(`연결 실패: ${error.message}`,'managementCameraDeviceStatus')}}
async function switchManagementDeviceCamera(){state.managementFacing=state.managementFacing==='environment'?'user':'environment';try{await acquireManagementDeviceCamera();note(state.managementFacing==='environment'?'후면 카메라':'전면 카메라','managementCameraDeviceStatus')}catch(error){note(`전환 실패: ${error.message}`,'managementCameraDeviceStatus')}}
function setupProgramDrop(){const stage=$('programStage');if(!stage)return;stage.addEventListener('dragover',event=>{if(event.dataTransfer?.types?.includes('text/ekodi-overlay')){event.preventDefault();stage.classList.add('drop-ready')}});stage.addEventListener('dragleave',()=>stage.classList.remove('drop-ready'));stage.addEventListener('drop',event=>{event.preventDefault();stage.classList.remove('drop-ready');const id=event.dataTransfer?.getData('text/ekodi-overlay');if(id)addOverlay(id)})}
function trackPayload(pc,stream,source='camera',languageCode=''){return pc.getTransceivers().filter(t=>t.sender?.track&&stream.getTracks().includes(t.sender.track)).map((t,index)=>({mid:t.mid,trackName:`${source}-${t.sender.track.kind}-${Date.now()}-${index}`,kind:t.sender.track.kind,sourceType:t.sender.track.kind==='audio'?'microphone':source,languageCode:languageCode||null}))}
async function publishStream(stream,source='camera'){for(const track of stream.getTracks())state.pc.addTrack(track,stream);const offer=await state.pc.createOffer();await state.pc.setLocalDescription(offer);await waitIce(state.pc);const tracks=trackPayload(state.pc,stream,source);if(tracks.some(t=>!t.mid))throw new Error('media_negotiation_not_ready');const data=await api(`/rooms/${state.room.id}/sessions/${state.session.id}/publish`,{method:'POST',session:true,body:JSON.stringify({sessionDescription:state.pc.localDescription,tracks})});const answer=providerDescription(data);if(!answer?.sdp)throw new Error('media_server_answer_missing');await state.pc.setRemoteDescription(answer)}

const RECORD_PART_TARGET=6*1024*1024;
function recordingMime(){for(const type of ['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'])if(globalThis.MediaRecorder?.isTypeSupported?.(type))return type;return 'video/webm'}
async function uploadRecordingBlob(rec,blob){
  const part=rec.part++;
  const response=await fetch(`${API}/rooms/${encodeURIComponent(state.room.id)}/recordings/${encodeURIComponent(rec.id)}/parts/${part}`,{method:'PUT',headers:{authorization:`Bearer ${token()}`,'content-type':rec.mime},body:blob});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`recording_part_${response.status}`);return data;
}
function flushRecordingPart(rec,force=false){
  if(!rec||!rec.pending.length||(!force&&rec.pendingBytes<RECORD_PART_TARGET))return;
  const blob=new Blob(rec.pending,{type:rec.mime});rec.pending=[];rec.pendingBytes=0;
  rec.queue=rec.queue.then(()=>uploadRecordingBlob(rec,blob)).catch(error=>{rec.failed=true;note(`녹화 저장 지연: ${error.message}. 방송은 계속됩니다.`)});
}
async function startRecording(){
  if(!state.room||!(state.program||state.local)||!globalThis.MediaRecorder)return false;
  try{
    const mime=recordingMime(),created=await api(`/rooms/${state.room.id}/recordings`,{method:'POST',body:JSON.stringify({mimeType:mime,title:state.room.title,retentionDays:180})});
    const rec={id:created.recording.id,mime,part:1,pending:[],pendingBytes:0,queue:Promise.resolve(),failed:false,media:null};
    const media=new MediaRecorder(state.program||state.local,{mimeType:mime});rec.media=media;state.recording=rec;
    media.ondataavailable=event=>{if(!event.data?.size)return;rec.pending.push(event.data);rec.pendingBytes+=event.data.size;flushRecordingPart(rec,false)};
    media.onerror=event=>{rec.failed=true;note(`녹화 오류: ${event.error?.message||'recording_error'}. 방송은 계속됩니다.`)};
    media.start(5000);note('방송 중입니다. 녹화본은 R2에 안전하게 기록한 뒤 공유드라이브로 보관합니다.');return true;
  }catch(error){note(`방송은 시작됐지만 녹화 준비에 실패했습니다: ${error.message}`);return false}
}
async function stopRecording(){
  const rec=state.recording;if(!rec)return null;
  if(rec.media?.state!=='inactive')await new Promise(resolve=>{rec.media.addEventListener('stop',resolve,{once:true});rec.media.stop()});
  flushRecordingPart(rec,true);await rec.queue;
  try{
    if(rec.failed){await api(`/rooms/${state.room.id}/recordings/${rec.id}/abort`,{method:'POST',body:'{}'}).catch(()=>{});return null}
    const done=await api(`/rooms/${state.room.id}/recordings/${rec.id}/finalize`,{method:'POST',body:'{}'});
    note(done.archive?.ok?'방송 종료 · 녹화본 공유드라이브 보관 완료':'방송 종료 · 녹화본 저장 완료, 공유드라이브 보관 대기');return done;
  }catch(error){note(`방송은 종료됐지만 녹화 확정에 실패했습니다: ${error.message}`);return null}
  finally{state.recording=null}
}
async function prepareStudio(){show('studioView');note('준비 중');try{await acquireCamera();await refreshCameraDevices();state.studioPrepared=true;$('goLiveButton').disabled=false;await loadExternalDestinations();note('준비 완료');return true}catch(error){state.studioPrepared=false;$('goLiveButton').disabled=true;note(`준비 실패: ${error.message}`);return false}}
async function startHost(){if(state.room&&state.session&&state.pc)return true;if(state.hosting)return false;state.hosting=true;show('studioView');note('연결 중');try{if(!state.room){const created=await createRoom();if(!created){state.hosting=false;return false}state.room=created.room}$('roomTitle').textContent=state.room.title;$('shareLink').value=`${location.origin}${cfg.livePath}?room=${encodeURIComponent(state.room.id)}`;$('roomLinks').classList.remove('hidden');const stream=state.local||await acquireCamera(),program=ensureProgram()||stream;await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'starting'})});await createSession(state.room.id,'owner');await publishStream(program,'program');startChatPolling();startParticipantMonitoring();await refreshManagementCameraPairs();note('송출 준비 완료');return true}catch(error){state.hosting=false;$('goLiveButton').disabled=false;note(`연결 실패: ${error.message}`);return false}}
async function goLive(){if(!state.room)return;try{await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'live'})});state.isLive=true;$('programBadge').textContent='LIVE';$('liveState').textContent='방송 중';$('goLiveButton').disabled=true;$('endLiveButton').disabled=false;note('방송 중 · 자동 녹화');await startRecording()}catch(error){$('goLiveButton').disabled=false;note(`방송 시작 실패: ${error.message}`)}}
async function startBroadcast(){if(!state.studioPrepared){const prepared=await prepareStudio();if(!prepared)return}if(!token())return login();$('goLiveButton').disabled=true;const ready=await startHost();if(!ready){$('goLiveButton').disabled=false;return}await goLive()}
async function endLive(){if(!state.room)return;state.closing=true;try{await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'ending'})});await stopRecording();if(state.session)await api(`/rooms/${state.room.id}/sessions/${state.session.id}/leave`,{method:'POST',session:true,body:'{}'}).catch(()=>{});state.pc?.close();cleanupCollaboration();for(const id of [...state.extraCameras.keys()])disconnectExtraCamera(id);state.local?.getTracks().forEach(t=>t.stop());state.screen?.getTracks().forEach(t=>t.stop());state.canvasStream?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(state.animationFrame);await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'ended'})});state.isLive=false;$('programBadge').textContent='종료';$('endLiveButton').disabled=true;if(!state.recording)note('방송이 종료되었습니다.')}catch(error){note(`방송 종료 처리 실패: ${error.message}`)}finally{state.closing=false}}
async function shareScreen(){if(!state.local)return note('먼저 카메라를 준비해 주세요.');if(state.screen){state.screen.getTracks().forEach(track=>track.stop());state.screen=null;setSourceVideo('screenSource',null);state.presenterHidden=false;removeOverlay('presenter');return note('화면공유를 종료했습니다.')}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});state.screen=stream;state.presenterHidden=false;setSourceVideo('screenSource',stream);const presenter=ensureOverlay('presenter',{type:'video',label:'발표자',stream:state.local});presenter.visible=true;syncOverlayHandles();renderSourceCards();stream.getVideoTracks()[0]?.addEventListener('ended',()=>{state.screen=null;state.presenterHidden=false;setSourceVideo('screenSource',null);removeOverlay('presenter')},{once:true});note('화면공유 중')}catch(error){if(error.name!=='NotAllowedError')note(`화면공유 실패: ${error.message}`)}}
function renderChatMessages(){for(const id of ['studioChatMessages','viewerChatMessages']){const root=$(id);if(!root)continue;root.replaceChildren();for(const row of state.chatMessages.slice(-80)){const item=document.createElement('div');item.className='chat-message';const meta=document.createElement('span');meta.textContent=row.displayName||'참여자';const p=document.createElement('p');p.textContent=row.message||'';item.append(meta,p);root.append(item)}root.scrollTop=root.scrollHeight}}
async function refreshChat(){if(!state.room)return;try{const data=await api(`/rooms/${encodeURIComponent(state.room.id)}/chat`);state.chatMessages=data.messages||[];renderChatMessages();if($('studioChatState'))$('studioChatState').textContent='연결';if($('viewerChatState'))$('viewerChatState').textContent='연결'}catch{}}
function collaborationPollDelay(kind){if(document.visibilityState==='hidden')return 30000;return kind==='chat'?8000:kind==='approval'?5000:10000}
function startChatPolling(){clearTimeout(state.chatTimer);const poll=async()=>{if(!state.room)return;await refreshChat();state.chatTimer=setTimeout(poll,collaborationPollDelay('chat'))};void poll()}
async function sendChat(inputId,label){const input=$(inputId),message=input?.value?.trim();if(!message||!state.room)return;input.disabled=true;try{await api(`/rooms/${encodeURIComponent(state.room.id)}/chat`,{method:'POST',body:JSON.stringify({message,displayName:label})});input.value='';await refreshChat()}catch(error){note(`채팅 전송 실패: ${error.message}`,inputId.startsWith('viewer')?'viewerStatus':'statusLog')}finally{input.disabled=false;input.focus()}}
function renderParticipationRequests(rows=[]){const root=$('participantRequests');if(!root)return;root.replaceChildren();const pending=rows.filter(r=>r.status==='pending');if(!pending.length){const empty=document.createElement('small');empty.textContent='대기 중인 카메라 참여 요청이 없습니다.';root.append(empty);return}for(const row of pending){const item=document.createElement('div');item.className='participant-request';const name=document.createElement('strong');name.textContent=row.displayName||'참여자';const actions=document.createElement('div'),approve=document.createElement('button'),reject=document.createElement('button');approve.type=reject.type='button';approve.textContent='승인';reject.textContent='거절';approve.addEventListener('click',()=>decideParticipation(row.id,'approved'));reject.addEventListener('click',()=>decideParticipation(row.id,'rejected'));actions.append(approve,reject);item.append(name,actions);root.append(item)}}
async function decideParticipation(id,status){if(!state.room)return;try{await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});await refreshParticipantSources()}catch(error){note(`참여 요청 처리 실패: ${error.message}`)}}
async function ensureParticipantPull(source){const kind=source.sourceRole==='management_camera'?'management_camera':'participant',id=`${kind}:${source.actorKey}`;if(state.participantPulls.has(id))return state.participantPulls.get(id);const created=await api(`/rooms/${encodeURIComponent(state.room.id)}/sessions`,{method:'POST',body:JSON.stringify({role:'viewer'})}),session=created.session,pc=new RTCPeerConnection({iceServers:created.iceServers||[]}),stream=new MediaStream(),label=source.displayName||'참여자 카메라',overlay=ensureOverlay(id,{type:'video',label,stream}),item={id,label,kind,source,session,pc,stream,overlay,ready:false};state.participantPulls.set(id,item);renderSourceCards();pc.ontrack=event=>{for(const track of event.streams?.[0]?.getTracks?.()||[event.track])if(!stream.getTracks().some(x=>x.id===track.id))stream.addTrack(track);item.ready=true;overlay.video?.play?.().catch(()=>{});renderSourceCards()};const pulled=await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/pull`,session.accessKey,{method:'POST',body:JSON.stringify({tracks:(source.tracks||[]).map(track=>({trackName:track.trackName}))})});if(!pulled.empty){const offer=providerDescription(pulled);if(offer?.sdp){await pc.setRemoteDescription(offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitIce(pc);await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/renegotiate`,session.accessKey,{method:'PUT',body:JSON.stringify({sessionDescription:pc.localDescription})})}}return item}
async function refreshParticipantSources(){if(!state.room||!token())return;try{const [requests,sources]=await Promise.all([api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests`),api(`/rooms/${encodeURIComponent(state.room.id)}/participant-sources`)]);renderParticipationRequests(requests.requests||[]);for(const source of (sources.sources||[]).slice(0,8)){const kind=source.sourceRole==='management_camera'?'management_camera':'participant',id=`${kind}:${source.actorKey}`;if(!state.participantPulls.has(id))await ensureParticipantPull(source).catch(()=>{})}renderSourceCards()}catch{}}
function startParticipantMonitoring(){state.participantWatchMode='host';clearTimeout(state.participantTimer);const poll=async()=>{if(!state.room||state.participantWatchMode!=='host')return;await refreshParticipantSources();state.participantTimer=setTimeout(poll,collaborationPollDelay('participant'))};void poll()}
async function requestCameraParticipation(){if(!state.room)return;if(!token())return login();try{await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests`,{method:'POST',body:JSON.stringify({displayName:'참여자'})});if($('participantCameraState'))$('participantCameraState').textContent='승인 대기';startParticipantApprovalPolling()}catch(error){note(`카메라 참여 요청 실패: ${error.message}`,'viewerStatus')}}
function startParticipantApprovalPolling(){state.participantWatchMode='approval';clearTimeout(state.participantTimer);const poll=async()=>{if(!state.room||!token()||state.participantWatchMode!=='approval')return;try{const data=await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-request/me`),status=data.request?.status;if($('participantCameraState'))$('participantCameraState').textContent=status==='approved'?'승인됨':status==='rejected'?'거절됨':status==='pending'?'승인 대기':'대기';if(status==='approved'&&!state.participantPublish)await startParticipantCameraPublish();if(status==='rejected'){state.participantWatchMode='';return}}catch{}state.participantTimer=setTimeout(poll,collaborationPollDelay('approval'))};void poll()}
async function startParticipantCameraPublish(){if(state.participantPublish||!state.room)return;try{const deviceId=$('participantCameraSelect')?.value,speakingLanguage=$('participantSpeakLanguage')?.value||'ko',stream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true}}),preview=$('participantCameraPreview');if(preview){preview.srcObject=stream;preview.classList.remove('hidden');preview.play?.().catch(()=>{})}const created=await api(`/rooms/${encodeURIComponent(state.room.id)}/sessions`,{method:'POST',body:JSON.stringify({role:'presenter'})}),session=created.session,pc=new RTCPeerConnection({iceServers:created.iceServers||[]});for(const track of stream.getTracks())pc.addTrack(track,stream);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const tracks=trackPayload(pc,stream,'camera',speakingLanguage),published=await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/publish`,session.accessKey,{method:'POST',body:JSON.stringify({sessionDescription:pc.localDescription,tracks})}),answer=providerDescription(published);if(!answer?.sdp)throw new Error('media_server_answer_missing');await pc.setRemoteDescription(answer);state.participantPublish={pc,session,stream};if($('participantCameraState'))$('participantCameraState').textContent='카메라 송출 중'}catch(error){if($('participantCameraState'))$('participantCameraState').textContent='연결 실패';note(`카메라 연결 실패: ${error.message}`,'viewerStatus')}}
function cleanupCollaboration(){clearTimeout(state.chatTimer);clearTimeout(state.participantTimer);state.chatTimer=null;state.participantTimer=null;state.participantWatchMode='';for(const item of state.participantPulls.values()){item.pc?.close();item.stream?.getTracks?.().forEach(t=>t.stop());item.overlay?.video?.remove?.()}state.participantPulls.clear();if(state.participantPublish){state.participantPublish.pc?.close();state.participantPublish.stream?.getTracks?.().forEach(t=>t.stop());state.participantPublish=null}}
async function joinViewer(roomId=''){show('viewerView');note('연결 중','viewerStatus');try{let id=roomId;if(!id){const live=await api(`/live?tenant=${encodeURIComponent(cfg.tenant)}`);if(!live.live||!live.room){$('viewerEmpty').textContent='현재 방송 없음';note('현재 방송 없음','viewerStatus');return}id=live.room.id}let detail=await api(`/rooms/${encodeURIComponent(id)}`);state.room=detail.room;state.viewerTracks=detail.tracks||[];renderInterpretationAvailability(state.viewerTracks);$('viewerTitle').textContent=state.room.title||cfg.defaultTitle;startChatPolling();await refreshCameraDevices().catch(()=>{});if(state.room.status!=='live'){note('방송 준비 중','viewerStatus');return}let lastError=null;for(let attempt=0;attempt<5;attempt++){try{const result=await connectViewerMedia(id,state.viewerTracks,state.viewerLanguage);if(result.empty)lastError=new Error('media_tracks_not_ready');else if(result.ok){const translated=state.viewerLanguage!=='original'&&state.viewerTracks.some(track=>(track.source_type||track.sourceType)==='translation'&&String(track.language_code||track.languageCode||'').toLowerCase()===state.viewerLanguage);note(translated?`${LANGUAGE_LABELS[state.viewerLanguage]||state.viewerLanguage} 통역`:(state.viewerLanguage==='original'?'수신 중':'통역 준비 중 · 원음'),'viewerStatus');return}else lastError=new Error('publisher_media_unavailable')}catch(error){lastError=error}if(attempt<4){note('다시 연결 중','viewerStatus');await closeViewerSession();await new Promise(resolve=>setTimeout(resolve,800));detail=await api(`/rooms/${encodeURIComponent(id)}`);state.room=detail.room;state.viewerTracks=detail.tracks||[];renderInterpretationAvailability(state.viewerTracks);if(state.room.status!=='live')throw new Error('broadcast_no_longer_live')}}if(lastError?.message==='media_tracks_not_ready'){$('viewerEmpty').textContent='송출 준비 중';note('송출 준비 중','viewerStatus');return}if(lastError?.message==='publisher_media_unavailable'){$('viewerEmpty').textContent='영상 없음';note('영상 확인 필요','viewerStatus');return}throw lastError}catch(error){note(`연결 실패: ${error.message}`,'viewerStatus')}}
async function switchViewerLanguage(value){state.viewerLanguage=LANGUAGE_LABELS[value]?value:'original';if($('viewerListenLanguage'))$('viewerListenLanguage').value=state.viewerLanguage;if(!state.room){renderInterpretationAvailability(state.viewerTracks);return}try{const detail=await api(`/rooms/${encodeURIComponent(state.room.id)}`);state.viewerTracks=detail.tracks||[];renderInterpretationAvailability(state.viewerTracks);if(state.room.status!=='live')return;await closeViewerSession();const result=await connectViewerMedia(state.room.id,state.viewerTracks,state.viewerLanguage);const translated=state.viewerLanguage!=='original'&&state.viewerTracks.some(track=>(track.source_type||track.sourceType)==='translation'&&String(track.language_code||track.languageCode||'').toLowerCase()===state.viewerLanguage);if(result.ok)note(translated?`${LANGUAGE_LABELS[state.viewerLanguage]} 통역`:(state.viewerLanguage==='original'?'원음':'통역 준비 중 · 원음'),'viewerStatus')}catch(error){note(`언어 전환 실패: ${error.message}`,'viewerStatus')}}
async function refreshLive(){try{const live=await api(`/live?tenant=${encodeURIComponent(cfg.tenant)}`);$('liveState').textContent=live.live?'현재 LIVE':'현재 대기';if(live.live)$('joinButton').textContent='현재 방송 참여하기'}catch{$('liveState').textContent='상태 확인 필요'}}
ensureOverlay('presenter',{type:'video',label:'발표자'});ensureOverlay('chat',{type:'chat',label:'실시간 채팅'});
setupProgramDrop();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'||!state.room)return;startChatPolling();if(state.participantWatchMode==='host')startParticipantMonitoring();else if(state.participantWatchMode==='approval')startParticipantApprovalPolling()});
$('presenterOverlaySource')?.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay','presenter'));
$('presenterOverlaySource')?.addEventListener('click',()=>state.overlays.get('presenter')?.visible?removeOverlay('presenter'):addOverlay('presenter'));
$('chatOverlaySource')?.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay','chat'));
$('chatOverlaySource')?.addEventListener('click',()=>state.overlays.get('chat')?.visible?removeOverlay('chat'):addOverlay('chat'));
$('connectExtraCameraButton')?.addEventListener('click',connectExtraCamera);
$('landscapeButton')?.addEventListener('click',()=>setProgramOrientation('landscape'));
$('portraitButton')?.addEventListener('click',()=>setProgramOrientation('portrait'));
$('cameraFitSelect')?.addEventListener('change',event=>setCameraFit(event.target.value));
$('refreshParticipantSourcesButton')?.addEventListener('click',refreshParticipantSources);
$('studioChatForm')?.addEventListener('submit',event=>{event.preventDefault();void sendChat('studioChatInput','방송자')});
$('viewerChatForm')?.addEventListener('submit',event=>{event.preventDefault();void sendChat('viewerChatInput','참여자')});
$('requestSpeakButton')?.addEventListener('click',requestCameraParticipation);
$('viewerListenLanguage')?.addEventListener('change',event=>void switchViewerLanguage(event.target.value));
$('openManagementCameraButton')?.addEventListener('click',()=>void openManagementCameraDialog());
$('newManagementCameraPairButton')?.addEventListener('click',()=>void createManagementCameraPair());
$('copyManagementCameraUrlButton')?.addEventListener('click',async()=>{const value=$('managementCameraUrl')?.value||'';if(value)await navigator.clipboard?.writeText?.(value);note('QR카메라 링크 복사됨')});
$('managementCameraDialog')?.addEventListener('close',()=>{clearTimeout(state.managementCameraTimer);state.managementCameraTimer=null});
$('managementCameraConnect')?.addEventListener('click',()=>void connectManagementDeviceCamera());
$('managementCameraSwitch')?.addEventListener('click',()=>void switchManagementDeviceCamera());
$('refreshDestinationsButton')?.addEventListener('click',()=>{if(!token())return login();loadExternalDestinations()});
$('hostButton')?.addEventListener('click',prepareStudio);$('joinButton')?.addEventListener('click',()=>joinViewer());$('goLiveButton')?.addEventListener('click',startBroadcast);$('endLiveButton')?.addEventListener('click',endLive);$('screenButton')?.addEventListener('click',shareScreen);$('cameraButton')?.addEventListener('click',async()=>{try{await acquireCamera();await refreshCameraDevices();note('카메라가 준비되었습니다.')}catch(error){note(`카메라 사용 불가: ${error.message}`)}});$('micButton')?.addEventListener('click',()=>{const track=state.local?.getAudioTracks?.()[0];if(!track)return note('먼저 카메라·마이크를 준비해 주세요.');track.enabled=!track.enabled;$('micButton').textContent=track.enabled?'마이크':'마이크 꺼짐'});$('copyLinkButton')?.addEventListener('click',async()=>{await navigator.clipboard?.writeText?.($('shareLink').value);note('참여 링크를 복사했습니다.')});$('openViewerButton')?.addEventListener('click',openViewerWindow);addEventListener('pagehide',hostExitCleanup);addEventListener('beforeunload',event=>{if(!state.hosting||!state.isLive||state.closing)return;event.preventDefault();event.returnValue='' });
window.addEventListener('resize',syncOverlayHandles);
if(cfg.cameraPair){state.managementDeviceKey=managementDeviceKey(cfg.cameraPair);note('대기','managementCameraDeviceStatus');addEventListener('pagehide',()=>{clearTimeout(state.managementCameraTimer);state.managementDevicePc?.close();state.managementDeviceStream?.getTracks?.().forEach(track=>track.stop())})}else{void bootstrapAuthHandoff().catch(error=>note(`로그인 연결 실패: ${error.message}`,'entryNote')).finally(()=>{if(params.get('mode')==='studio')prepareStudio();else if(params.get('room'))joinViewer(params.get('room'));else refreshLive()})}
})();
