(()=>{'use strict';
const API='/api/realtime',SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co',PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_',cfg=document.body.dataset,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),LANDSCAPE={width:1280,height:720},PORTRAIT={width:720,height:1280};
const state={room:null,pc:null,session:null,local:null,screen:null,program:null,canvas:null,ctx:null,canvasStream:null,animationFrame:null,remote:new MediaStream(),hosting:false,isLive:false,closing:false,viewerMutedFallback:false,recording:null,studioPrepared:false,destinationCatalogLoaded:false,overlayDrag:null,overlays:new Map(),extraCameras:new Map(),participantPulls:new Map(),participantPublish:null,presenterHidden:false,chatMessages:[],chatTimer:null,participantTimer:null,participantWatchMode:'',orientation:'landscape',cameraFit:'contain'};
function token(){try{return sessionStorage.getItem('ekodi-auth-token')||''}catch{return''}}
async function bootstrapAuthHandoff(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const tokenHash=hash.get('ekodi_token');if(!tokenHash)return false;history.replaceState(null,'',location.pathname+location.search);const response=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({token_hash:tokenHash,type:hash.get('ekodi_type')||'email'})});const data=await response.json().catch(()=>({}));const access=data?.access_token||data?.session?.access_token||'';if(!response.ok||!access)throw new Error(data?.msg||data?.error_description||'login_handoff_failed');sessionStorage.setItem('ekodi-auth-token',access);return true}
function headers(json=false,session=false){const h=new Headers();if(token())h.set('authorization',`Bearer ${token()}`);if(json)h.set('content-type','application/json');if(session&&state.session?.accessKey)h.set('x-ekodi-session-key',state.session.accessKey);return h}
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:headers(Boolean(options.body),Boolean(options.session)),cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error||`HTTP ${response.status}`);e.status=response.status;e.data=data;throw e}return data}
async function sessionApi(path,accessKey,options={}){const h=headers(Boolean(options.body),false);if(accessKey)h.set('x-ekodi-session-key',accessKey);const response=await fetch(`${API}${path}`,{...options,headers:h,cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error||`HTTP ${response.status}`);e.status=response.status;e.data=data;throw e}return data}
function show(id){for(const key of ['entryView','studioView','viewerView'])$(key)?.classList.add('hidden');$(id)?.classList.remove('hidden')}
function note(message,target='statusLog'){if($(target))$(target).textContent=message}
function login(){const returnTo=location.href;location.href=`/auth/?site=${encodeURIComponent(cfg.authSite||cfg.tenant)}&return_to=${encodeURIComponent(returnTo)}`}
async function waitIce(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const timer=setTimeout(resolve,2500);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve()}},{once:false})})}
function providerDescription(data){return data?.provider?.sessionDescription||data?.provider?.data?.sessionDescription||data?.sessionDescription||null}
function broadcastSelection(){const destinationIds=[...document.querySelectorAll('#externalDestinations input[data-destination]:checked')].map(input=>input.value).filter(Boolean);return {broadcastMode:destinationIds.length?'ekodi+external':'ekodi',destinationIds,multistream:destinationIds.length>0}}
function destinationReason(value){return ({channel_connection_required:'채널 연결 필요',live_provider_not_supported:'실시간 송출 미지원',live_permission_required:'실시간 권한 준비 필요',distribution_engine_pending:'외부 송출 엔진 준비 중'})[value]||'사용 준비 필요'}
function renderExternalDestinations(channels=[]){
  const root=$('externalDestinations');if(!root)return;
  root.replaceChildren();
  if(!channels.length){const empty=document.createElement('small');empty.textContent='연결된 외부 방송 채널이 없습니다. 사이트 관리자에서 채널을 연결한 뒤 다시 확인하세요.';root.append(empty);return}
  for(const channel of channels){
    const label=document.createElement('label');label.className='destination-row';
    const input=document.createElement('input');input.type='checkbox';input.value=channel.id;input.dataset.destination='true';input.disabled=!channel.selectable;
    const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=channel.label||channel.provider;const small=document.createElement('small');small.textContent=channel.selectable?'동시방송 선택 가능':destinationReason(channel.reason);copy.append(strong,small);label.append(input,copy);root.append(label);
  }
}
async function loadExternalDestinations(){
  if(!token()){renderExternalDestinations([]);const root=$('externalDestinations');if(root)root.querySelector('small').textContent='외부 방송 채널은 로그인 후 선택할 수 있습니다.';return false}
  try{const data=await api(`/destinations/catalog?tenant=${encodeURIComponent(cfg.tenant)}`);state.destinationCatalogLoaded=true;renderExternalDestinations(data.channels||[]);return true}
  catch(error){state.destinationCatalogLoaded=false;const root=$('externalDestinations');if(root)root.innerHTML='<small>외부 채널을 불러오지 못했습니다. 내부 방송과 자동 저장은 정상적으로 사용할 수 있습니다.</small>';note(`외부 채널 확인 실패: ${error.message}`);return false}
}
async function createRoom(){const body={tenant:cfg.tenant,mode:cfg.roomMode,title:params.get('title')||cfg.defaultTitle,interactiveParticipants:6,languages:0,durationMinutes:180,recording:true,publicViewers:true,ai:true,...broadcastSelection()};try{return await api('/rooms',{method:'POST',body:JSON.stringify(body)})}catch(error){if(error.status===401){login();return null}if(error.status===402&&error.data?.subscriptionUrl){location.href=error.data.subscriptionUrl;return null}throw error}}
async function createSession(roomId,role){const data=await api(`/rooms/${encodeURIComponent(roomId)}/sessions`,{method:'POST',body:JSON.stringify({role})});state.session=data.session;state.pc=new RTCPeerConnection({iceServers:data.iceServers||[]});state.pc.onconnectionstatechange=()=>{$('connectionState')&&($('connectionState').textContent=state.pc.connectionState)};return data}
function liveRemoteTracks(){return state.remote.getTracks().filter(track=>track.readyState==='live')}
async function waitForRemoteTracks(timeoutMs=5000){if(liveRemoteTracks().length)return liveRemoteTracks();const started=Date.now();while(Date.now()-started<timeoutMs){await new Promise(resolve=>setTimeout(resolve,150));if(liveRemoteTracks().length)return liveRemoteTracks()}return []}
async function closeViewerSession(){const roomId=state.room?.id,session=state.session;if(roomId&&session)await api(`/rooms/${roomId}/sessions/${session.id}/leave`,{method:'POST',session:true,body:'{}'}).catch(()=>{});state.pc?.close();state.pc=null;state.session=null;state.remote.getTracks().forEach(track=>track.stop());state.remote=new MediaStream();if($('viewerVideo'))$('viewerVideo').srcObject=null}
function attachViewerTracks(event){const incoming=event.streams?.length?event.streams.flatMap(stream=>stream.getTracks()):[event.track];for(const track of incoming)if(track&&!state.remote.getTracks().some(item=>item.id===track.id))state.remote.addTrack(track);const video=$('viewerVideo');if(!video)return;video.srcObject=state.remote;$('viewerEmpty')?.classList.add('hidden');video.play?.().catch(error=>{if(error?.name!=='NotAllowedError')return;video.muted=true;state.viewerMutedFallback=true;video.play?.().catch(()=>{})})}
async function connectViewerMedia(id,tracks){await createSession(id,'viewer');state.pc.ontrack=attachViewerTracks;const pulled=await api(`/rooms/${id}/sessions/${state.session.id}/pull`,{method:'POST',session:true,body:JSON.stringify({tracks:(tracks||[]).map(track=>({trackName:track.track_name||track.trackName}))})});if(pulled.empty)return {ok:false,empty:true};const offer=providerDescription(pulled);if(!offer?.sdp)throw new Error('media_server_offer_missing');await state.pc.setRemoteDescription(offer);const answer=await state.pc.createAnswer();await state.pc.setLocalDescription(answer);await waitIce(state.pc);await api(`/rooms/${id}/sessions/${state.session.id}/renegotiate`,{method:'PUT',session:true,body:JSON.stringify({sessionDescription:state.pc.localDescription})});const received=await waitForRemoteTracks();return {ok:received.length>0,empty:false,received:received.length}}
function openViewerWindow(){const url=$('shareLink')?.value;if(!url)return note('먼저 방송을 준비해 주세요.');const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';document.body.appendChild(link);link.click();link.remove();note('시청 화면을 새 탭으로 열었습니다. 송출 스튜디오는 그대로 유지합니다.')}
function hostExitCleanup(){if(!state.hosting||!state.isLive||state.closing||!state.room)return;state.isLive=false;const roomId=encodeURIComponent(state.room.id);if(state.session)fetch(`${API}/rooms/${roomId}/sessions/${state.session.id}/leave`,{method:'POST',headers:headers(true,true),body:'{}',keepalive:true,cache:'no-store'}).catch(()=>{});fetch(`${API}/rooms/${roomId}/status`,{method:'POST',headers:headers(true,false),body:JSON.stringify({status:'ended'}),keepalive:true,cache:'no-store'}).catch(()=>{})}
function setSourceVideo(id,stream){const video=$(id);if(!video)return;video.srcObject=stream;video.play?.().catch(()=>{})}
function drawContained(ctx,video,x,y,w,h){ctx.fillStyle='#090b0a';ctx.fillRect(x,y,w,h);if(!video?.videoWidth||!video?.videoHeight)return;const scale=Math.min(w/video.videoWidth,h/video.videoHeight),dw=video.videoWidth*scale,dh=video.videoHeight*scale;ctx.drawImage(video,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function drawCovered(ctx,video,x,y,w,h){if(!video?.videoWidth||!video?.videoHeight){ctx.fillStyle='#142019';ctx.fillRect(x,y,w,h);return}const scale=Math.max(w/video.videoWidth,h/video.videoHeight),sw=w/scale,sh=h/scale,sx=(video.videoWidth-sw)/2,sy=(video.videoHeight-sh)/2;ctx.drawImage(video,sx,sy,sw,sh,x,y,w,h)}
function programBox(){const stage=$('programStage');if(!stage)return null;const rect=stage.getBoundingClientRect();if(!rect.width||!rect.height)return null;const target=state.canvas?state.canvas.width/state.canvas.height:16/9;let width=rect.width,height=rect.height,left=0,top=0;if(width/height>target){width=height*target;left=(rect.width-width)/2}else if(width/height<target){height=width/target;top=(rect.height-height)/2}return {rect,left,top,width,height}}
function overlayDefaults(type,index=0){const video=type!=='chat';return {x:Math.min(.72,.04+(index%3)*.29),y:Math.min(.72,.08+Math.floor(index/3)*.22),w:video ? .26 : .34,h:video ? .146 : .38}}
function createOverlayVideo(stream,id){const video=document.createElement('video');video.className='source-video';video.autoplay=true;video.playsInline=true;video.muted=true;video.srcObject=stream;video.dataset.overlayVideo=id;$('programStage')?.append(video);video.play?.().catch(()=>{});return video}
function ensureOverlay(id,{type='video',label='소스',stream=null}={}){let overlay=state.overlays.get(id);if(!overlay){overlay={id,type,label,visible:false,...overlayDefaults(type,state.overlays.size),stream:null,video:null};state.overlays.set(id,overlay)}overlay.label=label||overlay.label;overlay.type=type;if(stream&&overlay.stream!==stream){overlay.stream=stream;overlay.video?.remove?.();overlay.video=createOverlayVideo(stream,id)}syncOverlayHandles();return overlay}
function overlayHandle(id){const layer=$('programOverlayLayer');if(!layer)return null;let h=[...layer.querySelectorAll('[data-program-overlay]')].find(node=>node.dataset.programOverlay===id);if(h)return h;const overlay=state.overlays.get(id);if(!overlay)return null;h=document.createElement('div');h.className='program-drag-handle';h.dataset.programOverlay=id;const label=document.createElement('span');label.textContent=overlay.label;const close=document.createElement('button');close.type='button';close.className='overlay-remove';close.textContent='×';close.addEventListener('click',event=>{event.stopPropagation();removeOverlay(id)});h.append(label,close);layer.append(h);h.addEventListener('pointerdown',beginOverlayDrag);h.addEventListener('pointermove',moveOverlayDrag);h.addEventListener('pointerup',endOverlayDrag);h.addEventListener('pointercancel',endOverlayDrag);return h}
function syncOverlayHandles(){const box=programBox();if(!box)return;for(const overlay of state.overlays.values()){const h=overlayHandle(overlay.id);if(!h)continue;h.classList.toggle('hidden',!overlay.visible);if(!overlay.visible)continue;h.style.left=`${box.left+overlay.x*box.width}px`;h.style.top=`${box.top+overlay.y*box.height}px`;h.style.width=`${overlay.w*box.width}px`;h.style.height=`${overlay.h*box.height}px`;h.querySelector('span').textContent=overlay.label}}
function addOverlay(id){const overlay=state.overlays.get(id);if(!overlay)return;if(id==='presenter'){if(!state.screen)return note('발표자는 화면공유 중에 방송화면에 추가할 수 있습니다.');state.presenterHidden=false}overlay.visible=true;syncOverlayHandles();renderSourceCards()}
function removeOverlay(id){const overlay=state.overlays.get(id);if(!overlay)return;if(id==='presenter')state.presenterHidden=true;overlay.visible=false;syncOverlayHandles();renderSourceCards()}
function beginOverlayDrag(event){if(event.target.closest('.overlay-remove'))return;const id=event.currentTarget.dataset.programOverlay,overlay=state.overlays.get(id),box=programBox();if(!overlay||!box)return;const rect=event.currentTarget.getBoundingClientRect();state.overlayDrag={id,pointerId:event.pointerId,offsetX:event.clientX-rect.left,offsetY:event.clientY-rect.top};event.currentTarget.setPointerCapture?.(event.pointerId);event.currentTarget.classList.add('dragging');event.preventDefault()}
function moveOverlayDrag(event){const drag=state.overlayDrag;if(!drag||drag.pointerId!==event.pointerId)return;const overlay=state.overlays.get(drag.id),box=programBox();if(!overlay||!box)return;const left=box.rect.left+box.left,top=box.rect.top+box.top;overlay.x=Math.max(0,Math.min(1-overlay.w,(event.clientX-left-drag.offsetX)/box.width));overlay.y=Math.max(0,Math.min(1-overlay.h,(event.clientY-top-drag.offsetY)/box.height));syncOverlayHandles()}
function endOverlayDrag(event){if(!state.overlayDrag||state.overlayDrag.pointerId!==event.pointerId)return;event.currentTarget.classList.remove('dragging');state.overlayDrag=null}
function drawChatOverlay(ctx,overlay,w,h){const x=Math.round(overlay.x*w),y=Math.round(overlay.y*h),ow=Math.round(overlay.w*w),oh=Math.round(overlay.h*h);ctx.save();ctx.fillStyle='rgba(16,21,18,.82)';ctx.fillRect(x,y,ow,oh);ctx.fillStyle='#fff';ctx.font='700 20px sans-serif';ctx.fillText('실시간 채팅',x+16,y+28);let line=y+58;for(const row of state.chatMessages.slice(-6)){ctx.fillStyle='#b9d1c1';ctx.font='700 14px sans-serif';ctx.fillText(String(row.displayName||'참여자').slice(0,16),x+16,line);ctx.fillStyle='#fff';ctx.font='500 16px sans-serif';let text=String(row.message||'').slice(0,70);while(ctx.measureText(text).width>ow-32&&text.length>4)text=text.slice(0,-2);ctx.fillText(text,x+16,line+20);line+=46;if(line>y+oh-18)break}ctx.restore()}
function drawOverlays(ctx,w,h){for(const overlay of state.overlays.values()){if(!overlay.visible)continue;if(overlay.type==='chat'){drawChatOverlay(ctx,overlay,w,h);continue}if(!overlay.video?.videoWidth)continue;const x=Math.round(overlay.x*w),y=Math.round(overlay.y*h),ow=Math.round(overlay.w*w),oh=Math.round(overlay.h*h);ctx.fillStyle='#f6f1e8';ctx.fillRect(x-3,y-3,ow+6,oh+6);drawCovered(ctx,overlay.video,x,y,ow,oh)}}
function drawProgram(){if(!state.ctx||!state.canvas)return;const ctx=state.ctx,w=state.canvas.width,h=state.canvas.height,camera=$('cameraSource'),screen=$('screenSource');ctx.fillStyle='#090b0a';ctx.fillRect(0,0,w,h);if(state.screen&&screen?.videoWidth){drawContained(ctx,screen,0,0,w,h);const presenter=ensureOverlay('presenter',{type:'video',label:'발표자',stream:state.local});presenter.visible=!state.presenterHidden}else{(state.cameraFit==='cover'?drawCovered:drawContained)(ctx,camera,0,0,w,h);const presenter=state.overlays.get('presenter');if(presenter)presenter.visible=false}drawOverlays(ctx,w,h);syncOverlayHandles();state.animationFrame=requestAnimationFrame(drawProgram)}
function ensureProgram(){if(state.program)return state.program;const canvas=document.createElement('canvas');const size=state.orientation==='portrait'?PORTRAIT:LANDSCAPE;canvas.width=size.width;canvas.height=size.height;state.canvas=canvas;state.ctx=canvas.getContext('2d',{alpha:false});if(typeof canvas.captureStream!=='function'){state.program=state.local;$('mainVideo').srcObject=state.local;return state.program}state.canvasStream=canvas.captureStream(30);state.program=new MediaStream([...state.canvasStream.getVideoTracks(),...state.local.getAudioTracks()]);$('mainVideo').srcObject=state.program;$('mainVideo').play?.().catch(()=>{});drawProgram();return state.program}
function setProgramOrientation(value){state.orientation=value==='portrait'?'portrait':'landscape';if(state.canvas){const size=state.orientation==='portrait'?PORTRAIT:LANDSCAPE;state.canvas.width=size.width;state.canvas.height=size.height}const stage=$('programStage');stage?.classList.toggle('portrait',state.orientation==='portrait');for(const [id,pressed] of [['landscapeButton',state.orientation==='landscape'],['portraitButton',state.orientation==='portrait']]){const button=$(id);if(button){button.classList.toggle('active',pressed);button.setAttribute('aria-pressed',String(pressed))}}syncOverlayHandles();note(state.orientation==='portrait'?'세로 9:16 방송 화면으로 전환했습니다.':'가로 16:9 방송 화면으로 전환했습니다.')}
function setCameraFit(value){state.cameraFit=value==='cover'?'cover':'contain';note(state.cameraFit==='contain'?'카메라를 맞춤 표시합니다. 주변이 잘리지 않습니다.':'카메라를 화면에 꽉 채워 표시합니다.')}
async function acquireCamera(){if(state.local)return state.local;const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true}});state.local=stream;setSourceVideo('cameraSource',stream);$('programPlaceholder')?.classList.add('hidden');ensureProgram();return stream}
function sourceCard(id,label,{subtitle='화면에 추가',onDelete=null}={}){
  const card=document.createElement('div');card.className='source-card-row';card.draggable=true;card.dataset.overlayId=id;
  const copy=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=label;small.textContent=subtitle;copy.append(strong,small);
  const add=document.createElement('button');add.type='button';add.textContent=state.overlays.get(id)?.visible?'화면에서 빼기':'추가';add.addEventListener('click',()=>state.overlays.get(id)?.visible?removeOverlay(id):addOverlay(id));card.append(copy,add);
  if(onDelete){const del=document.createElement('button');del.type='button';del.className='source-delete';del.textContent='연결 해제';del.addEventListener('click',onDelete);card.append(del)}
  card.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay',id));return card;
}
function renderSourceCards(){
  const presenter=$('presenterOverlaySource');if(presenter){const active=state.overlays.get('presenter')?.visible;presenter.querySelector('span').textContent=active?'화면에서 빼기':'화면공유 중 추가';presenter.classList.toggle('active',Boolean(active))}
  const chat=$('chatOverlaySource');if(chat){const active=state.overlays.get('chat')?.visible;chat.querySelector('span').textContent=active?'화면에서 빼기':'화면에 추가';chat.classList.toggle('active',Boolean(active))}
  const cameras=$('extraCameraSources');if(cameras){cameras.replaceChildren();for(const [id,item] of state.extraCameras)cameras.append(sourceCard(id,item.label,{onDelete:()=>disconnectExtraCamera(id)}))}
  const participants=$('participantSources');if(participants){participants.replaceChildren();for(const [id,item] of state.participantPulls)participants.append(sourceCard(id,item.label,{subtitle:item.ready?'화면에 추가':'연결 중'}))}
}
async function refreshCameraDevices(){
  if(!navigator.mediaDevices?.enumerateDevices)return;const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput'),primary=state.local?.getVideoTracks?.()[0]?.getSettings?.().deviceId||'';
  for(const select of [$('extraCameraSelect'),$('participantCameraSelect')].filter(Boolean)){const selected=select.value;select.replaceChildren(new Option(select.id==='extraCameraSelect'?'추가 카메라 선택':'카메라 선택',''));for(const [i,d] of devices.entries()){if(select.id==='extraCameraSelect'&&d.deviceId===primary)continue;select.append(new Option(d.label||`카메라 ${i+1}`,d.deviceId))}if([...select.options].some(o=>o.value===selected))select.value=selected}
}
async function connectExtraCamera(){const deviceId=$('extraCameraSelect')?.value;if(!deviceId)return note('추가할 카메라를 선택해 주세요.');const existing=[...state.extraCameras.values()].find(item=>item.deviceId===deviceId);if(existing){addOverlay(existing.id);return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}},audio:false}),label=$('extraCameraSelect').selectedOptions?.[0]?.textContent||'추가 카메라',id=`camera:${crypto.randomUUID()}`,overlay=ensureOverlay(id,{type:'video',label,stream});state.extraCameras.set(id,{id,deviceId,label,stream,overlay});renderSourceCards();note(`${label} 연결 완료. 끌어서 방송화면에 추가할 수 있습니다.`)}catch(error){note(`추가 카메라 연결 실패: ${error.message}`)}}
function disconnectExtraCamera(id){const item=state.extraCameras.get(id);if(!item)return;item.stream.getTracks().forEach(t=>t.stop());item.overlay?.video?.remove?.();state.extraCameras.delete(id);state.overlays.delete(id);syncOverlayHandles();renderSourceCards()}
function setupProgramDrop(){const stage=$('programStage');if(!stage)return;stage.addEventListener('dragover',event=>{if(event.dataTransfer?.types?.includes('text/ekodi-overlay')){event.preventDefault();stage.classList.add('drop-ready')}});stage.addEventListener('dragleave',()=>stage.classList.remove('drop-ready'));stage.addEventListener('drop',event=>{event.preventDefault();stage.classList.remove('drop-ready');const id=event.dataTransfer?.getData('text/ekodi-overlay');if(id)addOverlay(id)})}
function trackPayload(pc,stream,source='camera'){return pc.getTransceivers().filter(t=>t.sender?.track&&stream.getTracks().includes(t.sender.track)).map((t,index)=>({mid:t.mid,trackName:`${source}-${t.sender.track.kind}-${Date.now()}-${index}`,kind:t.sender.track.kind,sourceType:t.sender.track.kind==='audio'?'microphone':source}))}
async function publishStream(stream,source='camera'){for(const track of stream.getTracks())state.pc.addTrack(track,stream);const offer=await state.pc.createOffer();await state.pc.setLocalDescription(offer);await waitIce(state.pc);const tracks=trackPayload(state.pc,stream,source);if(tracks.some(t=>!t.mid))throw new Error('media_negotiation_not_ready');const data=await api(`/rooms/${state.room.id}/sessions/${state.session.id}/publish`,{method:'POST',session:true,body:JSON.stringify({sessionDescription:state.pc.localDescription,tracks})});const answer=providerDescription(data);if(!answer?.sdp)throw new Error('media_server_answer_missing');await state.pc.setRemoteDescription(answer)}

const RECORD_PART_TARGET=6*1024*1024;
function recordingMime(){for(const type of ['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'])if(globalThis.MediaRecorder?.isTypeSupported?.(type))return type;return 'video/webm'}
async function uploadRecordingBlob(rec,blob){
  const part=rec.part++;
  const response=await fetch(`${API}/rooms/${encodeURIComponent(state.room.id)}/recordings/${encodeURIComponent(rec.id)}/parts/${part}`,{method:'PUT',headers:{authorization:`Bearer ${token()}`,'content-type':rec.mime},body:blob});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`recording_part_${response.status}`);return data;
}
function flushRecordingPart(rec,force=false){
  if(!rec||!rec.pending.length||(!force&&rec.pendingBytes<RECORD_PART_TARGET))return;
  const blob=new Blob(rec.pending,{type:rec.mime});rec.pending=[];rec.pendingBytes=0;
  rec.queue=rec.queue.then(()=>uploadRecordingBlob(rec,blob)).catch(error=>{rec.failed=true;note(`녹화 저장 지연: ${error.message}. 방송은 계속됩니다.`)});
}
async function startRecording(){
  if(!state.room||!(state.program||state.local)||!globalThis.MediaRecorder)return false;
  try{
    const mime=recordingMime(),created=await api(`/rooms/${state.room.id}/recordings`,{method:'POST',body:JSON.stringify({mimeType:mime,title:state.room.title,retentionDays:180})});
    const rec={id:created.recording.id,mime,part:1,pending:[],pendingBytes:0,queue:Promise.resolve(),failed:false,media:null};
    const media=new MediaRecorder(state.program||state.local,{mimeType:mime});rec.media=media;state.recording=rec;
    media.ondataavailable=event=>{if(!event.data?.size)return;rec.pending.push(event.data);rec.pendingBytes+=event.data.size;flushRecordingPart(rec,false)};
    media.onerror=event=>{rec.failed=true;note(`녹화 오류: ${event.error?.message||'recording_error'}. 방송은 계속됩니다.`)};
    media.start(5000);note('방송 중입니다. 녹화본은 R2에 안전하게 기록한 뒤 공유드라이브로 보관합니다.');return true;
  }catch(error){note(`방송은 시작됐지만 녹화 준비에 실패했습니다: ${error.message}`);return false}
}
async function stopRecording(){
  const rec=state.recording;if(!rec)return null;
  if(rec.media?.state!=='inactive')await new Promise(resolve=>{rec.media.addEventListener('stop',resolve,{once:true});rec.media.stop()});
  flushRecordingPart(rec,true);await rec.queue;
  try{
    if(rec.failed){await api(`/rooms/${state.room.id}/recordings/${rec.id}/abort`,{method:'POST',body:'{}'}).catch(()=>{});return null}
    const done=await api(`/rooms/${state.room.id}/recordings/${rec.id}/finalize`,{method:'POST',body:'{}'});
    note(done.archive?.ok?'방송 종료 · 녹화본 공유드라이브 보관 완료':'방송 종료 · 녹화본 저장 완료, 공유드라이브 보관 대기');return done;
  }catch(error){note(`방송은 종료됐지만 녹화 확정에 실패했습니다: ${error.message}`);return null}
  finally{state.recording=null}
}
async function prepareStudio(){show('studioView');note('카메라·마이크와 송출 채널을 준비하고 있습니다.');try{await acquireCamera();await refreshCameraDevices();state.studioPrepared=true;$('goLiveButton').disabled=false;await loadExternalDestinations();note(token()?'준비 완료. 내부 방송·자동 저장은 기본이며, 필요하면 외부 채널을 선택한 뒤 방송을 시작하세요.':'준비 완료. 내부 방송·자동 저장은 기본입니다. 외부 채널 선택은 로그인 후 사용할 수 있습니다.');return true}catch(error){state.studioPrepared=false;$('goLiveButton').disabled=true;note(`방송 준비 실패: ${error.message}`);return false}}
async function startHost(){if(state.room&&state.session&&state.pc)return true;if(state.hosting)return false;state.hosting=true;show('studioView');note('방송 서버에 연결하고 있습니다.');try{const created=await createRoom();if(!created){state.hosting=false;return false}state.room=created.room;$('roomTitle').textContent=state.room.title;$('shareLink').value=`${location.origin}${cfg.livePath}?room=${encodeURIComponent(state.room.id)}`;$('roomLinks').classList.remove('hidden');const stream=state.local||await acquireCamera();const program=ensureProgram()||stream;await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'starting'})});await createSession(state.room.id,'owner');await publishStream(program,'program');startChatPolling();startParticipantMonitoring();note('미디어 연결 완료. 내부 녹화는 방송 시작과 함께 자동 실행됩니다.');return true}catch(error){state.hosting=false;$('goLiveButton').disabled=false;note(`방송 준비 실패: ${error.message}`);return false}}
async function goLive(){if(!state.room)return;try{await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'live'})});state.isLive=true;$('programBadge').textContent='LIVE';$('liveState').textContent='방송 중';$('goLiveButton').disabled=true;$('endLiveButton').disabled=false;note('방송 중입니다. 내부 녹화를 자동 시작합니다. 시청 화면은 새 탭으로 열어 주세요.');await startRecording()}catch(error){$('goLiveButton').disabled=false;note(`방송 시작 실패: ${error.message}`)}}
async function startBroadcast(){if(!state.studioPrepared){const prepared=await prepareStudio();if(!prepared)return}if(!token())return login();$('goLiveButton').disabled=true;const ready=await startHost();if(!ready){$('goLiveButton').disabled=false;return}await goLive()}
async function endLive(){if(!state.room)return;state.closing=true;try{await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'ending'})});await stopRecording();if(state.session)await api(`/rooms/${state.room.id}/sessions/${state.session.id}/leave`,{method:'POST',session:true,body:'{}'}).catch(()=>{});state.pc?.close();cleanupCollaboration();for(const id of [...state.extraCameras.keys()])disconnectExtraCamera(id);state.local?.getTracks().forEach(t=>t.stop());state.screen?.getTracks().forEach(t=>t.stop());state.canvasStream?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(state.animationFrame);await api(`/rooms/${state.room.id}/status`,{method:'POST',body:JSON.stringify({status:'ended'})});state.isLive=false;$('programBadge').textContent='종료';$('endLiveButton').disabled=true;if(!state.recording)note('방송이 종료되었습니다.')}catch(error){note(`방송 종료 처리 실패: ${error.message}`)}finally{state.closing=false}}
async function shareScreen(){if(!state.local)return note('먼저 카메라를 준비해 주세요.');if(state.screen){state.screen.getTracks().forEach(track=>track.stop());state.screen=null;setSourceVideo('screenSource',null);state.presenterHidden=false;removeOverlay('presenter');return note('화면공유를 종료했습니다.')}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});state.screen=stream;state.presenterHidden=false;setSourceVideo('screenSource',stream);const presenter=ensureOverlay('presenter',{type:'video',label:'발표자',stream:state.local});presenter.visible=true;syncOverlayHandles();renderSourceCards();stream.getVideoTracks()[0]?.addEventListener('ended',()=>{state.screen=null;state.presenterHidden=false;setSourceVideo('screenSource',null);removeOverlay('presenter')},{once:true});note('화면공유를 방송 화면에 합성했습니다. 발표자 위치를 자유롭게 이동할 수 있습니다.')}catch(error){if(error.name!=='NotAllowedError')note(`화면공유 실패: ${error.message}`)}}
function renderChatMessages(){for(const id of ['studioChatMessages','viewerChatMessages']){const root=$(id);if(!root)continue;root.replaceChildren();for(const row of state.chatMessages.slice(-80)){const item=document.createElement('div');item.className='chat-message';const meta=document.createElement('span');meta.textContent=row.displayName||'참여자';const p=document.createElement('p');p.textContent=row.message||'';item.append(meta,p);root.append(item)}root.scrollTop=root.scrollHeight}}
async function refreshChat(){if(!state.room)return;try{const data=await api(`/rooms/${encodeURIComponent(state.room.id)}/chat`);state.chatMessages=data.messages||[];renderChatMessages();if($('studioChatState'))$('studioChatState').textContent='연결';if($('viewerChatState'))$('viewerChatState').textContent='연결'}catch{}}
function collaborationPollDelay(kind){if(document.visibilityState==='hidden')return 30000;return kind==='chat'?8000:kind==='approval'?5000:10000}
function startChatPolling(){clearTimeout(state.chatTimer);const poll=async()=>{if(!state.room)return;await refreshChat();state.chatTimer=setTimeout(poll,collaborationPollDelay('chat'))};void poll()}
async function sendChat(inputId,label){const input=$(inputId),message=input?.value?.trim();if(!message||!state.room)return;input.disabled=true;try{await api(`/rooms/${encodeURIComponent(state.room.id)}/chat`,{method:'POST',body:JSON.stringify({message,displayName:label})});input.value='';await refreshChat()}catch(error){note(`채팅 전송 실패: ${error.message}`,inputId.startsWith('viewer')?'viewerStatus':'statusLog')}finally{input.disabled=false;input.focus()}}
function renderParticipationRequests(rows=[]){const root=$('participantRequests');if(!root)return;root.replaceChildren();const pending=rows.filter(r=>r.status==='pending');if(!pending.length){const empty=document.createElement('small');empty.textContent='대기 중인 카메라 참여 요청이 없습니다.';root.append(empty);return}for(const row of pending){const item=document.createElement('div');item.className='participant-request';const name=document.createElement('strong');name.textContent=row.displayName||'참여자';const actions=document.createElement('div'),approve=document.createElement('button'),reject=document.createElement('button');approve.type=reject.type='button';approve.textContent='승인';reject.textContent='거절';approve.addEventListener('click',()=>decideParticipation(row.id,'approved'));reject.addEventListener('click',()=>decideParticipation(row.id,'rejected'));actions.append(approve,reject);item.append(name,actions);root.append(item)}}
async function decideParticipation(id,status){if(!state.room)return;try{await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});await refreshParticipantSources()}catch(error){note(`참여 요청 처리 실패: ${error.message}`)}}
async function ensureParticipantPull(source){const id=`participant:${source.actorKey}`;if(state.participantPulls.has(id))return state.participantPulls.get(id);const created=await api(`/rooms/${encodeURIComponent(state.room.id)}/sessions`,{method:'POST',body:JSON.stringify({role:'viewer'})}),session=created.session,pc=new RTCPeerConnection({iceServers:created.iceServers||[]}),stream=new MediaStream(),label=source.displayName||'참여자 카메라',overlay=ensureOverlay(id,{type:'video',label,stream}),item={id,label,source,session,pc,stream,overlay,ready:false};state.participantPulls.set(id,item);renderSourceCards();pc.ontrack=event=>{for(const track of event.streams?.[0]?.getTracks?.()||[event.track])if(!stream.getTracks().some(x=>x.id===track.id))stream.addTrack(track);item.ready=true;overlay.video?.play?.().catch(()=>{});renderSourceCards()};const pulled=await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/pull`,session.accessKey,{method:'POST',body:JSON.stringify({tracks:(source.tracks||[]).map(track=>({trackName:track.trackName}))})});if(!pulled.empty){const offer=providerDescription(pulled);if(offer?.sdp){await pc.setRemoteDescription(offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitIce(pc);await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/renegotiate`,session.accessKey,{method:'PUT',body:JSON.stringify({sessionDescription:pc.localDescription})})}}return item}
async function refreshParticipantSources(){if(!state.room||!token())return;try{const [requests,sources]=await Promise.all([api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests`),api(`/rooms/${encodeURIComponent(state.room.id)}/participant-sources`)]);renderParticipationRequests(requests.requests||[]);for(const source of (sources.sources||[]).slice(0,6))if(!state.participantPulls.has(`participant:${source.actorKey}`))await ensureParticipantPull(source).catch(()=>{});renderSourceCards()}catch{}}
function startParticipantMonitoring(){state.participantWatchMode='host';clearTimeout(state.participantTimer);const poll=async()=>{if(!state.room||state.participantWatchMode!=='host')return;await refreshParticipantSources();state.participantTimer=setTimeout(poll,collaborationPollDelay('participant'))};void poll()}
async function requestCameraParticipation(){if(!state.room)return;if(!token())return login();try{await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-requests`,{method:'POST',body:JSON.stringify({displayName:'참여자'})});if($('participantCameraState'))$('participantCameraState').textContent='승인 대기';startParticipantApprovalPolling()}catch(error){note(`카메라 참여 요청 실패: ${error.message}`,'viewerStatus')}}
function startParticipantApprovalPolling(){state.participantWatchMode='approval';clearTimeout(state.participantTimer);const poll=async()=>{if(!state.room||!token()||state.participantWatchMode!=='approval')return;try{const data=await api(`/rooms/${encodeURIComponent(state.room.id)}/participation-request/me`),status=data.request?.status;if($('participantCameraState'))$('participantCameraState').textContent=status==='approved'?'승인됨':status==='rejected'?'거절됨':status==='pending'?'승인 대기':'대기';if(status==='approved'&&!state.participantPublish)await startParticipantCameraPublish();if(status==='rejected'){state.participantWatchMode='';return}}catch{}state.participantTimer=setTimeout(poll,collaborationPollDelay('approval'))};void poll()}
async function startParticipantCameraPublish(){if(state.participantPublish||!state.room)return;try{const deviceId=$('participantCameraSelect')?.value,stream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{width:{ideal:1280},height:{ideal:720}},audio:false}),preview=$('participantCameraPreview');if(preview){preview.srcObject=stream;preview.classList.remove('hidden');preview.play?.().catch(()=>{})}const created=await api(`/rooms/${encodeURIComponent(state.room.id)}/sessions`,{method:'POST',body:JSON.stringify({role:'presenter'})}),session=created.session,pc=new RTCPeerConnection({iceServers:created.iceServers||[]});for(const track of stream.getTracks())pc.addTrack(track,stream);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const tracks=trackPayload(pc,stream,'camera'),published=await sessionApi(`/rooms/${encodeURIComponent(state.room.id)}/sessions/${encodeURIComponent(session.id)}/publish`,session.accessKey,{method:'POST',body:JSON.stringify({sessionDescription:pc.localDescription,tracks})}),answer=providerDescription(published);if(!answer?.sdp)throw new Error('media_server_answer_missing');await pc.setRemoteDescription(answer);state.participantPublish={pc,session,stream};if($('participantCameraState'))$('participantCameraState').textContent='카메라 송출 중'}catch(error){if($('participantCameraState'))$('participantCameraState').textContent='연결 실패';note(`카메라 연결 실패: ${error.message}`,'viewerStatus')}}
function cleanupCollaboration(){clearTimeout(state.chatTimer);clearTimeout(state.participantTimer);state.chatTimer=null;state.participantTimer=null;state.participantWatchMode='';for(const item of state.participantPulls.values()){item.pc?.close();item.stream?.getTracks?.().forEach(t=>t.stop());item.overlay?.video?.remove?.()}state.participantPulls.clear();if(state.participantPublish){state.participantPublish.pc?.close();state.participantPublish.stream?.getTracks?.().forEach(t=>t.stop());state.participantPublish=null}}
async function joinViewer(roomId=''){show('viewerView');note('현재 방송을 찾고 있습니다.','viewerStatus');try{let id=roomId;if(!id){const live=await api(`/live?tenant=${encodeURIComponent(cfg.tenant)}`);if(!live.live||!live.room){$('viewerEmpty').textContent='현재 진행 중인 공개 방송이 없습니다.';note('현재 생방송이 없습니다.','viewerStatus');return}id=live.room.id}let detail=await api(`/rooms/${encodeURIComponent(id)}`);state.room=detail.room;$('viewerTitle').textContent=state.room.title||cfg.defaultTitle;startChatPolling();await refreshCameraDevices().catch(()=>{});if(state.room.status!=='live'){note('방송은 아직 공개 시작 전입니다. 잠시 후 다시 참여해 주세요.','viewerStatus');return}let lastError=null;for(let attempt=0;attempt<5;attempt++){try{const result=await connectViewerMedia(id,detail.tracks||[]);if(result.empty)lastError=new Error('media_tracks_not_ready');else if(result.ok){note(state.viewerMutedFallback?'실시간 영상 수신 중입니다. 소리는 플레이어에서 음소거를 해제해 주세요.':'실시간 방송 수신 중입니다.','viewerStatus');return}else lastError=new Error('publisher_media_unavailable')}catch(error){lastError=error}if(attempt<4){note(lastError?.message==='media_tracks_not_ready'?'송출 트랙을 기다리고 있습니다. 자동으로 다시 연결합니다.':'영상 수신을 다시 연결하고 있습니다.','viewerStatus');await closeViewerSession();await new Promise(resolve=>setTimeout(resolve,800));detail=await api(`/rooms/${encodeURIComponent(id)}`);state.room=detail.room;if(state.room.status!=='live')throw new Error('broadcast_no_longer_live')}}if(lastError?.message==='media_tracks_not_ready'){note('송출 트랙 준비가 지연되고 있습니다. 잠시 후 다시 참여해 주세요.','viewerStatus');$('viewerEmpty').textContent='송출 준비 지연';return}if(lastError?.message==='publisher_media_unavailable'){note('송출 영상이 도착하지 않습니다. 방송자 스튜디오가 열려 있는지 확인한 뒤 다시 참여해 주세요.','viewerStatus');$('viewerEmpty').textContent='송출 영상 없음';return}throw lastError}catch(error){note(`참여 연결 실패: ${error.message}`,'viewerStatus')}}
async function refreshLive(){try{const live=await api(`/live?tenant=${encodeURIComponent(cfg.tenant)}`);$('liveState').textContent=live.live?'현재 LIVE':'현재 대기';if(live.live)$('joinButton').textContent='현재 방송 참여하기'}catch{$('liveState').textContent='상태 확인 필요'}}
ensureOverlay('presenter',{type:'video',label:'발표자'});ensureOverlay('chat',{type:'chat',label:'실시간 채팅'});
setupProgramDrop();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'||!state.room)return;startChatPolling();if(state.participantWatchMode==='host')startParticipantMonitoring();else if(state.participantWatchMode==='approval')startParticipantApprovalPolling()});
$('presenterOverlaySource')?.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay','presenter'));
$('presenterOverlaySource')?.addEventListener('click',()=>state.overlays.get('presenter')?.visible?removeOverlay('presenter'):addOverlay('presenter'));
$('chatOverlaySource')?.addEventListener('dragstart',event=>event.dataTransfer?.setData('text/ekodi-overlay','chat'));
$('chatOverlaySource')?.addEventListener('click',()=>state.overlays.get('chat')?.visible?removeOverlay('chat'):addOverlay('chat'));
$('connectExtraCameraButton')?.addEventListener('click',connectExtraCamera);
$('landscapeButton')?.addEventListener('click',()=>setProgramOrientation('landscape'));
$('portraitButton')?.addEventListener('click',()=>setProgramOrientation('portrait'));
$('cameraFitSelect')?.addEventListener('change',event=>setCameraFit(event.target.value));
$('refreshParticipantSourcesButton')?.addEventListener('click',refreshParticipantSources);
$('studioChatForm')?.addEventListener('submit',event=>{event.preventDefault();void sendChat('studioChatInput','방송자')});
$('viewerChatForm')?.addEventListener('submit',event=>{event.preventDefault();void sendChat('viewerChatInput','참여자')});
$('requestSpeakButton')?.addEventListener('click',requestCameraParticipation);
$('refreshDestinationsButton')?.addEventListener('click',()=>{if(!token())return login();loadExternalDestinations()});
$('hostButton')?.addEventListener('click',prepareStudio);$('joinButton')?.addEventListener('click',()=>joinViewer());$('goLiveButton')?.addEventListener('click',startBroadcast);$('endLiveButton')?.addEventListener('click',endLive);$('screenButton')?.addEventListener('click',shareScreen);$('cameraButton')?.addEventListener('click',async()=>{try{await acquireCamera();await refreshCameraDevices();note('카메라가 준비되었습니다.')}catch(error){note(`카메라 사용 불가: ${error.message}`)}});$('micButton')?.addEventListener('click',()=>{const track=state.local?.getAudioTracks?.()[0];if(!track)return note('먼저 카메라·마이크를 준비해 주세요.');track.enabled=!track.enabled;$('micButton').textContent=track.enabled?'마이크':'마이크 꺼짐'});$('copyLinkButton')?.addEventListener('click',async()=>{await navigator.clipboard?.writeText?.($('shareLink').value);note('참여 링크를 복사했습니다.')});$('openViewerButton')?.addEventListener('click',openViewerWindow);addEventListener('pagehide',hostExitCleanup);addEventListener('beforeunload',event=>{if(!state.hosting||!state.isLive||state.closing)return;event.preventDefault();event.returnValue='' });
window.addEventListener('resize',syncOverlayHandles);
void bootstrapAuthHandoff().catch(error=>note(`로그인 연결 실패: ${error.message}`,'entryNote')).finally(()=>{if(params.get('mode')==='studio')prepareStudio();else if(params.get('room'))joinViewer(params.get('room'));else refreshLive()});
})();
