import { injectEkodiShell } from './ekodi-shell-injector.js';

const DEFAULT_SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
function headers(){return{'x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self'; img-src 'self' data: https:; connect-src 'self' https://renzehysxirjilvdxacv.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'; upgrade-insecure-requests"}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers()}})}
function config(env={}){return{service:'trade',canonicalHost:'trade.ekodi.kr',dataMode:env.DATA_MODE||'isolated-staging',authUrl:env.AUTH_URL||'https://auth.ekodi.kr/?site=trade',supabaseUrl:env.SUPABASE_URL||DEFAULT_SUPABASE_URL,publishableKey:env.SUPABASE_PUBLISHABLE_KEY||DEFAULT_PUBLISHABLE_KEY,tenantModel:'central-ekodi-tenants',counterpartyIsolation:true,humanGates:true,platformAdminImplicitTenantAccess:false}}
function secure(response){const h=new Headers(response.headers);for(const[k,v]of Object.entries(headers()))h.set(k,v);if(!h.has('cache-control'))h.set('cache-control',h.get('content-type')?.includes('text/html')?'no-cache':'public, max-age=300');return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
async function app(request,env){const url=new URL('/index.html',request.url);const response=await env.ASSETS.fetch(new Request(url,{headers:request.headers}));return injectEkodiShell(secure(response),'trade')}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health')return json({ok:true,...config(env),surface:'shared-trade-platform',hierarchy:['platform','tenant','counterparty','trade-case'],databaseNamespace:'trade_*',rls:'tenant-membership',adminSurface:true});if(url.pathname==='/config.js'){const surface=request.headers.get('x-ekodi-trade-surface')||'shared';const surfaceTenantKey=request.headers.get('x-ekodi-trade-tenant-key')||'';const clientConfig={...config(env),surface,surfaceTenantKey};return new Response(`window.EKODI_TRADE_CONFIG=${JSON.stringify(clientConfig)};`,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store',...headers()}});}if(url.pathname==='/admin'||url.pathname==='/admin/')return app(request,env);if(request.method!=='GET'&&request.method!=='HEAD')return json({error:'method_not_allowed'},405);const response=await env.ASSETS.fetch(request);if(response.status===404)return app(request,env);return injectEkodiShell(secure(response),'trade')}};
