const SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const SUPABASE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const YOUTUBE_STATUS='https://ekodi-mall.pages.dev/api/social/youtube/status';
const path=location.pathname.replace(/\/+$/,'');
const match=path.match(/^\/org\/([^/]+)(?:\/([^/]+))?\/admin(?:\/([^/]+))?$/i)||path.match(/^\/org\/([^/]+)\/admin(?:\/([^/]+))?$/i);
const workspace=match?.[1]?.toLowerCase()||'ekodibiz';
const service=path.includes('/mall/admin')?'mall':null;
const section=(service?(match?.[3]||'overview'):(match?.[2]||'overview')).toLowerCase();
const BASE=`/org/${workspace}`;
const ADMIN_BASE=service?`${BASE}/${service}/admin`:`${BASE}/admin`;
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0));
const WORKSPACES={ekodibiz:{name:'에코디비즈',publicUrl:'https://biz.ekodi.kr/'}};
const SERVICES={mall:{name:'에코디몰',publicUrl:'https://ekodi.kr/mall'}};
const NAV=service==='mall'?
  [['overview','대시보드'],['sales','영업장부'],['products','상품관리'],['marketing','홍보 · 게시'],['channels','채널연결'],['automation','자동화'],['analytics','분석']]:
  [['overview','운영 홈'],['mall','에코디몰'],['marketing','마케팅'],['work','업무'],['finance','재무'],['members','사용자 · 권한']];
const META={overview:['대시보드','이 서비스의 운영 상태와 다음 행동을 한눈에 확인합니다.'],sales:['영업장부','게시 → 유입 → 상품조회 → 제휴클릭 → 전환 흐름을 실제 이벤트 기준으로 확인합니다.'],products:['상품관리','공개 쇼핑몰 상품과 판매처 연결 상태를 관리합니다.'],marketing:['홍보 · 게시','콘텐츠 생성, 게시 준비와 UTM 캠페인을 관리합니다.'],channels:['채널연결','게시 채널의 실제 연결 상태를 확인합니다.'],automation:['자동화','콘텐츠 생성과 예약게시 자동화 준비 상태를 확인합니다.'],analytics:['분석','채널·캠페인별 유입과 클릭 성과를 비교합니다.'],mall:['에코디몰','에코디비즈가 운영하는 쇼핑몰 서비스로 이동합니다.'],work:['업무','에코디비즈 업무 서비스 상태를 확인합니다.'],finance:['재무','에코디비즈 재무 서비스 상태를 확인합니다.'],members:['사용자 · 권한','운영공간의 로컬 역할과 접근권한을 관리합니다.']};
function nav(){const host=$('adminNav');host.replaceChildren();NAV.forEach(([key,label])=>{const a=document.createElement('a');a.textContent=label;a.href=key==='overview'?ADMIN_BASE:`${ADMIN_BASE}/${key}`;if(key===section)a.classList.add('active');host.append(a)})}
function card(label,value,meta=''){return`<article class="card"><span>${label}</span><strong>${value}</strong><small>${meta}</small></article>`}
function setState(text){$('pageState').textContent=text}
function setup(){const w=WORKSPACES[workspace]||{name:workspace,publicUrl:BASE};const s=service?SERVICES[service]:null;$('workspaceName').textContent=w.name;$('scopeLabel').textContent=w.name;$('serviceName').textContent=s?.name||'운영관리';$('publicLink').href=s?.publicUrl||w.publicUrl;$('publicLink').textContent=s?'쇼핑몰 보기':'사용자 화면';$('breadcrumb').textContent=service?`${w.name} / ${s.name} / ADMIN`:`${w.name} / ADMIN`;const [title,copy]=META[section]||META.overview;$('pageTitle').textContent=title;$('pageCopy').textContent=copy;document.title=`${title} · ${s?.name||w.name}`;nav()}
async function getEvents(){const q=new URLSearchParams({select:'id,event_type,campaign,source,medium,content,landing_path,target_host,test,created_at,metadata',order:'created_at.desc',limit:'200'});const r=await fetch(`${SUPABASE_URL}/rest/v1/mall_sales_events?${q}`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${SUPABASE_KEY}`},cache:'no-store'});if(!r.ok)throw new Error(`ledger_${r.status}`);return r.json()}
function eventStats(events){const real=events.filter(e=>!e.test);const count=t=>real.filter(e=>e.event_type===t).length;return{real,visits:count('mall_visit'),views:count('product_view'),clicks:count('affiliate_click'),conversions:count('conversion')}}
function renderLedger(events){const s=eventStats(events);$('summaryCards').innerHTML=[card('실제 유입',fmt(s.visits),'test 제외'),card('상품조회',fmt(s.views),'실제 이벤트'),card('제휴클릭',fmt(s.clicks),'실제 이벤트'),card('전환',fmt(s.conversions),'기록된 전환')].join('');const rows=s.real.slice(0,100).map(e=>`<tr><td>${new Date(e.created_at).toLocaleString('ko-KR')}</td><td><span class="tag ${e.event_type==='affiliate_click'?'live':''}">${e.event_type||'-'}</span></td><td>${e.source||'-'}</td><td>${e.campaign||'-'}</td><td>${e.content||'-'}</td><td>${e.target_host||'-'}</td></tr>`).join('');$('mainPanel').innerHTML=`<h2>최근 실제 영업 이벤트</h2>${rows?`<div class="table-wrap"><table><thead><tr><th>시각</th><th>이벤트</th><th>채널</th><th>캠페인</th><th>콘텐츠</th><th>대상</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<p class="empty">실제 이벤트가 아직 없습니다.</p>'}<div class="actions"><a class="button" href="${SUPABASE_URL}/rest/v1/mall_sales_events" target="_blank" rel="noopener">원본 API</a></div>`;setState('실데이터')}
async function youtubeState(){try{const r=await fetch(YOUTUBE_STATUS,{cache:'no-store'});return r.ok?await r.json():{ok:false,reason:`HTTP_${r.status}`}}catch{return{ok:false,reason:'NETWORK_ERROR'}}}
function renderServices(){const items=[['에코디몰','상품·홍보·유입·제휴 영업 관리',`${BASE}/mall/admin`],['Marketing AI','콘텐츠·캠페인 운영','https://marketing.ekodi.kr/'],['Business OS','에코디비즈 경영 운영','https://business.ekodi.kr/ekodibiz']];$('summaryCards').innerHTML=[card('운영공간','에코디비즈','customer tenant'),card('서비스','3','연결된 운영면'),card('관리범위','로컬','플랫폼 권한과 분리'),card('상태','운영','tenant-scoped')].join('');$('mainPanel').innerHTML=`<h2>서비스</h2><div class="service-list">${items.map(([n,d,h])=>`<div class="service-row"><div><strong>${n}</strong><p>${d}</p></div><a href="${h}">열기</a></div>`).join('')}</div>`;setState('고객공간')}
async function renderMallOverview(){const [events,yt]=await Promise.all([getEvents().catch(()=>[]),youtubeState()]);const s=eventStats(events);$('summaryCards').innerHTML=[card('실제 유입',fmt(s.visits),'최근 200 이벤트'),card('제휴클릭',fmt(s.clicks),'test 제외'),card('YouTube',yt.canUpload?'연결':'대기',yt.reason||'업로드 가능'),card('자동게시',yt.canUpload?'준비됨':'차단',yt.canUpload?'gateway ready':'Google OAuth 필요')].join('');$('mainPanel').innerHTML=`<h2>에코디몰 운영 흐름</h2><div class="service-list"><div class="service-row"><div><strong>상품</strong><p>공개 몰의 상품·판매처 연결을 관리합니다.</p></div><a href="${ADMIN_BASE}/products">관리</a></div><div class="service-row"><div><strong>홍보 · 게시</strong><p>과도하지 않은 빈도로 콘텐츠 생성·UTM·게시 상태를 관리합니다.</p></div><a href="${ADMIN_BASE}/marketing">관리</a></div><div class="service-row"><div><strong>영업장부</strong><p>유입·상품조회·제휴클릭·전환을 실제 이벤트로 확인합니다.</p></div><a href="${ADMIN_BASE}/sales">보기</a></div></div>`;setState('운영')}
async function renderSection(){if(!service){if(section==='overview')return renderServices();if(section==='mall'){location.replace(`${BASE}/mall/admin`);return}$('summaryCards').innerHTML=[card('운영공간','에코디비즈','customer tenant'),card('메뉴',META[section]?.[0]||section,'로컬 관리')].join('');$('mainPanel').innerHTML='<p class="empty">이 기능은 독립 모듈 연결 준비 중입니다. 플랫폼 전체 관리자 권한과는 분리됩니다.</p>';setState('연결 준비');return}if(section==='sales'||section==='analytics'){try{return renderLedger(await getEvents())}catch(e){$('summaryCards').innerHTML=[card('장부','연결 실패',e.message)];$('mainPanel').innerHTML='<p class="empty">장부 데이터를 읽지 못했습니다. 게시 성공으로 간주하지 않습니다.</p>';setState('확인 필요');return}}if(section==='overview')return renderMallOverview();if(section==='channels'||section==='automation'||section==='marketing'){const yt=await youtubeState();$('summaryCards').innerHTML=[card('YouTube',yt.canUpload?'연결':'대기',yt.reason||'gateway ready'),card('OAuth Client',yt.oauthClientConfigured?'설정':'미설정','Google OAuth'),card('Refresh Token',yt.refreshTokenStored?'저장':'미저장',yt.tokenStore||'YOUTUBE_AUTH KV'),card('예약게시',yt.canUpload?'가능':'차단','실제 성공 전 성공표시 안 함')].join('');$('mainPanel').innerHTML=`<h2>게시 채널 상태</h2><div class="service-list"><div class="service-row"><div><strong>YouTube 직접 게이트웨이</strong><p>${yt.canUpload?'자동 업로드 준비가 완료되었습니다.':'Google OAuth 상시 연결이 아직 완료되지 않았습니다.'}</p></div><span class="tag ${yt.canUpload?'live':'warn'}">${yt.canUpload?'READY':'BLOCKED'}</span></div></div>`;setState(yt.canUpload?'연결됨':'연결 필요');return}$('summaryCards').innerHTML=[card('상품 서비스','에코디몰','EKODIBIZ 소유 운영'),card('공개주소','/mall','ekodi.kr')].join('');$('mainPanel').innerHTML=`<h2>상품 관리</h2><p class="empty">상품 원본은 에코디몰의 독립 상품 모듈에서 관리합니다.</p><div class="actions"><a class="button primary" href="https://ekodi.kr/mall">공개 몰 확인</a></div>`;setState('운영')}
setup();renderSection();
