function securityHeaders(env={}){
  const connect=["'self'"];
  if(env.SUPABASE_URL){try{connect.push(new URL(env.SUPABASE_URL).origin)}catch{}}
  return {
    'x-content-type-options':'nosniff',
    'referrer-policy':'strict-origin-when-cross-origin',
    'permissions-policy':'camera=(), microphone=(), geolocation=()',
    'content-security-policy':`default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self'; img-src 'self' data: https:; connect-src ${connect.join(' ')}; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests`,
  };
}
function json(env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...securityHeaders(env)}})}
function withHeaders(env,response){const headers=new Headers(response.headers);for(const [key,value] of Object.entries(securityHeaders(env)))headers.set(key,value);if(!headers.has('cache-control'))headers.set('cache-control',response.headers.get('content-type')?.includes('text/html')?'no-cache':'public, max-age=300');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function clean(s,max=5000){return String(s||'').replace(/[<>]/g,'').trim().slice(0,max)}
function draftFromBrief(brief){const text=clean(brief,4000);const lower=text.toLowerCase();const isProject=/프로젝트|건별|프리랜서/.test(text);const isIntern=/인턴/.test(text);const isFull=/정규직/.test(text);const employment_type=isProject?'프로젝트':isIntern?'인턴':isFull?'정규직':'아르바이트';const wageMatch=text.match(/(?:시급|시간당)\s*([0-9,]+)\s*원?/);const region=(text.match(/(서울|부산|대구|인천|광주|대전|울산|세종|제주|목포|무안|청계|전남|전북|경남|경북|충남|충북)[^,.\n]{0,18}/)||[])[0]||'';const schedule=(text.match(/(?:월|화|수|목|금|토|일)(?:요일)?[^,.\n]{0,45}/)||[])[0]||'';let category='현장·매장 운영';if(/영상|쇼츠|촬영|편집/.test(text))category='콘텐츠·영상';else if(/통역|번역|중국어|영어/.test(text))category='통역·언어';else if(/마케팅|홍보|sns/i.test(text))category='마케팅';else if(/개발|코딩|웹|ai/i.test(text))category='IT·AI';const skills=[];if(/초보|경력무관/.test(text))skills.push('경력무관');if(/고객|매장|치킨|카페|식당/.test(text))skills.push('고객응대');if(/영상|편집/.test(text))skills.push('영상편집');const languages=[];if(/한국어/.test(text))languages.push('한국어');if(/중국어|中文/.test(text))languages.push('中文');if(/영어|English/i.test(text))languages.push('English');const title=(category==='현장·매장 운영'?'함께 일할 팀원 모집':`${category} 인재 모집`);return{title,category,employment_type,region,location_text:region,schedule_text:schedule,wage_type:wageMatch?'hourly':'negotiable',wage_amount:wageMatch?Number(wageMatch[1].replaceAll(',','')):null,summary:text,skills,languages,visa_guidance:/외국인|유학생|비자/.test(lower)?'지원 전 체류자격과 근로가능 범위를 공식 절차로 확인합니다.':''}}
function compliance(body){const text=`${clean(body.title)} ${clean(body.summary)}`;const checks=[];const blocked=[['여자만','성별을 제한하는 표현이 포함되어 있습니다. 직무상 정당한 사유가 없다면 수정하세요.'],['남자만','성별을 제한하는 표현이 포함되어 있습니다. 직무상 정당한 사유가 없다면 수정하세요.'],['젊은','연령을 암시하거나 제한하는 표현은 차별 소지가 있습니다.'],['한국인만','국적을 일률적으로 제한하는 표현은 법적 검토가 필요합니다.']];for(const [term,message] of blocked)if(text.includes(term))checks.push({level:'danger',message});if(!body.wage_type)checks.push({level:'warn',message:'급여 형태가 비어 있습니다.'});if(body.wage_type!=='negotiable'&&!Number(body.wage_amount))checks.push({level:'warn',message:'급여 금액을 확인하세요. 최저임금 등 법정 기준은 게시 시점의 공식 정보를 확인해야 합니다.'});if(!clean(body.visa_guidance)&&/외국인|유학생|비자/.test(text))checks.push({level:'warn',message:'외국인 지원 가능 여부는 체류자격·근로가능 범위를 공식 절차에서 확인하도록 안내하세요.'});if(!checks.length)checks.push({level:'',message:'자동 점검에서 명백한 위험표현은 발견되지 않았습니다. 최종 법적 적합성은 사업주가 확인해야 합니다.'});return checks}
function runtimeConfig(env){const dataEnabled=env.DATA_ENABLED==='true'&&!!env.SUPABASE_URL&&!!env.SUPABASE_PUBLISHABLE_KEY;return{dataEnabled,dataMode:env.DATA_MODE||'isolated-staging',supabaseUrl:dataEnabled?env.SUPABASE_URL:'',supabasePublishableKey:dataEnabled?env.SUPABASE_PUBLISHABLE_KEY:'',authUrl:env.AUTH_URL||'https://auth.ekodi.kr/?site=work'}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/config.js'){const cfg=runtimeConfig(env);return new Response(`window.EKODI_WORK_CONFIG=${JSON.stringify(cfg)};`,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store',...securityHeaders(env)}})}if(url.pathname==='/health'){const cfg=runtimeConfig(env);return json(env,{ok:true,service:'ekodi-work',dataLayer:'supabase-work-namespace',dataMode:cfg.dataMode,dataEnabled:cfg.dataEnabled,aiDraft:'smart'})}if(url.pathname==='/admin'||url.pathname==='/admin/')return Response.redirect('https://admin.ekodi.kr/work',307);if(request.method==='POST'&&url.pathname==='/api/draft-job'){let body={};try{body=await request.json()}catch{return json(env,{error:'invalid_json'},400)}const brief=clean(body.brief);if(brief.length<8)return json(env,{error:'brief_too_short'},400);return json(env,{mode:'smart',draft:draftFromBrief(brief)})}if(request.method==='POST'&&url.pathname==='/api/compliance'){let body={};try{body=await request.json()}catch{return json(env,{error:'invalid_json'},400)}return json(env,{checks:compliance(body)})}return withHeaders(env,await env.ASSETS.fetch(request))}}
