function securityHeaders(env={}){
  const connect=["'self'"];
  if(env.SUPABASE_URL){try{connect.push(new URL(env.SUPABASE_URL).origin)}catch{}}
  return {
    'x-content-type-options':'nosniff',
    'referrer-policy':'strict-origin-when-cross-origin',
    'permissions-policy':'camera=(), microphone=(), geolocation=()',
    'content-security-policy':`default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self'; img-src 'self' data: https:; connect-src ${connect.join(' ')}; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests`,
  };
}
function json(env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...securityHeaders(env)}})}
function withHeaders(env,response){const headers=new Headers(response.headers);for(const [key,value] of Object.entries(securityHeaders(env)))headers.set(key,value);if(!headers.has('cache-control'))headers.set('cache-control',response.headers.get('content-type')?.includes('text/html')?'no-cache':'public, max-age=300');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function clean(s,max=5000){return String(s||'').replace(/[<>]/g,'').trim().slice(0,max)}
function draftFromBrief(brief){const text=clean(brief,4000);const lower=text.toLowerCase();const isProject=/프로젝트|건별|프리랜서/.test(text);const isIntern=/인턴/.test(text);const isFull=/정규직/.test(text);const employment_type=isProject?'프로젝트':isIntern?'인턴':isFull?'정규직':'아르바이트';const wageMatch=text.match(/(?:시급|시간당)\s*([0-9,]+)\s*원?/);const region=(text.match(/(서울|부산|대구|인천|광주|대전|울산|세종|제주|목포|무안|청계|전남|전북|경남|경북|충남|충북)[^,.\n]{0,18}/)||[])[0]||'';const schedule=(text.match(/(?:월|화|수|목|금|토|일)(?:요일)?[^,.\n]{0,45}/)||[])[0]||'';let category='현장·매장 운영';if(/영상|쇼츠|촬영|편집/.test(text))category='콘텐츠·영상';else if(/통역|번역|중국어|영어/.test(text))category='통역·언어';else if(/마케팅|홍보|sns/i.test(text))category='마케팅';else if(/개발|코딩|웹|ai/i.test(text))category='IT·AI';const skills=[];if(/초보|경력무관/.test(text))skills.push('경력무관');if(/고객|매장|치킨|카페|식당/.test(text))skills.push('고객응대');if(/영상|편집/.test(text))skills.push('영상편집');const languages=[];if(/한국어/.test(text))languages.push('한국어');if(/중국어|中文/.test(text))languages.push('中文');if(/영어|English/i.test(text))languages.push('English');const title=(category==='현장·매장 운영'?'함께 일할 팀원 모집':`${category} 인재 모집`);return{title,category,employment_type,region,location_text:region,schedule_text:schedule,wage_type:wageMatch?'hourly':'negotiable',wage_amount:wageMatch?Number(wageMatch[1].replaceAll(',','')):null,summary:text,skills,languages,visa_guidance:/외국인|유학생|비자/.test(lower)?'지원 전 체류자격과 근로가능 범위를 공식 절차로 확인합니다.':''}}
function compliance(body){const text=`${clean(body.title)} ${clean(body.summary)}`;const checks=[];const blocked=[['여자만','성별을 제한하는 표현이 포함되어 있습니다. 직무상 정당한 사유가 없다면 수정하세요.'],['남자만','성별을 제한하는 표현이 포함되어 있습니다. 직무상 정당한 사유가 없다면 수정하세요.'],['젊은','연령을 암시하거나 제한하는 표현은 차별 소지가 있습니다.'],['한국인만','국적을 일률적으로 제한하는 표현은 법적 검토가 필요합니다.']];for(const [term,message] of blocked)if(text.includes(term))checks.push({level:'danger',message});if(!body.wage_type)checks.push({level:'warn',message:'급여 형태가 비어 있습니다.'});if(body.wage_type!=='negotiable'&&!Number(body.wage_amount))checks.push({level:'warn',message:'급여 금액을 확인하세요. 최저임금 등 법정 기준은 게시 시점의 공식 정보를 확인해야 합니다.'});if(!clean(body.visa_guidance)&&/외국인|유학생|비자/.test(text))checks.push({level:'warn',message:'외국인 지원 가능 여부는 체류자격·근로가능 범위를 공식 절차에서 확인하도록 안내하세요.'});if(!checks.length)checks.push({level:'',message:'자동 점검에서 명백한 위험표현은 발견되지 않았습니다. 최종 법적 적합성은 사업주가 확인해야 합니다.'});return checks}
function runtimeConfig(env){const dataEnabled=env.DATA_ENABLED==='true'&&!!env.SUPABASE_URL&&!!env.SUPABASE_PUBLISHABLE_KEY;return{dataEnabled,dataMode:env.DATA_MODE||'isolated-staging',supabaseUrl:dataEnabled?env.SUPABASE_URL:'',supabasePublishableKey:dataEnabled?env.SUPABASE_PUBLISHABLE_KEY:'',authUrl:env.AUTH_URL||'https://auth.ekodi.kr/?site=work'}}
function decodeXml(value=''){return String(value).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&').trim()}
function xmlTag(block,tag){const m=String(block).match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1]):''}
function work24Date(value){const raw=String(value||'').replace(/[^0-9]/g,'');return raw.length>=8?`${raw.slice(0,4)}-${raw.slice(4,6)}-${raw.slice(6,8)}T00:00:00+09:00`:''}
function work24Employment(code){return String(code)==='10'?'정규직':String(code)==='11'?'정규직':String(code)==='20'?'계약직':String(code)==='21'?'계약직':''}
function nativeSalary(job){if(job.wage_type==='negotiable'||!job.wage_amount)return'급여 협의';const n=Number(job.wage_amount).toLocaleString('ko-KR');return job.wage_type==='hourly'?`시급 ${n}원`:job.wage_type==='monthly'?`월 ${n}원`:`${n}원`}
async function cachedText(url,ttl=600){const cache=globalThis.caches?.default;const key=new Request(url,{method:'GET'});if(cache){const hit=await cache.match(key);if(hit)return hit.text()}const response=await fetch(url,{headers:{accept:'application/xml,text/xml;q=0.9,*/*;q=0.5','user-agent':'EKODI-Work/1.0'}});if(!response.ok)throw new Error(`upstream_${response.status}`);const body=await response.text();if(cache){const cached=new Response(body,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':`public, max-age=${ttl}`}});await cache.put(key,cached)}return body}
async function loadWork24(env,keyword,limit){const enabled=!!env.WORK24_AUTH_KEY;if(!enabled)return{enabled:false,items:[]};const terms=keyword?[keyword]:['목포','무안'];const per=Math.max(4,Math.ceil(limit/terms.length));const batches=await Promise.allSettled(terms.map(async term=>{const api=new URL('https://www.work24.go.kr/cm/openApi/call/wk/callOpenApiSvcInfo210L01.do');api.searchParams.set('authKey',env.WORK24_AUTH_KEY);api.searchParams.set('callTp','L');api.searchParams.set('returnType','XML');api.searchParams.set('startPage','1');api.searchParams.set('display',String(Math.min(30,per)));api.searchParams.set('sortOrderBy','DESC');api.searchParams.set('keyword',term);const xml=await cachedText(api.toString(),600);return [...xml.matchAll(/<wanted>([\s\S]*?)<\/wanted>/gi)].map(match=>match[1]).map(block=>{const wantedAuthNo=xmlTag(block,'wantedAuthNo');const salTpNm=xmlTag(block,'salTpNm'),sal=xmlTag(block,'sal'),minSal=xmlTag(block,'minSal'),maxSal=xmlTag(block,'maxSal');const salaryText=[salTpNm,sal].filter(Boolean).join(' ')||[minSal,maxSal].filter(Boolean).join(' ~ ');return{id:`work24:${wantedAuthNo||crypto.randomUUID()}`,source:'work24',external:true,title:xmlTag(block,'title'),company:xmlTag(block,'company'),summary:[xmlTag(block,'indTpNm'),xmlTag(block,'career')].filter(Boolean).join(' · '),region:xmlTag(block,'region')||xmlTag(block,'basicAddr'),employmentType:work24Employment(xmlTag(block,'empTpCd')),scheduleText:xmlTag(block,'holidayTpNm'),salaryText,url:xmlTag(block,'wantedInfoUrl')||xmlTag(block,'wantedMobileInfoUrl'),publishedAt:work24Date(xmlTag(block,'regDt')),expiresAt:work24Date(xmlTag(block,'closeDt')),tags:[xmlTag(block,'minEdubg'),xmlTag(block,'career')].filter(Boolean)}})}));const items=batches.flatMap(result=>result.status==='fulfilled'?result.value:[]).filter(item=>item.title);return{enabled:true,items,error:batches.some(result=>result.status==='rejected')}}
async function loadNative(env,keyword,limit){const cfg=runtimeConfig(env);if(!cfg.dataEnabled)return{enabled:false,items:[]};const api=new URL(`${env.SUPABASE_URL}/rest/v1/work_jobs`);api.searchParams.set('select','id,title,summary,category,employment_type,region,location_text,schedule_text,wage_type,wage_amount,currency,skills,languages,visa_guidance,published_at,work_organizations(name,verified)');api.searchParams.set('status','eq.published');api.searchParams.set('order','published_at.desc');api.searchParams.set('limit',String(Math.min(60,Math.max(limit*2,30))));const response=await fetch(api.toString(),{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,accept:'application/json'}});if(!response.ok)throw new Error(`native_${response.status}`);let rows=await response.json();if(keyword){const terms=keyword.toLowerCase().split(/\s+/).filter(Boolean);rows=rows.filter(job=>{const hay=[job.title,job.summary,job.category,job.region,job.location_text,job.schedule_text,...(job.skills||[]),...(job.languages||[])].filter(Boolean).join(' ').toLowerCase();return terms.every(term=>hay.includes(term))})}const items=rows.slice(0,limit).map(job=>({id:`ekodi:${job.id}`,source:'ekodi',external:false,nativeId:job.id,title:job.title,company:job.work_organizations?.name||'EKODI 등록 사업장',verified:!!job.work_organizations?.verified,summary:job.summary,region:job.region,employmentType:job.employment_type,scheduleText:job.schedule_text,salaryText:nativeSalary(job),url:'',publishedAt:job.published_at,expiresAt:'',tags:[...(job.skills||[]),...(job.languages||[])].slice(0,8)}));return{enabled:true,items}}
function opportunityKey(item){return[clean(item.title,160).toLowerCase().replace(/\s+/g,''),clean(item.company,120).toLowerCase().replace(/\s+/g,''),clean(item.region,80).toLowerCase().replace(/\s+/g,'')].join('|')}
function opportunityTime(item){const value=Date.parse(item.publishedAt||'');return Number.isFinite(value)?value:0}
function mergeOpportunities(groups,limit){const seen=new Set(),items=[];for(const item of groups.flat()){const key=opportunityKey(item);if(!item.title||seen.has(key))continue;seen.add(key);items.push(item)}return items.sort((a,b)=>opportunityTime(b)-opportunityTime(a)).slice(0,limit)}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/config.js'){const cfg=runtimeConfig(env);return new Response(`window.EKODI_WORK_CONFIG=${JSON.stringify(cfg)};`,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store',...securityHeaders(env)}})}if(url.pathname==='/health'){const cfg=runtimeConfig(env);return json(env,{ok:true,service:'ekodi-work',dataLayer:'supabase-work-namespace',dataMode:cfg.dataMode,dataEnabled:cfg.dataEnabled,aiDraft:'smart',opportunityStream:'native+official-connectors',work24Configured:!!env.WORK24_AUTH_KEY})}if(request.method==='GET'&&url.pathname==='/api/opportunities'){const keyword=clean(url.searchParams.get('keyword')||'',100);const requested=Number(url.searchParams.get('limit')||24);const limit=Math.min(40,Math.max(4,Number.isFinite(requested)?requested:24));const [nativeResult,work24Result]=await Promise.allSettled([loadNative(env,keyword,limit),loadWork24(env,keyword,limit)]);const native=nativeResult.status==='fulfilled'?nativeResult.value:{enabled:runtimeConfig(env).dataEnabled,items:[],error:true};const work24=work24Result.status==='fulfilled'?work24Result.value:{enabled:!!env.WORK24_AUTH_KEY,items:[],error:true};const items=mergeOpportunities([native.items||[],work24.items||[]],limit);return json(env,{items,meta:{generatedAt:new Date().toISOString(),keyword,dataMode:runtimeConfig(env).dataMode,sources:[{id:'ekodi',label:'EKODI 직접 등록',enabled:!!native.enabled,count:(native.items||[]).length,error:!!native.error},{id:'work24',label:'고용24 공식 API',enabled:!!work24.enabled,count:(work24.items||[]).length,error:!!work24.error}]}})}if(url.pathname==='/admin'||url.pathname==='/admin/')return Response.redirect('https://admin.ekodi.kr/work',307);if(request.method==='POST'&&url.pathname==='/api/draft-job'){let body={};try{body=await request.json()}catch{return json(env,{error:'invalid_json'},400)}const brief=clean(body.brief);if(brief.length<8)return json(env,{error:'brief_too_short'},400);return json(env,{mode:'smart',draft:draftFromBrief(brief)})}if(request.method==='POST'&&url.pathname==='/api/compliance'){let body={};try{body=await request.json()}catch{return json(env,{error:'invalid_json'},400)}return json(env,{checks:compliance(body)})}return withHeaders(env,await env.ASSETS.fetch(request))}}
