name = "ekodi-service-proxy"
main = "service-proxy.js"
compatibility_date = "2026-08-11"
workers_dev = false
preview_urls = false

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "biz.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "church.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "live.church.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "lab.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mall.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mall.biz.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.biz.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.church.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.lab.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.books.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "mail.trade.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true
