name = "ekodi-shared-site-staging"
main = "platform-router-worker.js"
compatibility_date = "2026-08-12"
workers_dev = true
preview_urls = false

[vars]
ENVIRONMENT = "staging"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
