name = "ekodi-shell"
main = "ekodi-shell-worker.js"
compatibility_date = "2026-08-18"
workers_dev = false
preview_urls = false


[vars]
ENVIRONMENT = "production"

[assets]
directory = "./shell"
binding = "ASSETS"
run_worker_first = true

[observability.logs]
enabled = true
invocation_logs = true
