name = "ekodi-shell-staging"
main = "ekodi-shell-worker.js"
compatibility_date = "2026-08-19"
workers_dev = true
preview_urls = false

[vars]
ENVIRONMENT = "staging"

[assets]
directory = "./shell"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true
