name = "ekodi-biz-legacy-redirect"
main = "biz-legacy-redirect.js"
compatibility_date = "2026-08-12"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "ekodibiz.kr"
zone_name = "ekodibiz.kr"
custom_domain = true

[[routes]]
pattern = "www.ekodibiz.kr"
zone_name = "ekodibiz.kr"
custom_domain = true
