name = "shy-thunder-39a4"
compatibility_date = "2026-08-12"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "ekodi.kr"
custom_domain = true

[[routes]]
pattern = "www.ekodi.kr"
custom_domain = true

[assets]
directory = "./dist"
