name = "ekodi-shell"
main = "ekodi-shell-worker.js"
compatibility_date = "2026-08-19"
workers_dev = true
preview_urls = false

[[routes]]
pattern = "shell.ekodi.kr"
zone_name = "ekodi.kr"
custom_domain = true

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./shell"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true
