const cfg=window.EKODI_AI_CONFIG||{};
const SESSION_KEY='ekodi-ai-control-session';
const $=id=>document.getElementById(id);
const state={session:null,status:null,tasks:[],nodes:[]};

function storedSession(){try{const value=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return value?.accessToken?value:null}catch{return null}}
function saveSession(value){state.session=value;sessionStorage.setItem(SESSION_KEY,JSON.stringify(value));renderIdentity()}
function clearSession(){state.session=null;sessionStorage.removeItem(SESSION_KEY);renderIdentity()}
function authUrl(){return cfg.authUrl||'https://auth.ekodi.kr/?site=ai&return_to=https%3A%2F%2Fai.ekodi.kr%2F'}
function apiHeaders(){return state.session?.accessToken?{authorization:`Bearer ${state.session.accessToken}`}:{}}
function renderIdentity(){const member=Boolean(state.session?.accessToken);$('appPanel').hidden=!member;$('loginPanel').hidden=member;$('authLink').href=member?'#logout':authUrl();$('authLink').textContent=member?'로그아웃':'Google 로그인';$('loginButton').href=authUrl();$('identity').textContent=member?state.session?.user?.email||'관리자':''}
async function exchangeCentralToken(){const params=new URLSearchParams(location.hash.slice(1));const tokenHash=params.get('ekodi_token');if(!tokenHash)return false;const response=await fetch('/api/auth/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tokenHash,type:params.get('ekodi_type')||'email'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'auth_exchange_failed');saveSession(data);history.replaceState(null,'',location.pathname+location.search);return true}
async function loadStatus(){const response=await fetch('/api/status');const data=await response.json();state.status=data;$('healthDot').classList.toggle('ok',Boolean(data.ok));$('healthText').textContent=data.ok?'관제면 정상':'상태 확인 필요';$('stateStore').textContent=data.stateStore==='ready'?'연결됨':'미연결';$('branchState').textContent=data.config?.branchAllocationEnabled?'자동':'비활성';$('strategy').textContent=data.config?.mode||'free-first';if($('architectureState'))$('architectureState').textContent=data.config?.architectureVersion?`v${data.config.architectureVersion}`:'v1.8';renderProviders(data.providers||[])}
function providerLabel(provider){if(provider.kind==='account-cli')return'계정형 CLI';if(provider.kind==='official-api')return'공식 API';if(provider.kind==='external-worker')return'외부 어댑터';return provider.kind}
function costLabel(value){return({"free-preferred":'무료 우선',"chatgpt-plan-included":'ChatGPT 플랜 포함',"google-free-quota":'Google 무료 할당량',"claude-subscription":'Claude 구독',"paid-opt-in":'유료 선택',"provider-managed":'외부 관리'})[value]||value}
function renderProviders(providers){const host=$('providers');host.replaceChildren();if(!providers.length){host.innerHTML='<p class="muted">아직 실행 가능한 AI 공급자가 연결되지 않았습니다.</p>';return}for(const provider of providers){const card=document.createElement('article');card.className='provider';const strong=document.createElement('strong');strong.textContent=provider.id;const span=document.createElement('span');span.textContent=`${providerLabel(provider)} · ${costLabel(provider.costClass)} · ${provider.available?'사용 가능':'대기'}`;card.append(strong,span);host.append(card)}}
async function api(path,options={}){const headers={accept:'application/json',...apiHeaders(),...(options.headers||{})};if(options.body&&!headers['content-type'])headers['content-type']='application/json';const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403){clearSession();throw new Error(data.error||'login_required')}if(!response.ok)throw new Error(data.error||`http_${response.status}`);return data}
async function loadTasks(){if(!state.session)return;const data=await api('/api/tasks');state.tasks=data.tasks||[];await renderTasks()}
async function loadTaskDetails(id){return api(`/api/tasks/${encodeURIComponent(id)}`)}
async function loadNodes(){if(!state.session)return;const data=await api('/api/nodes');state.nodes=data.nodes||[];renderNodes()}
function renderNodes(){const host=$('nodes');host.replaceChildren();if(!state.nodes.length){host.innerHTML='<p class="muted">아직 연결된 계정형 작업노드가 없습니다.</p>';return}for(const node of state.nodes){const card=document.createElement('article');card.className='provider';const strong=document.createElement('strong');strong.textContent=node.name||node.id;const span=document.createElement('span');const providers=(node.providers||[]).join(', ')||'AI 미감지';span.textContent=`${node.online?'온라인':'오프라인'} · ${providers}`;const small=document.createElement('small');small.textContent=`${node.id} · 마지막 연결 ${node.last_seen_at?new Date(node.last_seen_at).toLocaleString():'-'}`;card.append(strong,span,small);host.append(card)}}
async function createPairing(){const button=$('pairNode');button.disabled=true;try{const data=await api('/api/nodes/pair',{method:'POST',body:'{}'});$('pairCode').textContent=data.code;$('pairExpiry').textContent=`만료 ${new Date(data.expiresAt).toLocaleTimeString()}`;$('pairing').hidden=false}catch(error){alert(`연결코드 발급 실패: ${error.message}`)}finally{button.disabled=false}}
function statusLabel(value){return({queued:'대기',allocating:'브랜치 할당',running:'AI 실행',approval_required:'승인 대기',completed:'완료',failed:'실패'})[value]||value}
async function renderTasks(){const host=$('tasks');host.replaceChildren();if(!state.tasks.length){host.innerHTML='<p class="muted">아직 작업이 없습니다.</p>';return}for(const task of state.tasks){const card=document.createElement('article');card.className='task';card.innerHTML='<div class="task-head"><div><h3></h3><p class="task-meta"></p></div><span class="badge"></span></div><div class="runs"></div>';card.querySelector('h3').textContent=task.title;card.querySelector('.task-meta').textContent=`${task.id} · ${task.mode}${task.branch?` · ${task.branch}`:''}`;card.querySelector('.badge').textContent=statusLabel(task.state);host.append(card);if(['running','allocating','approval_required','completed','failed'].includes(task.state)){try{const detail=await loadTaskDetails(task.id);const runs=card.querySelector('.runs');for(const run of detail.runs||[]){const box=document.createElement('div');box.className='run';const head=document.createElement('div');head.innerHTML='<strong></strong><small></small>';head.querySelector('strong').textContent=run.providerId;head.querySelector('small').textContent=`${run.role} · ${run.state==='queued'?'작업노드 대기':run.state==='leased'?'작업노드 실행':run.ok?'완료':'실패'}`;box.append(head);if(run.output){const pre=document.createElement('pre');pre.textContent=run.output;box.append(pre)}if(run.error){const pre=document.createElement('pre');pre.textContent=run.error;box.append(pre)}runs.append(box)}if(task.state==='approval_required'){const button=document.createElement('button');button.className='button small';button.textContent='결과 승인';button.addEventListener('click',()=>approve(task.id));runs.append(button)}}catch(error){console.error(error)}}}}
async function runTask(){const prompt=$('prompt').value.trim();if(!prompt){$('commandStatus').textContent='명령을 입력해 주세요.';return}$('runTask').disabled=true;$('commandStatus').textContent='작업 생성 중';try{const created=await api('/api/tasks',{method:'POST',body:JSON.stringify({title:$('title').value.trim(),prompt,mode:$('mode').value,needsCodeBranch:$('needsCodeBranch').checked})});await api(`/api/tasks/${encodeURIComponent(created.task.id)}/run`,{method:'POST'});$('commandStatus').textContent=`${created.task.id} 실행 시작`;$('prompt').value='';$('title').value='';await loadTasks()}catch(error){$('commandStatus').textContent=`실행 실패: ${error.message}`}finally{$('runTask').disabled=false}}
async function approve(id){try{await api(`/api/tasks/${encodeURIComponent(id)}/approve`,{method:'POST'});await loadTasks()}catch(error){alert(`승인 실패: ${error.message}`)}}
async function refreshAll(){await loadStatus();if(state.session)await Promise.all([loadTasks(),loadNodes()])}
async function boot(){state.session=storedSession();renderIdentity();try{await exchangeCentralToken()}catch(error){console.error(error);clearSession()}try{await loadStatus()}catch(error){$('healthText').textContent='상태 확인 실패'}if(state.session){try{await api('/api/session');await Promise.all([loadTasks(),loadNodes()])}catch(error){console.error(error)}}setInterval(()=>{if(state.session)Promise.all([loadTasks(),loadNodes()]).catch(()=>{})},12000)}
$('authLink').addEventListener('click',event=>{if(state.session){event.preventDefault();clearSession()}});$('runTask').addEventListener('click',runTask);$('refresh').addEventListener('click',()=>refreshAll());$('pairNode').addEventListener('click',createPairing);boot();
