import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.EKODI_BIBLE_CONFIG||{};
const enabled=Boolean(cfg.dataEnabled&&cfg.supabaseUrl&&cfg.supabasePublishableKey);
const sb=enabled?createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{detectSessionInUrl:true,persistSession:true}}):null;
const TOPICS=['관계','가족','돈','일','진로','외로움','실패','분노','감사','믿음'];
const GUIDES={관계:['골로새서 3:12-14','지금 그 관계에서 가장 지키고 싶은 것은 무엇인가요?'],가족:['에베소서 4:1-3','가족 안에서 지금 가장 필요한 평화의 행동은 무엇인가요?'],돈:['마태복음 6:25-34','돈에 대한 염려 가운데 오늘 내가 통제할 수 있는 한 가지는 무엇인가요?'],일:['골로새서 3:23-24','오늘의 일을 더 큰 의미와 연결한다면 무엇이 달라질까요?'],진로:['잠언 3:5-6','앞길 전체가 아니라 지금 걸을 수 있는 한 걸음은 무엇인가요?'],외로움:['시편 139:1-12','누군가에게 먼저 연결을 요청할 수 있다면 누구인가요?'],실패:['고린도후서 4:7-9','이번 실패가 끝이 아니라면 무엇을 다시 시작할 수 있을까요?'],분노:['야고보서 1:19-20','분노 아래에 숨은 상처나 두려움은 무엇인가요?'],감사:['데살로니가전서 5:16-18','오늘 받은 것 가운데 누구에게 흘려보낼 수 있는 감사가 있나요?'],믿음:['마가복음 9:24','믿음과 의심이 함께 있다면 하나님께 가장 정직하게 말하고 싶은 것은 무엇인가요?']};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
let session=null, topic='믿음', history=[], conversationId=null, journeys=[], groups=[];
function authUrl(){const u=new URL(cfg.authUrl||'https://auth.ekodi.kr/?site=bible');u.searchParams.set('site','bible');u.searchParams.set('return_to',location.origin+location.pathname);return u.href}
async function handoff(){if(!sb||!location.hash)return;const p=new URLSearchParams(location.hash.slice(1));const token=p.get('ekodi_token');if(!token)return;const {error}=await sb.auth.verifyOtp({token_hash:token,type:p.get('ekodi_type')||'email'});history.replaceState({},document.title,location.pathname);if(error)throw error}
function renderIdentity(){const b=$('#authButton'),n=$('#identityName');if(!enabled){b.textContent='격리 스테이징';b.disabled=true;n.textContent='데이터 격리 모드';return}if(session){const m=session.user.user_metadata||{};b.textContent='로그아웃';n.textContent=m.full_name||m.name||session.user.email?.split('@')[0]||'EKODI Member'}else{b.textContent='Google로 시작';n.textContent='로그인 전'}}
async function authAction(){if(!session){location.assign(authUrl());return}await sb.auth.signOut();session=null;conversationId=null;history=[];renderIdentity();await refreshPrivate()}
function showView(name,push=true){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(push)history.replaceState({},'',`/${name==='today'?'today':name}`);if(name==='journey')loadJourneys();if(name==='together')loadGroups()}
function renderTopics(){const host=$('#topicGrid');host.innerHTML=TOPICS.map(t=>`<button type="button" class="topic ${t===topic?'active':''}" data-topic="${t}">${t}</button>`).join('');$$('[data-topic]',host).forEach(b=>b.onclick=()=>{topic=b.dataset.topic;renderTopics();applyGuide();})}
function applyGuide(){const [ref,q]=GUIDES[topic]||GUIDES.믿음;$('#todayTitle').textContent=`${topic}, 말씀과 함께 바라보기`;$('#todayQuestion').textContent=q;$('#todayScripture').textContent=ref;$('#conversationScripture').textContent=ref;$('#conversationTitle').textContent=`${topic}에서 말씀으로`}
async function loadToday(){applyGuide();if(!enabled)return;const {data}=await sb.from('bible_content_plans').select('title,question,scripture_ref,practice_prompt').eq('tenant_slug',cfg.tenantSlug||'ekodi-church').eq('is_active',true).lte('active_date',new Date().toISOString().slice(0,10)).order('active_date',{ascending:false}).limit(1);if(data?.[0]){$('#todayTitle').textContent=data[0].title;$('#todayQuestion').textContent=data[0].question;$('#todayScripture').textContent=data[0].scripture_ref}}
function bubble(role,text){const el=document.createElement('div');el.className=`bubble ${role}`;el.innerHTML=`<small>${role==='user'?'나':'말씀대화'}</small>${esc(text).replace(/\n/g,'<br>')}`;$('#chat').append(el);$('#chat').scrollTop=$('#chat').scrollHeight}
async function ensureConversation(){if(!session||conversationId)return conversationId;const {data,error}=await sb.from('bible_conversations').insert({user_id:session.user.id,tenant_slug:cfg.tenantSlug||'ekodi-church',topic,mode:'guided'}).select('id').single();if(error)throw error;conversationId=data.id;return conversationId}
async function saveMessage(role,content,scriptureRef=''){if(!session)return;const id=await ensureConversation();await sb.from('bible_messages').insert({conversation_id:id,user_id:session.user.id,role,content,scripture_ref:scriptureRef})}
async function sendMessage(message){bubble('user',message);history.push({role:'user',content:message});await saveMessage('user',message);const token=session?.access_token||'';const r=await fetch('/api/assist',{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({message,topic,history:history.slice(-8)})});const data=await r.json().catch(()=>({}));const reply=data.reply||'지금은 AI 보조 기능 없이도 대화를 이어갈 수 있습니다. 이 이야기를 한 문장으로 더 말해 주시겠어요?';bubble('assistant',reply);history.push({role:'assistant',content:reply});await saveMessage('assistant',reply,data.scriptureRef||'');$('#modeBadge').textContent=data.mode==='ai'?'AI 대화':data.authenticated?'안전 대체 모드':'무료 안내';$('#aiNotice').textContent=data.notice||''}
async function loadJourneys(){const gate=$('#journeyGate'),host=$('#journeyList');if(!session){gate.innerHTML='<strong>로그인하면 Journey를 안전하게 저장합니다.</strong><p>개인 묵상과 기도, 실천 기록은 기본적으로 본인만 볼 수 있습니다.</p>';host.innerHTML='';journeys=[];syncShareOptions();return}gate.innerHTML='';const {data,error}=await sb.from('bible_journeys').select('*').order('created_at',{ascending:false}).limit(50);if(error){gate.textContent='Journey를 불러오지 못했습니다.';return}journeys=data||[];host.innerHTML=journeys.length?journeys.map(j=>`<article class="record"><span class="meta">${esc(j.topic)} · ${new Date(j.created_at).toLocaleDateString('ko-KR')}</span><h3>${esc(j.title)}</h3><p class="scripture">${esc(j.scripture_ref)}</p><p>${esc(j.reflection||'')}</p><button class="ghost" data-edit-journey="${j.id}" type="button">이어 기록하기</button></article>`).join(''):'<div class="empty">아직 Journey가 없습니다. 오늘의 대화에서 한 걸음을 기록해 보세요.</div>';$$('[data-edit-journey]').forEach(b=>b.onclick=()=>editJourney(b.dataset.editJourney));syncShareOptions()}
function editJourney(id){const j=journeys.find(x=>x.id===id);const f=$('#journeyForm');f.classList.remove('hidden');for(const k of ['id','title','topic','scripture_ref','reflection','prayer'])if(f.elements[k])f.elements[k].value=j?.[k]||'';f.scrollIntoView({behavior:'smooth'})}
async function saveJourney(form){if(!session){location.assign(authUrl());return}const f=new FormData(form),id=String(f.get('id')||''),payload={user_id:session.user.id,tenant_slug:cfg.tenantSlug||'ekodi-church',title:String(f.get('title')||'').trim(),topic:String(f.get('topic')||'').trim(),scripture_ref:String(f.get('scripture_ref')||'').trim(),reflection:String(f.get('reflection')||'').trim(),prayer:String(f.get('prayer')||'').trim(),status:'practicing',updated_at:new Date().toISOString()};let journeyId=id;if(id){const {error}=await sb.from('bible_journeys').update(payload).eq('id',id);if(error)throw error}else{const {data,error}=await sb.from('bible_journeys').insert(payload).select('id').single();if(error)throw error;journeyId=data.id}const practice=String(f.get('practice')||'').trim();if(practice)await sb.from('bible_practices').insert({user_id:session.user.id,journey_id:journeyId,action_text:practice,due_date:f.get('followup_date')||null});const d=String(f.get('followup_date')||'');if(d)await sb.from('bible_followups').insert({user_id:session.user.id,journey_id:journeyId,prompt:'이 말씀을 어떻게 살아보았나요?',due_at:`${d}T09:00:00+09:00`});form.reset();form.classList.add('hidden');await loadJourneys()}
async function loadGroups(){const gate=$('#groupGate'),host=$('#groupList');if(!session){gate.innerHTML='<strong>공동체 기능은 로그인 후 사용할 수 있습니다.</strong><p>초대코드로 가족·소그룹·교회 모임에 연결할 수 있습니다.</p>';host.innerHTML='';groups=[];syncShareOptions();return}gate.innerHTML='';const {data:members}=await sb.from('bible_group_members').select('group_id,role');const ids=(members||[]).map(x=>x.group_id);if(!ids.length){groups=[];host.innerHTML='<div class="empty">아직 연결된 공동체가 없습니다.</div>';syncShareOptions();return}const {data}=await sb.from('bible_groups').select('*').in('id',ids);groups=data||[];host.innerHTML=groups.map(g=>`<article class="record"><span class="meta">${esc(g.kind)}</span><h3>${esc(g.name)}</h3><p>초대코드 <strong>${esc(g.invite_code)}</strong></p></article>`).join('');syncShareOptions()}
function syncShareOptions(){$('#shareJourney').innerHTML=journeys.map(j=>`<option value="${j.id}">${esc(j.title)}</option>`).join('')||'<option value="">Journey 없음</option>';$('#shareGroup').innerHTML=groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')||'<option value="">공동체 없음</option>'}
async function refreshPrivate(){await Promise.all([loadJourneys(),loadGroups()])}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#authButton').onclick=authAction;$('#startToday').onclick=()=>{showView('conversation');const q=$('#todayQuestion').textContent;if(!history.length){bubble('assistant',`${q}\n\n${$('#todayScripture').textContent}`)}};$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=e.currentTarget.elements.message,message=input.value.trim();if(!message)return;input.value='';input.disabled=true;try{await sendMessage(message)}catch(err){console.error(err);bubble('assistant','대화를 연결하지 못했습니다. 잠시 후 다시 시도하거나 Journey에 직접 기록해 주세요.')}finally{input.disabled=false;input.focus()}};$('#newJourney').onclick=()=>{const f=$('#journeyForm');f.reset();f.classList.remove('hidden');f.elements.topic.value=topic;f.elements.scripture_ref.value=(GUIDES[topic]||GUIDES.믿음)[0]};$('#cancelJourney').onclick=()=>$('#journeyForm').classList.add('hidden');$('#journeyForm').onsubmit=async e=>{e.preventDefault();try{await saveJourney(e.currentTarget)}catch(err){console.error(err);alert('Journey 저장에 실패했습니다.')}};$('#createGroupForm').onsubmit=async e=>{e.preventDefault();if(!session){location.assign(authUrl());return}const f=new FormData(e.currentTarget);const {error}=await sb.rpc('bible_create_group',{p_name:String(f.get('name')||''),p_kind:String(f.get('kind')||'small_group'),p_tenant_slug:cfg.tenantSlug||'ekodi-church'});if(error){alert('공동체를 만들지 못했습니다.');return}e.currentTarget.reset();await loadGroups()};$('#joinGroupForm').onsubmit=async e=>{e.preventDefault();if(!session){location.assign(authUrl());return}const f=new FormData(e.currentTarget);const {error}=await sb.rpc('bible_join_group',{p_invite_code:String(f.get('invite_code')||'')});if(error){alert('초대코드를 확인해 주세요.');return}e.currentTarget.reset();await loadGroups()};$('#shareForm').onsubmit=async e=>{e.preventDefault();if(!session)return;const f=new FormData(e.currentTarget),journeyId=String(f.get('journey_id')||''),groupId=String(f.get('group_id')||'');if(!journeyId||!groupId)return;const {error}=await sb.from('bible_shared_journeys').insert({user_id:session.user.id,journey_id:journeyId,group_id:groupId,note:String(f.get('note')||'').trim()});alert(error?'공유하지 못했습니다.':'선택한 Journey만 공동체에 공유했습니다.')};
renderTopics();applyGuide();renderIdentity();const initial=location.pathname.split('/')[1];showView(['conversation','journey','together'].includes(initial)?initial:'today',false);await loadToday();if(enabled){try{await handoff()}catch(e){console.error('bible auth handoff',e)}const {data}=await sb.auth.getSession();session=data.session;renderIdentity();await refreshPrivate();sb.auth.onAuthStateChange(async(_e,next)=>{session=next;renderIdentity();await refreshPrivate()})}