const RAW_BOOKS = [
  ['GEN','창세기','창','Genesis','Genesis'],
  ['EXO','출애굽기','출','Exodus','Exodus'],
  ['LEV','레위기','레','Leviticus','Leviticus'],
  ['NUM','민수기','민','Numbers','Numbers'],
  ['DEU','신명기','신','Deuteronomy','Deuteronomy'],
  ['JOS','여호수아','수','Joshua','Joshua'],
  ['JDG','사사기','삿','Judges','Judges'],
  ['RUT','룻기','룻','Ruth','Ruth'],
  ['1SA','사무엘상','삼상','1 Samuel','1Samuel'],
  ['2SA','사무엘하','삼하','2 Samuel','2Samuel'],
  ['1KI','열왕기상','왕상','1 Kings','1Kings'],
  ['2KI','열왕기하','왕하','2 Kings','2Kings'],
  ['1CH','역대상','대상','1 Chronicles','1Chronicles'],
  ['2CH','역대하','대하','2 Chronicles','2Chronicles'],
  ['EZR','에스라','스','Ezra','Ezra'],
  ['NEH','느헤미야','느','Nehemiah','Nehemiah'],
  ['EST','에스더','에','Esther','Esther'],
  ['JOB','욥기','욥','Job','Job'],
  ['PSA','시편','시','Psalms','Psalms'],
  ['PRO','잠언','잠','Proverbs','Proverbs'],
  ['ECC','전도서','전','Ecclesiastes','Ecclesiastes'],
  ['SNG','아가','아','Song of Solomon','SongofSolomon'],
  ['ISA','이사야','사','Isaiah','Isaiah'],
  ['JER','예레미야','렘','Jeremiah','Jeremiah'],  ['LAM','예레미야애가','애','Lamentations','Lamentations'],
  ['EZK','에스겔','겔','Ezekiel','Ezekiel'],
  ['DAN','다니엘','단','Daniel','Daniel'],
  ['HOS','호세아','호','Hosea','Hosea'],
  ['JOL','요엘','욜','Joel','Joel'],
  ['AMO','아모스','암','Amos','Amos'],
  ['OBA','오바댜','옵','Obadiah','Obadiah'],
  ['JON','요나','욘','Jonah','Jonah'],
  ['MIC','미가','미','Micah','Micah'],
  ['NAM','나훔','나','Nahum','Nahum'],
  ['HAB','하박국','합','Habakkuk','Habakkuk'],
  ['ZEP','스바냐','습','Zephaniah','Zephaniah'],
  ['HAG','학개','학','Haggai','Haggai'],
  ['ZEC','스가랴','슥','Zechariah','Zechariah'],
  ['MAL','말라기','말','Malachi','Malachi'],
  ['MAT','마태복음','마','Matthew','Matthew'],
  ['MRK','마가복음','막','Mark','Mark'],
  ['LUK','누가복음','눅','Luke','Luke'],
  ['JHN','요한복음','요','John','John'],
  ['ACT','사도행전','행','Acts','Acts'],
  ['ROM','로마서','롬','Romans','Romans'],
  ['1CO','고린도전서','고전','1 Corinthians','1Corinthians'],
  ['2CO','고린도후서','고후','2 Corinthians','2Corinthians'],
  ['GAL','갈라디아서','갈','Galatians','Galatians'],
  ['EPH','에베소서','엡','Ephesians','Ephesians'],  ['PHP','빌립보서','빌','Philippians','Philippians'],
  ['COL','골로새서','골','Colossians','Colossians'],
  ['1TH','데살로니가전서','살전','1 Thessalonians','1Thessalonians'],
  ['2TH','데살로니가후서','살후','2 Thessalonians','2Thessalonians'],
  ['1TI','디모데전서','딤전','1 Timothy','1Timothy'],
  ['2TI','디모데후서','딤후','2 Timothy','2Timothy'],
  ['TIT','디도서','딛','Titus','Titus'],
  ['PHM','빌레몬서','몬','Philemon','Philemon'],
  ['HEB','히브리서','히','Hebrews','Hebrews'],
  ['JAS','야고보서','약','James','James'],
  ['1PE','베드로전서','벧전','1 Peter','1Peter'],
  ['2PE','베드로후서','벧후','2 Peter','2Peter'],
  ['1JN','요한일서','요일','1 John','1John'],
  ['2JN','요한이서','요이','2 John','2John'],
  ['3JN','요한삼서','요삼','3 John','3John'],
  ['JUD','유다서','유','Jude','Jude'],
  ['REV','요한계시록','계','Revelation','Revelation'],
];

export const BOOKS = RAW_BOOKS.map(([id,ko,abbr,en,source], index) => ({ id, ko, abbr, en, source, order:index + 1 }));
export const BOOK_BY_ID = Object.fromEntries(BOOKS.map(book => [book.id, book]));
export function resolveBook(value) {
  const needle = String(value || '').replace(/\s+/g, '').toLowerCase();
  return BOOKS.find(book => [book.id,book.ko,book.abbr,book.en,book.source].some(name => String(name).replace(/\s+/g, '').toLowerCase() === needle)) || null;
}