const cfg=window.EKODI_LOCAL_COMMERCE_CONFIG?.identity||{};
const box=document.getElementById('accountBox'),text=document.getElementById('accountText'),action=document.getElementById('accountAction');
const state={client:null,session:null,enabled:Boolean(cfg.enabled&&cfg.supabaseUrl&&cfg.publishableKey)};
window.EKODILocalCommerceSession=()=>state.session;
window.EKODILocalCommerceFetch=async(path,options={})=>{if(!state.session)throw new Error('authentication_required');const headers=new Headers(options.headers||{});headers.set('authorization',`Bearer ${state.session.access_token}`);if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');return fetch(path,{...options,headers,cache:'no-store'})};
function emit(extra={}){window.dispatchEvent(new CustomEvent('ekodi:local-commerce-account',{detail:{signedIn:Boolean(state.session),session:state.session,...extra}}))}
function setUi(label,button='로그인',mode='signed-out'){text.textContent=label;action.textContent=button;box.dataset.state=mode}
function loginUrl(){const u=new URL(cfg.authUrl||'https://auth.ekodi.kr/');u.searchParams.set('site','local-commerce');const back=new URL(location.href);back.hash='';u.searchParams.set('return_to',back.href);return u.href}
async function importClient(){try{return await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm')}catch{return import('https://esm.sh/@supabase/supabase-js@2?bundle')}}
async function consumeHandoff(client){const hash=new URLSearchParams(location.hash.replace(/^#/,'')),tokenHash=hash.get('ekodi_token');if(!tokenHash)return;const type=hash.get('ekodi_type')||'email';const {error}=await client.auth.verifyOtp({token_hash:tokenHash,type});if(error)throw error;history.replaceState(null,'',location.pathname+location.search)}
async function bootstrap(){if(!state.enabled){setUi('격리 스테이징','로그인','staging');action.disabled=true;emit({centralIdentityEnabled:false});return}setUi('로그인 확인 중','…','loading');action.disabled=true;try{const {createClient}=await importClient();state.client=createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{detectSessionInUrl:false,persistSession:true,autoRefreshToken:true}});await consumeHandoff(state.client);const {data,error}=await state.client.auth.getSession();if(error)throw error;state.session=data.session||null;if(state.session){setUi(state.session.user?.email||'로그인됨','로그아웃','signed-in')}else setUi('로그인하지 않음','로그인','signed-out');emit({centralIdentityEnabled:true})}catch(error){console.warn('local commerce auth',error);setUi('로그인 연결 확인 필요','다시 로그인','degraded');emit({centralIdentityEnabled:true,error:String(error?.message||error)})}finally{action.disabled=false}}
action.addEventListener('click',async()=>{if(state.session&&state.client){await state.client.auth.signOut().catch(()=>{});state.session=null;setUi('로그인하지 않음','로그인','signed-out');emit({centralIdentityEnabled:true});return}location.assign(loginUrl())});
bootstrap();
