const cfg=window.EKODI_LOCAL_COMMERCE_CONFIG||{};
const apiBase=String(cfg.apiBase||'https://api.ekodi.kr/api/local-commerce').replace(/\/$/,'');
const state={issuers:[],me:null,wallets:[],pendingPay:null,dashboard:null};
const manageRoles=new Set(['owner','admin','tenant_admin','manager','store_owner','operator']);
const accountingRoles=new Set(['accountant','accounting','finance','treasurer']);
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const n=v=>new Intl.NumberFormat('ko-KR').format(Number(v||0));
const toIso=v=>v?new Date(v).toISOString():null;
const toLocalInput=v=>{if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
async function publicApi(path){const r=await fetch(`${apiBase}${path}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||`HTTP_${r.status}`),{data:d,status:r.status});return d}
async function authApi(path,options={}){const r=await window.EKODILocalCommerceFetch(`${apiBase}${path}`,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||`HTTP_${r.status}`),{data:d,status:r.status});return d}
function formJson(form){return Object.fromEntries(new FormData(form).entries())}
function setIssuerOptions(){for(const select of $$('.issuer-select')){const current=select.value;select.innerHTML=`<option value="">운영주체 선택</option>`+state.issuers.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}${i.mascot_name?` · ${esc(i.mascot_name)}`:''}</option>`).join('');if(state.issuers.some(i=>i.id===current))select.value=current}}
async function loadIssuers(){try{const d=await publicApi('/issuers');state.issuers=d.issuers||[];setIssuerOptions()}catch(e){console.warn(e);toast('운영주체 목록을 불러오지 못했습니다.')}}
async function programs(issuerId){if(!issuerId)return[];const d=await publicApi(`/programs?issuer=${encodeURIComponent(issuerId)}`);return d.programs||[]}
async function fillPrograms(select,issuerId){const rows=await programs(issuerId).catch(()=>[]);select.innerHTML=`<option value="">프로그램 선택</option>`+rows.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.unit_name)}</option>`).join('');return rows}
function activateTab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));history.replaceState(null,'',`${location.pathname}${location.search}#${id}`)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.view)));
if(location.hash&&$(`.tab[data-view="${CSS.escape(location.hash.slice(1))}"]`))activateTab(location.hash.slice(1));

function populateWorkspaceSelects(){const contexts=state.me?.contexts||[];for(const id of ['issuerWorkspace','merchantWorkspace']){const el=$(`#${id}`);if(!el)continue;const keep=id==='merchantWorkspace'?'<option value="">개인/외부 상점</option>':'<option value="">운영공간 선택</option>';el.innerHTML=keep+contexts.map(c=>`<option value="${esc(c.workspaceSlug)}">${esc(c.workspaceName)} · ${esc(c.authorizationRole)}</option>`).join('')}}
function configureRoleTools(){const contexts=state.me?.contexts||[],merchants=state.me?.merchants||[];const canManage=contexts.some(c=>manageRoles.has(c.authorizationRole)),canAccount=contexts.some(c=>manageRoles.has(c.authorizationRole)||accountingRoles.has(c.authorizationRole)||accountingRoles.has(c.activityRole));$('#operatorGate').classList.toggle('hidden',canManage);$('#operatorTools').classList.toggle('hidden',!canManage);$('#settlementGate').classList.toggle('hidden',canAccount);$('#settlementTools').classList.toggle('hidden',!canAccount);$('#merchantGate').classList.toggle('hidden',merchants.length>0);$('#qrForm').classList.toggle('hidden',merchants.length===0);renderMerchantSelectors()}
function renderMerchantSelectors(){const rows=state.me?.merchants||[];const issuerIds=[...new Set(rows.map(x=>x.issuer_id).filter(Boolean))];$('#merchantIssuer').innerHTML='<option value="">운영주체 선택</option>'+issuerIds.map(id=>{const issuer=state.issuers.find(x=>x.id===id);return `<option value="${esc(id)}">${esc(issuer?.name||rows.find(x=>x.issuer_id===id)?.issuer_name||id)}</option>`}).join('');$('#merchantSelect').innerHTML='<option value="">상점 선택</option>'+rows.map(m=>`<option value="${esc(m.id)}" data-issuer="${esc(m.issuer_id||'')}">${esc(m.name)}${m.issuer_name?` · ${esc(m.issuer_name)}`:''}</option>`).join('')}
async function loadMe(){const d=await authApi('/me');state.me=d;populateWorkspaceSelects();configureRoleTools();return d}

function renderWallet(){const host=$('#walletCards');if(!state.wallets.length){host.className='cards empty';host.textContent='보유한 상품권·포인트가 없습니다.';return}host.className='cards';host.innerHTML=state.wallets.map(w=>`<article class="card wallet-card"><small>${esc(w.issuer_name)}${w.mascot_name?` · ${esc(w.mascot_name)}`:''}</small><h3>${esc(w.program_name)}</h3><div class="balance">${n(w.balance_minor)} ${esc(w.unit_name)}</div><small>최근 반영 ${new Date(w.updated_at).toLocaleString('ko-KR')}</small></article>`).join('')}
function renderLedger(entries){const host=$('#ledgerList');if(!entries.length){host.className='list empty';host.textContent='사용내역이 없습니다.';return}host.className='list';host.innerHTML=entries.map(e=>`<div class="list-row"><div><strong>${esc(e.issuer_name)} · ${esc(e.program_name)}</strong><div>${esc(e.merchant_name||e.entry_type)} · ${new Date(e.created_at).toLocaleString('ko-KR')}</div></div><div class="${Number(e.amount_minor)>=0?'amount-positive':'amount-negative'}"><strong>${Number(e.amount_minor)>=0?'+':''}${n(e.amount_minor)} ${esc(e.unit_name)}</strong><div>잔액 ${n(e.balance_after_minor)}</div></div></div>`).join('')}
async function loadWallet(){const [w,l]=await Promise.all([authApi('/wallet'),authApi('/wallet/ledger?limit=50')]);state.wallets=w.wallets||[];renderWallet();renderLedger(l.entries||[])}
$('#walletRefresh').addEventListener('click',()=>loadWallet().catch(e=>toast(e.message)));

$('#claimForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#claimResult');out.textContent='처리 중…';try{const d=await authApi('/claim',{method:'POST',body:JSON.stringify(formJson(e.currentTarget))});out.textContent=`${n(d.claimed.valueMinor)} 지급 완료 · 잔액 ${n(d.claimed.balanceMinor)}`;e.currentTarget.reset();await loadWallet()}catch(err){out.textContent=`수령 실패: ${err.message}`}});
$('#merchantRequestForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#merchantRequestResult');out.textContent='신청 중…';try{const d=await authApi('/merchant-requests',{method:'POST',body:JSON.stringify(formJson(e.currentTarget))});out.textContent=`신청 완료 · ${d.request.merchantName}`;e.currentTarget.reset();setIssuerOptions();populateWorkspaceSelects()}catch(err){out.textContent=`신청 실패: ${err.message}`}});

async function previewPay(intentId){const d=await authApi(`/qr-intents/${encodeURIComponent(intentId)}`);state.pendingPay=d.intent;const i=d.intent;$('#payPreview').classList.remove('muted');$('#payPreview').innerHTML=`<h2>결제 전 확인</h2><p><strong>${esc(i.merchant_name)}</strong></p><p>${esc(i.issuer_name)} · ${esc(i.program_name)}</p><div class="balance">${n(i.amount_minor)} ${esc(i.unit_name)}</div><p>내 잔액 ${n(i.balanceMinor)} ${esc(i.unit_name)}</p><p>유효시간 ${new Date(i.expires_at).toLocaleTimeString('ko-KR')}</p><button id="confirmPay" class="primary" ${i.canPay?'':'disabled'}>${i.canPay?'이 결제를 승인합니다':'잔액 부족 또는 만료'}</button>`;$('#confirmPay')?.addEventListener('click',confirmPay)}
async function confirmPay(){if(!state.pendingPay)return;const btn=$('#confirmPay');btn.disabled=true;try{const d=await authApi('/redeem',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({intentId:state.pendingPay.id})});$('#payPreview').innerHTML=`<h2 class="success">결제 완료</h2><p><strong>${esc(d.transaction.merchantName)}</strong></p><div class="balance">${n(d.transaction.amountMinor)} ${esc(d.transaction.unitName)}</div><p>남은 잔액 ${n(d.transaction.balanceMinor)} ${esc(d.transaction.unitName)}</p>`;state.pendingPay=null;await loadWallet()}catch(err){toast(`결제 실패: ${err.message}`);btn.disabled=false}}
$('#payPreviewForm').addEventListener('submit',e=>{e.preventDefault();previewPay(formJson(e.currentTarget).intentId).catch(err=>toast(`조회 실패: ${err.message}`))});

$('#merchantIssuer').addEventListener('change',async e=>{const issuerId=e.target.value;const allowed=(state.me?.merchants||[]).filter(m=>m.issuer_id===issuerId);$('#merchantSelect').innerHTML='<option value="">상점 선택</option>'+allowed.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');await fillPrograms($('#merchantProgram'),issuerId)});
$('#qrForm').addEventListener('submit',async e=>{e.preventDefault();try{const body=formJson(e.currentTarget);body.amountMinor=Number(body.amountMinor);const d=await authApi('/qr-intents',{method:'POST',body:JSON.stringify(body)});const payUrl=new URL('/local-commerce/',location.origin);payUrl.searchParams.set('pay',d.intent.id);const qr=`${cfg.qrRenderer||'https://quickchart.io/qr'}?size=280&text=${encodeURIComponent(payUrl.href)}`;const host=$('#qrResult');host.classList.remove('hidden');host.innerHTML=`<h2>${esc(d.intent.merchantName)} 결제요청</h2><img src="${esc(qr)}" alt="결제 QR"><div class="balance">${n(d.intent.amountMinor)}</div><p>5분 안에 스캔 · 만료 ${new Date(d.intent.expiresAt).toLocaleTimeString('ko-KR')}</p><code>${esc(d.intent.id)}</code><button id="copyIntent" type="button">코드 복사</button>`;$('#copyIntent').onclick=()=>navigator.clipboard?.writeText(d.intent.id).then(()=>toast('결제요청 코드를 복사했습니다.'))}catch(err){toast(`QR 생성 실패: ${err.message}`)}});

$('#issuerForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await authApi('/issuers',{method:'POST',body:JSON.stringify(formJson(e.currentTarget))});toast(`${d.issuer.name} 운영주체를 등록했습니다.`);e.currentTarget.reset();await loadIssuers();populateWorkspaceSelects()}catch(err){toast(`등록 실패: ${err.message}`)}});
$('#programForm').addEventListener('submit',async e=>{e.preventDefault();try{const body=formJson(e.currentTarget);body.budgetMinor=Number(body.budgetMinor||0);body.validFrom=toIso(body.validFrom);body.validTo=toIso(body.validTo);const d=await authApi('/programs',{method:'POST',body:JSON.stringify(body)});toast(`${d.program.name} 프로그램을 만들었습니다.`);e.currentTarget.reset();setIssuerOptions()}catch(err){toast(`생성 실패: ${err.message}`)}});
async function loadProgramPolicy(issuerId){const ps=$('#policyProgram'),ms=$('#policyMerchants'),out=$('#policyResult');ps.innerHTML='<option value="">\uD504\uB85C\uADF8\uB7A8 \uC120\uD0DD</option>';ms.innerHTML='';out.textContent='';if(!issuerId)return;try{const d=await authApi(`/dashboard?issuer=${encodeURIComponent(issuerId)}`);state.policyDashboard=d;ps.innerHTML='<option value="">\uD504\uB85C\uADF8\uB7A8 \uC120\uD0DD</option>'+(d.programs||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.status)}</option>`).join('');ms.innerHTML=(d.merchants||[]).filter(m=>m.status==='active').map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}catch(err){out.textContent=`\uC870\uD68C \uC2E4\uD328: ${err.message}`}}
function fillProgramPolicy(programId){const p=(state.policyDashboard?.programs||[]).find(x=>x.id===programId),form=$('#programPolicyForm');if(!p)return;let rules={};try{rules=JSON.parse(p.rules_json||'{}')}catch{}form.elements.status.value=p.status;form.elements.budgetMinor.value=Number(p.budget_minor||0);form.elements.validFrom.value=toLocalInput(p.valid_from);form.elements.validTo.value=toLocalInput(p.valid_to);form.elements.memberOnly.checked=rules.memberOnly===true;form.elements.maxTransactionMinor.value=Number(rules.maxTransactionMinor||0);form.elements.perUserRedemptionLimitMinor.value=Number(rules.perUserRedemptionLimitMinor||0);const allowed=new Set(Array.isArray(rules.allowedMerchantIds)?rules.allowedMerchantIds:[]);[...form.elements.allowedMerchantIds.options].forEach(o=>o.selected=allowed.has(o.value))}
$('#policyIssuer').addEventListener('change',e=>loadProgramPolicy(e.target.value));
$('#policyProgram').addEventListener('change',e=>fillProgramPolicy(e.target.value));
$('#programPolicyForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,out=$('#policyResult'),body={issuerId:f.elements.issuerId.value,programId:f.elements.programId.value,status:f.elements.status.value,budgetMinor:Number(f.elements.budgetMinor.value||0),validFrom:toIso(f.elements.validFrom.value),validTo:toIso(f.elements.validTo.value),rules:{memberOnly:f.elements.memberOnly.checked,maxTransactionMinor:Number(f.elements.maxTransactionMinor.value||0),perUserRedemptionLimitMinor:Number(f.elements.perUserRedemptionLimitMinor.value||0),allowedMerchantIds:[...f.elements.allowedMerchantIds.selectedOptions].map(o=>o.value)}};out.textContent='\uC800\uC7A5 \uC911…';try{await authApi('/programs/update',{method:'POST',body:JSON.stringify(body)});out.textContent='\uC6B4\uC601\uADDC\uCE59\uC744 \uC800\uC7A5\uD588\uC2B5\uB2C8\uB2E4.';await loadProgramPolicy(body.issuerId);$('#policyProgram').value=body.programId;fillProgramPolicy(body.programId)}catch(err){out.textContent=`\uC800\uC7A5 \uC2E4\uD328: ${err.message}`}});
$('#campaignIssuer').addEventListener('change',e=>fillPrograms($('#campaignProgram'),e.target.value));
$('#campaignForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#campaignResult');try{const body=formJson(e.currentTarget);body.valueMinor=Number(body.valueMinor);body.maxTotalClaims=Number(body.maxTotalClaims);const d=await authApi('/campaigns',{method:'POST',body:JSON.stringify(body)});out.innerHTML=`발행 완료 · 수령코드 <strong>${esc(d.campaign.claimCode)}</strong><br><small>이 코드는 지금 한 번만 표시됩니다.</small>`}catch(err){out.textContent=`발행 실패: ${err.message}`}});

async function loadMerchantRequests(){const issuerId=$('#requestIssuer').value,host=$('#merchantRequests');if(!issuerId){host.className='list empty';host.textContent='운영주체를 선택하세요.';return}try{const d=await authApi(`/merchant-requests?issuer=${encodeURIComponent(issuerId)}`);const rows=d.requests||[];if(!rows.length){host.className='list empty';host.textContent='신청 내역이 없습니다.';return}host.className='list';host.innerHTML=rows.map(r=>`<div class="list-row"><div><strong>${esc(r.merchant_name)}</strong><div>${esc(r.requested_by_email)} · ${esc(r.note||'')}</div></div><div><span>${esc(r.status)}</span>${r.status==='pending'?` <button data-approve="${esc(r.id)}">승인</button>`:''}</div></div>`).join('');$$('[data-approve]',host).forEach(b=>b.onclick=()=>approveMerchant(b.dataset.approve))}catch(err){host.className='list empty';host.textContent=`조회 불가: ${err.message}`}}
async function approveMerchant(id){try{const d=await authApi('/merchant-requests/approve',{method:'POST',body:JSON.stringify({requestId:id})});toast(`${d.merchant.name} 가맹점을 승인했습니다.`);await loadMerchantRequests()}catch(err){toast(`승인 실패: ${err.message}`)}}
$('#requestIssuer').addEventListener('change',loadMerchantRequests);

async function loadDashboard(){const issuerId=$('#settlementIssuer').value;if(!issuerId)return;try{const d=await authApi(`/dashboard?issuer=${encodeURIComponent(issuerId)}`);state.dashboard=d;$('#settlementSummary').innerHTML=`<article class="card"><small>프로그램</small><div class="balance">${d.programs.length}</div></article><article class="card"><small>가맹점</small><div class="balance">${d.merchants.length}</div></article><article class="card"><small>거래</small><div class="balance">${d.transactions.length}</div></article><article class="card"><small>자동송금</small><div class="balance">OFF</div></article>`;renderSettlements(d.settlements||[])}catch(err){$('#settlementSummary').innerHTML=`<article class="card muted">조회 불가: ${esc(err.message)}</article>`;$('#settlementList').innerHTML=''}}
function renderSettlements(rows){const host=$('#settlementList');if(!rows.length){host.className='list empty';host.textContent='정산 내역이 없습니다.';return}host.className='list';host.innerHTML=rows.map(s=>`<div class="list-row"><div><strong>${n(s.total_minor)} · ${s.transaction_count}건</strong><div>${esc(s.period_start)} ~ ${esc(s.period_end)}</div></div><div><span>${esc(s.status)}</span>${['draft','submitted'].includes(s.status)?` <button data-review="${esc(s.id)}">검토완료</button>`:''}${s.status==='reviewed'?` <button data-paid="${esc(s.id)}">외부지급 기록</button>`:''}</div></div>`).join('');$$('[data-review]',host).forEach(b=>b.onclick=()=>reviewSettlement(b.dataset.review));$$('[data-paid]',host).forEach(b=>b.onclick=()=>recordPaid(b.dataset.paid))}
$('#settlementIssuer').addEventListener('change',loadDashboard);
$('#settlementDraftForm').addEventListener('submit',async e=>{e.preventDefault();const issuerId=$('#settlementIssuer').value;if(!issuerId)return toast('운영주체를 선택하세요.');const raw=formJson(e.currentTarget);try{const body={issuerId,periodStart:new Date(raw.periodStart).toISOString(),periodEnd:new Date(raw.periodEnd).toISOString()};await authApi('/settlements/draft',{method:'POST',body:JSON.stringify(body)});toast('정산안을 만들었습니다.');await loadDashboard()}catch(err){toast(`정산안 생성 실패: ${err.message}`)}});
async function reviewSettlement(id){try{await authApi('/settlements/review',{method:'POST',body:JSON.stringify({settlementId:id})});toast('회계 검토를 완료했습니다.');await loadDashboard()}catch(err){toast(`검토 실패: ${err.message}`)}}
async function recordPaid(id){const ref=prompt('실제 외부 지급 확인번호 또는 회계 전표번호를 입력하세요.\nEKODI는 송금하지 않고 기록만 남깁니다.');if(!ref)return;try{await authApi('/settlements/paid-external',{method:'POST',headers:{'x-ekodi-confirm-impact':'confirm'},body:JSON.stringify({settlementId:id,externalReference:ref})});toast('외부 지급 사실을 기록했습니다.');await loadDashboard()}catch(err){toast(`기록 실패: ${err.message}`)}}

window.addEventListener('ekodi:local-commerce-account',async e=>{if(!e.detail.signedIn){state.me=null;state.wallets=[];renderWallet();renderLedger([]);$('#operatorTools').classList.add('hidden');$('#settlementTools').classList.add('hidden');return}try{await Promise.all([loadMe(),loadWallet()]);const pay=new URL(location.href).searchParams.get('pay');if(pay){$('#payIntentId').value=pay;activateTab('pay');await previewPay(pay)}}catch(err){console.error(err);toast(`계정 데이터 연결 실패: ${err.message}`)}});

loadIssuers();
