const state={catalog:null,mode:'user',persona:'small-business',service:'marketing',status:'all',step:1,room:null};
const $=selector=>document.querySelector(selector);const $$=selector=>Array.from(document.querySelectorAll(selector));const statusClass=status=>`status-${String(status||'').replace(/[^a-z-]/g,'')}`;
const icons={personal:'◉',church:'✦','small-business':'▣',business:'▥',organization:'●',project:'◆'};
const roomKinds=[
{id:'dashboard',label:'대시보드 룸',kicker:'MY EKODI',copy:'나의 활동과 중요한 흐름을 한눈에 살펴보는 공간입니다.'},
{id:'insight',label:'AI 인사이트 룸',kicker:'AI & DATA',copy:'합성 데이터를 바탕으로 AI가 어떤 도움을 주는지 체험합니다.'},
{id:'collab',label:'협업 워크룸',kicker:'WORK & RELATION',copy:'사람과 역할, 작업이 하나의 흐름으로 연결되는 공간입니다.'},
{id:'security',label:'보안 컨트롤 룸',kicker:'SECURE PROJECTION',copy:'원본을 노출하지 않고 목적에 필요한 모습만 투영하는 공간입니다.'}];
async function load(){const response=await fetch('/api/catalog',{headers:{accept:'application/json'}});if(!response.ok)throw new Error('catalog_unavailable');state.catalog=await response.json();if(location.pathname==='/developer')state.mode='developer';if(location.pathname==='/user')state.mode='user';render();initSceneMotion();initStarfield();bindStaticActions();}
function render(){renderModes();renderPersonas();renderWorkspace();renderRooms();renderStatus();renderProgress();}
function renderModes(){$$('.mode-card').forEach(button=>button.classList.toggle('is-active',button.dataset.mode===state.mode));$('#mode-description').textContent=state.mode==='user'?'하고 싶은 일을 중심으로 에코디를 체험합니다.':'실제 구현정보 없이 서비스의 역할·입력·처리·결과 관계만 안전하게 살펴봅니다.';$('#workspace-kicker').textContent=state.mode==='user'?'SYNTHETIC WORKSPACE':'SAFE X-RAY VIEW';}
function setMode(mode){state.mode=mode==='developer'?'developer':'user';state.step=Math.max(state.step,2);history.replaceState(null,'',state.mode==='developer'?'/developer':'/user');render();focusStep(2);}
function renderPersonas(){const root=$('#persona-grid'),mini=$('#persona-mini-grid');root.replaceChildren();mini.replaceChildren();for(const persona of state.catalog.personas){const button=document.createElement('button');button.type='button';button.className=`persona-card${persona.id===state.persona?' is-active':''}`;button.innerHTML=`<strong>${escapeHtml(persona.label)}</strong><span>${escapeHtml(persona.prompt)}</span><small>${escapeHtml(persona.sample)}</small>`;button.addEventListener('click',()=>selectPersona(persona.id));root.append(button);const m=document.createElement('button');m.type='button';m.className=`persona-mini${persona.id===state.persona?' is-active':''}`;m.innerHTML=`<span>${icons[persona.id]||'◇'}</span><b>${escapeHtml(persona.label)}</b>`;m.addEventListener('click',()=>selectPersona(persona.id));mini.append(m);}}
function selectPersona(id){state.persona=id;state.step=Math.max(state.step,3);const first=visibleServices()[0];if(first)state.service=first.id;render();focusStep(3);}
function visibleServices(){return state.catalog.services.filter(service=>service.personas.includes(state.persona));}
function renderWorkspace(){const persona=state.catalog.personas.find(item=>item.id===state.persona)||state.catalog.personas[0];$('#workspace-title').textContent=persona.sample;const services=visibleServices();if(!services.some(service=>service.id===state.service))state.service=services[0]?.id||'';const chips=$('#service-chip-grid');chips.replaceChildren();const nav=$('#service-list');nav.replaceChildren();for(const service of services){const mini=document.createElement('button');mini.type='button';mini.className=`service-mini${service.id===state.service?' is-active':''}`;mini.textContent=service.name;mini.title=service.name;mini.addEventListener('click',()=>selectService(service.id));chips.append(mini);const button=document.createElement('button');button.type='button';button.className=`service-tab${service.id===state.service?' is-active':''}`;button.innerHTML=`<span>${escapeHtml(service.name)}</span><small class="${statusClass(service.status)}">${escapeHtml(service.statusLabel)}</small>`;button.addEventListener('click',()=>selectService(service.id));nav.append(button);}renderStage(services.find(service=>service.id===state.service)||services[0]);}
function selectService(id){state.service=id;state.step=4;render();focusStep(4);}
function renderStage(service){const stage=$('#service-stage');if(!service){stage.innerHTML='<p>체험 가능한 서비스가 없습니다.</p>';return;}const top=`<div class="stage-top"><div><span class="service-group">${escapeHtml(service.group)}</span><h3>${escapeHtml(service.name)}</h3></div><span class="state-pill ${statusClass(service.status)}">${escapeHtml(service.statusLabel)}</span></div><p class="stage-summary">${escapeHtml(service.summary)}</p>`;if(state.mode==='developer'){stage.innerHTML=`${top}<div class="xray"><div class="xray-label">공개 가능한 관계 투영 · SAFE X-RAY</div>${service.flow.map((step,index)=>`<div class="xray-node"><span>${index+1}</span><strong>${escapeHtml(step)}</strong></div>${index<service.flow.length-1?'<div class="xray-arrow">↓</div>':''}`).join('')}</div><div class="boundary-note"><strong>보이지 않는 것</strong><span>소스코드 · 저장소 · 내부 API · DB · Worker · 인증 비밀 · 실제 고객 데이터</span></div>`;return;}stage.innerHTML=`${top}<div class="room-preview"><div class="room-preview-scene"></div><div class="room-preview-panel"><div class="preview-topline"><span>● SYNTHETIC LIVE PREVIEW</span><b>${escapeHtml(service.name)}</b></div><div class="preview-dashboard"><div class="preview-card"><strong>오늘의 흐름</strong><span>${metricFor(service.id,0)}</span><div class="preview-bars"><i style="height:38%"></i><i style="height:57%"></i><i style="height:74%"></i><i style="height:88%"></i><i style="height:66%"></i></div></div><div class="preview-card"><strong>연결된 단계</strong><span>${service.flow.length}</span><div class="dash-line"></div></div></div></div><div class="preview-actions"><small>${escapeHtml(simulationText(service.id))}</small><button class="enter-room" type="button" data-enter-room="${escapeHtml(service.id)}">공간 안으로 들어가기 →</button></div></div>`;stage.querySelector('[data-enter-room]')?.addEventListener('click',()=>openRoom(roomKinds[1],service));}
function metricFor(id,index){const seed=Array.from(String(id)).reduce((n,c)=>n+c.charCodeAt(0),0);return 8+((seed+index*7)%18);}
function simulationText(id){const map={marketing:'신메뉴 홍보 목적부터 콘텐츠와 채널 실행까지 이어지는 흐름을 살펴봅니다.',mall:'필요와 관계 맥락을 먼저 이해하고 추천 이유가 만들어지는 과정을 봅니다.',church:'가상의 교회 일정과 말씀 흐름을 기준으로 공동체의 다음 활동을 살펴봅니다.',invest:'프로젝트 자료가 정리되고 검토와 연결 준비로 이어지는 과정을 체험합니다.',my:'내 공간에서 여러 에코디 서비스가 하나의 여정으로 이어지는 모습을 봅니다.'};return map[id]||'가상의 상황을 바탕으로 이 서비스가 어떤 도움을 주는지 공간 안에서 확인합니다.';}
function renderRooms(){const root=$('#room-cards');root.replaceChildren();const current=visibleServices().find(service=>service.id===state.service)||visibleServices()[0];roomKinds.forEach(room=>{const card=document.createElement('article');card.className='room-card';card.tabIndex=0;card.innerHTML=`<div class="room-art"><span class="orb"></span><i class="screen s1"></i><i class="screen s2"></i></div><div class="room-card-content"><span>${escapeHtml(room.kicker)}</span><h3>${escapeHtml(room.label)}</h3><p>${escapeHtml(room.copy)}</p><b>→</b></div>`;const enter=()=>openRoom(room,current);card.addEventListener('click',enter);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();enter();}});root.append(card);});}
function openRoom(room,service){if(!room||!service)return;state.room={room,service};$('#immersive-room-kicker').textContent=`${room.kicker} · ${service.name}`;$('#immersive-room-title').textContent=room.label;$('#immersive-room-copy').textContent=`${room.copy} ${simulationText(service.id)}`;$('#room-dashboard').innerHTML=`<div class="dashboard-grid"><div class="dash-card"><small>활동</small><strong>${metricFor(service.id,1)}</strong><div class="dash-line"></div></div><div class="dash-card"><small>연결</small><strong>${service.flow.length}</strong><div class="dash-line" style="background:linear-gradient(90deg,#7ee7c2 72%,rgba(85,118,172,.25) 72%)"></div></div><div class="dash-card"><small>안전 상태</small><strong>SAFE</strong><div class="dash-line" style="background:linear-gradient(90deg,#8f78ff 90%,rgba(85,118,172,.25) 90%)"></div></div></div>`;const overlay=$('#room-overlay');overlay.hidden=false;document.body.classList.add('room-open');requestAnimationFrame(()=>overlay.querySelector('[data-close-room]')?.focus());}
function closeRoom(){$('#room-overlay').hidden=true;document.body.classList.remove('room-open');state.room=null;}
function renderStatus(){const groups=['all','live','beta','preparing','planned'];const labels={all:'전체',live:'운영 중',beta:'베타',preparing:'준비 중',planned:'계획'};const filters=$('#status-filters');filters.replaceChildren();groups.forEach(group=>{const b=document.createElement('button');b.type='button';b.textContent=labels[group];b.className=group===state.status?'is-active':'';b.addEventListener('click',()=>{state.status=group;renderStatus();});filters.append(b);});const root=$('#status-grid');root.replaceChildren();state.catalog.services.filter(service=>state.status==='all'||service.status===state.status).forEach(service=>{const card=document.createElement('article');card.className='status-card';card.innerHTML=`<div><span>${escapeHtml(service.group)}</span><strong>${escapeHtml(service.name)}</strong></div><small class="${statusClass(service.status)}">${escapeHtml(service.statusLabel)}</small><p>${escapeHtml(service.summary)}</p>`;root.append(card);});}
function renderProgress(){$$('#journey-progress button').forEach(button=>{const value=Number(button.dataset.jump);button.classList.toggle('is-active',value===state.step);button.querySelector('span').textContent=value<state.step?'✓':String(value);});$$('.journey-step').forEach(step=>step.classList.toggle('is-current',Number(step.dataset.step)===Math.min(state.step,3)));}
function focusStep(step){state.step=step;renderProgress();if(step===2||step===3)$('#journey-console')?.scrollIntoView({behavior:'smooth',block:'center'});if(step===4)$('#experience-map')?.scrollIntoView({behavior:'smooth',block:'start'});}
function bindStaticActions(){$$('.mode-card').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.mode)));$('#start-experience')?.addEventListener('click',()=>focusStep(1));$('#portal-scene')?.addEventListener('click',()=>focusStep(1));$('#view-guide')?.addEventListener('click',()=>$('#journey-console')?.scrollIntoView({behavior:'smooth',block:'center'}));$$('#journey-progress [data-jump]').forEach(button=>button.addEventListener('click',()=>focusStep(Number(button.dataset.jump))));$$('[data-close-room]').forEach(button=>button.addEventListener('click',closeRoom));$('#room-action')?.addEventListener('click',()=>{const service=state.room?.service;if(!service)return;const dashboard=$('#room-dashboard');if(dashboard.querySelector('.boundary-note'))return;dashboard.insertAdjacentHTML('beforeend',`<div class="boundary-note"><strong>가상 실행 완료</strong><span>${escapeHtml(service.name)}의 사용자 흐름을 합성 데이터로 체험했습니다. 실제 저장·결제·게시·메시지는 발생하지 않았습니다.</span></div>`);});$('#guide-bubble')?.addEventListener('click',()=>focusStep(state.step<4?state.step:1));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#room-overlay').hidden)closeRoom();});}
function initSceneMotion(){const scene=$('#portal-scene');if(!scene||matchMedia('(prefers-reduced-motion: reduce)').matches)return;scene.addEventListener('pointermove',event=>{const r=scene.getBoundingClientRect(),x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;scene.style.transform=`rotateY(${x*5}deg) rotateX(${-y*4}deg)`;});scene.addEventListener('pointerleave',()=>scene.style.transform='rotateY(0deg) rotateX(0deg)');}
function initStarfield(){const canvas=$('#experience-sky');if(!canvas||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=canvas.getContext('2d');let stars=[],raf=0;const resize=()=>{const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(150,Math.floor(innerWidth/9))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.2,s:Math.random()*.16+.03,a:Math.random()*.7+.15}));};const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){s.y+=s.s;if(s.y>innerHeight)s.y=0;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(170,210,255,${s.a})`;ctx.fill();}raf=requestAnimationFrame(draw);};resize();draw();addEventListener('resize',resize,{passive:true});addEventListener('pagehide',()=>cancelAnimationFrame(raf),{once:true});}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
load().catch(()=>{$('#experience-app').innerHTML='<section class="load-error"><h1>체험 정보를 불러오지 못했습니다.</h1><p>잠시 후 다시 열어 주세요.</p></section>';});