(()=>{const root=document.querySelector('[data-collab-editor]');if(!root)return;
const api='/ekodimission/api/collab';const token=location.hash.replace(/^#/,'').trim();const form=root.querySelector('[data-collab-form]');const editor=root.querySelector('[data-editor-name]');const save=root.querySelector('[data-save-state]');const revEl=root.querySelector('[data-revision-state]');const conn=root.querySelector('[data-connection-state]');const pubEl=root.querySelector('[data-publish-state]');const publish=root.querySelector('[data-publish]');const history=root.querySelector('[data-history-list]');let revision=0,baseline=null,permission='view',loading=false,timer=null,poll=null;
editor.value=localStorage.getItem('ekodi-collab-editor-name')||'';editor.addEventListener('input',()=>localStorage.setItem('ekodi-collab-editor-name',editor.value.trim()));
const rpc=async(action,extra={})=>{const r=await fetch(api,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},credentials:'same-origin',body:JSON.stringify({action,token,...extra})});const data=await r.json().catch(()=>({}));if(!r.ok||data?.error)throw new Error(data.message||'공동편집 연결을 확인해 주세요.');return data};
const asText=v=>String(v??'');const lodgingText=x=>[x?.name,x?.room,x?.capacity,x?.note].filter(Boolean).join(' · ');
function toFields(content={}){const s=Array.isArray(content.schedule)?content.schedule:[];const l=Array.isArray(content.lodging)?content.lodging:[];return{title:asText(content.title),theme:asText(content.theme),summary:asText(content.summary),capacity:Number(content.capacity||10),fee_krw:Number(content.fee_krw||0),fee_note:asText(content.fee_note),departure:asText(content.departure),return:asText(content.return),worship:asText(content.worship),schedule_1:asText(s[0]?.text),schedule_2:asText(s[1]?.text),lodging_1:lodgingText(l[0]),lodging_2:lodgingText(l[1]),notice:asText(content.notice)}}
function fromFields(){const f=new FormData(form);return{title:asText(f.get('title')).trim(),theme:asText(f.get('theme')).trim(),summary:asText(f.get('summary')).trim(),capacity:Number(f.get('capacity')||10),fee_krw:Number(f.get('fee_krw')||0),fee_note:asText(f.get('fee_note')).trim(),departure:asText(f.get('departure')).trim(),return:asText(f.get('return')).trim(),worship:asText(f.get('worship')).trim(),schedule:[{day:'10월 3일',text:asText(f.get('schedule_1')).trim()},{day:'10월 4일',text:asText(f.get('schedule_2')).trim()}],lodging:[{priority:1,name:asText(f.get('lodging_1')).trim(),room:'',capacity:'',note:''},{priority:2,name:asText(f.get('lodging_2')).trim(),room:'',capacity:'',note:''}],notice:asText(f.get('notice')).trim()}}
function fill(content){const values=toFields(content);for(const [k,v] of Object.entries(values)){const el=form.elements.namedItem(k);if(el)el.value=v}baseline=content}
function renderHistory(items=[]){history.replaceChildren(...(items.length?items.map(item=>{const li=document.createElement('li');li.textContent=`v${item.revision} · ${item.action==='publish'?'게시':'수정'} · ${item.editor_name||'익명'} `;const small=document.createElement('small');small.textContent=new Date(item.created_at).toLocaleString('ko-KR');li.append(small);return li}):[Object.assign(document.createElement('li'),{textContent:'변경 이력이 없습니다.'})]))}
function lock(){const locked=permission==='view';form.classList.toggle('collab-locked',locked);for(const el of form.querySelectorAll('input,textarea'))el.disabled=locked;publish.hidden=permission!=='owner'}
async function load(force=false){if(loading||!token)return;loading=true;try{const data=await rpc('snapshot');conn.textContent='공동편집 연결됨';permission=data.permission||'view';revEl.textContent=`초안 v${data.revision} · 게시 v${data.published_revision||0}`;pubEl.textContent=permission==='owner'?'게시 권한':'편집 권한';if(force||!baseline||data.revision!==revision){const local=baseline?fromFields():null;if(!force&&baseline&&JSON.stringify(local)!==JSON.stringify(baseline)){save.dataset.state='error';save.textContent='다른 편집자의 새 버전이 있습니다. 현재 입력을 저장하거나 최신본 불러오기를 선택하세요.'}else{revision=data.revision;fill(data.draft||{});save.dataset.state='success';save.textContent='최신 초안을 불러왔습니다.'}}renderHistory(data.history||[]);lock()}catch(e){conn.textContent='연결 실패';save.dataset.state='error';save.textContent=e.message}finally{loading=false}}
function changedKeys(a,b){const keys=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);return [...keys].filter(k=>JSON.stringify(a?.[k])!==JSON.stringify(b?.[k]))}
async function persist(){if(permission==='view'||!baseline)return;const local=fromFields();if(JSON.stringify(local)===JSON.stringify(baseline))return;save.dataset.state='';save.textContent='초안 저장 중…';try{let data=await rpc('update',{editorName:editor.value.trim()||'익명',content:local,expectedRevision:revision});if(data.conflict){const snap=await rpc('snapshot');const server=snap.draft||{};const mine=changedKeys(baseline,local);const theirs=changedKeys(baseline,server);const overlap=mine.filter(k=>theirs.includes(k));if(overlap.length){revision=snap.revision;fill(server);renderHistory(snap.history||[]);save.dataset.state='error';save.textContent='같은 항목을 다른 편집자가 먼저 수정했습니다. 최신본을 불러왔으니 다시 확인해 주세요.';return}const merged={...server};for(const k of mine)merged[k]=local[k];data=await rpc('update',{editorName:editor.value.trim()||'익명',content:merged,expectedRevision:snap.revision});if(!data.ok)throw new Error('동시 수정 충돌이 다시 발생했습니다. 최신본을 불러와 주세요.');revision=data.revision;fill(merged)}else{revision=data.revision;fill(local)}revEl.textContent=`초안 v${revision}`;save.dataset.state='success';save.textContent='초안 자동 저장 완료';await load(true)}catch(e){save.dataset.state='error';save.textContent=e.message}}
form.addEventListener('input',()=>{if(permission==='view')return;clearTimeout(timer);save.dataset.state='';save.textContent='수정 중…';timer=setTimeout(persist,850)});
root.querySelector('[data-reload]').addEventListener('click',()=>load(true));
publish.addEventListener('click',async()=>{if(permission!=='owner')return;await persist();if(!confirm('현재 초안을 에코디선교회 홈페이지에 게시할까요?'))return;try{const data=await rpc('publish',{editorName:editor.value.trim()||'관리자',expectedRevision:revision});if(data.conflict){await load(true);throw new Error('새 수정본이 있어 게시하지 않았습니다. 최신본을 확인해 주세요.')}save.dataset.state='success';save.textContent='홈페이지 게시가 완료되었습니다.';pubEl.textContent=`게시 v${data.revision}`;await load(true)}catch(e){save.dataset.state='error';save.textContent=e.message}});
if(!token){conn.textContent='편집 토큰 없음';save.dataset.state='error';save.textContent='올바른 공동편집 링크로 접속해 주세요.';form.classList.add('collab-locked');return}load(true);poll=setInterval(()=>load(false),3000);window.addEventListener('beforeunload',()=>clearInterval(poll));})();