const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Number(n||0));
const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:'#'}catch{return'#'}};
async function loadData(){const r=await fetch('/seonam-med/assets/data.json',{cache:'no-store'});if(!r.ok)throw new Error('data');return r.json()}
function renderStatus(data){$('#lastChecked').textContent='최종 점검 '+(data.lastChecked||'미확인');$('#statusCards').innerHTML=(data.status||[]).map(x=>`<article><small>${x.label}</small><strong>${x.value}</strong><p>${x.note||''}</p></article>`).join('')}
function renderTimeline(data,filter='all'){const rows=(data.timeline||[]).filter(x=>filter==='all'||x.type===filter);$('#timeline').innerHTML=rows.map(x=>`<li><time>${x.date}</time><div><h3>${x.title}</h3><p>${x.summary}</p><div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}${x.source?`<a class="source-link" href="${safeUrl(x.source)}" target="_blank" rel="noopener">출처 보기</a>`:''}</div></div></li>`).join('')}
function renderNews(data){$('#newsList').innerHTML=(data.news||[]).map(x=>`<article class="news-item"><time>${x.date}</time><a href="${safeUrl(x.url)}" target="_blank" rel="noopener">${x.title}</a><small>${x.publisher} · ${x.kind}</small></article>`).join('')}
function renderFinance(data){const f=data.finance||{};$('#totalIncome').textContent=money(f.income);$('#totalExpense').textContent=money(f.expense);$('#balance').textContent=money((f.income||0)-(f.expense||0));$('#financeUpdated').textContent=f.updated||'등록 전';const rows=f.entries||[];$('#financeList').innerHTML=rows.length?rows.map(x=>`<div class="finance-row"><span>${x.date}</span><strong>${x.kind}</strong><span>${x.memo}</span><span>${money(x.amount)}</span></div>`).join(''):'<div class="notice">공개 승인된 회계내역이 아직 등록되지 않았습니다.</div>'}
let DATA=null;
loadData().then(d=>{DATA=d;renderStatus(d);renderTimeline(d);renderNews(d);renderFinance(d)}).catch(()=>{$('#lastChecked').textContent='자료를 불러오지 못했습니다.'});
$('#historyFilters')?.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b||!DATA)return;document.querySelectorAll('#historyFilters button').forEach(x=>x.classList.toggle('active',x===b));renderTimeline(DATA,b.dataset.filter)});
$('#voiceForm')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#voiceStatus');const fd=new FormData(form);const body={category:fd.get('category'),name:fd.get('name'),contact:fd.get('contact'),message:fd.get('message'),website:fd.get('website'),publicConsent:fd.get('publicConsent')==='on',privacyConsent:fd.get('privacyConsent')==='on'};status.textContent='접수 중…';try{const r=await fetch('/seonam-med/api/voices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'접수 실패');status.textContent='접수되었습니다. 검토 후 필요한 경우 답변하거나 공개합니다.';form.reset()}catch(err){status.textContent=err.message||'접수하지 못했습니다.'}});
