const enc=new TextEncoder();
const now=()=>new Date().toISOString();
const clean=(v,n=12000)=>String(v??'').trim().slice(0,n);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:headers('application/json; charset=utf-8')});
function headers(type='text/html; charset=utf-8'){return {'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-frame-options':'SAMEORIGIN','content-security-policy':"default-src 'self'; style-src 'unsafe-inline' 'self'; script-src 'unsafe-inline' 'self'; connect-src 'self'; img-src 'self' data: blob:; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; object-src 'none'"}}
function boardPath(path){return path==='/board'||path==='/board/'?'/':path.startsWith('/board/')?path.slice(6):path}
async function ekodiIdentity(req,env){const auth=clean(req.headers.get('authorization'),8192);if(!auth.toLowerCase().startsWith('bearer '))return null;const token=auth.slice(7).trim();if(!token||!env.EKODI_SUPABASE_URL||!env.EKODI_SUPABASE_KEY)return null;try{const r=await fetch(env.EKODI_SUPABASE_URL+'/auth/v1/user',{headers:{apikey:env.EKODI_SUPABASE_KEY,authorization:'Bearer '+token}});if(!r.ok)return null;const u=await r.json();return u?.id?{subject:String(u.id),email:clean(u.email,320),displayName:clean(u.user_metadata?.name||u.user_metadata?.full_name||u.email?.split('@')[0]||'사용자',80)}:null}catch{return null}}
function adminEmails(env){return new Set(clean(env.BOARD_ADMIN_EMAILS,4000).toLowerCase().split(',').map(v=>v.trim()).filter(Boolean))}
async function member(req,env){const id=await ekodiIdentity(req,env);if(!id)return null;const t=now(),seedAdmin=adminEmails(env).has(id.email.toLowerCase());await env.BOARD_DB.prepare("INSERT INTO board_members(subject,email,display_name,role,status,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?) ON CONFLICT(subject) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,updated_at=excluded.updated_at").bind(id.subject,id.email,id.displayName,seedAdmin?'admin':'member',t,t).run();const row=await env.BOARD_DB.prepare('SELECT subject,email,display_name,role,status FROM board_members WHERE subject=?').bind(id.subject).first();return row?.status==='active'?row:null}
const isAdmin=m=>m?.role==='admin'||m?.role==='moderator';
async function audit(env,m,action,type,id=''){await env.BOARD_DB.prepare('INSERT INTO board_audit(actor_subject,action,resource_type,resource_id,created_at) VALUES(?,?,?,?,?)').bind(m.subject,action,type,String(id),now()).run()}
async function list(env,url){const q=clean(url.searchParams.get('q'),120);let sql="SELECT id,owner_subject,author_name,title,body,created_at,updated_at FROM board_posts WHERE status='published'",args=[];if(q){sql+=' AND (title LIKE ? OR body LIKE ?)';args=[`%${q}%`,`%${q}%`]}sql+=' ORDER BY id DESC LIMIT 100';const posts=(await env.BOARD_DB.prepare(sql).bind(...args).all()).results||[];const replies=(await env.BOARD_DB.prepare('SELECT id,post_id,owner_subject,author_name,body,created_at FROM board_replies ORDER BY id').all()).results||[];const files=(await env.BOARD_DB.prepare('SELECT id,post_id,name,content_type,size FROM board_files ORDER BY created_at').all()).results||[];return json({ok:true,boardId:env.BOARD_ID,posts:posts.map(p=>({...p,replies:replies.filter(r=>r.post_id===p.id),files:files.filter(f=>f.post_id===p.id)}))})}
async function parseJson(req){try{return await req.json()}catch{return{}}}
async function requireMember(req,env){const m=await member(req,env);return m||json({ok:false,error:'ekodi_auth_required'},401)}
async function removePost(env,id){const fs=(await env.BOARD_DB.prepare('SELECT object_key FROM board_files WHERE post_id=?').bind(id).all()).results||[];for(const f of fs)if(f.object_key)await env.BOARD_FILES.delete(f.object_key);await env.BOARD_DB.prepare('DELETE FROM board_files WHERE post_id=?').bind(id).run();await env.BOARD_DB.prepare('DELETE FROM board_replies WHERE post_id=?').bind(id).run();await env.BOARD_DB.prepare('DELETE FROM board_posts WHERE id=?').bind(id).run()}
function page(){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>시민의견</title><style>body{margin:0;font-family:system-ui,sans-serif;color:#111;background:#fff}main{max-width:920px;margin:auto;padding:12px}h1{font-size:22px;margin:0 0 8px}.bar,form,.post{border:1px solid #ddd;padding:12px;margin:8px 0}input,textarea,button{font:inherit;padding:9px;border:1px solid #bbb;background:#fff}input,textarea{box-sizing:border-box;width:100%;margin:4px 0}button{cursor:pointer}small{color:#666}.post h2{font-size:17px;margin:0 0 6px}.reply{margin:6px 0 0 18px;padding:6px;border-left:2px solid #ddd}.actions{display:flex;gap:6px;flex-wrap:wrap}.hidden{display:none}</style></head><body><main><h1>시민의견</h1><div class="bar"><span id="who">EKODI 로그인 확인 중…</span></div><form id="write"><input name="title" maxlength="160" placeholder="제목" required><textarea name="body" maxlength="12000" rows="4" placeholder="의견" required></textarea><input name="files" type="file" multiple><button>등록</button></form><form id="search"><input name="q" placeholder="검색"><button>검색</button></form><div id="list"></div></main><script>
const KEY='sb-renzehysxirjilvdxacv-auth-token';let me=null;
function token(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');const s=p?.currentSession||p?.session||p;return String(s?.access_token||'')}catch{return''}}
const H=()=>({authorization:'Bearer '+token(),'content-type':'application/json'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const h=new Headers(opt.headers||{});if(token())h.set('authorization','Bearer '+token());if(opt.body&&!(opt.body instanceof FormData)&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch('/board'+path,{...opt,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'request_failed');return b}
async function load(q=''){try{const b=await api('/api/posts'+(q?'?q='+encodeURIComponent(q):''));document.querySelector('#list').innerHTML=b.posts.map(p=>'<article class="post" data-id="'+p.id+'"><h2>'+esc(p.title)+'</h2><small>'+esc(p.author_name)+' · '+esc(p.created_at)+'</small><p>'+esc(p.body).replace(/\n/g,'<br>')+'</p>'+p.files.map(f=>'<a href="/board/api/files/'+encodeURIComponent(f.id)+'">'+esc(f.name)+'</a>').join(' ')+'<div>'+p.replies.map(r=>'<div class="reply"><b>'+esc(r.author_name)+'</b> '+esc(r.body)+'</div>').join('')+'</div><form data-reply><input name="body" maxlength="6000" placeholder="답글" required><button>답글</button></form><div class="actions">'+(me&&(me.subject===p.owner_subject||['admin','moderator'].includes(me.role))?'<button data-delete type="button">삭제</button>':'')+'</div></article>').join('')}catch(e){document.querySelector('#list').textContent=e.message}}
async function init(){try{me=(await api('/api/me')).member;document.querySelector('#who').textContent=me.display_name+' · EKODI 인증';document.querySelector('#write').classList.remove('hidden');await load()}catch{document.querySelector('#who').textContent='EKODI 로그인이 필요합니다.';document.querySelector('#write').classList.add('hidden');await load()}}
document.querySelector('#write').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const p=await api('/api/posts',{method:'POST',body:JSON.stringify({title:f.get('title'),body:f.get('body')})});for(const file of f.getAll('files'))if(file.size){const fd=new FormData();fd.set('file',file);await api('/api/posts/'+p.id+'/files',{method:'POST',body:fd})}e.target.reset();await load()};
document.querySelector('#search').onsubmit=e=>{e.preventDefault();load(new FormData(e.target).get('q'))};
document.querySelector('#list').onsubmit=async e=>{const f=e.target.closest('[data-reply]');if(!f)return;e.preventDefault();const id=f.closest('[data-id]').dataset.id;await api('/api/posts/'+id+'/replies',{method:'POST',body:JSON.stringify({body:new FormData(f).get('body')})});await load()};
document.querySelector('#list').onclick=async e=>{if(!e.target.matches('[data-delete]'))return;const id=e.target.closest('[data-id]').dataset.id;if(confirm('삭제할까요?')){await api('/api/posts/'+id,{method:'DELETE'});await load()}};
init();</script></body></html>`}
export default {async fetch(req,env){const url=new URL(req.url),path=boardPath(url.pathname);
if(path==='/')return new Response(page(),{headers:headers()});
if(path==='/health')return json({ok:true,service:'independent-board',boardId:env.BOARD_ID,auth:'ekodi-only',db:Boolean(env.BOARD_DB),files:Boolean(env.BOARD_FILES)});
if(path==='/api/posts'&&req.method==='GET')return list(env,url);
if(path==='/api/me'&&req.method==='GET'){const m=await requireMember(req,env);if(m instanceof Response)return m;return json({ok:true,member:m})}
if(path==='/api/posts'&&req.method==='POST'){const m=await requireMember(req,env);if(m instanceof Response)return m;const b=await parseJson(req),title=clean(b.title,160),content=clean(b.body,12000);if(!title||!content)return json({ok:false,error:'required_fields'},400);const t=now(),r=await env.BOARD_DB.prepare('INSERT INTO board_posts(owner_subject,author_name,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(m.subject,m.display_name,title,content,t,t).run();await audit(env,m,'create','post',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201)}
const reply=path.match(/^\/api\/posts\/(\d+)\/replies$/);if(reply&&req.method==='POST'){const m=await requireMember(req,env);if(m instanceof Response)return m;const b=await parseJson(req),content=clean(b.body,6000);if(!content)return json({ok:false,error:'required_fields'},400);const post=await env.BOARD_DB.prepare("SELECT id FROM board_posts WHERE id=? AND status='published'").bind(+reply[1]).first();if(!post)return json({ok:false,error:'not_found'},404);const r=await env.BOARD_DB.prepare('INSERT INTO board_replies(post_id,owner_subject,author_name,body,created_at) VALUES(?,?,?,?,?)').bind(post.id,m.subject,m.display_name,content,now()).run();await audit(env,m,'create','reply',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201)}
const postPath=path.match(/^\/api\/posts\/(\d+)$/);if(postPath&&req.method==='DELETE'){const m=await requireMember(req,env);if(m instanceof Response)return m;const p=await env.BOARD_DB.prepare('SELECT id,owner_subject FROM board_posts WHERE id=?').bind(+postPath[1]).first();if(!p)return json({ok:false,error:'not_found'},404);if(p.owner_subject!==m.subject&&!isAdmin(m))return json({ok:false,error:'forbidden'},403);await removePost(env,p.id);await audit(env,m,'delete','post',p.id);return json({ok:true})}
const upload=path.match(/^\/api\/posts\/(\d+)\/files$/);if(upload&&req.method==='POST'){const m=await requireMember(req,env);if(m instanceof Response)return m;const p=await env.BOARD_DB.prepare('SELECT id,owner_subject FROM board_posts WHERE id=?').bind(+upload[1]).first();if(!p)return json({ok:false,error:'not_found'},404);if(p.owner_subject!==m.subject&&!isAdmin(m))return json({ok:false,error:'forbidden'},403);const form=await req.formData(),file=form.get('file');if(!(file instanceof File)||file.size<1||file.size>10*1024*1024)return json({ok:false,error:'invalid_file'},400);const allowed=/^(image\/(jpeg|png|gif|webp)|application\/pdf|text\/plain)$/i;if(!allowed.test(file.type||''))return json({ok:false,error:'file_type_denied'},415);const id=crypto.randomUUID(),key=env.BOARD_ID+'/'+p.id+'/'+id;await env.BOARD_FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await env.BOARD_DB.prepare('INSERT INTO board_files(id,post_id,owner_subject,object_key,name,content_type,size,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,p.id,m.subject,key,clean(file.name,240),file.type,file.size,now()).run();await audit(env,m,'upload','file',id);return json({ok:true,id},201)}
const filePath=path.match(/^\/api\/files\/([A-Za-z0-9-]+)$/);if(filePath&&req.method==='GET'){const f=await env.BOARD_DB.prepare('SELECT object_key,name,content_type FROM board_files WHERE id=?').bind(filePath[1]).first();if(!f)return json({ok:false,error:'not_found'},404);const obj=await env.BOARD_FILES.get(f.object_key);if(!obj)return json({ok:false,error:'not_found'},404);return new Response(obj.body,{headers:{...headers(f.content_type),'content-disposition':"inline; filename*=UTF-8''"+encodeURIComponent(f.name)}})}
if(path==='/api/admin/backup'&&req.method==='POST'){const m=await requireMember(req,env);if(m instanceof Response)return m;if(!isAdmin(m))return json({ok:false,error:'forbidden'},403);const [posts,replies,files,members]=await Promise.all(['board_posts','board_replies','board_files','board_members'].map(t=>env.BOARD_DB.prepare('SELECT * FROM '+t).all()));const key='backups/'+env.BOARD_ID+'/'+now().replace(/[:.]/g,'-')+'.json';await env.BOARD_FILES.put(key,JSON.stringify({version:1,createdAt:now(),posts:posts.results,replies:replies.results,files:files.results,members:members.results}),{httpMetadata:{contentType:'application/json'}});await audit(env,m,'backup','board',key);return json({ok:true,key})}
return json({ok:false,error:'not_found'},404)}};