import { rankCircles, rankPeople, recommendationBasis } from './recommendation-lens.js';

const SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const COMMUNITY_API=`${SUPABASE_URL}/functions/v1/community-api`;
const sb=window.supabase.createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const state={session:null,profile:null,circles:[],people:[],filter:'all',role:''};
const PRESETS={
  interests:['성경공부','기도','찬양','선교','외국인교류','청년','지역활동','봉사','독서','AI','소상공인','한국어','영어','여행','음악','영상','육아','도시재생'],
  offers:['한국어','영어','찬양','영상촬영','영상편집','디자인','컴퓨터','경영','마케팅','상담','운전','요리','성경공부','지역안내'],
  learns:['한국어','영어','AI','영상편집','디자인','악기','성경','마케팅','창업','한국문화','요리','운동'],
  languages:['한국어','English','中文','Tiếng Việt','ខ្មែរ','नेपाली','Монгол','Русский']
};
const demoCircles=[
  {id:'demo1',name:'함께하는 식탁',summary:'지역 주민과 외국인 유학생이 한 달에 한 번 식사를 나누며 언어와 삶을 교환합니다.',category:'global',tags:['외국인교류','한국어','지역활동'],mode:'offline',schedule_text:'월 1회',member_count:8,match_score:0},
  {id:'demo2',name:'AI 작은가게 Lab',summary:'소상공인이 AI를 실제 가게 운영과 콘텐츠에 적용해 보고 서로 사례를 나누는 실험 모임입니다.',category:'learning',tags:['AI','소상공인','마케팅'],mode:'hybrid',schedule_text:'격주',member_count:11,match_score:0},
  {id:'demo3',name:'말씀과 산책 Circle',summary:'짧은 말씀을 읽고 함께 걸으며 일상과 신앙을 부담 없이 나누는 열린 모임입니다.',category:'faith',tags:['성경공부','기도','지역활동'],mode:'offline',schedule_text:'월 2회',member_count:6,match_score:0}
];
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function setSignedIn(on){$$('.signed-in-only').forEach(el=>{el.hidden=!on});$$('.signed-out-only').forEach(el=>{el.hidden=on});$('#loginBtn').textContent=on?'로그아웃':'Google로 시작';$('#profileBtn').hidden=!on}
function login(){const auth=new URL('https://auth.ekodi.kr/');auth.searchParams.set('site','community');auth.searchParams.set('return_to',location.href.split('#')[0]);location.assign(auth.href)}
async function logout(){await sb.auth.signOut();state.session=null;state.profile=null;state.circles=[];state.people=[];setSignedIn(false);renderCircles(demoCircles);toast('로그아웃했습니다.')}
async function exchangeCentralToken(){const p=new URLSearchParams(location.hash.slice(1)),token=p.get('ekodi_token'),type=p.get('ekodi_type')||'email';if(!token)return;try{const {error}=await sb.auth.verifyOtp({token_hash:token,type});if(error)throw error;history.replaceState(null,'',location.pathname+location.search);toast('Community에 연결되었습니다.')}catch(e){console.error(e);toast('로그인 연결을 완료하지 못했습니다. 다시 시도해 주세요.')}}
async function api(path,options={}){const session=state.session||(await sb.auth.getSession()).data.session;if(!session)throw new Error('login_required');const headers={apikey:PUBLISHABLE_KEY,authorization:`Bearer ${session.access_token}`,...(options.headers||{})};if(options.body&&!headers['content-type'])headers['content-type']='application/json';const r=await fetch(`${COMMUNITY_API}${path}`,{...options,headers,cache:'no-store'});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw Object.assign(new Error(data.error||`http_${r.status}`),{status:r.status,data});return data}
function openModal(id){const el=$(id);if(!el)return;el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModals(){$$('.modal.open').forEach(el=>{el.classList.remove('open');el.setAttribute('aria-hidden','true')});document.body.classList.remove('modal-open')}
function makeChoice(host,values,name){host.replaceChildren();values.forEach(v=>{const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='checkbox';input.name=name;input.value=v;const span=document.createElement('span');span.textContent=v;label.append(input,span);host.append(label)})}
function selected(form,name){return $$(`input[name="${name}"]:checked`,form).map(x=>x.value)}
function fillChoices(name,values){$$(`input[name="${name}"]`,$('#profileForm')).forEach(el=>{el.checked=values.includes(el.value)})}
function categoryLabel(v){return({faith:'Faith',culture:'Culture',learning:'Learning',local:'Local',global:'Diaspora',life:'Life',general:'Community'})[v]||v||'Community'}
function modeLabel(v){return v==='online'?'온라인':v==='offline'?'오프라인':'온·오프라인'}
function recommendationContext(){return {role:state.role||document.documentElement.dataset.ekodiUserRole||''}}
function updateRecommendationCopy(){if(!state.profile)return;const basis=recommendationBasis(state.profile,recommendationContext());$('#welcomeCopy').textContent=basis.length?`${basis.join(' · ')} 기준으로 Circle과 사람의 추천 순서를 조정했습니다.`:'관심사를 추가하면 더 좋은 연결을 추천할 수 있습니다.'}
function renderInterestCloud(){const host=$('#myInterestCloud');host.replaceChildren();(state.profile?.interests||[]).slice(0,8).forEach(v=>{const s=document.createElement('span');s.className='chip match';s.textContent=v;host.append(s)})}
function renderFilters(circles){const host=$('#circleFilters');const tags=[...new Set(circles.flatMap(c=>c.tags||[]))].slice(0,12);host.replaceChildren();['all',...tags].forEach(v=>{const b=document.createElement('button');b.type='button';b.className=`filter-chip${state.filter===v?' active':''}`;b.textContent=v==='all'?'추천순':v;b.addEventListener('click',()=>{state.filter=v;renderFilters(circles);renderCircles(circles)});host.append(b)})}
function circleCard(c){const card=document.createElement('article');card.className='circle-card';const top=document.createElement('div');top.className='card-top';const cat=document.createElement('span');cat.className='category';cat.textContent=categoryLabel(c.category);top.append(cat);if(c.recommendation_reasons?.length||c.match_score>0){const m=document.createElement('span');m.className='match-badge';m.textContent=c.recommendation_reasons?.[0]||'관심 연결';top.append(m)}const h=document.createElement('h3');h.textContent=c.name;const p=document.createElement('p');p.textContent=c.summary||c.purpose||'함께 만들어 가는 EKODI Circle입니다.';const tags=document.createElement('div');tags.className='tag-row';(c.tags||[]).slice(0,5).forEach(v=>{const s=document.createElement('span');s.className='tag';s.textContent=v;tags.append(s)});const meta=document.createElement('div');meta.className='card-meta';const a=document.createElement('span');a.textContent=`${modeLabel(c.mode)} · ${c.schedule_text||'일정 조율'}`;const b=document.createElement('span');b.textContent=`${c.member_count||0}명`;meta.append(a,b);card.append(top,h,p,tags);if(c.recommendation_reasons?.length){const why=document.createElement('div');why.className='why recommendation-why';why.textContent=`추천 이유 · ${c.recommendation_reasons.join(' / ')}`;card.append(why)}card.append(meta);const actions=document.createElement('div');actions.className='card-actions';const share=document.createElement('button');share.type='button';share.textContent='공유';share.addEventListener('click',()=>shareCircle(c));const join=document.createElement('button');join.type='button';join.className='join';if(!state.session){join.textContent='로그인 후 참여';join.addEventListener('click',login)}else if(c.my_membership?.status==='active'){join.textContent='참여 중';join.disabled=true}else if(c.my_membership?.status==='pending'){join.textContent='승인 대기';join.disabled=true}else{join.textContent=c.join_policy==='open'?'바로 참여':'참여 신청';join.addEventListener('click',()=>joinCircle(c,join))}actions.append(share,join);card.append(actions);return card}
function renderCircles(list=state.circles.length?state.circles:demoCircles){const host=$('#circleGrid'),ranked=state.session&&state.profile?rankCircles(list,state.profile,recommendationContext()):list,filtered=state.filter==='all'?ranked:ranked.filter(c=>(c.tags||[]).includes(state.filter));host.replaceChildren();filtered.forEach(c=>host.append(circleCard(c)));$('#circleEmpty').hidden=filtered.length>0;renderFilters(ranked)}
async function joinCircle(circle,button){if(String(circle.id).startsWith('demo'))return login();button.disabled=true;try{const data=await api(`/circles/${circle.id}/join`,{method:'POST',body:'{}'});circle.my_membership=data.membership;circle.member_count=(circle.member_count||0)+(data.membership.status==='active'?1:0);toast(data.membership.status==='active'?'Circle에 참여했습니다.':'참여 신청을 보냈습니다.');renderCircles()}catch(e){console.error(e);button.disabled=false;toast(e.message==='circle_full'?'정원이 가득 찼습니다.':'참여 신청을 처리하지 못했습니다.')}}
async function shareCircle(c){const url=String(c.id).startsWith('demo')?location.href:`${location.origin}/?circle=${encodeURIComponent(c.id)}`;const data={title:`${c.name} · Community`,text:c.summary||'함께할 사람을 찾고 있습니다.',url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.title}\n${url}`);toast('공유 링크를 복사했습니다.')}}catch(e){if(e?.name!=='AbortError')toast('공유 링크를 복사하지 못했습니다.')}}
function renderPeople(){const host=$('#peopleGrid'),people=state.session&&state.profile?rankPeople(state.people,state.profile,recommendationContext()):state.people;host.replaceChildren();people.forEach(p=>{const card=document.createElement('article');card.className='person-card';const head=document.createElement('div');head.className='person-head';const av=document.createElement('span');av.className='avatar';av.textContent=(p.display_name||'?').trim().charAt(0).toUpperCase();const t=document.createElement('div');const h=document.createElement('h3');h.textContent=p.display_name||'Community member';const s=document.createElement('small');s.textContent=p.region||'지역 공개 안 함';t.append(h,s);head.append(av,t);const bio=document.createElement('p');bio.textContent=p.bio||'관심사를 통해 연결될 수 있는 회원입니다.';const tags=document.createElement('div');tags.className='tag-row';(p.shared_interests||[]).slice(0,4).forEach(v=>{const x=document.createElement('span');x.className='tag';x.textContent=v;tags.append(x)});const why=document.createElement('div');why.className='why';const reasons=[];if(p.shared_interests?.length)reasons.push(`공통 관심 ${p.shared_interests.join(' · ')}`);if(p.can_help_me_with?.length)reasons.push(`${p.can_help_me_with.join(' · ')} 도움 가능`);if(p.i_can_help_with?.length)reasons.push(`내가 ${p.i_can_help_with.join(' · ')} 도움 가능`);why.textContent=p.recommendation_reasons?.length?`추천 이유 · ${p.recommendation_reasons.join(' / ')}`:(reasons.join(' / ')||'서로의 관심이 맞닿아 있습니다.');card.append(head,bio,tags,why);host.append(card)});$('#peopleEmpty').hidden=state.people.length>0}
async function loadProfile(){const data=await api('/profile');state.profile=data.profile;if(!state.profile){openProfile(true);return false}$('#welcomeName').textContent=`${state.profile.display_name||'회원'}님, 오늘은 누구와 연결될까요?`;renderInterestCloud();updateRecommendationCopy();return true}
function openProfile(first=false){const f=$('#profileForm');f.display_name.value=state.profile?.display_name||state.session?.user?.user_metadata?.full_name||state.session?.user?.email?.split('@')[0]||'';f.bio.value=state.profile?.bio||'';f.region.value=state.profile?.region||'';f.discoverable.checked=state.profile?.discoverable!==false;fillChoices('interests',state.profile?.interests||[]);fillChoices('skills_offered',state.profile?.skills_offered||[]);fillChoices('wants_to_learn',state.profile?.wants_to_learn||[]);fillChoices('languages',state.profile?.languages||['한국어']);openModal('#profileModal');if(first)toast('관심사를 몇 가지만 선택하면 추천이 시작됩니다.')}
async function saveProfile(ev){ev.preventDefault();const f=ev.currentTarget,payload={display_name:f.display_name.value,bio:f.bio.value,region:f.region.value,interests:selected(f,'interests'),skills_offered:selected(f,'skills_offered'),wants_to_learn:selected(f,'wants_to_learn'),languages:selected(f,'languages'),discoverable:f.discoverable.checked,visibility:'members'};const btn=$('button[type="submit"]',f);btn.disabled=true;try{const data=await api('/profile',{method:'POST',body:JSON.stringify(payload)});state.profile=data.profile;closeModals();renderInterestCloud();$('#welcomeName').textContent=`${state.profile.display_name}님, 오늘은 누구와 연결될까요?`;updateRecommendationCopy();toast('연결 프로필을 저장했습니다.');await refreshRecommendations()}catch(e){console.error(e);toast('프로필을 저장하지 못했습니다.')}finally{btn.disabled=false}}
function openCircle(){if(!state.session)return login();if(!state.profile)return openProfile(true);$('#circleBrief').value='';$('#circleForm').hidden=true;$('#aiNote').textContent='하고 싶은 일을 편하게 적어 주세요. 초안을 만든 뒤 모든 내용을 직접 고칠 수 있습니다.';openModal('#circleModal')}
async function draftCircle(){const brief=$('#circleBrief').value.trim(),btn=$('#draftCircleBtn');if(brief.length<6)return toast('조금 더 구체적으로 적어 주세요.');btn.disabled=true;btn.textContent='초안 만드는 중…';try{const {draft}=await api('/circles/draft',{method:'POST',body:JSON.stringify({brief})});const f=$('#circleForm');['name','category','summary','purpose','location_text','schedule_text','capacity','mode','join_policy'].forEach(k=>{if(f[k])f[k].value=draft[k]??''});f.tags.value=(draft.tags||[]).join(', ');f.hidden=false;$('#aiNote').textContent=draft.ai_mode==='provider'?'AI가 초안을 만들었습니다. 사실·일정·장소는 직접 확인해 주세요.':'현재는 스마트 초안 엔진으로 만들었습니다. AI 제공자 연결 후 생성형 초안으로 자동 전환됩니다.';f.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){console.error(e);toast('초안을 만들지 못했습니다.')}finally{btn.disabled=false;btn.textContent='✨ 초안 만들기'}}
async function createCircle(ev){ev.preventDefault();const f=ev.currentTarget,payload={name:f.name.value,category:f.category.value,summary:f.summary.value,purpose:f.purpose.value,tags:f.tags.value.split(',').map(x=>x.trim()).filter(Boolean),mode:f.mode.value,join_policy:f.join_policy.value,capacity:f.capacity.value?Number(f.capacity.value):null,location_text:f.location_text.value,schedule_text:f.schedule_text.value,visibility:'public'};const btn=$('button[type="submit"]',f);btn.disabled=true;try{const {circle}=await api('/circles',{method:'POST',body:JSON.stringify(payload)});closeModals();toast(`“${circle.name}” Circle을 열었습니다.`);await refreshRecommendations();setTimeout(()=>$('#circles').scrollIntoView({behavior:'smooth'}),80)}catch(e){console.error(e);toast(e.message==='profile_required'?'먼저 연결 프로필을 저장해 주세요.':'Circle을 만들지 못했습니다.')}finally{btn.disabled=false}}
async function refreshRecommendations(){if(!state.session)return;const [c,p]=await Promise.all([api('/circles'),api('/people/recommendations')]);state.circles=c.circles||[];state.people=p.people||[];renderCircles();renderPeople()}
async function boot(){state.role=document.documentElement.dataset.ekodiUserRole||'';makeChoice($('#interestChoices'),PRESETS.interests,'interests');makeChoice($('#offerChoices'),PRESETS.offers,'skills_offered');makeChoice($('#learnChoices'),PRESETS.learns,'wants_to_learn');makeChoice($('#languageChoices'),PRESETS.languages,'languages');await exchangeCentralToken();state.session=(await sb.auth.getSession()).data.session;setSignedIn(Boolean(state.session));if(!state.session){renderCircles(demoCircles);return}const hasProfile=await loadProfile();if(hasProfile)await refreshRecommendations();else{state.circles=[];renderCircles(demoCircles)}}

$$('[data-login]').forEach(el=>el.addEventListener('click',login));$$('[data-open-circle]').forEach(el=>el.addEventListener('click',openCircle));$$('[data-open-profile]').forEach(el=>el.addEventListener('click',()=>state.session?openProfile():login()));$$('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModals));$('#loginBtn').addEventListener('click',()=>state.session?logout():login());$('#profileBtn').addEventListener('click',()=>openProfile());$('#mobileMy').addEventListener('click',()=>state.session?openProfile():login());$('#profileForm').addEventListener('submit',saveProfile);$('#draftCircleBtn').addEventListener('click',draftCircle);$('#circleForm').addEventListener('submit',createCircle);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});function applyRecommendationContext(detail={}){const next=String(detail.role||document.documentElement.dataset.ekodiUserRole||'');if(next===state.role)return;state.role=next;if(state.session&&state.profile){updateRecommendationCopy();renderCircles();renderPeople()}}window.addEventListener('ekodi:shell-context',event=>applyRecommendationContext(event.detail||{}));window.addEventListener('ekodi:user-context',event=>applyRecommendationContext(event.detail||{}));sb.auth.onAuthStateChange((_event,session)=>{state.session=session;setSignedIn(Boolean(session))});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
boot().catch(e=>{console.error('community boot',e);renderCircles(demoCircles);toast('Community를 불러오는 중 문제가 발생했습니다.')});
