import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const GOOGLE_CLIENT_ID=Deno.env.get("INSURANCE_GOOGLE_CLIENT_ID")||"";
const AUTH_ORIGIN=Deno.env.get("INSURANCE_AUTH_ORIGIN")||"";
const GOOGLE_ISSUERS=new Set(["accounts.google.com","https://accounts.google.com"]);
const JWKS_URL="https://www.googleapis.com/oauth2/v3/certs";
const CHALLENGE_MINUTES=10;
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const encoder=new TextEncoder();
let jwksCache:{keys:any[],expiresAt:number}={keys:[],expiresAt:0};

const cors=(req:Request)=>{const origin=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":origin===AUTH_ORIGIN?AUTH_ORIGIN:"null","Access-Control-Allow-Headers":"content-type, apikey, x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}};
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors(req),"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const hex=(bytes:Uint8Array)=>[...bytes].map(b=>b.toString(16).padStart(2,"0")).join("");
async function sha256(value:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value))))}
function b64bytes(value:string){const normalized=value.replace(/-/g,"+").replace(/_/g,"/");const padded=normalized+"=".repeat((4-normalized.length%4)%4);const binary=atob(padded);return Uint8Array.from(binary,c=>c.charCodeAt(0));}
function b64json(value:string){return JSON.parse(new TextDecoder().decode(b64bytes(value)));}
async function googleKeys(){if(jwksCache.expiresAt>Date.now()&&jwksCache.keys.length)return jwksCache.keys;const r=await fetch(JWKS_URL,{headers:{accept:"application/json"}});if(!r.ok)throw new Error("google_keys_unavailable");const d=await r.json();const maxAge=Number((r.headers.get("cache-control")||"").match(/max-age=(\d+)/)?.[1]||300);jwksCache={keys:Array.isArray(d.keys)?d.keys:[],expiresAt:Date.now()+Math.max(60,maxAge)*1000};return jwksCache.keys;}
async function verifySignature(jwk:any,h:string,p:string,s:string,payload:any,nonce:string){const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);const ok=await crypto.subtle.verify({name:"RSASSA-PKCS1-v1_5"},key,b64bytes(s),encoder.encode(`${h}.${p}`));if(!ok)throw new Error("google_signature_invalid");const now=Math.floor(Date.now()/1000);const aud=Array.isArray(payload.aud)?payload.aud.includes(GOOGLE_CLIENT_ID):payload.aud===GOOGLE_CLIENT_ID;if(!aud)throw new Error("google_audience_invalid");if(!GOOGLE_ISSUERS.has(payload.iss))throw new Error("google_issuer_invalid");if(!Number.isFinite(Number(payload.exp))||Number(payload.exp)<=now)throw new Error("google_token_expired");if(Number(payload.iat||now)>now+300)throw new Error("google_token_time_invalid");if(!payload.sub||!payload.email||payload.email_verified!==true)throw new Error("verified_google_email_required");if(payload.nonce!==nonce)throw new Error("google_nonce_invalid");return payload;}
async function verifyGoogle(token:string,nonce:string){if(!GOOGLE_CLIENT_ID)throw new Error("google_client_id_missing");const parts=String(token||"").split(".");if(parts.length!==3)throw new Error("google_token_invalid");const [h,p,s]=parts,header=b64json(h),payload=b64json(p);if(header.alg!=="RS256"||!header.kid)throw new Error("google_header_invalid");let keys=await googleKeys();let jwk=keys.find((k:any)=>k.kid===header.kid&&k.kty==="RSA");if(!jwk){jwksCache.expiresAt=0;keys=await googleKeys();jwk=keys.find((k:any)=>k.kid===header.kid&&k.kty==="RSA");}if(!jwk)throw new Error("google_key_not_found");return verifySignature(jwk,h,p,s,payload,nonce);}
async function issueChallenge(req:Request){const nonce=hex(crypto.getRandomValues(new Uint8Array(24))),nonceHash=await sha256(nonce);const now=new Date(),expires=new Date(now.getTime()+CHALLENGE_MINUTES*60*1000);await admin.from("insurance_identity_challenges").delete().lte("expires_at",now.toISOString());const {error}=await admin.from("insurance_identity_challenges").insert({nonce_hash:nonceHash,expires_at:expires.toISOString()});if(error)throw error;return json(req,{nonce,clientId:GOOGLE_CLIENT_ID,expiresAt:expires.toISOString()},201);}
async function consumeChallenge(nonce:string){if(!/^[a-f0-9]{48}$/i.test(nonce))return false;const hash=await sha256(nonce),now=new Date().toISOString();const {data}=await admin.from("insurance_identity_challenges").select("nonce_hash").eq("nonce_hash",hash).gt("expires_at",now).maybeSingle();if(!data)return false;const {error}=await admin.from("insurance_identity_challenges").delete().eq("nonce_hash",hash);if(error)throw error;return true;}
async function exchange(req:Request){const body=await req.json().catch(()=>({}));const nonce=String(body?.nonce||"").trim(),credential=String(body?.credential||"").trim();if(!nonce||!credential)return json(req,{error:"credential_and_nonce_required"},400);if(!(await consumeChallenge(nonce)))return json(req,{error:"challenge_expired_or_used"},400);const profile=await verifyGoogle(credential,nonce),email=String(profile.email).trim().toLowerCase();const {data,error}=await admin.auth.admin.generateLink({type:"magiclink",email});if(error||!data?.properties?.hashed_token){console.error("insurance identity generateLink",error?.message||"missing_hashed_token");return json(req,{error:"identity_session_issue_failed"},500);}return json(req,{ok:true,tokenHash:data.properties.hashed_token,type:"email",user:{email,name:String(profile.name||"").slice(0,120)}},200);}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(!AUTH_ORIGIN||req.headers.get("Origin")!==AUTH_ORIGIN)return json(req,{error:"origin_not_allowed"},403);const path=new URL(req.url).pathname.replace(/^\/insurance-identity-staging/,"")||"/";try{if(req.method==="POST"&&path==="/challenge")return await issueChallenge(req);if(req.method==="POST"&&path==="/google/exchange")return await exchange(req);return json(req,{error:"not_found"},404)}catch(e){console.error("insurance-identity-staging",e);return json(req,{error:"insurance_identity_failed"},500)}});
