const JADAM_PILOT_PATH='/jadam';
const JADAM_STORAGE='ekodi_energy_jadam_mokpo_01_v1';
const isJadamPilot=()=>location.pathname.replace(/\/+$/,'')===JADAM_PILOT_PATH||new URLSearchParams(location.search).get('pilot')==='jadam-mokpo-01';
const n=(value)=>{const parsed=Number(String(value??'').replace(/[^0-9.-]/g,''));return Number.isFinite(parsed)?parsed:0};
const won=(value)=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Math.round(value||0));
const pct=(value)=>`${value>=0?'+':''}${value.toFixed(1)}%`;
function monthKeys(count=6){const now=new Date();return Array.from({length:count},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(count-1-i),1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})}
function loadPilot(){try{const saved=JSON.parse(localStorage.getItem(JADAM_STORAGE)||'null');if(saved?.bills)return saved}catch{}return{siteId:'jadam-mokpo-01',storeName:'자담치킨 목포대점',bills:monthKeys().map(month=>({month,kwh:'',amount:''}))}}
function savePilot(data){localStorage.setItem(JADAM_STORAGE,JSON.stringify(data))}
function analyzeBills(bills){
  const rows=bills.filter(row=>row.month&&n(row.kwh)>0&&n(row.amount)>0).sort((a,b)=>a.month.localeCompare(b.month));
  if(rows.length<2)return{ready:false,message:'최소 2개월, 권장 4~12개월의 사용량(kWh)과 청구금액을 입력하세요.'};
  const latest=rows.at(-1),previous=rows.slice(Math.max(0,rows.length-4),-1);
  const avg=(key)=>previous.reduce((sum,row)=>sum+n(row[key]),0)/previous.length;
  const baseKwh=avg('kwh'),baseAmount=avg('amount'),latestKwh=n(latest.kwh),latestAmount=n(latest.amount);
  const usageDelta=baseKwh?((latestKwh-baseKwh)/baseKwh)*100:0,billDelta=baseAmount?((latestAmount-baseAmount)/baseAmount)*100:0;
  const unitNow=latestKwh?latestAmount/latestKwh:0,baseUnit=baseKwh?baseAmount/baseKwh:0,unitDelta=baseUnit?((unitNow-baseUnit)/baseUnit)*100:0;
  const excess=Math.max(0,latestAmount-baseAmount);
  let signal='정상 범위';let reason='최근 기준선과 큰 차이가 없습니다.';
  if(usageDelta>=15){signal='사용량 급증';reason='청구금액보다 먼저 실제 사용량이 크게 늘었습니다. AMI 연결 후 영업외 시간대와 피크 구간을 확인해야 합니다.'}
  else if(unitDelta>=10){signal='단가·요금구조 점검';reason='사용량 변화보다 kWh당 비용 증가가 큽니다. 계약전력·요금제·기본요금 항목을 확인할 필요가 있습니다.'}
  else if(billDelta>=10){signal='비용 증가';reason='최근 기준선보다 청구금액이 높습니다. 영업일수·날씨·사용시간을 함께 보정하면 원인을 더 좁힐 수 있습니다.'}
  return{ready:true,rows,latest,baseKwh,baseAmount,latestKwh,latestAmount,usageDelta,billDelta,unitNow,unitDelta,excess,signal,reason};
}
function billRows(data){return data.bills.map((row,index)=>`<div class="jd-bill-row" data-row="${index}"><input type="month" value="${row.month||''}" aria-label="청구월"><input inputmode="decimal" value="${row.kwh||''}" placeholder="사용량 kWh" aria-label="사용량 kWh"><input inputmode="numeric" value="${row.amount||''}" placeholder="청구금액 원" aria-label="청구금액 원"></div>`).join('')}
function readBills(){return [...document.querySelectorAll('.jd-bill-row')].map(row=>{const inputs=row.querySelectorAll('input');return{month:inputs[0].value,kwh:n(inputs[1].value)||'',amount:n(inputs[2].value)||''}})}
function renderResult(result){const host=document.getElementById('jdAnalysis');if(!host)return;if(!result.ready){host.innerHTML=`<div class="jd-empty"><b>분석 대기</b><p>${result.message}</p></div>`;return}host.innerHTML=`<div class="jd-score"><span>${result.signal}</span><strong>${pct(result.billDelta)}</strong><small>최근 1~3개월 기준선 대비 청구금액</small></div><div class="jd-metrics"><article><small>최근 사용량</small><b>${result.latestKwh.toLocaleString()} kWh</b><em>${pct(result.usageDelta)}</em></article><article><small>최근 청구금액</small><b>${won(result.latestAmount)}</b><em>${pct(result.billDelta)}</em></article><article><small>kWh당 비용</small><b>${won(result.unitNow)}</b><em>${pct(result.unitDelta)}</em></article><article><small>초과비용 후보</small><b>${won(result.excess)}</b><em>날씨·영업일 보정 전</em></article></div><div class="jd-reason"><b>AI 1차 진단</b><p>${result.reason}</p></div>`}
async function fetchInsight(bills){const host=document.getElementById('jdServerInsight');if(!host)return;host.textContent='분석 중…';try{const response=await fetch('/api/insight',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({siteId:'jadam-mokpo-01',billingHistory:bills})});const data=await response.json();host.innerHTML=`<b>${data.insight?.title||'AI 분석'}</b><p>${data.insight?.body||'분석 결과를 준비하지 못했습니다.'}</p>`}catch{host.innerHTML='<b>로컬 진단은 저장되었습니다.</b><p>서버 분석 연결에 실패했습니다. 실제 설비 제어는 실행되지 않았습니다.</p>'}}
function parseImport(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{try{const text=String(reader.result||'');if(file.name.toLowerCase().endsWith('.json')){const value=JSON.parse(text);return resolve(Array.isArray(value)?value:value.bills||[])}const lines=text.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(',').map(v=>v.trim().toLowerCase());const idx=(...names)=>head.findIndex(v=>names.includes(v));const mi=idx('month','월','청구월'),ki=idx('kwh','usage','사용량'),ai=idx('amount','bill','금액','청구금액');resolve(lines.map(line=>{const c=line.split(',');return{month:c[mi]||'',kwh:n(c[ki]),amount:n(c[ai])}}))}catch(error){reject(error)}};reader.readAsText(file,'utf-8')})}
function addBlankRow(){const wrap=document.getElementById('jdBillRows');const index=wrap.children.length;wrap.insertAdjacentHTML('beforeend',`<div class="jd-bill-row" data-row="${index}"><input type="month" aria-label="청구월"><input inputmode="decimal" placeholder="사용량 kWh" aria-label="사용량 kWh"><input inputmode="numeric" placeholder="청구금액 원" aria-label="청구금액 원"></div>`)}
function installJadamPilot(){
  const data=loadPilot();document.body.classList.add('jadam-energy-pilot');document.title='자담치킨 목포대점 · EKODI Energy AI 1호 모델';
  const brand=document.querySelector('.brand span:last-child');if(brand)brand.innerHTML='자담치킨 목포대점 <b>ENERGY AI</b>';
  const nav=document.querySelector('.topbar nav');if(nav)nav.innerHTML='<a class="jd-nav" href="#jdOverview">진단</a><a class="jd-nav" href="#jdBills">고지서</a><a class="jd-nav" href="#jdConnect">연결</a>';
  const live=document.querySelector('.live-chip');if(live)live.innerHTML='<span class="live-dot"></span><small>1호 모델</small><strong>READ ONLY</strong>';
  const main=document.querySelector('main');
  main.innerHTML=`<section id="jdOverview" class="jd-hero"><span class="eyebrow">EKODI ENERGY AI · PILOT 01</span><h1>자담치킨 목포대점의<br><em>전기세가 왜 늘었는지 찾습니다.</em></h1><p>최근 고지서만으로 기준선을 만들고, 사용량 증가와 요금단가 변화를 분리합니다. 실제 AMI가 연결되기 전에는 시간대·기기 원인을 단정하지 않습니다.</p><div class="jd-tags"><span>사업장 1호</span><span>실데이터 입력형</span><span>설비 제어 OFF</span></div></section><section class="jd-status-grid"><article><small>현재 단계</small><b>고지서 기반 1차 진단</b><span>장비 없이 시작</span></article><article><small>실시간 AMI</small><b>연결 대기</b><span>한전 데이터 동의 후</span></article><article><small>회로별 측정</small><b>2단계</b><span>분전반 CT 센서</span></article><article><small>자동 조절</small><b>비활성</b><span>승인형 IoT 이후</span></article></section><section id="jdBills" class="jd-panel"><div class="jd-head"><div><span class="eyebrow">STEP 1 · BILL BASELINE</span><h2>최근 전기고지서 입력</h2></div><button id="jdAddRow" class="jd-secondary">+ 월 추가</button></div><p class="jd-help">고지서의 청구월, 사용량(kWh), 청구금액만 입력하면 됩니다. 4~12개월이면 계절성 판단이 훨씬 좋아집니다.</p><div class="jd-bill-head"><span>청구월</span><span>사용량(kWh)</span><span>청구금액(원)</span></div><div id="jdBillRows">${billRows(data)}</div><div class="jd-actions"><button id="jdAnalyze" class="jd-primary">저장하고 AI 분석</button><label class="jd-file">CSV/JSON 가져오기<input id="jdImport" type="file" accept=".csv,.json"></label></div><small class="jd-format">CSV 열 이름: month, kwh, amount · 사진/PDF 자동인식은 다음 연결 단계</small></section><section class="jd-panel"><div class="jd-head"><div><span class="eyebrow">DIAGNOSIS</span><h2>이번 달 비용 증가 원인</h2></div><span class="jd-readonly">추정 · 읽기전용</span></div><div id="jdAnalysis"></div><div id="jdServerInsight" class="jd-server"><b>분석 준비</b><p>고지서를 입력하면 서버 규칙엔진이 같은 데이터를 한 번 더 검증합니다.</p></div></section><section id="jdConnect" class="jd-panel"><div class="jd-head"><div><span class="eyebrow">STEP 2 · FIND THE LEAK</span><h2>원인을 시간대와 회로까지 좁히기</h2></div></div><div class="jd-roadmap"><article><b>① 한전 AMI</b><p>시간대별 사용량을 받아 영업 종료 후 전력, 휴무일 사용, 피크 구간을 찾습니다.</p><span>다음 연결</span></article><article><b>② 분전반 CT</b><p>냉난방·주방·냉장·조명·온수 등 회로별 소비를 분리합니다.</p><span>선택 설치</span></article><article><b>③ 승인형 제어</b><p>스마트릴레이가 지원되는 비안전 핵심부하만 사용자 승인 후 예약 제어합니다.</p><span>후속 단계</span></article></div><div class="jd-safety"><b>안전 경계</b><p>차단기 보호기능, 보호계전, 비상제어, 안전인터록은 AI 자동화 대상이 아닙니다.</p></div></section>`;
  renderResult(analyzeBills(data.bills));document.getElementById('jdAddRow').addEventListener('click',addBlankRow);document.getElementById('jdAnalyze').addEventListener('click',async()=>{const bills=readBills();savePilot({...data,bills});renderResult(analyzeBills(bills));await fetchInsight(bills)});document.getElementById('jdImport').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{const imported=(await parseImport(file)).filter(row=>row.month);if(!imported.length)throw new Error('empty');const next={...data,bills:imported};savePilot(next);document.getElementById('jdBillRows').innerHTML=billRows(next);renderResult(analyzeBills(imported))}catch{alert('CSV/JSON 형식을 확인해 주세요. month, kwh, amount 열이 필요합니다.')}})
}
if(isJadamPilot())window.addEventListener('DOMContentLoaded',installJadamPilot);
