const PILOT_PATH='/pizzamaru';
const PILOT_ID='pizzamaru-mokpo-01';
const PILOT_STORAGE='ekodi_energy_pizzamaru_mokpo_01_v1';
const isPilot=()=>location.pathname.replace(/\/+$/,'')===PILOT_PATH||new URLSearchParams(location.search).get('pilot')===PILOT_ID;
const n=value=>{const parsed=Number(String(value??'').replace(/[^0-9.-]/g,''));return Number.isFinite(parsed)?parsed:0};
const won=value=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Math.round(value||0));
const pct=value=>`${value>=0?'+':''}${value.toFixed(1)}%`;

function monthKeys(count=6){const now=new Date();return Array.from({length:count},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(count-1-i),1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})}
function loadPilot(){try{const saved=JSON.parse(localStorage.getItem(PILOT_STORAGE)||'null');if(saved?.bills)return saved}catch{}return{siteId:PILOT_ID,storeName:'피자마루 목포대점',bills:monthKeys().map(month=>({month,kwh:'',amount:''}))}}
function savePilot(data){localStorage.setItem(PILOT_STORAGE,JSON.stringify(data))}
function analyzeBills(bills){
  const rows=bills.filter(row=>row.month&&n(row.kwh)>0&&n(row.amount)>0).sort((a,b)=>a.month.localeCompare(b.month));
  if(rows.length<2)return{ready:false,message:'최소 2개월, 권장 4~12개월의 사용량(kWh)과 청구금액을 입력하세요.'};
  const latest=rows.at(-1),previous=rows.slice(Math.max(0,rows.length-4),-1);
  const avg=key=>previous.reduce((sum,row)=>sum+n(row[key]),0)/previous.length;
  const baseKwh=avg('kwh'),baseAmount=avg('amount'),latestKwh=n(latest.kwh),latestAmount=n(latest.amount);
  const usageDelta=baseKwh?((latestKwh-baseKwh)/baseKwh)*100:0,billDelta=baseAmount?((latestAmount-baseAmount)/baseAmount)*100:0;
  const unitNow=latestKwh?latestAmount/latestKwh:0,baseUnit=baseKwh?baseAmount/baseKwh:0,unitDelta=baseUnit?((unitNow-baseUnit)/baseUnit)*100:0;
  const excess=Math.max(0,latestAmount-baseAmount);
  let signal='정상 범위';let reason='최근 기준선과 큰 차이가 없습니다.';
  if(usageDelta>=15){signal='사용량 급증';reason='청구금액보다 실제 사용량이 크게 늘었습니다. AMI 연결 후 영업 종료 후 전력과 피크 시간대를 먼저 확인해야 합니다.'}
  else if(unitDelta>=10){signal='단가·요금구조 점검';reason='사용량 변화보다 kWh당 비용 증가가 큽니다. 계약전력·요금제·기본요금 항목을 확인할 필요가 있습니다.'}
  else if(billDelta>=10){signal='비용 증가';reason='최근 기준선보다 청구금액이 높습니다. 영업일수·날씨·사용시간을 함께 보정하면 원인을 더 좁힐 수 있습니다.'}
  return{ready:true,rows,latest,baseKwh,baseAmount,latestKwh,latestAmount,usageDelta,billDelta,unitNow,unitDelta,excess,signal,reason};
}
function billRows(data){return data.bills.map((row,index)=>`<div class="pm-bill-row" data-row="${index}"><input type="month" value="${row.month||''}" aria-label="청구월"><input inputmode="decimal" value="${row.kwh||''}" placeholder="사용량 kWh" aria-label="사용량 kWh"><input inputmode="numeric" value="${row.amount||''}" placeholder="청구금액 원" aria-label="청구금액 원"></div>`).join('')}
function readBills(){return [...document.querySelectorAll('.pm-bill-row')].map(row=>{const inputs=row.querySelectorAll('input');return{month:inputs[0].value,kwh:n(inputs[1].value)||'',amount:n(inputs[2].value)||''}})}
function renderResult(result){const host=document.getElementById('pmAnalysis');if(!host)return;if(!result.ready){host.innerHTML=`<div class="pm-empty"><b>분석 대기</b><p>${result.message}</p></div>`;return}host.innerHTML=`<div class="pm-score"><span>${result.signal}</span><strong>${pct(result.billDelta)}</strong><small>최근 1~3개월 기준선 대비 청구금액</small></div><div class="pm-metrics"><article><small>최근 사용량</small><b>${result.latestKwh.toLocaleString()} kWh</b><em>${pct(result.usageDelta)}</em></article><article><small>최근 청구금액</small><b>${won(result.latestAmount)}</b><em>${pct(result.billDelta)}</em></article><article><small>kWh당 비용</small><b>${won(result.unitNow)}</b><em>${pct(result.unitDelta)}</em></article><article><small>초과비용 후보</small><b>${won(result.excess)}</b><em>날씨·영업일 보정 전</em></article></div><div class="pm-reason"><b>Energy Engine 1차 진단</b><p>${result.reason}</p></div>`}
async function fetchInsight(bills){const host=document.getElementById('pmServerInsight');if(!host)return;host.textContent='분석 중…';try{const response=await fetch('/api/energy/v1/insight',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({siteId:PILOT_ID,billingHistory:bills})});const data=await response.json();host.innerHTML=`<b>${data.insight?.title||'AI 분석'}</b><p>${data.insight?.body||'분석 결과를 준비하지 못했습니다.'}</p>`}catch{host.innerHTML='<b>로컬 진단은 저장되었습니다.</b><p>서버 분석 연결에 실패했습니다. 실제 설비 제어는 실행되지 않았습니다.</p>'}}
async function loadConnectors(){const host=document.getElementById('pmConnectors');if(!host)return;try{const response=await fetch(`/api/energy/v1/pilots/${PILOT_ID}/connectors`);const data=await response.json();host.innerHTML=(data.connectors||[]).map(item=>`<article><b>${item.label}</b><span>${connectorLabel(item.status)}</span></article>`).join('')}catch{host.innerHTML='<article><b>연결 상태</b><span>확인 필요</span></article>'}}
function connectorLabel(status){return({ready:'사용 가능',adapter_contract_ready:'연결 규격 준비',connection_required:'연결 필요',optional_phase2:'선택 설치'}[status]||status)}
function parseImport(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{try{const text=String(reader.result||'');if(file.name.toLowerCase().endsWith('.json')){const value=JSON.parse(text);return resolve(Array.isArray(value)?value:value.bills||[])}const lines=text.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(',').map(v=>v.trim().toLowerCase());const idx=(...names)=>head.findIndex(v=>names.includes(v));const mi=idx('month','월','청구월'),ki=idx('kwh','usage','사용량'),ai=idx('amount','bill','금액','청구금액');resolve(lines.map(line=>{const c=line.split(',');return{month:c[mi]||'',kwh:n(c[ki]),amount:n(c[ai])}}))}catch(error){reject(error)}};reader.readAsText(file,'utf-8')})}
function addBlankRow(){const wrap=document.getElementById('pmBillRows');const index=wrap.children.length;wrap.insertAdjacentHTML('beforeend',`<div class="pm-bill-row" data-row="${index}"><input type="month" aria-label="청구월"><input inputmode="decimal" placeholder="사용량 kWh" aria-label="사용량 kWh"><input inputmode="numeric" placeholder="청구금액 원" aria-label="청구금액 원"></div>`)}
function installPilot(){
  const data=loadPilot();document.body.classList.add('pizzamaru-energy-pilot');document.title='피자마루 목포대점 · EKODI Energy AI 1호 실증';
  const brand=document.querySelector('.brand span:last-child');if(brand)brand.innerHTML='피자마루 목포대점 <b>ENERGY AI</b>';
  const nav=document.querySelector('.topbar nav');if(nav)nav.innerHTML='<a class="pm-nav" href="#pmOverview">진단</a><a class="pm-nav" href="#pmBills">고지서</a><a class="pm-nav" href="#pmConnect">연결</a>';
  const live=document.querySelector('.live-chip');if(live)live.innerHTML='<span class="live-dot"></span><small>실증 1호</small><strong>READ ONLY</strong>';
  const main=document.querySelector('main');
  main.innerHTML=`<section id="pmOverview" class="pm-hero"><span class="eyebrow">EKODI ENERGY AI · PILOT 01</span><h1>피자마루 목포대점의<br><em>전기세가 왜 늘었는지 먼저 찾습니다.</em></h1><p>센서 설치를 출발점으로 삼지 않습니다. 최근 고지서로 기준선을 만들고, AMI가 연결되면 시간대 이상을 좁히며, 그래도 원인이 불명확할 때만 핵심 회로에 CT 센서를 선택 설치합니다.</p><div class="pm-tags"><span>실증 1호</span><span>무센서 우선</span><span>설비 제어 OFF</span></div></section><section class="pm-status-grid"><article><small>현재 단계</small><b>고지서 기반 1차 진단</b><span>장비 없이 시작</span></article><article><small>실시간 AMI</small><b>연결 대기</b><span>사용자 동의 후</span></article><article><small>회로별 측정</small><b>선택형 2단계</b><span>필요 설비만 CT</span></article><article><small>자동 조절</small><b>비활성</b><span>승인형 제어 이후</span></article></section><section id="pmBills" class="pm-panel"><div class="pm-head"><div><span class="eyebrow">STEP 1 · BILL BASELINE</span><h2>최근 전기고지서 입력</h2></div><button id="pmAddRow" class="pm-secondary">+ 월 추가</button></div><p class="pm-help">청구월, 사용량(kWh), 청구금액만 입력하면 됩니다. 4~12개월이면 계절성 판단이 더 안정적입니다. 이후 Gmail·Drive 자동수집 어댑터가 같은 형식으로 데이터를 넣도록 설계합니다.</p><div class="pm-bill-head"><span>청구월</span><span>사용량(kWh)</span><span>청구금액(원)</span></div><div id="pmBillRows">${billRows(data)}</div><div class="pm-actions"><button id="pmAnalyze" class="pm-primary">저장하고 분석</button><label class="pm-file">CSV/JSON 가져오기<input id="pmImport" type="file" accept=".csv,.json"></label></div><small class="pm-format">CSV 열 이름: month, kwh, amount · 사진/PDF 자동인식은 문서 Connector 단계에서 추가</small></section><section class="pm-panel"><div class="pm-head"><div><span class="eyebrow">DIAGNOSIS</span><h2>이번 달 비용 증가 원인</h2></div><span class="pm-readonly">추정 · 읽기전용</span></div><div id="pmAnalysis"></div><div id="pmServerInsight" class="pm-server"><b>분석 준비</b><p>고지서를 입력하면 서버의 설명 가능한 규칙엔진이 같은 데이터를 한 번 더 검증합니다.</p></div></section><section id="pmConnect" class="pm-panel"><div class="pm-head"><div><span class="eyebrow">STEP 2 · CONNECT ONLY WHAT HELPS</span><h2>필요한 데이터만 단계적으로 연결</h2></div></div><div id="pmConnectors" class="pm-connectors"></div><div class="pm-roadmap"><article><b>① 고지서 자동수집</b><p>Gmail·Google Drive 고지서를 사용자 동의 아래 자동으로 가져오는 Connector를 붙입니다.</p><span>저비용 우선</span></article><article><b>② AMI 시간대 분석</b><p>영업 종료 후 전력, 휴무일 사용, 피크 구간을 찾아 원인을 시간대로 좁힙니다.</p><span>다음 연결</span></article><article><b>③ 선택 CT 센서</b><p>AMI만으로 원인을 특정하기 어려운 경우 냉난방·냉장·주방 등 핵심 회로에만 설치합니다.</p><span>필요할 때만</span></article></div><div class="pm-safety"><b>안전 경계</b><p>차단기 보호기능, 보호계전, 비상제어, 안전인터록은 AI 자동화 대상이 아닙니다. 실증 1단계는 관찰·진단만 수행합니다.</p></div></section>`;
  renderResult(analyzeBills(data.bills));loadConnectors();
  document.getElementById('pmAddRow').addEventListener('click',addBlankRow);
  document.getElementById('pmAnalyze').addEventListener('click',async()=>{const bills=readBills();savePilot({...data,bills});renderResult(analyzeBills(bills));await fetchInsight(bills)});
  document.getElementById('pmImport').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{const imported=(await parseImport(file)).filter(row=>row.month);if(!imported.length)throw new Error('empty');const next={...data,bills:imported};savePilot(next);document.getElementById('pmBillRows').innerHTML=billRows(next);renderResult(analyzeBills(imported))}catch{alert('CSV/JSON 형식을 확인해 주세요. month, kwh, amount 열이 필요합니다.')}});
}
if(isPilot())window.addEventListener('DOMContentLoaded',installPilot);
