const CONFIG=window.EKODI_WORK_CONFIG||{dataEnabled:false,dataMode:'isolated-staging',supabaseUrl:'',supabasePublishableKey:'',authUrl:''};
const sb=CONFIG.dataEnabled&&window.supabase?window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}):null;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={session:null,jobs:[],profile:null,org:null,applications:[],employerApplications:[],query:'',type:''};
const STATUS_LABEL={submitted:'지원완료',reviewing:'검토중',interview:'면접',accepted:'채용',rejected:'종료',withdrawn:'지원취소'};
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2500)}
function splitTags(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function money(job){if(job.wage_type==='negotiable'||!job.wage_amount)return '급여 협의';const n=Number(job.wage_amount).toLocaleString('ko-KR');return job.wage_type==='hourly'?`시급 ${n}원`:job.wage_type==='monthly'?`월 ${n}원`:`${n}원`}
function login(){if(!CONFIG.dataEnabled||!CONFIG.authUrl)return toast('격리 스테이징에서는 로그인과 운영 데이터 연결을 비활성화했습니다.');location.href=CONFIG.authUrl}
async function exchangeCentralToken(){if(!sb)return;const p=new URLSearchParams(location.hash.slice(1)),token=p.get('ekodi_token'),type=p.get('ekodi_type')||'email';if(!token)return;try{const {error}=await sb.auth.verifyOtp({token_hash:token,type});if(error)throw error;history.replaceState(null,'',location.pathname+location.search);toast('EKODI Work에 연결되었습니다.')}catch(e){console.error(e);toast('로그인 연결을 완료하지 못했습니다.')}}
function setSignedIn(on){const btn=$('#loginBtn');if(!CONFIG.dataEnabled){btn.textContent='격리 스테이징';btn.disabled=true;return}btn.disabled=false;btn.textContent=on?'로그아웃':'Google로 시작'}
async function logout(){if(!sb)return;await sb.auth.signOut();state.session=null;state.profile=null;state.org=null;state.applications=[];state.employerApplications=[];setSignedIn(false);renderApplications();renderEmployerApplications();toast('로그아웃했습니다.')}
function setView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${name}View`));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===name))}
function dataNotice(text=''){const el=$('#dataNotice');el.textContent=text;el.classList.toggle('hide',!text)}
async function loadJobs(){if(!sb){state.jobs=[];renderJobs();dataNotice('격리 스테이징입니다. UI·Worker는 운영 데이터와 분리되어 있고, DB 권한·지원 흐름은 별도 PostgreSQL CI에서 검증합니다.');return}try{const {data,error}=await sb.from('work_jobs').select('id,title,summary,category,employment_type,region,location_text,schedule_text,wage_type,wage_amount,currency,skills,languages,visa_guidance,published_at,work_organizations(name,verified)').eq('status','published').order('published_at',{ascending:false}).limit(60);if(error)throw error;state.jobs=data||[];dataNotice('');renderJobs()}catch(e){console.error(e);state.jobs=[];renderJobs();dataNotice('Work 데이터 레이어를 불러오지 못했습니다. 관리자에게 알려 주세요.')}}
function matches(job){const q=state.query.toLowerCase();if(state.type&&job.employment_type!==state.type)return false;if(!q)return true;const text=[job.title,job.summary,job.category,job.region,job.location_text,...(job.skills||[]),...(job.languages||[]),job.visa_guidance].join(' ').toLowerCase();return q.split(/\s+/).filter(Boolean).every(x=>text.includes(x))}
function renderJobs(){const host=$('#jobGrid');host.replaceChildren();const list=state.jobs.filter(matches);list.forEach(job=>host.append(jobCard(job)));$('#jobEmpty').classList.toggle('hide',list.length>0)}
function jobCard(job){const card=document.createElement('article');card.className='job-card';const org=job.work_organizations||{};const top=document.createElement('div');top.className='job-top';const orgName=document.createElement('span');orgName.className='org-name';orgName.textContent=org.name||'사업장';top.append(orgName);if(org.verified){const v=document.createElement('span');v.className='verified';v.textContent='사업장 확인';top.append(v)}const h=document.createElement('h3');h.textContent=job.title;const p=document.createElement('p');p.textContent=job.summary||'';const meta=document.createElement('div');meta.className='job-meta';[job.employment_type,job.region,job.schedule_text].filter(Boolean).forEach(x=>{const s=document.createElement('span');s.textContent=x;meta.append(s)});const tags=document.createElement('div');tags.className='tag-row';[...(job.skills||[]),...(job.languages||[])].slice(0,5).forEach(x=>{const t=document.createElement('span');t.className='tag';t.textContent=x;tags.append(t)});const wage=document.createElement('div');wage.className='wage';wage.textContent=money(job);const actions=document.createElement('div');actions.className='job-actions';const apply=document.createElement('button');apply.textContent=state.session?'지원하기':'로그인 후 지원';apply.addEventListener('click',()=>state.session?openApply(job):login());actions.append(apply);card.append(top,h,p,meta,tags,wage,actions);return card}
async function loadProfile(){if(!sb||!state.session)return;try{const {data,error}=await sb.from('work_profiles').select('*').eq('user_id',state.session.user.id).maybeSingle();if(error)throw error;state.profile=data||null;fillProfile()}catch(e){console.error(e)}}
function fillProfile(){const f=$('#profileForm'),p=state.profile||{};f.display_name.value=p.display_name||state.session?.user?.user_metadata?.full_name||'';f.role.value=p.role||'seeker';f.region.value=p.region||'';f.skills.value=(p.skills||[]).join(', ');f.languages.value=(p.languages||[]).join(', ');f.visa_status.value=p.visa_status||'';f.discoverable.checked=!!p.discoverable}
async function saveProfile(ev){ev.preventDefault();if(!sb||!state.session)return login();const f=ev.currentTarget,payload={user_id:state.session.user.id,display_name:f.display_name.value.trim(),role:f.role.value,region:f.region.value.trim(),skills:splitTags(f.skills.value),languages:splitTags(f.languages.value),visa_status:f.visa_status.value.trim(),discoverable:f.discoverable.checked,updated_at:new Date().toISOString()};const {data,error}=await sb.from('work_profiles').upsert(payload,{onConflict:'user_id'}).select().single();if(error){console.error(error);return toast('프로필을 저장하지 못했습니다.')}state.profile=data;toast('Work Profile을 저장했습니다.')}
async function loadOrg(){if(!sb||!state.session)return;try{const {data,error}=await sb.rpc('work_get_my_organization');if(error)throw error;state.org=(Array.isArray(data)?data[0]:data)||null;renderOrg()}catch(e){console.error(e)}}
function renderOrg(){const f=$('#orgForm'),el=$('#orgSaved');if(!state.org){el.classList.add('hide');return}f.name.value=state.org.name||'';f.region.value=state.org.region||'';el.textContent=`${state.org.name} · ${state.org.region}${state.org.verified?' · 확인됨':''}`;el.classList.remove('hide')}
async function saveOrg(ev){ev.preventDefault();if(!sb||!state.session)return login();const f=ev.currentTarget,name=f.name.value.trim(),region=f.region.value.trim();let q;if(state.org){q=sb.from('work_organizations').update({name,region,updated_at:new Date().toISOString()}).eq('id',state.org.id)}else{q=sb.from('work_organizations').insert({owner_user_id:state.session.user.id,name,region})}const {data,error}=await q.select('id,name,region,verified,created_at,updated_at').single();if(error){console.error(error);return toast('사업장을 저장하지 못했습니다.')}state.org=data;renderOrg();toast('사업장 정보를 저장했습니다.');await loadEmployerApplications()}
async function draftJob(){const brief=$('#jobBrief').value.trim();if(brief.length<8)return toast('채용 상황을 조금 더 구체적으로 적어 주세요.');const btn=$('#draftBtn');btn.disabled=true;try{const r=await fetch('/api/draft-job',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brief})});const data=await r.json();if(!r.ok)throw new Error(data.error||'draft_failed');const f=$('#jobForm'),d=data.draft;for(const k of ['title','category','employment_type','region','location_text','schedule_text','wage_type','wage_amount','summary','visa_guidance'])if(f[k]&&d[k]!=null)f[k].value=d[k];f.skills.value=(d.skills||[]).join(', ');f.languages.value=(d.languages||[]).join(', ');$('#draftMode').textContent=data.mode==='smart'?'현재는 스마트 구조화 엔진으로 초안을 만들었습니다. 생성형 AI 연결 후 자동 전환할 수 있습니다.':'AI가 초안을 만들었습니다. 사실과 조건을 직접 확인해 주세요.';toast('공고 초안을 만들었습니다.')}catch(e){console.error(e);toast('초안을 만들지 못했습니다.')}finally{btn.disabled=false}}
async function checkCompliance(){const f=$('#jobForm'),payload={title:f.title.value,summary:f.summary.value,wage_type:f.wage_type.value,wage_amount:f.wage_amount.value,visa_guidance:f.visa_guidance.value};const r=await fetch('/api/compliance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();const host=$('#complianceResult');host.className='compliance-list';host.replaceChildren();(data.checks||[]).forEach(c=>{const d=document.createElement('div');d.className=`check-item ${c.level||''}`;d.textContent=c.message;host.append(d)});return data.checks||[]}
async function publishJob(ev){ev.preventDefault();if(!sb||!state.session)return login();if(!state.org)return toast('사업장 정보를 먼저 저장해 주세요.');const checks=await checkCompliance();if(checks.some(x=>x.level==='danger'))return toast('위험표현을 수정한 뒤 다시 게시해 주세요.');const f=ev.currentTarget,payload={organization_id:state.org.id,created_by:state.session.user.id,title:f.title.value.trim(),category:f.category.value.trim(),employment_type:f.employment_type.value,region:f.region.value.trim(),location_text:f.location_text.value.trim(),schedule_text:f.schedule_text.value.trim(),wage_type:f.wage_type.value,wage_amount:f.wage_amount.value?Number(f.wage_amount.value):null,summary:f.summary.value.trim(),skills:splitTags(f.skills.value),languages:splitTags(f.languages.value),visa_guidance:f.visa_guidance.value.trim(),status:'published',published_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await sb.from('work_jobs').insert(payload);if(error){console.error(error);return toast('공고를 게시하지 못했습니다.')}f.reset();$('#complianceResult').replaceChildren();toast('채용공고를 게시했습니다.');await loadJobs();setView('jobs')}
function openApply(job){if(!state.profile){setView('me');return toast('지원 전에 Work Profile을 먼저 저장해 주세요.')}const m=$('#applyModal');$('#applyTitle').textContent=`${job.title} 지원`;$('#applyForm').job_id.value=job.id;m.classList.add('open');m.setAttribute('aria-hidden','false')}
function closeApply(){const m=$('#applyModal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
async function submitApplication(ev){ev.preventDefault();if(!sb||!state.session)return login();if(!state.profile){closeApply();setView('me');return toast('지원 전에 Work Profile을 먼저 저장해 주세요.')}const f=ev.currentTarget,payload={job_id:f.job_id.value,applicant_user_id:state.session.user.id,message:f.message.value.trim(),status:'submitted'};const {error}=await sb.from('work_applications').insert(payload);if(error){console.error(error);return toast(error.code==='23505'?'이미 지원한 공고입니다.':'지원을 보내지 못했습니다.')}closeApply();f.reset();toast('지원서를 보냈습니다.');await loadApplications()}
async function loadApplications(){if(!sb||!state.session)return renderApplications();try{const {data,error}=await sb.from('work_applications').select('id,status,created_at,work_jobs(title,work_organizations(name))').eq('applicant_user_id',state.session.user.id).order('created_at',{ascending:false});if(error)throw error;state.applications=data||[];renderApplications()}catch(e){console.error(e);state.applications=[];renderApplications()}}
function renderApplications(){const host=$('#applicationList');host.replaceChildren();state.applications.forEach(a=>{const d=document.createElement('div');d.className='application-item';const strong=document.createElement('strong');strong.textContent=a.work_jobs?.title||'지원 공고';const span=document.createElement('span');span.textContent=`${a.work_jobs?.work_organizations?.name||''} · ${STATUS_LABEL[a.status]||a.status}`;d.append(strong,span);host.append(d)});$('#applicationEmpty').classList.toggle('hide',state.applications.length>0)}
async function loadEmployerApplications(){if(!sb||!state.session||!state.org){state.employerApplications=[];return renderEmployerApplications()}try{const {data,error}=await sb.rpc('work_employer_applications');if(error)throw error;state.employerApplications=data||[];renderEmployerApplications()}catch(e){console.error(e);state.employerApplications=[];renderEmployerApplications()}}
function renderEmployerApplications(){const host=$('#employerApplicationList');host.replaceChildren();state.employerApplications.forEach(a=>{const card=document.createElement('article');card.className='employer-app-item';const head=document.createElement('div');head.className='employer-app-head';const title=document.createElement('div');const h=document.createElement('strong');h.textContent=a.applicant_display_name||'지원자';const sub=document.createElement('span');sub.textContent=`${a.job_title||'채용공고'} · ${a.applicant_region||'지역 미입력'}`;title.append(h,sub);const badge=document.createElement('span');badge.className=`status-badge status-${a.status}`;badge.textContent=STATUS_LABEL[a.status]||a.status;head.append(title,badge);const tags=document.createElement('div');tags.className='tag-row';[...(a.applicant_skills||[]),...(a.applicant_languages||[])].slice(0,6).forEach(v=>{const t=document.createElement('span');t.className='tag';t.textContent=v;tags.append(t)});const msg=document.createElement('p');msg.className='employer-app-message';msg.textContent=a.message||'지원 메시지가 없습니다.';const actions=document.createElement('div');actions.className='employer-app-actions';[['reviewing','검토'],['interview','면접'],['accepted','채용'],['rejected','종료']].forEach(([status,label])=>{const b=document.createElement('button');b.type='button';b.className=status==='rejected'?'secondary':'';b.textContent=label;b.disabled=a.status===status;b.addEventListener('click',()=>updateEmployerApplication(a.application_id,status));actions.append(b)});card.append(head,tags,msg,actions);host.append(card)});$('#employerApplicationEmpty').classList.toggle('hide',state.employerApplications.length>0)}
async function updateEmployerApplication(id,status){if(!sb||!state.session)return login();try{const {error}=await sb.rpc('work_update_application_status',{p_application_id:id,p_status:status});if(error)throw error;toast(`지원 상태를 '${STATUS_LABEL[status]}'으로 변경했습니다.`);await loadEmployerApplications()}catch(e){console.error(e);toast('지원 상태를 변경하지 못했습니다.')}}
async function boot(){await exchangeCentralToken();if(sb){state.session=(await sb.auth.getSession()).data.session;setSignedIn(!!state.session);await loadJobs();if(state.session)await Promise.all([loadProfile(),loadOrg(),loadApplications()]);if(state.session){await loadEmployerApplications()}sb.auth.onAuthStateChange((_event,session)=>{state.session=session;setSignedIn(!!session)})}else{setSignedIn(false);await loadJobs();renderApplications();renderEmployerApplications()}}
$$('.nav-link').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#loginBtn').addEventListener('click',()=>state.session?logout():login());$('#jobSearch').addEventListener('input',e=>{state.query=e.target.value;renderJobs()});$('#jobType').addEventListener('change',e=>{state.type=e.target.value;renderJobs()});$('#naturalSearchBtn').addEventListener('click',()=>{state.query=$('#naturalSearch').value;$('#jobSearch').value=state.query;setView('jobs');renderJobs()});$$('[data-query]').forEach(b=>b.addEventListener('click',()=>{$('#naturalSearch').value=b.dataset.query;state.query=b.dataset.query;$('#jobSearch').value=state.query;setView('jobs');renderJobs()}));$('#profileForm').addEventListener('submit',saveProfile);$('#orgForm').addEventListener('submit',saveOrg);$('#draftBtn').addEventListener('click',draftJob);$('#checkBtn').addEventListener('click',checkCompliance);$('#jobForm').addEventListener('submit',publishJob);$('#applyForm').addEventListener('submit',submitApplication);$('.modal-close').addEventListener('click',closeApply);$('#applyModal').addEventListener('click',e=>{if(e.target.id==='applyModal')closeApply()});boot();
