(()=>{
  const state={items:[],keyword:'',meta:null,loading:false};
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const text=v=>String(v??'').trim();
  const dateLabel=value=>{if(!value)return'';const raw=text(value).replace(/[^0-9]/g,'');if(raw.length===8)return`${raw.slice(4,6)}/${raw.slice(6,8)}`;const d=new Date(value);return Number.isNaN(d.valueOf())?'':`${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`};
  const freshLabel=value=>{if(!value)return'';const d=new Date(value);if(Number.isNaN(d.valueOf()))return dateLabel(value);const diff=Math.max(0,Date.now()-d.valueOf());const min=Math.floor(diff/60000);if(min<60)return min<=1?'방금 등록':`${min}분 전`;const hour=Math.floor(min/60);if(hour<24)return`${hour}시간 전`;const day=Math.floor(hour/24);return day<8?`${day}일 전`:dateLabel(value)};
  const sourceLabel=item=>item.source==='work24'?'고용24':'EKODI';
  function setLoading(on){state.loading=on;const featured=$('#featuredOpportunities');if(on&&featured){featured.replaceChildren();for(let i=0;i<3;i++){const s=document.createElement('div');s.className='loading-card';featured.append(s)}}}
  function revealNative(item){const nav=$('.nav-link[data-view="jobs"]');if(nav)nav.click();const search=$('#jobSearch');if(search){search.value=item.title||'';search.dispatchEvent(new Event('input',{bubbles:true}))}setTimeout(()=>$('#jobsView')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
  function featureCard(item){const card=document.createElement('article');card.className='featured-card';const main=document.createElement('div');main.className='featured-main';const source=document.createElement('div');source.className='featured-source';source.textContent=`${sourceLabel(item)} · ${freshLabel(item.publishedAt)||'공개중'}`;const title=document.createElement('div');title.className='featured-title';title.textContent=item.title||'일자리';const meta=document.createElement('div');meta.className='featured-meta';meta.textContent=[item.company,item.region,item.employmentType].filter(Boolean).join(' · ');main.append(source,title,meta);const side=document.createElement('div');const salary=document.createElement('div');salary.className='featured-salary';salary.textContent=item.salaryText||'조건 확인';side.append(salary);if(item.external&&item.url){const a=document.createElement('a');a.href=item.url;a.target='_blank';a.rel='noopener';a.textContent='원문';side.append(a)}else{const b=document.createElement('button');b.type='button';b.textContent='보기';b.addEventListener('click',()=>revealNative(item));side.append(b)}card.append(main,side);return card}
  function externalCard(item){const card=document.createElement('article');card.className='job-card';const top=document.createElement('div');top.className='job-top';const badge=document.createElement('span');badge.className=`source-badge ${item.source==='work24'?'work24':''}`;badge.textContent=`정보출처: ${sourceLabel(item)}`;const when=document.createElement('span');when.className='org-name';when.textContent=freshLabel(item.publishedAt)||'공개중';top.append(badge,when);const h=document.createElement('h3');h.textContent=item.title||'일자리';const p=document.createElement('p');p.textContent=item.summary||item.company||'';const meta=document.createElement('div');meta.className='job-meta';[item.company,item.employmentType,item.region,item.scheduleText].filter(Boolean).slice(0,4).forEach(v=>{const span=document.createElement('span');span.textContent=v;meta.append(span)});const wage=document.createElement('div');wage.className='wage';wage.textContent=item.salaryText||'급여·조건 원문 확인';card.append(top,h,p,meta,wage);if(item.expiresAt){const deadline=document.createElement('div');deadline.className='deadline';deadline.textContent=`마감 ${dateLabel(item.expiresAt)}`;card.append(deadline)}const actions=document.createElement('div');actions.className='job-actions';if(item.url){const a=document.createElement('a');a.className='external-link';a.href=item.url;a.target='_blank';a.rel='noopener';a.textContent='원문에서 확인';actions.append(a)}card.append(actions);return card}
  function currentExternal(){const q=text($('#jobSearch')?.value).toLowerCase();const type=text($('#jobType')?.value);return state.items.filter(x=>x.external).filter(item=>{if(type&&item.employmentType!==type)return false;if(!q)return true;const hay=[item.title,item.company,item.region,item.summary,item.employmentType,item.scheduleText,item.salaryText,...(item.tags||[])].filter(Boolean).join(' ').toLowerCase();return q.split(/\s+/).filter(Boolean).every(token=>hay.includes(token))})}
  function render(){const featured=$('#featuredOpportunities'),featuredEmpty=$('#featuredEmpty');if(featured){featured.replaceChildren();state.items.slice(0,4).forEach(item=>featured.append(featureCard(item)));featuredEmpty?.classList.toggle('hide',state.items.length>0)}const list=currentExternal();const grid=$('#externalGrid');if(grid){grid.replaceChildren();list.forEach(item=>grid.append(externalCard(item)))}$('#externalCount')&&( $('#externalCount').textContent=`${list.length}건` );const empty=$('#externalEmpty');if(empty){empty.classList.toggle('hide',list.length>0);if(!list.length){const work24=state.meta?.sources?.find(s=>s.id==='work24');empty.textContent=work24?.enabled?'현재 조건과 맞는 외부 공개 기회를 찾지 못했습니다. 다른 지역·직무로 다시 찾아보세요.':'고용24 공식 API 인증키가 연결되면 외부 공개 기회가 이곳에 자동으로 들어옵니다. 지금은 EKODI 직접 등록 기회를 먼저 보여드립니다.'}}updateSourceStatus()}
  function updateSourceStatus(){const pill=$('#work24SourcePill');const work24=state.meta?.sources?.find(s=>s.id==='work24');if(pill&&work24){pill.classList.toggle('connected',!!work24.enabled);pill.classList.toggle('waiting',!work24.enabled);pill.innerHTML=`<b>고용24</b> ${work24.enabled?`공식 API · ${work24.count||0}건`:'공식 API 연결 준비'}`}const status=$('#feedStatus');if(status){const native=state.meta?.sources?.find(s=>s.id==='ekodi');status.textContent=`EKODI ${native?.count||0}건 · 외부 ${state.items.filter(x=>x.external).length}건`}const updated=$('#feedUpdatedAt');if(updated&&state.meta?.generatedAt){const d=new Date(state.meta.generatedAt);updated.textContent=Number.isNaN(d.valueOf())?'':`업데이트 ${d.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`}}
  async function load(keyword=state.keyword){if(state.loading)return;state.keyword=text(keyword);setLoading(true);const notice=$('#externalNotice');notice?.classList.add('hide');try{const params=new URLSearchParams({limit:'24'});if(state.keyword)params.set('keyword',state.keyword);const response=await fetch(`/api/opportunities?${params.toString()}`,{headers:{accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||'opportunity_fetch_failed');state.items=Array.isArray(data.items)?data.items:[];state.meta=data.meta||null;render()}catch(error){console.error(error);state.items=[];state.meta=null;render();if(notice){notice.textContent='실시간 기회 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.';notice.classList.remove('hide')}const empty=$('#featuredEmpty');if(empty){empty.textContent='실시간 정보를 불러오지 못했습니다.';empty.classList.remove('hide')}}finally{setLoading(false)}}
  function bind(){$('#refreshFeedBtn')?.addEventListener('click',()=>load());$$('[data-op-query]').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.dataset.opQuery||'';const input=$('#naturalSearch');if(input)input.value=q;load(q)}));$('#focusSearchBtn')?.addEventListener('click',()=>{const input=$('#naturalSearch');input?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>input?.focus(),260)});$('#needPersonBtn')?.addEventListener('click',()=>{$('.nav-link[data-view="employer"]')?.click();setTimeout(()=>$('#employerView')?.scrollIntoView({behavior:'smooth',block:'start'}),40)});$('#naturalSearchBtn')?.addEventListener('click',()=>load($('#naturalSearch')?.value||''));$('#naturalSearch')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();load(event.currentTarget.value)}});$$('.quick-chips [data-query]').forEach(btn=>btn.addEventListener('click',()=>load(btn.dataset.query||'')));$('#jobSearch')?.addEventListener('input',render);$('#jobType')?.addEventListener('change',render)}
  bind();load('');
})();
