import fs from 'node:fs';
const html=fs.readFileSync(new URL('./public/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('./public/app.js',import.meta.url),'utf8');
const bridge=fs.readFileSync(new URL('./public/server-bridge.js',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('./worker.js',import.meta.url),'utf8');
const privacyCss=fs.readFileSync(new URL('./public/privacy.css',import.meta.url),'utf8');
const chatCss=fs.readFileSync(new URL('./public/chat.css',import.meta.url),'utf8');
const adminHtml=fs.readFileSync(new URL('./public/admin.html',import.meta.url),'utf8');
const adminJs=fs.readFileSync(new URL('./public/admin.js',import.meta.url),'utf8');
const advisorHtml=fs.readFileSync(new URL('./public/advisor.html',import.meta.url),'utf8');
const carGuideHtml=fs.readFileSync(new URL('./public/car-insurance-guide.html',import.meta.url),'utf8');
const carGuideJs=fs.readFileSync(new URL('./public/car-insurance-guide.js',import.meta.url),'utf8');
const carGuideCss=fs.readFileSync(new URL('./public/car-insurance-guide.css',import.meta.url),'utf8');
const knowledgeJs=fs.readFileSync(new URL('./public/insurance-knowledge.js',import.meta.url),'utf8');
const knowledgeCss=fs.readFileSync(new URL('./public/insurance-knowledge.css',import.meta.url),'utf8');
const detailHtml=fs.readFileSync(new URL('./public/insurance-detail.html',import.meta.url),'utf8');
const detailJs=fs.readFileSync(new URL('./public/insurance-detail.js',import.meta.url),'utf8');
const detailCss=fs.readFileSync(new URL('./public/insurance-detail.css',import.meta.url),'utf8');
const lawManifest=JSON.parse(fs.readFileSync(new URL('./public/insurance-law-sources.json',import.meta.url),'utf8'));
const lawWatch=fs.readFileSync(new URL('./check-law-sources.mjs',import.meta.url),'utf8');
const wrangler=fs.readFileSync(new URL('./wrangler.toml',import.meta.url),'utf8');
const centralEntry=fs.readFileSync(new URL('../../customer-entry-worker.js',import.meta.url),'utf8');
const centralWrangler=fs.readFileSync(new URL('../../wrangler.api.toml',import.meta.url),'utf8');
for(const required of ['AI 보험점검','내 보험','청구도움','비교 준비','상담','개인정보 보호센터','보험설계사 되어보기']){if(!html.includes(required))throw new Error(`missing UI: ${required}`)}
for(const required of ['localStorage','diagnosisPriority','analysisRules','claimDocs','deleteAllDataBtn','setupAdvisorChat','aiReply','humanRequestForm','summarizeConversation']){if(!js.includes(required))throw new Error(`missing behavior: ${required}`)}
for(const required of ['AI가 먼저 충분히 상담합니다.','설계사 전화상담 요청','AI 상담요약','대화내용','처리상태']){if(!(js+adminHtml).includes(required))throw new Error(`missing consultation contract: ${required}`)}
if(html.includes('/100')||js.includes('diagnosisScore'))throw new Error('opaque numeric insurance score must not return');
if(!html.includes('/privacy.css')||!privacyCss.includes('.privacy-grid'))throw new Error('privacy UI stylesheet missing');
if(!chatCss.includes('.chat-layout')||!chatCss.includes('.handoff-panel'))throw new Error('AI chat stylesheet missing');
if(!adminHtml.includes('STAGING LOCAL ADMIN')||(!adminJs.includes('HUMAN_HANDOFF_QUEUE')&&!adminJs.includes('AI_CHAT_HANDOFF')))throw new Error('staging admin queue missing');
if(!html.includes('상품 추천 기능이 아닙니다.'))throw new Error('insurance recommendation boundary missing');
if(!html.includes('민감정보 입력 최소화'))throw new Error('sensitive-data minimization notice missing');
for(const marker of ["personalInsuranceCare:'my-ekodi'","personalInsurancePath:'https://ekodi.kr/my/insurance/'","consultationStorage:'encrypted-d1-on-explicit-handoff'","privacyCenter:true",'aiChat:true','humanHandoffQueue:true','adminQueue:true','externalAiProvider:false'])if(!worker.includes(marker))throw new Error(`health signal missing: ${marker}`);
for(const marker of ['ekodi-insurance-api-staging.ekodi-development.workers.dev','ekodi-insurance-api-green.topmaster-joseph.workers.dev','contactConsent','transcriptConsent','shareConsent','shareTranscript','AI 상담 대화 공유 (선택)','consultation-access-v1'])if(!bridge.includes(marker))throw new Error(`separate-consent D1 handoff bridge missing: ${marker}`);
if(!bridge.includes("messages: transcriptConsent ? messages : []"))throw new Error('unconsented AI transcript must not be sent by bridge');
if(!bridge.includes("topic: transcriptConsent ? topic : ''"))throw new Error('unconsented free-text topic must not be sent by bridge');
if(!bridge.includes('선택하지 않아도 상담요청은 가능합니다'))throw new Error('optional transcript consent disclosure missing');
if(!bridge.includes('event.stopImmediatePropagation()'))throw new Error('legacy local handoff submit must be stopped before D1 handoff');
for(const marker of ['loadReferenceCatalog','/api/network/catalog','컴플라이언스 게이트 닫힘'])if(!bridge.includes(marker))throw new Error(`reference-only comparison gate missing: ${marker}`);
for(const marker of ['serverConsultationPanel','상담요청 철회','revokeConsultation','/revoke'])if(!bridge.includes(marker))throw new Error(`customer revoke UI missing: ${marker}`);
if(!worker.includes('실제 설계사 상담을 요청할 때만 이름과 연락처를 암호화'))throw new Error('server-rendered privacy truth copy missing');
if(!worker.includes('ekodi-insurance-api-green.topmaster-joseph.workers.dev'))throw new Error('Green API CSP allowlist missing');
if(!worker.includes("frame-ancestors 'none'"))throw new Error('CSP missing');
for(const marker of ['insuranceAdminEnabled','INSURANCE_ADMIN_ENABLED','disabledInsuranceAdminResponse','INSURANCE_ADMIN_NOT_ENABLED'])if(!centralEntry.includes(marker))throw new Error(`central Insurance default-off gate missing: ${marker}`);
if(!centralWrangler.includes('INSURANCE_ADMIN_ENABLED = "false"'))throw new Error('production central Insurance admin route must remain disabled by default');
for(const marker of ['__LANG__','__TITLE__','__DESCRIPTION__','data-i18n="liabilityTitle"','data-i18n="roadsideTitle"','보험사·설계사와 무관한 일반적인 공용 정보'])if(!carGuideHtml.includes(marker))throw new Error(`multilingual car guide shell missing: ${marker}`);
for(const marker of ["SUPPORTED_LANGUAGES=['ko','en','zh-CN','vi']",'Liability Insurance','汽车责任保险','Bảo hiểm trách nhiệm','navigator.share','navigator.clipboard.writeText','/guide/car-insurance/'])if(!carGuideJs.includes(marker))throw new Error(`multilingual car guide behavior missing: ${marker}`);
for(const marker of ['/guide/car-insurance','/advisor/guide/car-insurance','multilingualCarGuide:true','publicMultilingualCarGuide:true','advisorGuideCanonicalRedirect:true','CAR_GUIDE_META','injectBridge:false','content-language'])if(!worker.includes(marker))throw new Error(`multilingual car guide route missing: ${marker}`);
for(const marker of ['id="foreignGuide"','/guide/car-insurance/ko','/guide/car-insurance/en','/guide/car-insurance/zh-CN','/guide/car-insurance/vi'])if(!advisorHtml.includes(marker))throw new Error(`advisor public multilingual entry missing: ${marker}`);
if(!carGuideHtml.includes('id="insuranceHomeLink"'))throw new Error('public guide insurance-home link missing');
if(carGuideHtml.includes('Advisor Quick Guide')||carGuideHtml.includes('정찬균 설계사 페이지로'))throw new Error('public guide must not be advisor-owned');
if(!carGuideCss.includes('@media(max-width:720px)')||!carGuideCss.includes('.guide-grid'))throw new Error('responsive car guide styles missing');
if(/롯데|Lotte/i.test(carGuideHtml+carGuideJs))throw new Error('unapproved insurer brand must not appear in generic guide content');
if(/최적|best product|추천상품/i.test(carGuideHtml+carGuideJs))throw new Error('car guide must remain general information, not product recommendation');
for(const marker of ['보험이란?','자동차보험','실손의료보험','건강·질병보험','배상책임보험','연금·저축성보험','/guide/insurance/'])if(!knowledgeJs.includes(marker))throw new Error(`knowledge hub missing: ${marker}`);
if(!knowledgeCss.includes('.knowledge-topics')||!knowledgeCss.includes('@media(max-width:560px)'))throw new Error('knowledge hub responsive styles missing');
for(const marker of ['topicTitle','lawPanel','advisorPanel','보험사별 추가 안내'])if(!detailHtml.includes(marker))throw new Error(`insurance detail shell missing: ${marker}`);
for(const marker of ["auto:{title:'자동차보험'",'1억5천만원','2천만원','긴급출동서비스','/api/advisor/profile','insurance-law-sources.json'])if(!detailJs.includes(marker))throw new Error(`insurance detail content missing: ${marker}`);
if(!detailCss.includes('.advisor-link')||!detailCss.includes('@media(max-width:720px)'))throw new Error('insurance detail responsive styles missing');
if(lawManifest.lastVerifiedAt!=='2026-09-11')throw new Error('law manifest verification date missing');
const autoLaw=lawManifest.topics?.auto;if(!autoLaw||autoLaw.sources?.length<3)throw new Error('automobile law sources incomplete');
for(const fact of ['1억5천만원','2천만원'])if(!JSON.stringify(autoLaw).includes(fact))throw new Error(`automobile law fact missing: ${fact}`);
for(const marker of ['law.go.kr','source.markers','normalizeLawText','process.exit(1)'])if(!lawWatch.includes(marker))throw new Error(`law source watcher missing: ${marker}`);
for(const marker of ['insuranceKnowledgeHub:true','lawSourceManifest:true','/guide/insurance/'])if(!worker.includes(marker))throw new Error(`knowledge hub worker integration missing: ${marker}`);
if(!wrangler.includes('"/guide/*"')||!wrangler.includes('"/advisor/guide/*"'))throw new Error('guide paths must run worker first');
console.log('EKODI Insurance free-D1 single-source separate-consent consultation checks passed');
console.log('EKODI Insurance public knowledge hub and advisor bridge checks passed');
console.log('EKODI Insurance public multilingual car guide canonical checks passed');
console.log('EKODI Insurance official law-source governance checks passed');
