-- EKODIBIZ trade counterparty administration with explicit company scopes.
-- Overall EKODIBIZ tenant admins retain full authority; delegated trade admins are scoped independently.

create table if not exists public.trade_counterparties (
  id uuid primary key default gen_random_uuid(),
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  slug text not null,
  display_name text not null,
  legal_name text not null default '',
  country_code text not null default '',
  registration_no text not null default '',
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trade_counterparties_slug_format check (slug ~ '^[a-z0-9][a-z0-9-]{0,98}$'),
  constraint trade_counterparties_status_check check (status in ('active','paused','archived')),
  unique (workspace_tenant_id, slug)
);

create table if not exists public.trade_admin_grants (
  id uuid primary key default gen_random_uuid(),
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  person_id uuid references public.people(id) on delete set null,
  email text not null,
  role text not null,
  scope_mode text not null default 'selected',
  status text not null default 'active',  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trade_admin_grants_email_lower check (email = lower(email)),
  constraint trade_admin_grants_role_check check (role in ('trade_admin','trade_manager','trade_viewer')),
  constraint trade_admin_grants_scope_check check (scope_mode in ('all','selected')),
  constraint trade_admin_grants_status_check check (status in ('active','disabled')),
  unique (workspace_tenant_id, email)
);

create table if not exists public.trade_admin_company_scopes (
  grant_id uuid not null references public.trade_admin_grants(id) on delete cascade,
  counterparty_id uuid not null references public.trade_counterparties(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (grant_id, counterparty_id)
);

create table if not exists public.trade_access_audit_log (
  id bigint generated by default as identity primary key,
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  actor_user_id uuid,
  action text not null,
  resource_type text not null,
  resource_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_counterparties_workspace_status_idx
  on public.trade_counterparties(workspace_tenant_id, status, display_name);create index if not exists trade_admin_grants_person_idx
  on public.trade_admin_grants(workspace_tenant_id, person_id) where person_id is not null;
create index if not exists trade_admin_scopes_counterparty_idx
  on public.trade_admin_company_scopes(counterparty_id, grant_id);
create index if not exists trade_access_audit_workspace_created_idx
  on public.trade_access_audit_log(workspace_tenant_id, created_at desc);

alter table public.trade_counterparties enable row level security;
alter table public.trade_admin_grants enable row level security;
alter table public.trade_admin_company_scopes enable row level security;
alter table public.trade_access_audit_log enable row level security;

revoke all on table public.trade_counterparties from anon, authenticated;
revoke all on table public.trade_admin_grants from anon, authenticated;
revoke all on table public.trade_admin_company_scopes from anon, authenticated;
revoke all on table public.trade_access_audit_log from anon, authenticated;

insert into public.site_access_registry(email,site_key,tenant_id,role,status,source,note,plan,created_at,updated_at)
select distinct lower(li.email),'trade',t.id,'member'::public.app_role,'active','ekodibiz_workspace_admin','EKODIBIZ trade workspace access','standard',now(),now()
  from public.tenants t
  join public.tenant_members tm on tm.tenant_id=t.id and tm.status='active' and tm.role::text='tenant_admin'
  join public.login_identities li on li.auth_user_id=tm.user_id and li.status='active'
 where t.slug='ekodi-biz'
on conflict(email,site_key,tenant_id,role) do update set status='active',source=excluded.source,note=excluded.note,updated_at=now();

create or replace function public.trade_workspace_admin(p_workspace_tenant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
      from public.tenant_members tm
     where tm.tenant_id = p_workspace_tenant_id
       and tm.user_id = auth.uid()
       and tm.status = 'active'
       and tm.role::text in ('tenant_admin','owner')
  );
$$;create or replace function public.trade_current_access(p_workspace_slug text default 'ekodi-biz')
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_workspace_id uuid;
  v_email text := lower(coalesce(auth.jwt()->>'email',''));
  v_person_id uuid;
  v_grant public.trade_admin_grants%rowtype;
  v_company_ids jsonb := '[]'::jsonb;
begin
  if auth.uid() is null or v_email = '' then
    return jsonb_build_object('allowed',false,'reason','auth_required');
  end if;

  select id into v_workspace_id
    from public.tenants
   where slug = p_workspace_slug and status = 'active'
   limit 1;
  if v_workspace_id is null then
    return jsonb_build_object('allowed',false,'reason','workspace_not_found');
  end if;

  if public.trade_workspace_admin(v_workspace_id) then
    return jsonb_build_object(
      'allowed',true,'source','workspace_admin','workspace_id',v_workspace_id,
      'role','workspace_admin','scope_mode','all','company_ids','[]'::jsonb,
      'can_write',true,'can_manage_companies',true,'can_manage_access',true
    );
  end if;  select li.person_id into v_person_id
    from public.login_identities li
   where li.auth_user_id = auth.uid()
     and li.status = 'active'
   order by li.is_primary desc, li.linked_at asc
   limit 1;

  select g.* into v_grant
    from public.trade_admin_grants g
   where g.workspace_tenant_id = v_workspace_id
     and g.status = 'active'
     and (
       (v_person_id is not null and g.person_id = v_person_id)
       or lower(g.email) = v_email
     )
   order by case when v_person_id is not null and g.person_id = v_person_id then 0 else 1 end,
            g.updated_at desc
   limit 1;

  if v_grant.id is null then
    return jsonb_build_object('allowed',false,'reason','trade_access_required','workspace_id',v_workspace_id);
  end if;

  if v_grant.scope_mode = 'selected' then
    select coalesce(jsonb_agg(s.counterparty_id order by s.counterparty_id), '[]'::jsonb)
      into v_company_ids
      from public.trade_admin_company_scopes s
     where s.grant_id = v_grant.id;
  end if;

  return jsonb_build_object(
    'allowed',true,'source','trade_grant','workspace_id',v_workspace_id,
    'grant_id',v_grant.id,'role',v_grant.role,'scope_mode',v_grant.scope_mode,
    'company_ids',v_company_ids,
    'can_write',v_grant.role in ('trade_admin','trade_manager'),
    'can_manage_companies',v_grant.role = 'trade_admin' and v_grant.scope_mode = 'all',
    'can_manage_access',false
  );
end
$$;create or replace function public.trade_visible_counterparties(p_workspace_slug text default 'ekodi-biz')
returns table(
  id uuid, slug text, display_name text, legal_name text,
  country_code text, registration_no text, status text,
  metadata jsonb, created_at timestamptz, updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_access jsonb := public.trade_current_access(p_workspace_slug);
  v_workspace_id uuid := nullif(v_access->>'workspace_id','')::uuid;
  v_scope text := coalesce(v_access->>'scope_mode','');
  v_grant_id uuid := nullif(v_access->>'grant_id','')::uuid;
begin
  if coalesce((v_access->>'allowed')::boolean,false) is not true then
    return;
  end if;

  if v_scope = 'all' then
    return query
      select c.id,c.slug,c.display_name,c.legal_name,c.country_code,c.registration_no,
             c.status,c.metadata,c.created_at,c.updated_at
        from public.trade_counterparties c
       where c.workspace_tenant_id = v_workspace_id
       order by c.display_name, c.created_at;
    return;
  end if;

  return query
    select c.id,c.slug,c.display_name,c.legal_name,c.country_code,c.registration_no,
           c.status,c.metadata,c.created_at,c.updated_at
      from public.trade_counterparties c
      join public.trade_admin_company_scopes s on s.counterparty_id = c.id
     where s.grant_id = v_grant_id
       and c.workspace_tenant_id = v_workspace_id
     order by c.display_name, c.created_at;
end
$$;create or replace function public.trade_list_admin_grants(p_workspace_slug text default 'ekodi-biz')
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_workspace_id uuid;
  v_result jsonb;
begin
  select id into v_workspace_id
    from public.tenants
   where slug = p_workspace_slug and status = 'active'
   limit 1;
  if v_workspace_id is null then
    return jsonb_build_object('error','workspace_not_found');
  end if;
  if not public.trade_workspace_admin(v_workspace_id) then
    return jsonb_build_object('error','workspace_admin_required');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',g.id,'email',g.email,'person_id',g.person_id,'role',g.role,
    'scope_mode',g.scope_mode,'status',g.status,'created_at',g.created_at,'updated_at',g.updated_at,
    'companies',coalesce((
      select jsonb_agg(jsonb_build_object('id',c.id,'slug',c.slug,'name',c.display_name) order by c.display_name)
        from public.trade_admin_company_scopes s
        join public.trade_counterparties c on c.id = s.counterparty_id
       where s.grant_id = g.id
    ),'[]'::jsonb)
  ) order by g.email),'[]'::jsonb)
    into v_result
    from public.trade_admin_grants g
   where g.workspace_tenant_id = v_workspace_id;

  return jsonb_build_object('workspace_id',v_workspace_id,'admins',v_result);
end
$$;create or replace function public.trade_upsert_counterparty(
  p_workspace_slug text,
  p_id uuid,
  p_slug text,
  p_display_name text,
  p_legal_name text default '',
  p_country_code text default '',
  p_registration_no text default '',
  p_status text default 'active'
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_access jsonb := public.trade_current_access(p_workspace_slug);
  v_workspace_id uuid := nullif(v_access->>'workspace_id','')::uuid;
  v_id uuid;
  v_slug text := lower(trim(coalesce(p_slug,'')));
  v_name text := trim(coalesce(p_display_name,''));
begin
  if coalesce((v_access->>'allowed')::boolean,false) is not true
     or coalesce((v_access->>'can_manage_companies')::boolean,false) is not true then
    return jsonb_build_object('error','trade_company_manage_forbidden');
  end if;
  if v_slug !~ '^[a-z0-9][a-z0-9-]{0,98}$' or v_name = '' then
    return jsonb_build_object('error','invalid_counterparty');
  end if;

  if p_id is null then
    insert into public.trade_counterparties(
      workspace_tenant_id,slug,display_name,legal_name,country_code,registration_no,status,created_by
    ) values (
      v_workspace_id,v_slug,v_name,trim(coalesce(p_legal_name,'')),upper(trim(coalesce(p_country_code,''))),
      trim(coalesce(p_registration_no,'')),coalesce(nullif(p_status,''),'active'),auth.uid()
    ) returning id into v_id;
  else
    update public.trade_counterparties
       set slug=v_slug,display_name=v_name,legal_name=trim(coalesce(p_legal_name,'')),
           country_code=upper(trim(coalesce(p_country_code,''))),registration_no=trim(coalesce(p_registration_no,'')),
           status=coalesce(nullif(p_status,''),'active'),updated_at=now()
     where id=p_id and workspace_tenant_id=v_workspace_id
     returning id into v_id;
  end if;  if v_id is null then
    return jsonb_build_object('error','counterparty_not_found');
  end if;

  insert into public.trade_access_audit_log(
    workspace_tenant_id,actor_user_id,action,resource_type,resource_id,metadata
  ) values (
    v_workspace_id,auth.uid(),case when p_id is null then 'trade.counterparty.create' else 'trade.counterparty.update' end,
    'counterparty',v_id::text,jsonb_build_object('slug',v_slug,'display_name',v_name,'status',p_status)
  );

  return jsonb_build_object('ok',true,'id',v_id,'slug',v_slug);
exception
  when unique_violation then
    return jsonb_build_object('error','counterparty_slug_exists');
  when check_violation then
    return jsonb_build_object('error','invalid_counterparty');
end
$$;

create or replace function public.trade_upsert_admin_grant(
  p_workspace_slug text,
  p_email text,
  p_role text,
  p_scope_mode text,
  p_counterparty_ids uuid[] default '{}'::uuid[],
  p_status text default 'active'
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_workspace_id uuid;
  v_email text := lower(trim(coalesce(p_email,'')));
  v_person_id uuid;
  v_grant_id uuid;
  v_invalid_count integer := 0;
begin
  select id into v_workspace_id
    from public.tenants
   where slug = p_workspace_slug and status = 'active'
   limit 1;
  if v_workspace_id is null then
    return jsonb_build_object('error','workspace_not_found');
  end if;
  if not public.trade_workspace_admin(v_workspace_id) then
    return jsonb_build_object('error','workspace_admin_required');
  end if;  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    return jsonb_build_object('error','invalid_email');
  end if;
  if p_role not in ('trade_admin','trade_manager','trade_viewer') then
    return jsonb_build_object('error','invalid_role');
  end if;
  if p_scope_mode not in ('all','selected') then
    return jsonb_build_object('error','invalid_scope_mode');
  end if;
  if p_status not in ('active','disabled') then
    return jsonb_build_object('error','invalid_status');
  end if;

  if p_scope_mode = 'selected' then
    if coalesce(cardinality(p_counterparty_ids),0) = 0 then
      return jsonb_build_object('error','selected_companies_required');
    end if;
    select count(*) into v_invalid_count
      from unnest(p_counterparty_ids) requested(id)
      left join public.trade_counterparties c
        on c.id=requested.id and c.workspace_tenant_id=v_workspace_id and c.status <> 'archived'
     where c.id is null;
    if v_invalid_count > 0 then
      return jsonb_build_object('error','invalid_counterparty_scope');
    end if;
  end if;

  select li.person_id into v_person_id
    from public.login_identities li
   where lower(li.email) = v_email and li.status = 'active'
   order by li.is_primary desc, li.linked_at asc
   limit 1;

  insert into public.trade_admin_grants(
    workspace_tenant_id,person_id,email,role,scope_mode,status,created_by
  ) values (
    v_workspace_id,v_person_id,v_email,p_role,p_scope_mode,p_status,auth.uid()
  )
  on conflict (workspace_tenant_id,email) do update
    set person_id=coalesce(excluded.person_id,public.trade_admin_grants.person_id),
        role=excluded.role,scope_mode=excluded.scope_mode,status=excluded.status,
        updated_at=now()
  returning id into v_grant_id;

  insert into public.site_access_registry(email,site_key,tenant_id,role,status,source,note,plan,created_at,updated_at)
  values(v_email,'trade',v_workspace_id,'member'::public.app_role,
    case when p_status='disabled' then 'revoked' else 'active' end,
    'trade_admin_grant','Trade admin scope: '||p_scope_mode,'standard',now(),now())
  on conflict(email,site_key,tenant_id,role) do update
    set status=excluded.status,source=excluded.source,note=excluded.note,updated_at=now();

  delete from public.trade_admin_company_scopes where grant_id=v_grant_id;
  if p_scope_mode = 'selected' and p_status = 'active' then
    insert into public.trade_admin_company_scopes(grant_id,counterparty_id)
    select v_grant_id, id from unnest(p_counterparty_ids) scoped(id)
    on conflict do nothing;
  end if;

  insert into public.trade_access_audit_log(
    workspace_tenant_id,actor_user_id,action,resource_type,resource_id,metadata
  ) values (
    v_workspace_id,auth.uid(),'trade.admin.upsert','trade_admin_grant',v_grant_id::text,
    jsonb_build_object('email',v_email,'role',p_role,'scope_mode',p_scope_mode,'status',p_status,
      'counterparty_ids',to_jsonb(coalesce(p_counterparty_ids,'{}'::uuid[])))
  );

  return jsonb_build_object('ok',true,'id',v_grant_id,'email',v_email,'role',p_role,
    'scope_mode',p_scope_mode,'status',p_status);
end
$$;

revoke all on function public.trade_workspace_admin(uuid) from public, anon;
revoke all on function public.trade_current_access(text) from public, anon;
revoke all on function public.trade_visible_counterparties(text) from public, anon;
revoke all on function public.trade_list_admin_grants(text) from public, anon;
revoke all on function public.trade_upsert_counterparty(text,uuid,text,text,text,text,text,text) from public, anon;
revoke all on function public.trade_upsert_admin_grant(text,text,text,text,uuid[],text) from public, anon;

grant execute on function public.trade_workspace_admin(uuid) to authenticated;
grant execute on function public.trade_current_access(text) to authenticated;
grant execute on function public.trade_visible_counterparties(text) to authenticated;
grant execute on function public.trade_list_admin_grants(text) to authenticated;
grant execute on function public.trade_upsert_counterparty(text,uuid,text,text,text,text,text,text) to authenticated;
grant execute on function public.trade_upsert_admin_grant(text,text,text,text,uuid[],text) to authenticated;