-- EKODI Trade shared operating layer.
-- Reuses the canonical trade_counterparties / trade_admin_* model and adds
-- tenant + counterparty scoped trade cases, documents, approvals, and audit events.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.trade_counterparties'::regclass
      AND conname = 'trade_counterparties_workspace_id_unique'
  ) THEN
    ALTER TABLE public.trade_counterparties
      ADD CONSTRAINT trade_counterparties_workspace_id_unique
      UNIQUE (workspace_tenant_id, id);
  END IF;
END $$;

create table if not exists public.trade_cases (
  id uuid primary key default gen_random_uuid(),
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  counterparty_id uuid,
  trade_key text not null,
  title text not null default '',
  direction text not null default 'import' check(direction in ('import','export')),
  state text not null default 'draft' check(state in ('draft','quoted','ordered','production','ready_to_ship','in_transit','customs','released','delivered','closed','cancelled')),
  currency text not null default 'USD',
  incoterm text,
  hs_code text,
  fta_claimed boolean not null default false,
  regulated boolean not null default false,
  operational_data jsonb not null default '{}'::jsonb,
  financial_data jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_tenant_id,trade_key),
  unique(workspace_tenant_id,id),
  foreign key(workspace_tenant_id,counterparty_id)
    references public.trade_counterparties(workspace_tenant_id,id) on delete restrict
);

create table if not exists public.trade_documents (
  id uuid primary key default gen_random_uuid(),
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  trade_case_id uuid not null,
  counterparty_id uuid,
  document_type text not null,
  storage_ref text,
  status text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(workspace_tenant_id,trade_case_id)
    references public.trade_cases(workspace_tenant_id,id) on delete cascade,
  foreign key(workspace_tenant_id,counterparty_id)
    references public.trade_counterparties(workspace_tenant_id,id) on delete set null
);

create table if not exists public.trade_approvals (
  id uuid primary key default gen_random_uuid(),
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  trade_case_id uuid not null,
  gate text not null,
  status text not null default 'pending' check(status in ('pending','approved','rejected','revoked')),
  requested_by uuid references auth.users(id),
  decided_by uuid references auth.users(id),
  decided_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  foreign key(workspace_tenant_id,trade_case_id)
    references public.trade_cases(workspace_tenant_id,id) on delete cascade
);

create table if not exists public.trade_audit_events (
  id bigint generated by default as identity primary key,
  workspace_tenant_id uuid not null references public.tenants(id) on delete cascade,
  counterparty_id uuid,
  trade_case_id uuid,
  actor_user_id uuid references auth.users(id),
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  foreign key(workspace_tenant_id,counterparty_id)
    references public.trade_counterparties(workspace_tenant_id,id) on delete set null,
  foreign key(workspace_tenant_id,trade_case_id)
    references public.trade_cases(workspace_tenant_id,id) on delete set null
);

create index if not exists trade_cases_workspace_counterparty_idx on public.trade_cases(workspace_tenant_id,counterparty_id,state);
create index if not exists trade_documents_case_idx on public.trade_documents(workspace_tenant_id,trade_case_id);
create index if not exists trade_approvals_case_idx on public.trade_approvals(workspace_tenant_id,trade_case_id,status);
create index if not exists trade_audit_workspace_idx on public.trade_audit_events(workspace_tenant_id,created_at desc);

create or replace function public.trade_case_access(
  p_workspace_tenant_id uuid,
  p_counterparty_id uuid default null,
  p_write boolean default false
) returns boolean
language plpgsql stable security definer
set search_path=public,auth
as $$
declare
  v_email text := lower(coalesce(auth.jwt()->>'email',''));
  v_grant public.trade_admin_grants%rowtype;
begin
  if auth.uid() is null then return false; end if;

  if exists (
    select 1 from public.tenant_members tm
    where tm.tenant_id=p_workspace_tenant_id
      and tm.user_id=auth.uid()
      and tm.status='active'
  ) then return true; end if;

  if v_email='' then return false; end if;
  select * into v_grant
  from public.trade_admin_grants g
  where g.workspace_tenant_id=p_workspace_tenant_id
    and g.email=v_email
    and g.status='active'
  limit 1;

  if v_grant.id is null then return false; end if;
  if p_write and v_grant.role not in ('trade_admin','trade_manager') then return false; end if;
  if v_grant.scope_mode='all' then return true; end if;
  if p_counterparty_id is null then return false; end if;

  return exists (
    select 1 from public.trade_admin_company_scopes s
    where s.grant_id=v_grant.id and s.counterparty_id=p_counterparty_id
  );
end
$$;

alter table public.trade_cases enable row level security;
alter table public.trade_documents enable row level security;
alter table public.trade_approvals enable row level security;
alter table public.trade_audit_events enable row level security;

DROP POLICY IF EXISTS trade_cases_read ON public.trade_cases;
DROP POLICY IF EXISTS trade_cases_write ON public.trade_cases;
DROP POLICY IF EXISTS trade_documents_read ON public.trade_documents;
DROP POLICY IF EXISTS trade_documents_write ON public.trade_documents;
DROP POLICY IF EXISTS trade_approvals_read ON public.trade_approvals;
DROP POLICY IF EXISTS trade_approvals_write ON public.trade_approvals;
DROP POLICY IF EXISTS trade_audit_read ON public.trade_audit_events;
DROP POLICY IF EXISTS trade_audit_insert ON public.trade_audit_events;

create policy trade_cases_read on public.trade_cases for select to authenticated
using(public.trade_case_access(workspace_tenant_id,counterparty_id,false));
create policy trade_cases_write on public.trade_cases for all to authenticated
using(public.trade_case_access(workspace_tenant_id,counterparty_id,true))
with check(public.trade_case_access(workspace_tenant_id,counterparty_id,true));

create policy trade_documents_read on public.trade_documents for select to authenticated
using(public.trade_case_access(workspace_tenant_id,counterparty_id,false));
create policy trade_documents_write on public.trade_documents for all to authenticated
using(public.trade_case_access(workspace_tenant_id,counterparty_id,true))
with check(public.trade_case_access(workspace_tenant_id,counterparty_id,true));

create policy trade_approvals_read on public.trade_approvals for select to authenticated
using(exists(select 1 from public.trade_cases c where c.id=trade_case_id and c.workspace_tenant_id=trade_approvals.workspace_tenant_id and public.trade_case_access(c.workspace_tenant_id,c.counterparty_id,false)));
create policy trade_approvals_write on public.trade_approvals for all to authenticated
using(exists(select 1 from public.trade_cases c where c.id=trade_case_id and c.workspace_tenant_id=trade_approvals.workspace_tenant_id and public.trade_case_access(c.workspace_tenant_id,c.counterparty_id,true)))
with check(exists(select 1 from public.trade_cases c where c.id=trade_case_id and c.workspace_tenant_id=trade_approvals.workspace_tenant_id and public.trade_case_access(c.workspace_tenant_id,c.counterparty_id,true)));

create policy trade_audit_read on public.trade_audit_events for select to authenticated
using(public.trade_case_access(workspace_tenant_id,counterparty_id,false));
create policy trade_audit_insert on public.trade_audit_events for insert to authenticated
with check(actor_user_id=auth.uid() and public.trade_case_access(workspace_tenant_id,counterparty_id,true));

grant select,insert,update,delete on public.trade_cases to authenticated;
grant select,insert,update,delete on public.trade_documents to authenticated;
grant select,insert,update,delete on public.trade_approvals to authenticated;
grant select,insert on public.trade_audit_events to authenticated;
grant execute on function public.trade_case_access(uuid,uuid,boolean) to authenticated;
