-- Modular EKODI identity foundation.
-- Additive only: existing Google login and person/login_identity relationships remain intact.

alter table public.people
  add column if not exists ekodi_id text;

update public.people
   set ekodi_id = 'EKD-' || upper(replace(id::text, '-', ''))
 where ekodi_id is null;

alter table public.people
  alter column ekodi_id set not null;

create unique index if not exists people_ekodi_id_uidx
  on public.people(ekodi_id);

create table if not exists public.identity_providers (
  provider text primary key,
  display_name text not null,
  strategy text not null,
  enabled boolean not null default false,
  supports_login boolean not null default true,
  supports_link boolean not null default true,
  requires_verified_email boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint identity_providers_provider_format check (provider ~ '^[a-z0-9][a-z0-9_-]{0,31}$')
);

insert into public.identity_providers
  (provider, display_name, strategy, enabled, supports_login, supports_link, requires_verified_email, sort_order)
values
  ('google', 'Google', 'google_identity_services', true, true, true, true, 10),
  ('kakao', '카카오', 'oauth2', false, true, true, false, 20),
  ('naver', '네이버', 'oauth2', false, true, true, false, 30),
  ('apple', 'Apple', 'oidc', false, true, true, false, 40),
  ('microsoft', 'Microsoft', 'oidc', false, true, true, true, 50),
  ('passkey', '패스키', 'webauthn', false, true, true, false, 60)
on conflict (provider) do update
set display_name = excluded.display_name,
    strategy = excluded.strategy,
    supports_login = excluded.supports_login,
    supports_link = excluded.supports_link,
    requires_verified_email = excluded.requires_verified_email,
    sort_order = excluded.sort_order,
    updated_at = now();

alter table public.identity_challenges
  add column if not exists provider text not null default 'google';

create index if not exists identity_challenges_provider_expiry_idx
  on public.identity_challenges(provider, expires_at);

create table if not exists public.identity_audit_logs (
  id bigint generated by default as identity primary key,
  person_id uuid references public.people(id) on delete set null,
  auth_user_id uuid,
  action text not null,
  provider text,
  identity_id uuid references public.login_identities(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint identity_audit_action_format check (action ~ '^[a-z0-9_.-]{2,80}$')
);

create index if not exists identity_audit_person_created_idx
  on public.identity_audit_logs(person_id, created_at desc);
create index if not exists identity_audit_auth_user_created_idx
  on public.identity_audit_logs(auth_user_id, created_at desc);

alter table public.identity_providers enable row level security;
alter table public.identity_audit_logs enable row level security;
revoke all on table public.identity_providers from anon, authenticated;
revoke all on table public.identity_audit_logs from anon, authenticated;

create or replace function public.disconnect_person_identity(
  p_initiator_user_id uuid,
  p_identity_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_person_id uuid;
  v_target_person_id uuid;
  v_target_auth_user_id uuid;
  v_target_primary boolean;
  v_active_count integer;
  v_next_identity uuid;
begin
  select person_id
    into v_person_id
    from public.login_identities
   where auth_user_id = p_initiator_user_id
     and status = 'active'
   limit 1;

  if v_person_id is null then
    raise exception 'initiator_person_required';
  end if;

  select person_id, auth_user_id, is_primary
    into v_target_person_id, v_target_auth_user_id, v_target_primary
    from public.login_identities
   where id = p_identity_id
     and status = 'active';

  if v_target_person_id is null or v_target_person_id <> v_person_id then
    raise exception 'identity_not_found';
  end if;

  select count(*)
    into v_active_count
    from public.login_identities
   where person_id = v_person_id
     and status = 'active';

  if v_active_count <= 1 then
    raise exception 'last_identity_cannot_disconnect';
  end if;

  if v_target_auth_user_id = p_initiator_user_id then
    raise exception 'current_identity_cannot_disconnect';
  end if;

  update public.login_identities
     set status = 'disconnected',
         is_primary = false,
         last_seen_at = now()
   where id = p_identity_id;

  if v_target_primary then
    select id
      into v_next_identity
      from public.login_identities
     where person_id = v_person_id
       and status = 'active'
     order by linked_at asc
     limit 1;

    update public.login_identities
       set is_primary = (id = v_next_identity)
     where person_id = v_person_id
       and status = 'active';
  end if;

  insert into public.identity_audit_logs(person_id, auth_user_id, action, identity_id)
  values (v_person_id, p_initiator_user_id, 'identity.disconnected', p_identity_id);

  return v_person_id;
end
$$;

revoke all on function public.disconnect_person_identity(uuid, uuid) from public, anon, authenticated;
grant execute on function public.disconnect_person_identity(uuid, uuid) to service_role;
