-- EKODI Trade shared module. Canonical hierarchy:
-- platform -> tenant company -> counterparty company -> trade case.
-- Existing tenants / tenant_members remain the identity and authorization source.

create table if not exists public.trade_counterparties (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  slug text not null,
  name text not null,
  type text not null default 'other' check(type in ('supplier','buyer','agent','broker','forwarder','customs','other')),
  country_code text,
  status text not null default 'active' check(status in ('active','inactive','blocked')),
  unique_profile jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tenant_id,slug)
);

create table if not exists public.trade_cases (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  counterparty_id uuid references public.trade_counterparties(id) on delete restrict,
  trade_key text not null,
  title text not null default '',
  direction text not null default 'import' check(direction in ('import','export')),
  state text not null default 'draft',
  supplier_id uuid references public.trade_counterparties(id) on delete restrict,
  buyer_id uuid references public.trade_counterparties(id) on delete restrict,
  currency text not null default 'USD',
  incoterm text,
  hs_code text,
  fta_claimed boolean not null default false,
  regulated boolean not null default false,
  operational_data jsonb not null default '{}'::jsonb,
  financial_data jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tenant_id,trade_key)
);

create table if not exists public.trade_documents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  trade_case_id uuid not null references public.trade_cases(id) on delete cascade,
  counterparty_id uuid references public.trade_counterparties(id) on delete set null,
  document_type text not null,
  storage_ref text,
  status text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_approvals (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  trade_case_id uuid not null references public.trade_cases(id) on delete cascade,
  gate text not null,
  status text not null default 'pending' check(status in ('pending','approved','rejected','revoked')),
  requested_by uuid references auth.users(id),
  decided_by uuid references auth.users(id),
  decided_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_audit_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  counterparty_id uuid references public.trade_counterparties(id) on delete set null,
  trade_case_id uuid references public.trade_cases(id) on delete set null,
  actor_user_id uuid references auth.users(id),
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_counterparties_tenant_idx on public.trade_counterparties(tenant_id,status,name);
create index if not exists trade_cases_tenant_counterparty_idx on public.trade_cases(tenant_id,counterparty_id,state);
create index if not exists trade_documents_case_idx on public.trade_documents(tenant_id,trade_case_id);
create index if not exists trade_approvals_case_idx on public.trade_approvals(tenant_id,trade_case_id,status);
create index if not exists trade_audit_tenant_idx on public.trade_audit_events(tenant_id,created_at desc);

create or replace function public.trade_tenant_member(p_tenant_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.tenant_members tm
    where tm.tenant_id=p_tenant_id and tm.user_id=auth.uid() and tm.status='active'
  );
$$;

create or replace function public.trade_tenant_manager(p_tenant_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.tenant_members tm
    where tm.tenant_id=p_tenant_id and tm.user_id=auth.uid() and tm.status='active'
      and tm.role::text in ('tenant_admin','owner','manager','admin')
  );
$$;

grant execute on function public.trade_tenant_member(uuid) to authenticated;
grant execute on function public.trade_tenant_manager(uuid) to authenticated;

alter table public.trade_counterparties enable row level security;
alter table public.trade_cases enable row level security;
alter table public.trade_documents enable row level security;
alter table public.trade_approvals enable row level security;
alter table public.trade_audit_events enable row level security;

create policy trade_counterparties_read on public.trade_counterparties for select to authenticated using(public.trade_tenant_member(tenant_id));
create policy trade_counterparties_write on public.trade_counterparties for all to authenticated using(public.trade_tenant_manager(tenant_id)) with check(public.trade_tenant_manager(tenant_id));
create policy trade_cases_read on public.trade_cases for select to authenticated using(public.trade_tenant_member(tenant_id));
create policy trade_cases_write on public.trade_cases for all to authenticated using(public.trade_tenant_member(tenant_id)) with check(public.trade_tenant_member(tenant_id));
create policy trade_documents_read on public.trade_documents for select to authenticated using(public.trade_tenant_member(tenant_id));
create policy trade_documents_write on public.trade_documents for all to authenticated using(public.trade_tenant_member(tenant_id)) with check(public.trade_tenant_member(tenant_id));
create policy trade_approvals_read on public.trade_approvals for select to authenticated using(public.trade_tenant_member(tenant_id));
create policy trade_approvals_write on public.trade_approvals for all to authenticated using(public.trade_tenant_manager(tenant_id)) with check(public.trade_tenant_manager(tenant_id));
create policy trade_audit_read on public.trade_audit_events for select to authenticated using(public.trade_tenant_member(tenant_id));
create policy trade_audit_insert on public.trade_audit_events for insert to authenticated with check(public.trade_tenant_member(tenant_id) and actor_user_id=auth.uid());

grant select,insert,update,delete on public.trade_counterparties to authenticated;
grant select,insert,update,delete on public.trade_cases to authenticated;
grant select,insert,update,delete on public.trade_documents to authenticated;
grant select,insert,update,delete on public.trade_approvals to authenticated;
grant select,insert on public.trade_audit_events to authenticated;
