-- Reusable tenant-scoped organization operations for presbyteries, inspection bodies and associations.
-- Issue #1691 activates the engine for the Hammu inspection body without granting platform-global authority.

insert into public.tenants(slug,name,status,kind,settings)
values ('hammu','함무시찰회','active','association',jsonb_build_object('ownership','customer','operating_model','customer-site','site_key','hammu','canonical_path','/hammu','admin_path','/hammu/admin','organization_engine','v1','default_activity_role','inspection_officer','default_activity_role_label','시찰회 임원'))
on conflict (slug) do update set name=excluded.name,status='active',kind=excluded.kind,settings=coalesce(public.tenants.settings,'{}'::jsonb)||excluded.settings;

-- Explicit one-time delegation from the user's existing platform-admin identity into this tenant.
-- This does not create implicit platform->tenant inheritance for future administrators.
with hammu as (select id from public.tenants where slug='hammu'), delegated as (
  select distinct lower(email) email from public.site_access_registry where site_key='admin' and role='platform_admin'::public.app_role and status='active'
)
insert into public.site_access_registry(email,site_key,tenant_id,role,status,source,note,plan,created_at,updated_at)
select d.email,'hammu',h.id,'tenant_admin'::public.app_role,'active','explicit_user_delegation_issue_1691','Tenant-local bootstrap delegated by the user for Hammu operations; no platform authority inheritance.','standard',now(),now() from delegated d cross join hammu h
on conflict(email,site_key,tenant_id,role) do update set status='active',source=excluded.source,note=excluded.note,updated_at=now();

with hammu as (select id from public.tenants where slug='hammu'), delegated as (
  select distinct lower(email) email from public.site_access_registry where site_key='hammu' and role='tenant_admin'::public.app_role and status='active'
), identities as (
  select distinct li.auth_user_id from public.login_identities li join delegated d on lower(li.email)=d.email where li.status='active'
)
insert into public.tenant_members(tenant_id,user_id,role,status)
select h.id,i.auth_user_id,'tenant_admin'::public.app_role,'active' from hammu h cross join identities i
on conflict(tenant_id,user_id,role) do update set status='active';

create table if not exists public.organization_profiles(tenant_id uuid primary key references public.tenants(id) on delete cascade,organization_type text not null default 'association',tagline text not null default '',description text not null default '',public_status text not null default 'review' check(public_status in ('review','published','hidden')),show_finance boolean not null default true,show_attendance boolean not null default true,updated_at timestamptz not null default now());
create table if not exists public.organization_terms(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,label text not null,starts_on date,ends_on date,status text not null default 'planned' check(status in ('planned','current','closed')),created_at timestamptz not null default now(),unique(tenant_id,label));
create table if not exists public.organization_office_rules(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,office_key text not null,office_label text not null,sort_order integer not null default 100,succession_from_office_key text,auto_success boolean not null default false,active boolean not null default true,unique(tenant_id,office_key));
create table if not exists public.organization_officers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,term_id uuid not null references public.organization_terms(id) on delete cascade,office_key text not null,church_name text not null default '',person_name text not null default '',source text not null default 'manual' check(source in ('manual','auto','override')),locked boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(term_id,office_key));
create table if not exists public.organization_notice_sources(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,source_key text not null,source_label text not null,source_url text not null,active boolean not null default true,sort_order integer not null default 100,unique(tenant_id,source_key));
create table if not exists public.organization_notices(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,source_key text not null,external_key text not null,title text not null,url text not null default '',published_at timestamptz,summary text not null default '',publication_state text not null default 'review' check(publication_state in ('review','published','hidden')),synced_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,source_key,external_key));
create table if not exists public.organization_finance_reports(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,term_id uuid references public.organization_terms(id) on delete set null,period_label text not null,period_start date,period_end date,opening_balance bigint not null default 0,income_total bigint not null default 0,expense_total bigint not null default 0,closing_balance bigint not null default 0,note text not null default '',publication_state text not null default 'review' check(publication_state in ('review','published','hidden')),updated_at timestamptz not null default now(),unique(tenant_id,period_label));
create table if not exists public.organization_finance_entries(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,report_id uuid not null references public.organization_finance_reports(id) on delete cascade,occurred_on date not null,entry_type text not null check(entry_type in ('income','expense')),category text not null default '',description text not null,amount bigint not null check(amount>=0),evidence_ref text not null default '',is_private boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.organization_meetings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,term_id uuid references public.organization_terms(id) on delete set null,held_at timestamptz not null,title text not null,venue text not null default '',attendance_public boolean not null default false,status text not null default 'scheduled' check(status in ('scheduled','open','closed','cancelled')),created_at timestamptz not null default now());
create table if not exists public.organization_attendance(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,meeting_id uuid not null references public.organization_meetings(id) on delete cascade,attendee_key text not null,attendee_name text not null,church_name text not null default '',attendance_state text not null check(attendance_state in ('present','late','absent','excused')),checked_at timestamptz not null default now(),unique(meeting_id,attendee_key));
create table if not exists public.organization_audit_logs(id bigint generated by default as identity primary key,tenant_id uuid not null references public.tenants(id) on delete cascade,actor_user_id uuid,action text not null,entity_type text not null default '',entity_id text not null default '',detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create index if not exists organization_notices_tenant_published_idx on public.organization_notices(tenant_id,publication_state,published_at desc);
create index if not exists organization_finance_reports_tenant_idx on public.organization_finance_reports(tenant_id,publication_state,updated_at desc);
create index if not exists organization_meetings_tenant_idx on public.organization_meetings(tenant_id,held_at desc);
create index if not exists organization_attendance_meeting_idx on public.organization_attendance(meeting_id,attendance_state);
create index if not exists organization_audit_tenant_idx on public.organization_audit_logs(tenant_id,created_at desc);

alter table public.organization_profiles enable row level security; alter table public.organization_terms enable row level security; alter table public.organization_office_rules enable row level security; alter table public.organization_officers enable row level security; alter table public.organization_notice_sources enable row level security; alter table public.organization_notices enable row level security; alter table public.organization_finance_reports enable row level security; alter table public.organization_finance_entries enable row level security; alter table public.organization_meetings enable row level security; alter table public.organization_attendance enable row level security; alter table public.organization_audit_logs enable row level security;
revoke all on table public.organization_profiles,public.organization_terms,public.organization_office_rules,public.organization_officers,public.organization_notice_sources,public.organization_notices,public.organization_finance_reports,public.organization_finance_entries,public.organization_meetings,public.organization_attendance,public.organization_audit_logs from anon,authenticated;

create or replace function public.organization_can_manage(p_tenant_id uuid) returns boolean language sql stable security definer set search_path=public,auth as $$ select auth.uid() is not null and exists(select 1 from public.tenant_members m where m.tenant_id=p_tenant_id and m.user_id=auth.uid() and m.status='active' and m.role::text in ('tenant_admin','store_owner')); $$;
revoke all on function public.organization_can_manage(uuid) from public,anon; grant execute on function public.organization_can_manage(uuid) to authenticated;

create or replace function public.organization_public_snapshot(p_slug text) returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare v_tenant uuid; v_profile public.organization_profiles%rowtype; v_term public.organization_terms%rowtype; v_result jsonb;
begin
  select t.id into v_tenant from public.tenants t where t.slug=lower(trim(p_slug)) and t.status='active' and coalesce(t.settings->>'organization_engine','')='v1';
  if v_tenant is null then return '{}'::jsonb; end if;
  select * into v_profile from public.organization_profiles where tenant_id=v_tenant;
  if v_profile.tenant_id is null or v_profile.public_status<>'published' then return jsonb_build_object('slug',lower(trim(p_slug)),'name',(select name from public.tenants where id=v_tenant),'publicationState',coalesce(v_profile.public_status,'review')); end if;
  select * into v_term from public.organization_terms where tenant_id=v_tenant and status='current' order by starts_on desc nulls last,created_at desc limit 1;
  select jsonb_build_object(
    'slug',lower(trim(p_slug)),'name',(select name from public.tenants where id=v_tenant),'organizationType',v_profile.organization_type,'tagline',v_profile.tagline,'description',v_profile.description,'publicationState',v_profile.public_status,
    'currentTerm',case when v_term.id is null then null else jsonb_build_object('id',v_term.id,'label',v_term.label,'startsOn',v_term.starts_on,'endsOn',v_term.ends_on) end,
    'officers',coalesce((select jsonb_agg(jsonb_build_object('officeKey',o.office_key,'officeLabel',r.office_label,'personName',o.person_name,'churchName',o.church_name) order by r.sort_order,o.office_key) from public.organization_officers o join public.organization_office_rules r on r.tenant_id=o.tenant_id and r.office_key=o.office_key where o.tenant_id=v_tenant and o.term_id=v_term.id),'[]'::jsonb),
    'noticeSources',coalesce((select jsonb_agg(jsonb_build_object('sourceKey',s.source_key,'sourceLabel',s.source_label,'sourceUrl',s.source_url) order by s.sort_order,s.source_label) from public.organization_notice_sources s where s.tenant_id=v_tenant and s.active),'[]'::jsonb),
    'notices',coalesce((select jsonb_agg(jsonb_build_object('sourceKey',n.source_key,'sourceLabel',coalesce(s.source_label,n.source_key),'title',n.title,'url',n.url,'publishedAt',n.published_at) order by n.published_at desc nulls last,n.created_at desc) from (select * from public.organization_notices where tenant_id=v_tenant and publication_state='published' order by published_at desc nulls last,created_at desc limit 12) n left join public.organization_notice_sources s on s.tenant_id=n.tenant_id and s.source_key=n.source_key),'[]'::jsonb),
    'financeReports',case when v_profile.show_finance then coalesce((select jsonb_agg(jsonb_build_object('periodLabel',f.period_label,'openingBalance',f.opening_balance,'incomeTotal',f.income_total,'expenseTotal',f.expense_total,'closingBalance',f.closing_balance,'note',f.note) order by f.updated_at desc) from (select * from public.organization_finance_reports where tenant_id=v_tenant and publication_state='published' order by updated_at desc limit 6) f),'[]'::jsonb) else '[]'::jsonb end,
    'attendance',case when v_profile.show_attendance then coalesce((select jsonb_agg(jsonb_build_object('meetingId',m.id,'heldAt',m.held_at,'title',m.title,'venue',m.venue,'attendedCount',coalesce(a.attended_count,0),'totalCount',coalesce(a.total_count,0),'attendanceRate',case when coalesce(a.total_count,0)=0 then null else round((a.attended_count::numeric/a.total_count::numeric)*100,1) end) order by m.held_at desc) from (select * from public.organization_meetings where tenant_id=v_tenant and attendance_public=true and status in ('open','closed') order by held_at desc limit 6) m left join lateral (select count(*)::int total_count,count(*) filter(where attendance_state in ('present','late'))::int attended_count from public.organization_attendance x where x.meeting_id=m.id) a on true),'[]'::jsonb) else '[]'::jsonb end
  ) into v_result; return v_result;
end $$;
revoke all on function public.organization_public_snapshot(text) from public; grant execute on function public.organization_public_snapshot(text) to anon,authenticated;

create or replace function public.organization_preview_succession(p_slug text) returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare v_tenant uuid; v_term uuid; v_result jsonb;
begin
  select id into v_tenant from public.tenants where slug=lower(trim(p_slug)) and status='active'; if v_tenant is null or not public.organization_can_manage(v_tenant) then raise exception 'organization_manage_required' using errcode='42501'; end if;
  select id into v_term from public.organization_terms where tenant_id=v_tenant and status='current' order by starts_on desc nulls last,created_at desc limit 1;
  select coalesce(jsonb_agg(jsonb_build_object('officeKey',r.office_key,'officeLabel',r.office_label,'personName',coalesce(o.person_name,''),'churchName',coalesce(o.church_name,''),'reason',case when r.auto_success and r.succession_from_office_key is not null then '직전 '||coalesce(fr.office_label,r.succession_from_office_key)||' 자동승계' else '관리자 지정 필요' end) order by r.sort_order,r.office_key),'[]'::jsonb) into v_result from public.organization_office_rules r left join public.organization_office_rules fr on fr.tenant_id=r.tenant_id and fr.office_key=r.succession_from_office_key left join public.organization_officers o on o.tenant_id=r.tenant_id and o.term_id=v_term and o.office_key=r.succession_from_office_key where r.tenant_id=v_tenant and r.active; return v_result;
end $$;
revoke all on function public.organization_preview_succession(text) from public,anon; grant execute on function public.organization_preview_succession(text) to authenticated;

create or replace function public.organization_admin_snapshot(p_slug text) returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare v_tenant uuid; v_term public.organization_terms%rowtype; v_result jsonb;
begin
  select id into v_tenant from public.tenants where slug=lower(trim(p_slug)) and status='active'; if v_tenant is null or not public.organization_can_manage(v_tenant) then raise exception 'organization_manage_required' using errcode='42501'; end if;
  select * into v_term from public.organization_terms where tenant_id=v_tenant and status='current' order by starts_on desc nulls last,created_at desc limit 1;
  select jsonb_build_object('slug',lower(trim(p_slug)),'tenantId',v_tenant,'name',(select name from public.tenants where id=v_tenant),'currentTerm',case when v_term.id is null then null else jsonb_build_object('id',v_term.id,'label',v_term.label,'startsOn',v_term.starts_on,'endsOn',v_term.ends_on) end,
  'terms',coalesce((select jsonb_agg(jsonb_build_object('id',id,'label',label,'startsOn',starts_on,'endsOn',ends_on,'status',status) order by starts_on desc nulls last,created_at desc) from public.organization_terms where tenant_id=v_tenant),'[]'::jsonb),
  'officeRules',coalesce((select jsonb_agg(jsonb_build_object('officeKey',office_key,'officeLabel',office_label,'sortOrder',sort_order,'successionFromOfficeKey',succession_from_office_key,'autoSuccess',auto_success) order by sort_order,office_key) from public.organization_office_rules where tenant_id=v_tenant and active),'[]'::jsonb),
  'officers',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'termId',o.term_id,'officeKey',o.office_key,'officeLabel',coalesce(r.office_label,o.office_key),'personName',o.person_name,'churchName',o.church_name,'source',o.source,'locked',o.locked) order by t.starts_on desc nulls last,r.sort_order,o.office_key) from public.organization_officers o join public.organization_terms t on t.id=o.term_id left join public.organization_office_rules r on r.tenant_id=o.tenant_id and r.office_key=o.office_key where o.tenant_id=v_tenant),'[]'::jsonb),
  'noticeSources',coalesce((select jsonb_agg(jsonb_build_object('sourceKey',source_key,'sourceLabel',source_label,'sourceUrl',source_url,'active',active) order by sort_order,source_label) from public.organization_notice_sources where tenant_id=v_tenant),'[]'::jsonb),
  'notices',coalesce((select jsonb_agg(jsonb_build_object('id',n.id,'sourceKey',n.source_key,'sourceLabel',coalesce(s.source_label,n.source_key),'title',n.title,'url',n.url,'publishedAt',n.published_at,'publicationState',n.publication_state,'syncedAt',n.synced_at) order by n.published_at desc nulls last,n.created_at desc) from public.organization_notices n left join public.organization_notice_sources s on s.tenant_id=n.tenant_id and s.source_key=n.source_key where n.tenant_id=v_tenant),'[]'::jsonb),
  'financeReports',coalesce((select jsonb_agg(jsonb_build_object('id',id,'termId',term_id,'periodLabel',period_label,'openingBalance',opening_balance,'incomeTotal',income_total,'expenseTotal',expense_total,'closingBalance',closing_balance,'note',note,'publicationState',publication_state) order by updated_at desc) from public.organization_finance_reports where tenant_id=v_tenant),'[]'::jsonb),
  'financeEntries',coalesce((select jsonb_agg(jsonb_build_object('id',id,'reportId',report_id,'occurredOn',occurred_on,'entryType',entry_type,'category',category,'description',description,'amount',amount,'evidenceRef',evidence_ref) order by occurred_on desc,created_at desc) from (select * from public.organization_finance_entries where tenant_id=v_tenant order by occurred_on desc,created_at desc limit 200) q),'[]'::jsonb),
  'meetings',coalesce((select jsonb_agg(jsonb_build_object('id',id,'termId',term_id,'heldAt',held_at,'title',title,'venue',venue,'attendancePublic',attendance_public,'status',status) order by held_at desc) from public.organization_meetings where tenant_id=v_tenant),'[]'::jsonb),
  'attendance',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'meetingId',a.meeting_id,'meetingTitle',m.title,'attendeeKey',a.attendee_key,'attendeeName',a.attendee_name,'churchName',a.church_name,'attendanceState',a.attendance_state,'checkedAt',a.checked_at) order by m.held_at desc,a.attendee_name) from public.organization_attendance a join public.organization_meetings m on m.id=a.meeting_id where a.tenant_id=v_tenant limit 500),'[]'::jsonb),
  'audit',coalesce((select jsonb_agg(jsonb_build_object('id',id,'action',action,'entityType',entity_type,'entityId',entity_id,'detail',detail,'createdAt',created_at) order by created_at desc) from (select * from public.organization_audit_logs where tenant_id=v_tenant order by created_at desc limit 50) q),'[]'::jsonb)) into v_result; return v_result;
end $$;
revoke all on function public.organization_admin_snapshot(text) from public,anon; grant execute on function public.organization_admin_snapshot(text) to authenticated;

create or replace function public.organization_admin_command(p_slug text,p_action text,p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql volatile security definer set search_path=public,auth as $$
declare v_tenant uuid; v_term uuid; v_report uuid; v_meeting uuid; v_id uuid; v_action text:=lower(trim(coalesce(p_action,''))); v_label text; v_source text; v_external text;
begin
  select id into v_tenant from public.tenants where slug=lower(trim(p_slug)) and status='active'; if v_tenant is null or not public.organization_can_manage(v_tenant) then raise exception 'organization_manage_required' using errcode='42501'; end if;
  if v_action='set_officer' then
    v_term=nullif(p_payload->>'termId','')::uuid; if not exists(select 1 from public.organization_terms where id=v_term and tenant_id=v_tenant) then raise exception 'invalid_term' using errcode='22023'; end if;
    insert into public.organization_officers(tenant_id,term_id,office_key,person_name,church_name,source,locked,updated_at) values(v_tenant,v_term,trim(p_payload->>'officeKey'),trim(coalesce(p_payload->>'personName','')),trim(coalesce(p_payload->>'churchName','')),'override',true,now()) on conflict(term_id,office_key) do update set person_name=excluded.person_name,church_name=excluded.church_name,source='override',locked=true,updated_at=now() returning id into v_id;
  elsif v_action='upsert_notice' then
    v_source=trim(coalesce(p_payload->>'sourceKey','hammu')); v_external=coalesce(nullif(trim(p_payload->>'externalKey'),''),md5(v_source||'|'||coalesce(p_payload->>'title','')||'|'||coalesce(p_payload->>'url','')||'|'||coalesce(p_payload->>'publishedAt','')));
    insert into public.organization_notices(tenant_id,source_key,external_key,title,url,published_at,summary,publication_state,synced_at,updated_at) values(v_tenant,v_source,v_external,trim(p_payload->>'title'),trim(coalesce(p_payload->>'url','')),nullif(p_payload->>'publishedAt','')::timestamptz,trim(coalesce(p_payload->>'summary','')),coalesce(nullif(p_payload->>'publicationState',''),'review'),now(),now()) on conflict(tenant_id,source_key,external_key) do update set title=excluded.title,url=excluded.url,published_at=excluded.published_at,summary=excluded.summary,publication_state=excluded.publication_state,synced_at=now(),updated_at=now() returning id into v_id;
  elsif v_action='upsert_finance_report' then
    insert into public.organization_finance_reports(tenant_id,term_id,period_label,period_start,period_end,opening_balance,income_total,expense_total,closing_balance,note,publication_state,updated_at) values(v_tenant,nullif(p_payload->>'termId','')::uuid,trim(p_payload->>'periodLabel'),nullif(p_payload->>'periodStart','')::date,nullif(p_payload->>'periodEnd','')::date,coalesce(nullif(p_payload->>'openingBalance','')::bigint,0),coalesce(nullif(p_payload->>'incomeTotal','')::bigint,0),coalesce(nullif(p_payload->>'expenseTotal','')::bigint,0),coalesce(nullif(p_payload->>'closingBalance','')::bigint,0),trim(coalesce(p_payload->>'note','')),coalesce(nullif(p_payload->>'publicationState',''),'review'),now()) on conflict(tenant_id,period_label) do update set term_id=excluded.term_id,period_start=excluded.period_start,period_end=excluded.period_end,opening_balance=excluded.opening_balance,income_total=excluded.income_total,expense_total=excluded.expense_total,closing_balance=excluded.closing_balance,note=excluded.note,publication_state=excluded.publication_state,updated_at=now() returning id into v_id;
  elsif v_action='add_finance_entry' then
    v_report=nullif(p_payload->>'reportId','')::uuid; if not exists(select 1 from public.organization_finance_reports where id=v_report and tenant_id=v_tenant) then raise exception 'invalid_finance_report' using errcode='22023'; end if;
    insert into public.organization_finance_entries(tenant_id,report_id,occurred_on,entry_type,category,description,amount,evidence_ref,is_private) values(v_tenant,v_report,(p_payload->>'occurredOn')::date,trim(p_payload->>'entryType'),trim(coalesce(p_payload->>'category','')),trim(p_payload->>'description'),coalesce(nullif(p_payload->>'amount','')::bigint,0),trim(coalesce(p_payload->>'evidenceRef','')),true) returning id into v_id;
  elsif v_action='create_meeting' then
    select id into v_term from public.organization_terms where tenant_id=v_tenant and status='current' order by starts_on desc nulls last limit 1; insert into public.organization_meetings(tenant_id,term_id,held_at,title,venue,attendance_public,status) values(v_tenant,v_term,(p_payload->>'heldAt')::timestamptz,trim(p_payload->>'title'),trim(coalesce(p_payload->>'venue','')),coalesce((p_payload->>'attendancePublic')::boolean,false),'open') returning id into v_id;
  elsif v_action='mark_attendance' then
    v_meeting=nullif(p_payload->>'meetingId','')::uuid; if not exists(select 1 from public.organization_meetings where id=v_meeting and tenant_id=v_tenant) then raise exception 'invalid_meeting' using errcode='22023'; end if; insert into public.organization_attendance(tenant_id,meeting_id,attendee_key,attendee_name,church_name,attendance_state,checked_at) values(v_tenant,v_meeting,trim(p_payload->>'attendeeKey'),trim(p_payload->>'attendeeName'),trim(coalesce(p_payload->>'churchName','')),trim(p_payload->>'attendanceState'),now()) on conflict(meeting_id,attendee_key) do update set attendee_name=excluded.attendee_name,church_name=excluded.church_name,attendance_state=excluded.attendance_state,checked_at=now() returning id into v_id;
  elsif v_action='apply_succession' then
    v_label=trim(p_payload->>'label'); if v_label='' then raise exception 'term_label_required' using errcode='22023'; end if; insert into public.organization_terms(tenant_id,label,starts_on,ends_on,status) values(v_tenant,v_label,nullif(p_payload->>'startsOn','')::date,nullif(p_payload->>'endsOn','')::date,'planned') on conflict(tenant_id,label) do update set starts_on=excluded.starts_on,ends_on=excluded.ends_on returning id into v_term;
    insert into public.organization_officers(tenant_id,term_id,office_key,church_name,person_name,source,locked,updated_at) select v_tenant,v_term,r.office_key,coalesce(o.church_name,''),coalesce(o.person_name,''),'auto',false,now() from public.organization_office_rules r left join public.organization_terms ct on ct.tenant_id=v_tenant and ct.status='current' left join public.organization_officers o on o.tenant_id=v_tenant and o.term_id=ct.id and o.office_key=r.succession_from_office_key where r.tenant_id=v_tenant and r.active and r.auto_success and r.succession_from_office_key is not null on conflict(term_id,office_key) do update set church_name=case when public.organization_officers.locked then public.organization_officers.church_name else excluded.church_name end,person_name=case when public.organization_officers.locked then public.organization_officers.person_name else excluded.person_name end,source=case when public.organization_officers.locked then public.organization_officers.source else 'auto' end,updated_at=now(); v_id=v_term;
  else raise exception 'unsupported_organization_action' using errcode='22023'; end if;
  insert into public.organization_audit_logs(tenant_id,actor_user_id,action,entity_type,entity_id,detail) values(v_tenant,auth.uid(),v_action,v_action,coalesce(v_id::text,''),coalesce(p_payload,'{}'::jsonb)); return public.organization_admin_snapshot(p_slug);
end $$;
revoke all on function public.organization_admin_command(text,text,jsonb) from public,anon; grant execute on function public.organization_admin_command(text,text,jsonb) to authenticated;

-- Bootstrap Hammu profile and current term. No person/church is fabricated; officers remain empty until verified.
with h as (select id from public.tenants where slug='hammu') insert into public.organization_profiles(tenant_id,organization_type,tagline,description,public_status,show_finance,show_attendance,updated_at) select id,'inspection_body','함께 섬기고, 함께 세우는 교회 공동체','목포노회 안에서 교회와 목회자가 서로 연결되고 섬김을 이어가는 운영공간입니다.','published',true,true,now() from h on conflict(tenant_id) do update set organization_type=excluded.organization_type,tagline=excluded.tagline,description=excluded.description,public_status='published',updated_at=now();
with h as (select id from public.tenants where slug='hammu') insert into public.organization_terms(tenant_id,label,starts_on,ends_on,status) select id,'2026 회기','2026-01-01','2026-12-31','current' from h on conflict(tenant_id,label) do update set status='current',starts_on=excluded.starts_on,ends_on=excluded.ends_on;
with h as (select id from public.tenants where slug='hammu'),rules(office_key,office_label,sort_order,from_key,auto_success) as (values ('chair','회장',10,'vice_chair',true),('vice_chair','부회장',20,'secretary',true),('secretary','서기',30,'assistant_secretary',true),('assistant_secretary','부서기',40,null,false),('treasurer','회계',50,'assistant_treasurer',true),('assistant_treasurer','부회계',60,null,false)) insert into public.organization_office_rules(tenant_id,office_key,office_label,sort_order,succession_from_office_key,auto_success,active) select h.id,r.office_key,r.office_label,r.sort_order,r.from_key,r.auto_success,true from h cross join rules r on conflict(tenant_id,office_key) do update set office_label=excluded.office_label,sort_order=excluded.sort_order,succession_from_office_key=excluded.succession_from_office_key,auto_success=excluded.auto_success,active=true;
with h as (select id from public.tenants where slug='hammu'),sources(source_key,source_label,source_url,sort_order) as (values ('hammu','함무시찰회','https://ekodi.kr/hammu',10),('mokpo_presbytery','목포노회','http://cafe.daum.net/pckmp',20),('pck_general','대한예수교장로회 총회','https://www.pck.or.kr/combination_pck.php',30)) insert into public.organization_notice_sources(tenant_id,source_key,source_label,source_url,active,sort_order) select h.id,s.source_key,s.source_label,s.source_url,true,s.sort_order from h cross join sources s on conflict(tenant_id,source_key) do update set source_label=excluded.source_label,source_url=excluded.source_url,active=true,sort_order=excluded.sort_order;
with h as (select id from public.tenants where slug='hammu'),notices(external_key,title,published_at) as (values ('pck-20260910-nepal-flood-envelope','네팔대홍수긴급구호헌금 봉투 양식(파일첨부)','2026-09-10'::timestamptz),('pck-20260910-world-mission-admin','[행정] 세계선교부 110-16차 행정 안내','2026-09-10'::timestamptz),('pck-20260907-education-week','제58차 기독교교육주간 및 2027 교육 안내','2026-09-07'::timestamptz)) insert into public.organization_notices(tenant_id,source_key,external_key,title,url,published_at,summary,publication_state,synced_at,updated_at) select h.id,'pck_general',n.external_key,n.title,'https://www.pck.or.kr/combination_pck.php',n.published_at,'','published',now(),now() from h cross join notices n on conflict(tenant_id,source_key,external_key) do update set title=excluded.title,url=excluded.url,published_at=excluded.published_at,publication_state='published',synced_at=now(),updated_at=now();

comment on table public.organization_finance_entries is 'Tenant-private accounting ledger. Never projected by organization_public_snapshot.';
comment on table public.organization_attendance is 'Tenant-private individual attendance. Public projection returns aggregate counts only.';
comment on function public.organization_public_snapshot(text) is 'Safe public projection: no finance entries, evidence references, attendee names, attendee keys, or individual attendance rows.';
