-- EKODI Admin Strategy Room
-- Server-managed strategy conversations and AI REPORT ledger.
-- Browser clients do not receive direct table mutation privileges.

create table if not exists public.admin_strategy_threads (
  id uuid primary key default gen_random_uuid(),
  admin_email text not null,
  title text not null default '새 전략회의',
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_strategy_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.admin_strategy_threads(id) on delete cascade,
  admin_email text not null,
  role text not null check (role in ('user','assistant','system')),
  classification text not null default 'INFO' check (classification in ('INFO','REPORT','WARNING','INCIDENT','DECISION')),
  content text not null,
  council jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_reports (
  id uuid primary key default gen_random_uuid(),
  admin_email text not null,
  report_type text not null default 'REPORT' check (report_type in ('REPORT','WARNING','INCIDENT','DECISION','STRATEGY')),
  status text not null default 'open' check (status in ('open','resolved','acknowledged','archived')),
  title text not null,
  summary text not null default '',
  details text not null default '',
  decision_required boolean not null default false,
  related_services jsonb not null default '[]'::jsonb,
  source text not null default 'strategy-room',
  thread_id uuid references public.admin_strategy_threads(id) on delete set null,
  message_id bigint references public.admin_strategy_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists idx_admin_strategy_threads_email_updated
  on public.admin_strategy_threads(admin_email, updated_at desc);
create index if not exists idx_admin_strategy_messages_thread_time
  on public.admin_strategy_messages(thread_id, created_at);
create index if not exists idx_ai_reports_email_time
  on public.ai_reports(admin_email, created_at desc);
create index if not exists idx_ai_reports_decision_open
  on public.ai_reports(admin_email, created_at desc)
  where decision_required = true and status = 'open';

alter table public.admin_strategy_threads enable row level security;
alter table public.admin_strategy_messages enable row level security;
alter table public.ai_reports enable row level security;

-- Strategy records are accessed only through the authenticated admin Edge Function.
-- service_role bypasses RLS; browser roles receive no direct CRUD privileges.
revoke all on public.admin_strategy_threads from anon, authenticated;
revoke all on public.admin_strategy_messages from anon, authenticated;
revoke all on public.ai_reports from anon, authenticated;

comment on table public.admin_strategy_threads is 'Persistent EKODI Chief AI strategy meetings, scoped to the verified admin email.';
comment on table public.admin_strategy_messages is 'Server-written strategy conversation history with Council metadata and decision classification.';
comment on table public.ai_reports is 'Durable EKODI AI REPORT ledger generated from verified operations and strategy meetings.';