-- EKODI Docs AI: private person-scoped documents, versions and AI usage audit.
create table if not exists public.document_files (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  workspace_key text not null,
  title text not null default '제목 없는 문서',
  content_html text not null default '<p><br></p>',
  source_format text not null default 'ekodi',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_files_title_length check (char_length(title) <= 160),
  constraint document_files_content_size check (octet_length(content_html) <= 2097152),
  constraint document_files_format_length check (char_length(source_format) <= 40)
);

create index if not exists document_files_owner_updated_idx
  on public.document_files(owner_user_id, updated_at desc);

alter table public.document_files enable row level security;

drop policy if exists document_files_select_own on public.document_files;
create policy document_files_select_own on public.document_files
  for select to authenticated using (auth.uid() = owner_user_id);

drop policy if exists document_files_insert_own on public.document_files;
create policy document_files_insert_own on public.document_files
  for insert to authenticated with check (
    auth.uid() = owner_user_id
    and workspace_key = ('personal:' || auth.uid()::text)
  );

drop policy if exists document_files_update_own on public.document_files;
create policy document_files_update_own on public.document_files
  for update to authenticated
  using (auth.uid() = owner_user_id)
  with check (
    auth.uid() = owner_user_id
    and workspace_key = ('personal:' || auth.uid()::text)
  );

drop policy if exists document_files_delete_own on public.document_files;
create policy document_files_delete_own on public.document_files
  for delete to authenticated using (auth.uid() = owner_user_id);

grant select, insert, update, delete on public.document_files to authenticated;

create table if not exists public.document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.document_files(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content_html text not null,
  source_format text not null default 'ekodi',
  created_at timestamptz not null default now(),
  constraint document_versions_content_size check (octet_length(content_html) <= 2097152)
);

create index if not exists document_versions_doc_created_idx
  on public.document_versions(document_id, created_at desc);

alter table public.document_versions enable row level security;

drop policy if exists document_versions_select_own on public.document_versions;
create policy document_versions_select_own on public.document_versions
  for select to authenticated using (auth.uid() = owner_user_id);

drop policy if exists document_versions_insert_own on public.document_versions;
create policy document_versions_insert_own on public.document_versions
  for insert to authenticated with check (
    auth.uid() = owner_user_id
    and exists (
      select 1 from public.document_files d
      where d.id = document_id and d.owner_user_id = auth.uid()
    )
  );

drop policy if exists document_versions_delete_own on public.document_versions;
create policy document_versions_delete_own on public.document_versions
  for delete to authenticated using (auth.uid() = owner_user_id);

grant select, insert, delete on public.document_versions to authenticated;

create table if not exists public.document_ai_usage (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  operation text not null,
  provider text not null default '',
  model text not null default '',
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  status text not null default 'completed',
  error_code text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists document_ai_usage_owner_created_idx
  on public.document_ai_usage(owner_user_id, created_at desc);

alter table public.document_ai_usage enable row level security;

drop policy if exists document_ai_usage_select_own on public.document_ai_usage;
create policy document_ai_usage_select_own on public.document_ai_usage
  for select to authenticated using (auth.uid() = owner_user_id);

grant select on public.document_ai_usage to authenticated;
revoke insert, update, delete on public.document_ai_usage from anon, authenticated;

comment on table public.document_files is 'Private person-scoped EKODI Docs documents. Workspace identity remains immutable and separate from file format.';
comment on table public.document_versions is 'User-created document snapshots for recovery and version history.';
comment on table public.document_ai_usage is 'Server-written, user-readable Docs AI usage audit used for free-first rate governance.';
