-- EKODI Approval Core: person-scoped decisions with workspace context.
-- Decision records and execution records are deliberately separated.

create table if not exists public.approval_requests (
  id uuid primary key default gen_random_uuid(),
  workspace_key text,
  scope text not null default 'workspace',
  request_type text not null,
  title text not null,
  description text,
  requester_person_id uuid not null references public.people(id) on delete restrict,
  assignee_person_id uuid references public.people(id) on delete restrict,
  status text not null default 'pending',
  priority text not null default 'normal',
  risk_level text not null default 'low',
  source_service text not null default 'ekodi',
  source_ref text,
  ai_summary text,
  due_at timestamptz,
  submitted_at timestamptz not null default now(),
  decided_at timestamptz,
  decision_comment text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approval_scope_check check (scope in ('personal','workspace','platform')),
  constraint approval_status_check check (status in ('pending','approved','rejected','cancelled')),
  constraint approval_priority_check check (priority in ('low','normal','high','urgent')),
  constraint approval_risk_check check (risk_level in ('low','medium','high','critical'))
);
create index if not exists approval_requests_requester_idx
  on public.approval_requests(requester_person_id, created_at desc);
create index if not exists approval_requests_assignee_idx
  on public.approval_requests(assignee_person_id, status, due_at);
create index if not exists approval_requests_workspace_idx
  on public.approval_requests(workspace_key, status, created_at desc);
create unique index if not exists approval_requests_source_uidx
  on public.approval_requests(source_service, source_ref)
  where source_ref is not null;

create table if not exists public.approval_events (
  id bigint generated by default as identity primary key,
  approval_id uuid not null references public.approval_requests(id) on delete cascade,
  event_type text not null,
  actor_person_id uuid references public.people(id) on delete set null,
  from_status text,
  to_status text,
  comment text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists approval_events_request_idx
  on public.approval_events(approval_id, created_at asc);

create table if not exists public.approval_executions (
  id uuid primary key default gen_random_uuid(),
  approval_id uuid not null references public.approval_requests(id) on delete cascade,
  action_type text not null,
  status text not null default 'pending',
  requested_by_person_id uuid references public.people(id) on delete set null,
  started_at timestamptz,
  completed_at timestamptz,
  result jsonb not null default '{}'::jsonb,
  error_text text,
  created_at timestamptz not null default now(),
  constraint approval_execution_status_check
    check (status in ('pending','running','succeeded','failed','cancelled'))
);

create index if not exists approval_executions_request_idx
  on public.approval_executions(approval_id, created_at asc);

alter table public.approval_requests enable row level security;
alter table public.approval_events enable row level security;
alter table public.approval_executions enable row level security;

revoke all on table public.approval_requests from anon, authenticated;
revoke all on table public.approval_events from anon, authenticated;
revoke all on table public.approval_executions from anon, authenticated;
grant select on table public.approval_requests to authenticated;
grant select on table public.approval_events to authenticated;
grant select on table public.approval_executions to authenticated;

drop policy if exists "approval_participant_select" on public.approval_requests;
create policy "approval_participant_select"
on public.approval_requests
for select to authenticated
using (
  requester_person_id = (select private.current_person_id())
  or assignee_person_id = (select private.current_person_id())
);
drop policy if exists "approval_event_participant_select" on public.approval_events;
create policy "approval_event_participant_select"
on public.approval_events
for select to authenticated
using (
  exists (
    select 1 from public.approval_requests request
    where request.id = approval_events.approval_id
      and (
        request.requester_person_id = (select private.current_person_id())
        or request.assignee_person_id = (select private.current_person_id())
      )
  )
);

drop policy if exists "approval_execution_participant_select" on public.approval_executions;
create policy "approval_execution_participant_select"
on public.approval_executions
for select to authenticated
using (
  exists (
    select 1 from public.approval_requests request
    where request.id = approval_executions.approval_id
      and (
        request.requester_person_id = (select private.current_person_id())
        or request.assignee_person_id = (select private.current_person_id())
      )
  )
);

create or replace function public.my_approval_person_id()
returns uuid
language sql
stable
security invoker
set search_path = public, private, auth
as $$
  select private.current_person_id()
$$;

revoke all on function public.my_approval_person_id() from public, anon;
grant execute on function public.my_approval_person_id() to authenticated;

create or replace function public.decide_approval(
  p_approval_id uuid,
  p_decision text,
  p_comment text default null
)
returns public.approval_requests
language plpgsql
security definer
set search_path = public, private, auth
as $$
declare
  v_person_id uuid;
  v_request public.approval_requests;
  v_decision text := lower(trim(coalesce(p_decision, '')));
begin
  v_person_id := private.current_person_id();
  if v_person_id is null then
    raise exception 'approval_identity_required';
  end if;
  
  if v_decision not in ('approved','rejected') then
    raise exception 'approval_decision_invalid';
  end if;
  if length(coalesce(p_comment, '')) > 1000 then
    raise exception 'approval_comment_too_long';
  end if;

  select * into v_request
    from public.approval_requests
   where id = p_approval_id
   for update;
  if v_request.id is null then
    raise exception 'approval_not_found';
  end if;
  if v_request.assignee_person_id is distinct from v_person_id then
    raise exception 'approval_not_assignee';
  end if;
  if v_request.status <> 'pending' then
    raise exception 'approval_already_decided';
  end if;

  update public.approval_requests
     set status = v_decision,
         decided_at = now(),
         decision_comment = nullif(trim(coalesce(p_comment, '')), ''),
         updated_at = now()
   where id = p_approval_id
   returning * into v_request;

  insert into public.approval_events
    (approval_id, event_type, actor_person_id, from_status, to_status, comment)
  values
    (p_approval_id, 'decision.' || v_decision, v_person_id, 'pending', v_decision,
     nullif(trim(coalesce(p_comment, '')), ''));

  return v_request;
end
$$;

revoke all on function public.decide_approval(uuid, text, text) from public, anon;
grant execute on function public.decide_approval(uuid, text, text) to authenticated;

create or replace function public.cancel_approval(p_approval_id uuid, p_comment text default null)
returns public.approval_requests
language plpgsql
security definer
set search_path = public, private, auth
as $$
declare
  v_person_id uuid;
  v_request public.approval_requests;
begin
  v_person_id := private.current_person_id();
  if v_person_id is null then raise exception 'approval_identity_required'; end if;
  if length(coalesce(p_comment, '')) > 1000 then raise exception 'approval_comment_too_long'; end if;

  select * into v_request
    from public.approval_requests
   where id = p_approval_id
   for update;

  if v_request.id is null then raise exception 'approval_not_found'; end if;
  if v_request.requester_person_id is distinct from v_person_id then
    raise exception 'approval_not_requester';
  end if;
  if v_request.status <> 'pending' then raise exception 'approval_already_decided'; end if;

  update public.approval_requests
     set status = 'cancelled',
         decided_at = now(),
         decision_comment = nullif(trim(coalesce(p_comment, '')), ''),
         updated_at = now()
   where id = p_approval_id
   returning * into v_request;

  insert into public.approval_events
    (approval_id, event_type, actor_person_id, from_status, to_status, comment)
  values
    (p_approval_id, 'request.cancelled', v_person_id, 'pending', 'cancelled',
     nullif(trim(coalesce(p_comment, '')), ''));

  return v_request;
end
$$;
revoke all on function public.cancel_approval(uuid, text) from public, anon;
grant execute on function public.cancel_approval(uuid, text) to authenticated;

create or replace function public.log_approval_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.approval_events
    (approval_id, event_type, actor_person_id, to_status, metadata)
  values
    (new.id, 'request.submitted', new.requester_person_id, new.status,
     jsonb_build_object('source_service', new.source_service, 'scope', new.scope));
  return new;
end
$$;

revoke all on function public.log_approval_submission() from public, anon, authenticated;

drop trigger if exists approval_submission_event on public.approval_requests;
create trigger approval_submission_event
after insert on public.approval_requests
for each row execute function public.log_approval_submission();

comment on table public.approval_requests is
  'EKODI shared approval inbox. UI may aggregate across workspaces while RLS remains person scoped.';
comment on table public.approval_events is
  'Immutable decision timeline for approvals. Decision history is separate from execution history.';
comment on table public.approval_executions is
  'Execution attempts created after an approval decision; approval itself never implies successful execution.';