-- EKODI AI Context Hub: additive shared context/event layer for specialist AI collaboration.
-- No customer, payment, auth, or existing application table is altered.

create extension if not exists pgcrypto;

create table if not exists public.ai_shared_context (
  id uuid primary key default gen_random_uuid(),
  context_type text not null check (context_type in ('fact','observation','constraint','decision','report','opportunity','task')),
  visibility text not null default 'ecosystem' check (visibility in ('ecosystem','restricted','agent')),
  sensitivity text not null default 'internal' check (sensitivity in ('public','internal','confidential','restricted')),
  source_agent text not null,
  owner_agent text,
  subject_type text not null default 'ecosystem',
  subject_key text not null default 'ekodi',
  title text not null,
  summary text not null,
  payload jsonb not null default '{}'::jsonb,
  related_services text[] not null default '{}'::text[],
  related_agents text[] not null default '{}'::text[],
  confidence numeric(4,3) not null default 1.000 check (confidence >= 0 and confidence <= 1),
  status text not null default 'active' check (status in ('active','superseded','resolved','expired')),
  valid_from timestamptz not null default now(),
  expires_at timestamptz,
  supersedes_id uuid references public.ai_shared_context(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_shared_context_active_idx
  on public.ai_shared_context (status, context_type, updated_at desc);
create index if not exists ai_shared_context_subject_idx
  on public.ai_shared_context (subject_type, subject_key, updated_at desc);
create index if not exists ai_shared_context_source_idx
  on public.ai_shared_context (source_agent, updated_at desc);
create index if not exists ai_shared_context_related_services_gin
  on public.ai_shared_context using gin (related_services);
create index if not exists ai_shared_context_related_agents_gin
  on public.ai_shared_context using gin (related_agents);

create table if not exists public.ai_collaboration_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('observed','proposed','delegated','started','completed','failed','blocked','escalated','decided','reported','context_updated')),
  source_agent text not null,
  target_agents text[] not null default '{}'::text[],
  context_id uuid references public.ai_shared_context(id) on delete set null,
  correlation_id uuid not null default gen_random_uuid(),
  sensitivity text not null default 'internal' check (sensitivity in ('public','internal','confidential','restricted')),
  summary text not null,
  payload jsonb not null default '{}'::jsonb,
  related_services text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create index if not exists ai_collaboration_events_created_idx
  on public.ai_collaboration_events (id desc, created_at desc);
create index if not exists ai_collaboration_events_source_idx
  on public.ai_collaboration_events (source_agent, id desc);
create index if not exists ai_collaboration_events_targets_gin
  on public.ai_collaboration_events using gin (target_agents);
create index if not exists ai_collaboration_events_services_gin
  on public.ai_collaboration_events using gin (related_services);

create table if not exists public.ai_agent_cursors (
  agent_key text primary key,
  last_event_id bigint not null default 0,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_ai_shared_context_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_ai_shared_context_updated_at on public.ai_shared_context;
create trigger trg_ai_shared_context_updated_at
before update on public.ai_shared_context
for each row execute function public.touch_ai_shared_context_updated_at();

-- Keep browser/database clients closed. Server-side orchestration uses the service role
-- after its own admin or internal-agent authentication.
alter table public.ai_shared_context enable row level security;
alter table public.ai_collaboration_events enable row level security;
alter table public.ai_agent_cursors enable row level security;

revoke all on public.ai_shared_context from anon, authenticated;
revoke all on public.ai_collaboration_events from anon, authenticated;
revoke all on public.ai_agent_cursors from anon, authenticated;
revoke all on function public.touch_ai_shared_context_updated_at() from public, anon, authenticated;

grant all on public.ai_shared_context to service_role;
grant all on public.ai_collaboration_events to service_role;
grant all on public.ai_agent_cursors to service_role;
grant execute on function public.touch_ai_shared_context_updated_at() to service_role;

grant usage, select on sequence public.ai_collaboration_events_id_seq to service_role;

comment on table public.ai_shared_context is 'Canonical non-secret context shared across EKODI specialist AIs with explicit sensitivity and visibility.';
comment on table public.ai_collaboration_events is 'Append-oriented collaboration event stream used by Chief AI and specialist AIs.';
comment on table public.ai_agent_cursors is 'Per-agent event consumption checkpoint; avoids duplicate collaboration work.';
