-- My EKODI progressive personalization.
-- Person-scoped, private-first, additive, and intentionally separate from authorization truth.

create table if not exists public.my_personalization_preferences (
  person_id uuid not null references public.people(id) on delete cascade,
  service_id text not null,
  state text not null default 'available',
  interest_score numeric(5,2) not null default 0,
  last_engaged_at timestamptz,
  dismissed_until timestamptz,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (person_id, service_id),
  constraint my_personalization_service_id_format check (service_id ~ '^[a-z][a-z0-9-]{0,79}$'),
  constraint my_personalization_state_check check (state in ('available','active','pinned')),
  constraint my_personalization_interest_check check (interest_score between 0 and 10)
);

create table if not exists public.my_personalization_signals (
  id bigint generated by default as identity primary key,
  person_id uuid not null references public.people(id) on delete cascade,
  service_id text not null,
  source text not null,
  signal_type text not null default 'context',
  weight numeric(5,2) not null default 1,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  constraint my_personalization_signal_service_format check (service_id ~ '^[a-z][a-z0-9-]{0,79}$'),
  constraint my_personalization_signal_source_check check (source in ('system','admin','ai')),
  constraint my_personalization_signal_weight_check check (weight between -5 and 5)
);

create index if not exists my_personalization_preferences_updated_idx
  on public.my_personalization_preferences(person_id, updated_at desc);
create index if not exists my_personalization_signals_person_created_idx
  on public.my_personalization_signals(person_id, created_at desc);
create index if not exists my_personalization_signals_expiry_idx
  on public.my_personalization_signals(person_id, expires_at) where expires_at is not null;

alter table public.my_personalization_preferences enable row level security;
alter table public.my_personalization_signals enable row level security;

drop policy if exists my_personalization_preferences_select_own on public.my_personalization_preferences;
create policy my_personalization_preferences_select_own
  on public.my_personalization_preferences for select to authenticated
  using (person_id = (select private.current_person_id()));

drop policy if exists my_personalization_signals_select_own on public.my_personalization_signals;
create policy my_personalization_signals_select_own
  on public.my_personalization_signals for select to authenticated
  using (person_id = (select private.current_person_id()));

revoke all on table public.my_personalization_preferences from anon, authenticated;
revoke all on table public.my_personalization_signals from anon, authenticated;
grant select on table public.my_personalization_preferences to authenticated;
grant select on table public.my_personalization_signals to authenticated;

create or replace function public.set_my_personalization_preference(
  p_service_id text,
  p_action text
)
returns public.my_personalization_preferences
language plpgsql
security definer
set search_path = public, private, auth
as $$
declare
  v_person_id uuid := private.current_person_id();
  v_service_id text := lower(trim(coalesce(p_service_id,'')));
  v_action text := lower(trim(coalesce(p_action,'')));
  v_now timestamptz := now();
  v_row public.my_personalization_preferences;
begin
  if auth.uid() is null or v_person_id is null then
    raise exception 'authentication_required' using errcode='42501';
  end if;
  if v_service_id !~ '^[a-z][a-z0-9-]{0,79}$' then
    raise exception 'invalid_service_id' using errcode='22023';
  end if;
  if v_action not in ('interest','engage','activate','pin','unpin','dismiss','restore') then
    raise exception 'invalid_personalization_action' using errcode='22023';
  end if;

  insert into public.my_personalization_preferences(person_id,service_id)
  values(v_person_id,v_service_id)
  on conflict(person_id,service_id) do nothing;

  update public.my_personalization_preferences
     set state = case
       when v_action='activate' then 'active'
       when v_action='pin' then 'pinned'
       when v_action='unpin' then 'active'
       when v_action in ('dismiss','restore') then 'available'
       else state
     end,
     interest_score = case
       when v_action='interest' then least(10,interest_score+2)
       when v_action='engage' then least(10,interest_score+1)
       when v_action='activate' then greatest(4,interest_score)
       when v_action='pin' then greatest(6,interest_score)
       when v_action='dismiss' then greatest(0,interest_score-4)
       else interest_score
     end,
     last_engaged_at = case when v_action in ('interest','engage','activate','pin','unpin') then v_now else last_engaged_at end,
     activated_at = case when v_action in ('activate','pin') then coalesce(activated_at,v_now) else activated_at end,
     dismissed_until = case
       when v_action='dismiss' then v_now + interval '30 days'
       when v_action in ('interest','engage','activate','pin','unpin','restore') then null
       else dismissed_until
     end,
     updated_at = v_now
   where person_id=v_person_id and service_id=v_service_id
   returning * into v_row;

  return v_row;
end
$$;

revoke all on function public.set_my_personalization_preference(text,text) from public, anon;
grant execute on function public.set_my_personalization_preference(text,text) to authenticated;

comment on table public.my_personalization_preferences is
  'Person-scoped My EKODI presentation preferences. Never grants service authorization.';
comment on table public.my_personalization_signals is
  'Read-only-to-user contextual recommendation signals from EKODI system/admin/AI. Never grants service authorization.';
comment on function public.set_my_personalization_preference(text,text) is
  'Mutates only the signed-in person presentation preference; service access remains governed by canonical membership/RBAC.';
