-- EKODI Author AI foundation
-- Private-by-default author projects with explicit human publication gate.

create table if not exists public.author_projects (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  working_title text not null default '',
  interest text not null default '',
  field text not null default 'Other',
  audience text not null default '',
  book_format text not null default '',
  tone text not null default 'warm',
  narrative_mode text not null default 'story',
  source_mode text not null default 'author-first',
  target_words integer not null default 48000 check (target_words between 1000 and 300000),
  status text not null default 'idea' check (status in ('idea','plan','writing','review','author_approved','publish_ready','published')),
  selected_plan jsonb not null default '{}'::jsonb,
  book_memory jsonb not null default '{}'::jsonb,
  chief_share_level text not null default 'metadata' check (chief_share_level in ('none','metadata','summary','full')),
  books_publication_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.author_chapters (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.author_projects(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  chapter_order integer not null check (chapter_order between 1 and 500),
  title text not null default '',
  purpose text not null default '',
  draft_text text not null default '',
  status text not null default 'planned' check (status in ('planned','drafting','reviewed','approved')),
  version integer not null default 0 check (version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, chapter_order)
);

create table if not exists public.author_events (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.author_projects(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  actor text not null check (actor in ('author','author-ai','research-ai','editor-ai','chief-ai','books','system')),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.author_agent_jobs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.author_projects(id) on delete cascade,
  chapter_id uuid references public.author_chapters(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  agent_role text not null check (agent_role in ('author-ai','research-ai','editor-ai','chief-ai','books')),
  task_type text not null,
  instructions text not null default '',
  context_scope text not null default 'project' check (context_scope in ('chapter','project','metadata')),
  status text not null default 'queued' check (status in ('queued','running','review_required','completed','failed','cancelled')),
  result_summary text not null default '',
  error_message text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_author_projects_owner_updated on public.author_projects(owner_user_id, updated_at desc);
create index if not exists idx_author_projects_status on public.author_projects(owner_user_id, status);
create index if not exists idx_author_chapters_project_order on public.author_chapters(project_id, chapter_order);
create index if not exists idx_author_events_project_time on public.author_events(project_id, created_at desc);
create index if not exists idx_author_jobs_owner_status on public.author_agent_jobs(owner_user_id, status, created_at);

alter table public.author_projects enable row level security;
alter table public.author_chapters enable row level security;
alter table public.author_events enable row level security;
alter table public.author_agent_jobs enable row level security;

create policy "author_projects_owner_select" on public.author_projects for select to authenticated using (owner_user_id = auth.uid());
create policy "author_projects_owner_insert" on public.author_projects for insert to authenticated with check (owner_user_id = auth.uid());
create policy "author_projects_owner_update" on public.author_projects for update to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy "author_projects_owner_delete" on public.author_projects for delete to authenticated using (owner_user_id = auth.uid());

create policy "author_chapters_owner_select" on public.author_chapters for select to authenticated using (owner_user_id = auth.uid());
create policy "author_chapters_owner_insert" on public.author_chapters for insert to authenticated with check (owner_user_id = auth.uid());
create policy "author_chapters_owner_update" on public.author_chapters for update to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy "author_chapters_owner_delete" on public.author_chapters for delete to authenticated using (owner_user_id = auth.uid());

create policy "author_events_owner_select" on public.author_events for select to authenticated using (owner_user_id = auth.uid());
create policy "author_events_owner_insert" on public.author_events for insert to authenticated with check (owner_user_id = auth.uid());

create policy "author_jobs_owner_select" on public.author_agent_jobs for select to authenticated using (owner_user_id = auth.uid());
create policy "author_jobs_owner_insert" on public.author_agent_jobs for insert to authenticated with check (owner_user_id = auth.uid());
create policy "author_jobs_owner_update" on public.author_agent_jobs for update to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy "author_jobs_owner_delete" on public.author_agent_jobs for delete to authenticated using (owner_user_id = auth.uid());

-- Every verified EKODI identity receives a private, free Author workspace.
-- Keep the existing Mall and Marketing synthetic workspace behavior intact.
create or replace function public.current_site_workspaces(p_site_key text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_rows jsonb;
  v_result jsonb;
  v_user_id uuid := auth.uid();
  v_person_id uuid;
  v_personal_key text;
  v_workspace_name text;
begin
  v_rows := public.current_site_workspaces_base(p_site_key);

  if p_site_key in ('mall','author') and v_user_id is not null then
    if not exists (
      select 1
        from jsonb_array_elements(coalesce(v_rows, '[]'::jsonb)) item
       where item->>'workspace_kind' = 'personal'
    ) then
      select person_id
        into v_person_id
        from public.login_identities
       where auth_user_id = v_user_id
         and status = 'active'
       limit 1;

      v_personal_key := 'personal:' || coalesce(v_person_id::text, v_user_id::text);
      v_workspace_name := case when p_site_key = 'author' then '내 저자 스튜디오' else '개인 판매자' end;
      v_rows := coalesce(v_rows, '[]'::jsonb) || jsonb_build_array(
        jsonb_build_object(
          'workspace_key', v_personal_key,
          'workspace_kind', 'personal',
          'workspace_name', v_workspace_name,
          'site', p_site_key,
          'tenant_id', null,
          'tenant', null,
          'role', 'member',
          'status', 'active',
          'plan', 'free',
          'store_id', null,
          'store', null,
          'store_name', null,
          'requires_handoff', true,
          'source', 'synthetic'
        )
      );
    end if;
  end if;

  select coalesce(
    jsonb_agg(
      case
        when item->>'source' = 'synthetic'
         and item->>'workspace_kind' = 'personal'
         and p_site_key = 'marketing'
        then item || jsonb_build_object('requires_handoff', true, 'status', 'active')
        else item
      end
    ),
    '[]'::jsonb
  )
  into v_result
  from jsonb_array_elements(coalesce(v_rows, '[]'::jsonb)) item;

  return v_result;
end
$$;

revoke all on function public.current_site_workspaces(text) from public, anon;
grant execute on function public.current_site_workspaces(text) to authenticated;

comment on table public.author_projects is 'Private Author AI book projects. Chief AI receives metadata/events by explicit sharing policy, not manuscript body by default.';
comment on table public.author_events is 'Cross-agent collaboration event contract for Author AI, Chief AI and EKODI BOOKS.';
comment on function public.current_site_workspaces(text) is 'Returns person-scoped service workspaces including free personal Author AI and Mall workspaces.';
