-- EKODI Author AI membership and paid-only provider billing gate.
-- Free members can use the author workspace without triggering any paid AI provider request.

create table if not exists public.author_plan_catalog (
  plan_code text primary key,
  display_name text not null,
  is_paid boolean not null default false,
  monthly_ai_units integer not null default 0 check (monthly_ai_units >= 0),
  max_projects integer check (max_projects is null or max_projects > 0),
  features jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.author_plan_catalog(plan_code, display_name, is_paid, monthly_ai_units, max_projects, features)
values
  ('free', 'FREE', false, 0, 3, '{"ai_generation":false,"direct_writing":true,"book_planning":true,"publish_handoff":true}'::jsonb),
  ('author', 'AUTHOR', true, 120, 20, '{"ai_generation":true,"author_ai":true,"editor_ai":true,"chief_ai":true,"publish_handoff":true}'::jsonb),
  ('pro', 'PRO', true, 500, null, '{"ai_generation":true,"author_ai":true,"editor_ai":true,"research_ai":true,"chief_ai":true,"priority_generation":true,"publish_handoff":true}'::jsonb)
on conflict (plan_code) do update
set display_name = excluded.display_name,
    is_paid = excluded.is_paid,
    monthly_ai_units = excluded.monthly_ai_units,
    max_projects = excluded.max_projects,
    features = excluded.features,
    active = true,
    updated_at = now();

create table if not exists public.author_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'free' references public.author_plan_catalog(plan_code),
  status text not null default 'active' check (status in ('active','past_due','cancelled','suspended')),
  billable_ai_enabled boolean not null default false,
  paid_until timestamptz,
  billing_provider text,
  provider_membership_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (plan_code = 'free' and billable_ai_enabled = false)
    or plan_code <> 'free'
  )
);

create table if not exists public.author_ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.author_projects(id) on delete set null,
  chapter_id uuid references public.author_chapters(id) on delete set null,
  operation text not null,
  provider text not null default 'openai',
  model text,
  ai_units integer not null default 0 check (ai_units >= 0),
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  status text not null default 'completed' check (status in ('completed','failed')),
  provider_request_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.author_ai_quota_cycles (
  user_id uuid not null references auth.users(id) on delete cascade,
  cycle_start date not null,
  units_reserved integer not null default 0 check (units_reserved >= 0),
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, cycle_start)
);

create index if not exists idx_author_memberships_plan_status on public.author_memberships(plan_code, status);
create index if not exists idx_author_ai_usage_user_time on public.author_ai_usage(user_id, created_at desc);
create index if not exists idx_author_ai_usage_project_time on public.author_ai_usage(project_id, created_at desc);

alter table public.author_plan_catalog enable row level security;
alter table public.author_memberships enable row level security;
alter table public.author_ai_usage enable row level security;
alter table public.author_ai_quota_cycles enable row level security;

-- Catalog is safe for authenticated users to read. Membership and usage are owner-readable only.
create policy "author_plan_catalog_authenticated_select" on public.author_plan_catalog
  for select to authenticated using (active = true);
create policy "author_memberships_owner_select" on public.author_memberships
  for select to authenticated using (user_id = (select auth.uid()));
create policy "author_ai_usage_owner_select" on public.author_ai_usage
  for select to authenticated using (user_id = (select auth.uid()));
create policy "author_ai_quota_owner_select" on public.author_ai_quota_cycles
  for select to authenticated using (user_id = (select auth.uid()));

-- Users cannot mutate paid state or usage. Only trusted server code using service_role may do so.
revoke insert, update, delete on public.author_memberships from authenticated, anon;
revoke insert, update, delete on public.author_ai_usage from authenticated, anon;
revoke insert, update, delete on public.author_ai_quota_cycles from authenticated, anon;

create or replace function public.ensure_author_free_membership(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if p_user_id is null then
    raise exception 'user_required';
  end if;
  insert into public.author_memberships(user_id, plan_code, status, billable_ai_enabled)
  values (p_user_id, 'free', 'active', false)
  on conflict (user_id) do nothing;
end
$$;

create or replace function public.author_reserve_ai_units(
  p_user_id uuid,
  p_operation text,
  p_units integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_plan public.author_plan_catalog%rowtype;
  v_membership public.author_memberships%rowtype;
  v_cycle date := date_trunc('month', now())::date;
  v_used integer := 0;
begin
  if p_user_id is null or p_units is null or p_units <= 0 then
    raise exception 'invalid_ai_reservation';
  end if;

  perform public.ensure_author_free_membership(p_user_id);

  select * into v_membership
    from public.author_memberships
   where user_id = p_user_id
   for update;

  select * into v_plan
    from public.author_plan_catalog
   where plan_code = v_membership.plan_code
     and active = true;

  -- Hard financial safety gate: no paid provider call unless payment-backed access is active.
  if v_plan.plan_code is null
     or v_plan.is_paid is not true
     or v_membership.status <> 'active'
     or v_membership.billable_ai_enabled is not true
     or v_membership.paid_until is null
     or v_membership.paid_until <= now() then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'paid_membership_required',
      'plan', coalesce(v_membership.plan_code, 'free'),
      'monthly_ai_units', coalesce(v_plan.monthly_ai_units, 0),
      'used_ai_units', 0,
      'remaining_ai_units', 0
    );
  end if;

  insert into public.author_ai_quota_cycles(user_id, cycle_start, units_reserved, request_count)
  values (p_user_id, v_cycle, 0, 0)
  on conflict (user_id, cycle_start) do nothing;

  select units_reserved into v_used
    from public.author_ai_quota_cycles
   where user_id = p_user_id and cycle_start = v_cycle
   for update;

  if v_used + p_units > v_plan.monthly_ai_units then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'monthly_ai_quota_exceeded',
      'plan', v_membership.plan_code,
      'monthly_ai_units', v_plan.monthly_ai_units,
      'used_ai_units', v_used,
      'remaining_ai_units', greatest(v_plan.monthly_ai_units - v_used, 0)
    );
  end if;

  update public.author_ai_quota_cycles
     set units_reserved = units_reserved + p_units,
         request_count = request_count + 1,
         updated_at = now()
   where user_id = p_user_id and cycle_start = v_cycle;

  return jsonb_build_object(
    'allowed', true,
    'reason', 'paid_membership_active',
    'plan', v_membership.plan_code,
    'operation', p_operation,
    'reserved_ai_units', p_units,
    'monthly_ai_units', v_plan.monthly_ai_units,
    'used_ai_units', v_used + p_units,
    'remaining_ai_units', greatest(v_plan.monthly_ai_units - (v_used + p_units), 0),
    'paid_until', v_membership.paid_until
  );
end
$$;

create or replace function public.author_release_ai_units(
  p_user_id uuid,
  p_units integer
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_cycle date := date_trunc('month', now())::date;
begin
  if p_user_id is null or p_units is null or p_units <= 0 then return; end if;
  update public.author_ai_quota_cycles
     set units_reserved = greatest(units_reserved - p_units, 0),
         updated_at = now()
   where user_id = p_user_id and cycle_start = v_cycle;
end
$$;

revoke all on function public.ensure_author_free_membership(uuid) from public, anon, authenticated;
revoke all on function public.author_reserve_ai_units(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.author_release_ai_units(uuid, integer) from public, anon, authenticated;
grant execute on function public.ensure_author_free_membership(uuid) to service_role;
grant execute on function public.author_reserve_ai_units(uuid, text, integer) to service_role;
grant execute on function public.author_release_ai_units(uuid, integer) to service_role;

comment on table public.author_memberships is 'Server-managed Author AI membership state. Free users can never set billable_ai_enabled.';
comment on function public.author_reserve_ai_units(uuid,text,integer) is 'Atomic server-only financial gate. A paid AI provider request is impossible unless a paid active membership and quota are both valid.';
