const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
const state={goal:'',consult:null,order:null};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'request_failed');return data;}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setBusy(on){$('#consultButton').disabled=on;$('#consultButton').textContent=on?'정리하는 중…':'시작하기';}
function offerCard(o){return `<article class="offer-card"><div><span class="pill">${escapeHtml(o.category)}</span><h3>${escapeHtml(o.name)}</h3><p>${escapeHtml(o.summary)}</p><ul>${o.outcomes.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><button data-offer="${escapeHtml(o.id)}">이 제안으로 계속</button></article>`;}
function renderConsult(data){state.consult=data;$('#diagnosis').textContent=data.diagnosis;$('#freeNextStep').textContent=data.freeNextStep;$('#offers').innerHTML=data.suggestedOffers.map(offerCard).join('');$('#workspace').classList.remove('hidden');$('#workspace').scrollIntoView({behavior:'smooth',block:'start'});$$('[data-offer]').forEach(b=>b.addEventListener('click',()=>createOffer(b.dataset.offer)));}
async function consult(goal){state.goal=goal;setBusy(true);try{const data=await api('/api/consult',{goal});renderConsult(data);localStorage.setItem('ekodibiz.lastGoal',goal);}catch(e){alert('진단을 시작하지 못했습니다. 잠시 후 다시 시도해 주세요.');}finally{setBusy(false);}}
async function createOffer(offerId){try{const data=await api('/api/offers',{goal:state.goal,offerId});state.order=data;$('#orderTitle').textContent=data.offer.name;$('#orderSummary').textContent=data.offer.summary;$('#orderOutcomes').innerHTML=data.offer.outcomes.map(x=>`<li>${escapeHtml(x)}</li>`).join('');$('#orderId').textContent=data.orderId;$('#checkoutMessage').textContent='';$('#orderPanel').classList.remove('hidden');$('#orderPanel').scrollIntoView({behavior:'smooth',block:'center'});localStorage.setItem('ekodibiz.orderDraft',JSON.stringify(data));}catch(e){alert('제안서를 만들지 못했습니다.');}}
async function previewExecution(){if(!state.order)return;try{const data=await api('/api/execution-preview',{goal:state.goal,offerId:state.order.offer.id});$('#executionStages').innerHTML=data.stages.map((s,i)=>`<article class="stage ${s.status}"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${escapeHtml(s.label)}</strong><p>${Array.isArray(s.output)?s.output.map(escapeHtml).join(' · '):escapeHtml(s.output)}</p></div><span>${s.status==='human_gate'?'사용자 승인':s.status==='ready'?'자동 준비':'후속 실행'}</span></article>`).join('');$('#executionPanel').classList.remove('hidden');$('#executionPanel').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){alert('실행계획을 만들지 못했습니다.');}}
async function checkout(){if(!state.order)return;try{const data=await api('/api/checkout-intent',{orderId:state.order.orderId});$('#checkoutMessage').textContent=data.message;if(data.checkoutUrl)location.href=data.checkoutUrl;}catch(e){$('#checkoutMessage').textContent='결제 승인 단계를 준비하지 못했습니다.';}}
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const goal=$('#goal').value.trim();if(goal)consult(goal);});
$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('#goal').value=b.dataset.prompt;consult(b.dataset.prompt);}));
$('#approveButton').addEventListener('click',previewExecution);$('#checkoutButton').addEventListener('click',checkout);
(async()=>{try{const h=await api('/api/health');if(h.ok)document.body.dataset.runtime='ready';}catch{}const saved=localStorage.getItem('ekodibiz.lastGoal');if(saved)$('#goal').value=saved;})();